### ISSUE TITLE
Attention! Using version 1.26.1 is not safe!

### ISSUE THREAD

**Issue by wendig0x** [veracrypt/VeraCrypt#1007]
@idrassi I ask you to completely roll back this pull request (https://github.com/veracrypt/VeraCrypt/pull/957), because I consider it suspicious. These changes require detailed analysis.

The protective properties of the application have been deliberately weakened!

**Comment by Radium-bit** [comment]
Agreed, I don't want VeraCrypt to do away with the way entropy is collected from the mouse. Just one question, do you absolutely trust the random number generator of the system or device manufacturer?

**Comment by idrassi** [comment]
The PR in question has been reverted on December 11th 2022: https://github.com/veracrypt/VeraCrypt/commit/44c9c077f379e65ef45952e1e78059cdec2fa36f

Closing this issue.
