### ISSUE TITLE
LNK2019	无法解析的外部符号 _blake2s_has_sse2，函数 _blake2s_init 中引用了该符号

### ISSUE THREAD

**Issue by xhf2006hn** [veracrypt/VeraCrypt#1008]
vs2019   build  ExpandVolume  project
![1670570525002](https://user-images.githubusercontent.com/19721628/206647325-93360c8c-facd-4882-b2b1-a55ee0b7fe7d.png)

**Comment by phant0ms** [comment]
附加依赖项里面的Crypto.lib名字大小写不对，改成Crypto项目编译输出的Crypto.lib就通过了

**Comment by idrassi** [comment]
This issue was fixed in the following commit: https://github.com/veracrypt/VeraCrypt/commit/40caafdb1be73ac645c75ef31cbbc32624b6eee3

Thank you for the report.
