### ISSUE TITLE
qBittorrent & Veracrypt container not working properly

### ISSUE THREAD

**Issue by Virtix21** [veracrypt/VeraCrypt#102]
Hello, i have a 1.5TB container, when i mount it, it works properly with zero issues.
However, if i try to download with qBittorrent straight to the container, it works fine at the first 10 or so seconds, then speed drops to nothing.
The torrent works fine when using a normal drive to download to.
Thanks.
Windows 7, x64
Veracrypt version:1.18a

**Comment by Tharn** [comment]
Similar issue, possibly related:

When mounting a file as a volume, and this volume is set to be shared over a network with full read and write permissions, I am unable to write to that volume from another computer. It gives me a 'permission denied'. It works fine with regular VC volumes.
