### ISSUE TITLE
Paste does not work in the "Change System Password" dialogue

### ISSUE THREAD

**Issue by necrevistonnezr** [veracrypt/VeraCrypt#104]
Veracrypt 1.19-BETA2 (64-bit)
Windows 7 64 bit

When I change a system encrpytion password and try to copy & paste a new password generated by my password manager (Enpass), I cannot paste the password into the "New Password" box.

**Comment by idrassi** [comment]
This is done on purpose for Pre-Boot passwords. We don't allow copy-past operations in order to ensure that the password is typed using the correct keyboard layout and that it contains only valid characters recognized by BIOS.
