### ISSUE TITLE
Support BLAKE3 hash algorithm

### ISSUE THREAD

**Issue by sandakersmann** [veracrypt/VeraCrypt#1058]
More info:

https://twitter.com/zooko/status/1652743779932045313

https://github.com/BLAKE3-team/BLAKE3

**Comment by idrassi** [comment]
As @cypherbits wrote, BLAKE3 is not meant to be used for cases like VeraCrypt since it is too fast. This is even mentionned in BLAKE3 documentation.
Thus closing it.
