### ISSUE TITLE
/q /w command line doesn't wipe cache immediately

### ISSUE THREAD

**Issue by fdsx121** [veracrypt/VeraCrypt#1083]
win7x64sp1 , veracrypt 1.25.9 installed
1. /q /w command line doesn't wipe cache immediately , but after dismount.

2. /w wipe cache immediately only if GUI is poped up,
if i program it to run at autohotkey hide mode to hide the GUI pop up , it will only wipe cache after dismount.

example cmd code
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /w
or
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /s /q /w /c /v "C:\1gb" /l o

if i'm not doing it correctly , please correct me.

**Comment by idrassi** [comment]
I'm not able to reproduce the issue: wiping the cache is immediat and the code is implemented correctly for this.
The second command you wrote is strange because you combine `/w `and `/c`: why specifying /c is you want to wipe the cache just after mounting?

**Comment by fdsx121** [comment]
you are right.
i just tested it again and found out , it did wipe cached immediately , but just the GUI didnt show it/grayout for the first time until i check on it the second time.
https://i.imgur.com/y9HyKl2.gif
ty for your time

**Comment by idrassi** [comment]
Thank you for the confirmation.
