### ISSUE TITLE
Using OSXFuse instead of MacFUSE

### ISSUE THREAD

**Issue by kgadek** [veracrypt/VeraCrypt#11]
I tried to install VeraCrypt 1.0f on my Mac and I got the "MacFUSE compatibility layer" error. I started digging through issues and found a solution – install OSXFuse from pkg instead of homebrew, select "MacFUSE compat layer".

But the thing is *why* homebrew version does not include that. The reason was discussed there ([homebrew/issues/25565](https://github.com/Homebrew/homebrew/issues/25565)) and the issue was marked as WONTFIX because of following discussion in the upstream package ([osxfuse/issues/114](https://github.com/osxfuse/osxfuse/issues/114)):

@bfleischer (emphasis mine):

> (…) **MacFUSE is dead**. The compatibility layer that is included in the packaged version was intended to smoothen the transition. **But I've noticed that some people are linking file systems against the compatibility layer. This is a really bad idea**. Other formulas should link against libosxfuse not libfuse. There should really be no need for the compatibility layer in homebrew.

So VeraCrypt should use libosxfuse, not libfuse.

**Comment by nszceta** [comment]
+1

**Comment by idrassi** [comment]
This is planned.
The dependency to libfuse was left to minimize code modifications (stable code inherited from TrueCrypt) while at the same time adding explicit dependency to OSXFuse to prepare room for the upcoming changes.
If everything goes as planned, the next version should be based solely on OSXFuse.

**Comment by kgadek** [comment]
@idrassi, that's great to hear, thank you for information.

**Comment by basnijholt** [comment]
Any updates on this? I went trough some trouble uninstalling (brew installed) OSXFuse and reinstalling it again from the website.

I do hope that in the future VeraCrypt will be installable via Homebrew, as it's the only software that I use that now requires so much work to install.

**Comment by JonLevy** [comment]
+1 It should be a top priority for Veracrypt's future to be installable with Homebrew (or at least compatible with libraries installed that way).  Otherwise sophisticated Mac users will avoid it.

**Comment by aktau** [comment]
I can't do more but echo @JonLevy's comment. I've been hoping for this for some time after TrueCrypt's shutdown.

**Comment by tristan-k** [comment]
+1

**Comment by tsone** [comment]
+1

**Comment by xyb** [comment]
+1

**Comment by zsmizzle** [comment]
+1

**Comment by kwladyka** [comment]
+1

**Comment by medfreeman** [comment]
+1

**Comment by Ben305** [comment]
+1

**Comment by friendimaginary** [comment]
ditto.

**Comment by Chream** [comment]
+1

**Comment by basnijholt** [comment]
+1

On Thu, 11 Feb 2016 at 14:43 Christopher Eames

<
mailto:Christopher Eames <notifications@github.com>
> wrote:

+1

**Comment by PaulWoitaschek** [comment]
Any news on this?

**Comment by idrassi** [comment]
No advance made on this.
All resources focused now on implementing UEFI support for system encryption on Windows so other issues related to OSX and Linux are on hold.

External help is welcomed and the project is open for other developers contributions.

**Comment by jcouturier** [comment]
Any news here?

VeraCrypt 1.17 with OSXFuse 3.5.2 installed WITH the compatibility layer, but VeraCrypt still throws the error "VeraCrypt requires OSXFUSE 2.3 or later with MacFUSE compatibility layer installer."

**Comment by idrassi** [comment]
@jcouturier : VeraCrypt 1.18 solved this error, so you should use it instead of 1.17.

As for OsxFuse instead of MACFuse, I have already done the necessary modifications and version 1.19 that is coming in few days will not require MacFuse compatibility layer.

**Comment by jcouturier** [comment]
@idrassi Excellent, thank you! v1.18 is working for me now.

**Comment by swingingsimian** [comment]
+10 The advised install has not only failed to mount the device, but it's also completely broken my sshfs setup which I actively use for software development. Any news on 1.19?

**Comment by idrassi** [comment]
I have published an installer for 1.19-BETA3 that removes dependency to MACFuse compatibility layer. You can find it at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/

Can you check that it works now on your system (especially brew version of OSXFuse)?

**Comment by swingingsimian** [comment]
Tested with working version brew of OSXFuse installed. Failed with same error. Tried the main (external SSD) device /dev/rdisk2 and the 'sub device' /dev/rdsisk2s1'. I also tested 1.18 on another mac without brew osxfuse installed, and used the dmg version of OSXfuse with macfuse compatibility layer enabled. Error is:
Operation failed due to one or more of the following:
 - Incorrect password
 - Incorrect Volume PIM number
 - Incorrect PRF (hash)
 - Not a valid volume

Thanks

Nathan

**Comment by idrassi** [comment]
Just for clarification: VeraCrypt is running fine but you can't access your disk?
What happens of you create a file container and then try to mount it?

To me, it looks a different issue from the OSXFuse dependency for which this ticket was created.

**Comment by swingingsimian** [comment]
Yes, apologies, I think I was reading about three threads around the macfuse issue as it appeared to be related, and posted here without double checking the context. I will try and test as suggested and raise a separate thread.

**Comment by kainjow** [comment]
Just installed VeryCrypt and OSXFuse and successfully mounted a FAT volume I created on Windows.

I'd say this issue could be closed.
