### ISSUE TITLE
Create list of remaining security issues discovered by OSTI audit (from old TC)

### ISSUE THREAD

**Issue by breznak** [veracrypt/VeraCrypt#110]
The report is here: https://ostif.org/wp-content/uploads/2016/10/VeraCrypt-Audit-Final-for-Public-Release.pdf 

Create a milestone, create separate issues so users can work on fixing the remaining problems (eg. outdated compression libs, ...)

**Comment by idrassi** [comment]
To be clear: I worked closely with uarkslab during the audit and all issues specific to VeraCrypt were fixed already in 1.19 as indicated in the release notes.

The remaining issues comes from TrueCrypt and where already mentioned by the Open Crypto Audit.

**Comment by breznak** [comment]
Yes, and thank you for your work @idrassi :+1: Edited the label to reflect that..
