### ISSUE TITLE
Veracrypt Expander Add multiple languages

### ISSUE THREAD

**Issue by fzxx** [veracrypt/VeraCrypt#1106]
Currently only English
![图片](https://github.com/veracrypt/VeraCrypt/assets/53783792/d2714218-95b0-4e81-b01d-20d602a1a547)

**Comment by idrassi** [comment]
I have pushed a commit to fix localization support of the main dialog of Expander: https://github.com/veracrypt/VeraCrypt/commit/394ed5d867402b8dec51094281492c1552d5478e

For the other dialogs of Expander, some extra work is needed to add appropriate entries in the XML file. I will push a followup commit to Expander 100% localizable.

**Comment by idrassi** [comment]
I have finished localization of all Expander UI string and UI message: https://github.com/veracrypt/VeraCrypt/commit/78d22e569bf8b907cfe1aba8fcbc9377f5c6f852
I will pushed an update to the language XML files to add the new Expander entries: https://github.com/veracrypt/VeraCrypt/commit/83064d6cec5951b6bd5ac59fc8249787b6978c59
This will be included in the next build (no date yet).
Thank you for raising this issue.
