### ISSUE TITLE
When normal volume is configured to handle less than 4 GB, the hidden volume always goes to 3 MB.

### ISSUE THREAD

**Issue by Dreadysa** [veracrypt/VeraCrypt#1131]
# Expected behaviour 

I expected it to either refuse the user to create a more than 4 Gb hidden volume or give an error telling the user to make the volume larger for the normal decoy volume.
# Observed behaviour

When making the decoy less than 4 GB (selecting "I do not plan to store more than 4 GB) with the file format as FAT as always, the hidden volume claims that its size is what you would expect something such as 333 GB on my 512 GB Sandisk (listed as 412 GB on my comp but advertised as 512 GB)  but then when it is all done, its 3 MB or even sometimes in the KB range. While I've since switched to a regular drive instead of a hidden drive for unrelated reasons, it's still fresh in my mind

Keep in mind that it gives the same (Do you want to store files more than 4 GB on this drive?) prompt for the hidden drive as well. Responding with Yes will still render the space as 3 MB or even in the KB range.

My main fear is that because the software is not working well in a scenario like this, it could possibly introduce an unknown security vulnerability with hidden volumes akin to the 1.18a vulnerability. It is well known that software is most vulnerable in its buggy states.
# Steps to reproduce

1.  Use a non-file Drive such as a USB.
2. Set up a hidden volume, make it so that the decoy volume uses less than 4 GB
3. Set up as normal, whatever you want.
4. Once you build the hidden volume, mount. You will see a ludicrously low volume of space. In my case, it was always in the 3 MB range for some reason.

# Your Environment
EndeavourOS, latest kernel, 6.3.9-arch1-1 (64-bit), got Veracrypt GUI from the official arch pacman repository.

Veracrypt Version 1.25.9

**Comment by idrassi** [comment]
I was not able to reproduce this issue depite several tries.
Since we don't provide an official Arch package, I advise you to test using official generic installer.
On my side, I tested using official Ubuntu 20.04 package of version 1.25.9.
I made a video of the whole process where I create a 3GB outer volume followed by the creation of a 1GB hidden volume and after that hidden volume is mounted correctly with the correct side: https://youtu.be/lYz6FXqdpVA

I'm also attaching the video here.
The volume is created on an external USB driver.

Can you please indicate if you followed a different approach?

The code for creation of hidden volume have been tested for many years and it will be surprising that such bug exists. So if you can please redo the test and share a recording or the detailed steps this will be very helpful.

Thank you.



https://github.com/veracrypt/VeraCrypt/assets/4698669/ebaf70a6-e616-4d86-b06f-e74f1ae54684

**Comment by Dreadysa** [comment]
https://github.com/veracrypt/VeraCrypt/assets/138035247/5a606c83-b900-4870-9609-fa5dd1961228


Here is the video of me doing this with the official generic GUI listed on your website, 64-bit and straight from the tar.gz file. My mistake, it's always EXACLTY 3.9 MiB.

Interestingly, this issue only occurs whenever I select "Use all available space." for the hidden volume. If I select the space as the total amount of GiB available (349 GiB) and minus it by 1 (348 GiB) it works. Occasionally, it shaves off a few GiB in the volume selector in the GUI (from 348 to maybe 346-345 GiB.)

A part of me thinks that this might just be the Sandisk USB being glitchy, but I'm also worried of a potential threat where an adversary could detect a hidden volume if they check if there is a 3.9 MiB chunk of data after the decoy volume that is encrypted, but the empty space is a repeating pattern that indicates that it is empty or otherwise not an important space.

I am really confused because I don't know whether the hidden volume is safe if the software is glitching like this.

**Comment by Dreadysa** [comment]
> In `VolumeSizeWizardPage.cpp` to validate state of the "Next" button we are using `MaxVolumeSize` when `MaxVolumeSizeValid` is `true` and for the value in the text "Maximum possible hidden volume size for this volume is X" we use `freeSpaceText`. But when we click "Use all available free space" we are actually setting the value to `AvailableDiskSpace` which we ultimately get from `wxGetDiskSpace`. So it appears that we are showing one thing to the user, but doing something different on the background assuming that these numbers from different sources will be the same (which they didn't happen to be). I've yet to dig deeper why the numbers differ.
> 
> EDIT: The "use all space" checkbox was added (or edited at least) in a commit [5e547b1](https://github.com/veracrypt/VeraCrypt/commit/5e547b127f25b0d4f526fdb4126b95c4ba03c4b2) only 2 years ago, so it is not too unreasonable to think it has gone without notice.
> 
> Possible patch to fix, though I don't have Windows system to test if it behaves differently. But this seems to fix it for Linux:
> 
> ```
> --- VolumeSizeWizardPage.cpp	2023-06-29 21:07:42.487178582 +0300
> +++ /home/user/git/VeraCrypt/src/Main/Forms/VolumeSizeWizardPage.cpp	2023-06-29 21:06:29.744327195 +0300
> @@ -79,7 +82,7 @@
>  		uint64 val;
>  		if (UseAllFreeSpaceCheckBox->IsChecked ())
>  		{
> -			val = AvailableDiskSpace;
> +			val = MaxVolumeSizeValid ? MaxVolumeSize : AvailableDiskSpace;
>  		}
>  		else
>  		{
> ```

Sounds good. Once I get official confirmation that this will be added to the main patch by idrassi in the next update, I will mark as solved and closed.

**Comment by Dreadysa** [comment]
I accidentally set the issue as closed! excuse me

**Comment by Dreadysa** [comment]
> Thank you @Dreadysa for the video and the explanation. Now the issue is clear in my mind. Thank you also @Jertzukka for the analysis and the fix. You have nailed down the issue correctly!
> 
> In my test, I completely ignored the "use all available free space" for hidden volume because in my mind **it should never be used** since this virtually means that no new data can be added to the outer volume. In practice, you want to regularly add and remove data from the outer volume in order to preserve plausible deniability. If hidden volume takes all free space, then adding new data to the outer volume will overwrite the hidden volume making it unusable afterwards.
> 
> I hesitated between disabling this option when creating a hidden volume or adding the fix proposed by @Jertzukka. I ended up choosing the fix approach to give users freedom of choice. The commit is here: [df62c02](https://github.com/veracrypt/VeraCrypt/commit/df62c0227c40682a69c15d8477b7ddcc0f380678)

Merci.
