### ISSUE TITLE
unknown type name 'ssize_t'; did you mean 'size_t'?

### ISSUE THREAD

**Issue by Sod-Almighty** [veracrypt/VeraCrypt#1163]
# Expected behavior
The source compiles.

# Observed behavior
The source does not compile, and the following errors are printed:

```
Compiling jitterentropy-base.c
In file included from ../Crypto/jitterentropy-base.c:74:
../Crypto/jitterentropy.h:124:1: error: unknown type name 'ssize_t'; did you mean 'size_t'?
  124 | ssize_t jent_read_entropy(struct rand_data *ec, char *data, size_t len);
      | ^~~~~~~
      | size_t
../Crypto/jitterentropy-base.c:585:1: error: unknown type name 'ssize_t'; did you mean 'size_t'?
  585 | ssize_t jent_read_entropy(struct rand_data *ec, char *data, size_t len)
      | ^~~~~~~
      | size_t
make[1]: *** [/tmp/VeraCrypt_1.25.9_Source/src/Build/Include/Makefile.inc:25: ../Crypto/jitterentropy-base.o0] Error 1
make: *** [Makefile:487: all] Error 2
```

# Steps to reproduce
1. Install Alpine Linux.
2. Install build-base and yasm.
3. Download and unpack the source.
4. `make`

# Your Environment

**VeraCrypt version:** 1.25.9

**Operating system and version:** Alpine Linux 3.18

**System type:** 64-bit

**Comment by Jertzukka** [comment]
`ssize_t` is defined in `src/Crypto/jitterentropy-base-user.h` which should be included properly. First of all, I'd recommend compiling the master branch instead of 1.25.9 as it has a lot of fixes yet to be pushed to stable, second of did you follow https://veracrypt.fr/en/CompilingGuidelineLinux.html?

**Comment by Sod-Almighty** [comment]
I already have `linux-headers`. And, indeed, before Veracrypt was [removed from the official Alpine repo](https://git.alpinelinux.org/aports/commit/?id=ce9644ed6d9226f5e81b04b122598c1fd5f1585a) in April (for having a license technically prohibiting inclusion into _any_ repo), the repo included a [little patch file](https://git.alpinelinux.org/aports/tree/testing/veracrypt/10-ssize-t.patch?id=a9fee80d909c41ceea2bfa19ac7a1b64477e2eb9) for it that added `#include <sys/types.h>` to jitterentropy.h.

**Comment by idrassi** [comment]
I have pushed a change to add explicit include of `<sys/types.h>` in `jitterentropy-base-user.h` in cases other than Windows. This is similar to the patch you uses but in a better place: https://github.com/veracrypt/VeraCrypt/commit/fba1943d87eb604edc5c4f7d86878425eb48cd6b
