### ISSUE TITLE
create volume fail - macOS/

### ISSUE THREAD

**Issue by rollinroy** [veracrypt/VeraCrypt#117]
(macOS 10.12.1/ osxfuse 3.5.3/ veracrypt 1.19) Just installed osxfuse and veracrypt.  When creating an encrypted volume with filesystem=mac os extended, I get the following error:
"mount_osxfuse: the OSXFUSE file system is not available (255). 
 fuse: failed to mount file system: invalid argument"

If i select filesystem=none, the volume is mounted.

Any suggestions or ideas?  btw, if I do specify none for the filesystem, can I still encrypt a hierarchical folder structure?  I eventually get the same error with filesystem=none when I attempt to mount it.

tia.

cheers, roy

**Comment by rollinroy** [comment]
Using filesytem=none produces the same error when I try to mount it (which kind of makes sense since there's no filesystem).  So I'm dead in the water.

**Comment by idrassi** [comment]
The error "OSXFUSE file system is not available" is similar to a previously reported issue for which I have posted a solution: https://github.com/veracrypt/VeraCrypt/issues/106

Can you please follow the steps in the link above and tell us if it solves your issue?

Thanks.

**Comment by rollinroy** [comment]
Following the steps in solution: #106 did work.  Much thanks and sorry for not seeing that solution eariler.

cheers, roy
