### ISSUE TITLE
Veracrypt -c is unusable on Alpine due to weird text printing issue

### ISSUE THREAD

**Issue by Sod-Almighty** [veracrypt/VeraCrypt#1171]
**VeraCrypt version:** 1.26.4
**Operating system and version:** Alpine Linux 3.18
**System type:** 64-bit

I compiled Veracrypt on Alpine linux as detailed [here](https://github.com/veracrypt/VeraCrypt/issues/1165#issuecomment-1665585789), and it just isn't usable. It's having severe difficulties in printing messages to the console.

For example, I tried to create a volume:

```
# veracrypt -c test
Illegal option -p
Volume type:
 1) Normal
 2) Hidden
```

(It prints `Illegal option -p` because I haven't recompiled since [this commit](https://github.com/veracrypt/VeraCrypt/commit/dab261c6941e1ee04d823effdf65784f1a554cb8).)

So, I type "1" and enter. The terminal now looks like this:

```
# veracrypt -c test
Illegal option -p
Volume type:
 1) Normal
 2) Hidden
1
Select [1]:

```

Weird right? So I type "1" again, and press enter. The terminal now looks like this:

```
# veracrypt -c test
Illegal option -p
Volume type:
 1) Normal
 2) Hidden
1
Select [1]:
1
Enter volume size (sizeK/size[M]/sizeG.sizeT/max):
Encryption Algorithm:
 1) AES
 2) Serpent
 3) Twofish
 4) Camellia
 5) Kuznyechik
 6) AES(Twofish)
 7) AES(Twofish(Serpent))
 8) Camellia(Kuznyechik)
 9) Camellia(Serpent)
 10) Kuznyechik(AES)
 11) Kuznyechik(Serpent(Camellia))
 12) Kuznyechik(Twofish)
 13) Serpent(AES)
 14) Serpent(Twofish(AES))
 15) Twofish(Serpent)

```

Veracrypt has taken my input as being the desired size of the file! Before it even asked the question!

Something is seriously awry.

**Comment by Jertzukka** [comment]
There seems to be some difference between libc and musl on how/when they flush the stdout buffer. You can workaround it by changing:

https://github.com/veracrypt/VeraCrypt/blob/f48c21a54ba461c0356d5a9358ae7e441ab269c3/src/Main/TextUserInterface.cpp#L1048-L1051

to `wcout << str.c_str() << endl;` in your compile, though you'll end up with some extra linebreaks as `\n` is used a lot in the option list sections as `DoShowString()` doesn't linebreak in itself. I'll maybe take a look at some point whether it's possible to get both behave the same.

**Comment by Sod-Almighty** [comment]
I guess my ignorance is showing here but uhh......how do I apply that patch, exactly?

**Comment by Jertzukka** [comment]
> I guess my ignorance is showing here but uhh......how do I apply that patch, exactly?

Save it and run `git apply patchname.patch` in VeraCrypt directory.

**Comment by Sod-Almighty** [comment]
Ah, thank you. That worked.

(Now I just have to somehow solve the issue that I can't use fuse from within an LXC container........argh!)

**Comment by Jertzukka** [comment]
Here's even simpler:

```
diff --git a/src/Main/TextUserInterface.cpp b/src/Main/TextUserInterface.cpp
index 37b346bd..637d5caa 100644
--- a/src/Main/TextUserInterface.cpp
+++ b/src/Main/TextUserInterface.cpp
@@ -1047,7 +1047,7 @@ namespace VeraCrypt
 
 	void TextUserInterface::DoShowString (const wxString &str) const
 	{
-		wcout << str.c_str();
+		wcout << str.c_str() << flush;
 	}
 
 	void TextUserInterface::DoShowWarning (const wxString &message) const
```

I tried it also on the glibc version and didn't notice any regressions, so if a better solution is not found, it could be upstreamed.
