### ISSUE TITLE
Unexpected behavior: Kuznyechik always mounts to /dev/loop/31 instead of /dev/mapper/veracrypt1

### ISSUE THREAD

**Issue by springfielddatarecovery** [veracrypt/VeraCrypt#1178]
# Expected behavior
When mounting Veracrypt volumes, they normally create a /dev/mapper/veracryptx device with x being the next available number. 

# Observed behavior
This holds true for all algorithms except Kuznyechik or cascades with Kuznyechik in them, in which case the device is /dev/loop/31. Not a huge issue but unexpected.

# Your Environment
Tested in Ubuntu 18.04 (64-bit), Veracrypt 1.23 using these commands for vault creation
`sudo /usr/bin/veracrypt --text --mount /path/to/my_file.vc /media/veracrypt1 --password mypassword --pim 0 --keyfiles '' --slot 1 --protect-hidden no`

**Comment by idrassi** [comment]
Thank you for bringing up this observation.

Firstly, I'd like to point out that the behavior you noticed isn't specifically tied to the Kuznyechik algorithm. In fact, you can reproduce this with any encryption algorithm if you use the mount option `nokernelcrypto` in your command line (`-mount-options=nokernelcrypt`).

VeraCrypt is designed to leverage the Linux dm-crypt kernel module for managing volumes that utilize algorithms supported by the Linux kernel. The primary motivation behind this design is to achieve optimal performance. When the Linux kernel doesn't support a particular encryption algorithm used by a volume (as is the case with Kuznyechik), VeraCrypt defaults back to using the loop device.

To provide further insight:

- **dm-crypt**: This module acts as a transparent disk encryption subsystem in Linux. When VeraCrypt uses an encryption algorithm that's supported by the Linux kernel, it uses dm-crypt to create the `/dev/mapper/veracryptx` device.
- **loop device**: This is more of a fallback mechanism in case the desired encryption algorithm is not supported by the kernel. As you observed, in such cases, the volume gets attached to `/dev/loop/31` or a similar loop device.

If you ever wish to disable dm-crypt support entirely, you have a couple of options:

- UI: Head to Preferences -> System Integration and choose the option "don't use kernel cryptographic services".
- Command Line: As mentioned earlier, you can use the nokernelcrypto mount option.

I hope this provides clarity on the behavior you observed.
