### ISSUE TITLE
Question about deleting files from Portable VeraCrypt installation

### ISSUE THREAD

**Issue by ghost** [veracrypt/VeraCrypt#1189]
VeraCrypt Portable 1.25.9

1) If I don't need the arm64 version, can I delete the following files?
veracrypt-arm64.cat
VeraCrypt-arm64.exe
veracrypt-arm64.sys
VeraCrypt Format-arm64.exe
VeraCryptExpander-arm64.exe

2) If I don't need help can I delete the "docs" folder?
3) If I don't need additional languages, can I delete the "Languages" folder?

4) Can I delete the following files?
LICENSE
NOTICE
License.txt

5) If I just run VeraCrypt.exe, then only the 32-bit version of VeraCrypt is launched?

**Comment by rafaelazvdo** [comment]
The answer is yes to all questions.
