### ISSUE TITLE
Cannot paste password from clipboard on Windows 10 22H2

### ISSUE THREAD

**Issue by jakche** [veracrypt/VeraCrypt#1191]
As it's mentinoed in #463 I cannot paste my password when trying to encrypt the whole drive. Using VeraCrypt 1.25.9

**Comment by jakche** [comment]
@idrassi Thank you, you explained it perfectly, that is what I was trying to do exactly.

**Comment by idrassi** [comment]
I noticed that the documentation doesn't mention this design choice nor its rational. So I have updated it to mention it: https://github.com/veracrypt/VeraCrypt/commit/a8972c656951e4c67907f1dcd740c77543e4ab2e

Thank you for your report. It help enhance the documentation.
