### ISSUE TITLE
Ghost drivers, detect unknown device? Win10

### ISSUE THREAD

**Issue by MrBlueBird** [veracrypt/VeraCrypt#1212]
Hey, My diskpart indicates that I have only one disk device.

DISKPART> list disk

  Disk ###  Status         Size     Free     Dyn  Gpt
  --------  -------------  -------  -------  ---  ---
  Disk 0    Online          447 GB      0 B

Veracrypt 1.25.9x64

when selecting devices it shows an unknown ghost drive, is it some software bug?

![scr1](https://github.com/veracrypt/VeraCrypt/assets/18251856/3a5f7621-1052-4943-a514-e87e2681a7d0)

I found a similar thread on reddit with the same problem: https://www.reddit.com/r/VeraCrypt/comments/r9sg11/veracrypt_showing_a_hdd_which_does_not_exist/

**Comment by idrassi** [comment]
Thank you for providing detailed information about the issue you encountered.

Based on your observations, it indeed looks like you're seeing a system-generated disk that corresponds to the Windows Sandbox feature which is an isolated environment designed to run untrusted applications safely. To achieve this, Windows creates a [dynamic image (VHDX) that represents a clean Windows installation](https://techcommunity.microsoft.com/t5/windows-os-platform-blog/windows-sandbox/ba-p/301849), which includes a base system image, user data, and the runtime state. The size of this image is typically around 8 GB, matching the "ghost" drive you observed.

When VeraCrypt enumerates devices on your system, it checks for all available disk devices using device path format "`\Device\HardDiskX\PartitionY`" without checking their physical nature. Hence, VeraCrypt lists \Device\HardDisk1\Partition1 even though you don't see it as a physical disk in diskpart.

Considering the potential confusion this might cause for other users, and noting an unanswered thread on Reddit regarding this issue, I will add this information to the VeraCrypt FAQ. This will hopefully assist others who might encounter a similar scenario.

**Comment by idrassi** [comment]
I pushed a commit (https://github.com/veracrypt/VeraCrypt/commit/7f902227b036876eecd115601793a1286bdc015f) to add this information to the FAQ and it is also published online at the bottom of https://veracrypt.fr/en/FAQ.html
