### ISSUE TITLE
ARM64 and ARMhf Linux packages missing for latest release 1.26.7

### ISSUE THREAD

**Issue by theofficialgman** [veracrypt/VeraCrypt#1217]
# Expected behavior

ARM64 and ARMhf Linux packages are present for latest release as there were for the previous release 1.25.9

# Observed behavior

ARM64 and ARMhf Linux packages are not present for latest release

# Steps to reproduce

1. check github release and sourceforge pages

**Comment by idrassi** [comment]
The ARM64 package for Ubuntu 22.04 has been uploaded. Additional packages will be released in the coming days.
Please note that preparing all ARM-based packages is time-consuming since we are using a single Raspberry Pi machine to build all variants. Its performance is notably slower than that of regular desktop machines.

**Comment by theofficialgman** [comment]
@idrassi 

Consider using oracle's always free (yes it's really free) arm ampere server. I have mine configured with 4 cores, 24GB of ram, super fast networking, and 200GB of storage (had it for over a year now). It chews through builds and I have multiple chroots on it for building on multiple distros

https://www.oracle.com/cloud/free/

**Comment by idrassi** [comment]
Thank you for bringing this to my attention. I took some time to explore Oracle's free tier offerings and, I must admit, the capabilities and specs are quite compellin especially in light of the Geekbench results,

Given the compelling advantages, I'm inclined to explore this further and see how I can optimize the build processes. 
Thank you again, your feedback has been invaluable.

**Comment by idrassi** [comment]
The ARM64 and ARMhf Linux packages are now available for [download](https://veracrypt.fr/en/Downloads.html).
