### ISSUE TITLE
Bundle Download option still missing

### ISSUE THREAD

**Issue by BigPanda97** [veracrypt/VeraCrypt#1224]
The classical “Bundle” version which contains everything is still missing for the new 1.26.7 release.

**Comment by idrassi** [comment]
Indeed, the bundle is not available yet. Some packages, especially the Linux ARM ones, are still in the build process. As soon as they are ready, the complete bundle will be published. I anticipate it to be available by tomorrow.

Thank you for your patience.

**Comment by BigPanda97** [comment]
Oh, alright, I just thought it might have been forgotten. 😅
Thanks

**Comment by idrassi** [comment]
The full Bundle is now available for [download](https://veracrypt.fr/en/Downloads.html).
