### ISSUE TITLE
Installer Says Mac OS 11 Big Sur is unsupported, but the website states otherwise.

### ISSUE THREAD

**Issue by SammyD2002** [veracrypt/VeraCrypt#1236]
Good afternoon! Earlier today, I was attempting to install VeraCrypt on Mac OS Big Sur, but the installer stated that Mac OS Big Sur is not supported. However, the official VeraCrypt website says Mac OS Big Sur is supported at the following URL: https://veracrypt.fr/en/Supported%20Operating%20Systems.html
Is the website incorrect, or is there an issue with the Mac OS VeraCrypt Installer that is causing this? Thanks for your help!

# Screenshots

Installer Failing
![Screen Shot 2023-10-20 at 3 35 01 PM](https://github.com/veracrypt/VeraCrypt/assets/35823092/508ca4cf-a521-43a8-8621-78c730549c5d)

VeraCrypt Supported Versions Page
![Screen Shot 2023-10-20 at 3 36 11 PM](https://github.com/veracrypt/VeraCrypt/assets/35823092/86ca51f9-32cd-480f-8ae2-23a17c57bb99)

# Your Environment

**VeraCrypt version:**  1.26.7

**Operating system and version:** Mac OS 11.7.10

**System type:**  64-bit

**Comment by idrassi** [comment]
Thank you for bringing this discrepancy to our attention. You're correct: the website's information on macOS compatibility was out of date, and I apologize for the oversight.

I have updated the [Supported Operating Systems](https://veracrypt.fr/en/Supported%20Operating%20Systems.html) page to reflect the changes. Starting with VeraCrypt version 1.26.7, we are now focusing our support on the three most recent versions of macOS: Sonoma, Ventura, and Monterey.

The rationale for this decision is grounded in the complexities of maintaining compatibility across multiple versions of an operating system. To provide the most secure and stable experience for our users, we've opted to concentrate our development efforts on the latest versions of macOS. This approach is commonly followed in the software industry, as it enables us to utilize the newest security features and APIs while streamlining our development process.
