### ISSUE TITLE
Not running on Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by albrt68** [veracrypt/VeraCrypt#1240]
I have been using Linux Distributions for around 5 years now and despite there being an official installer for Debian 12, I have not been able to install VeraCrypt. Not even after 3 hours. I literally went through the entire Issue list on Github for VeraCrypt. I found similar topics regarding my issue, however none that worked for me.

Following the instructions, I got stuck for 90 minutes at
sudo apt install libwxgtk3.0-gtk3-dev 
It tells me no such option exists. I spend almost an hour trying to find a solution for this on the Internet.

I eventually managed to bypass this by manually installing the needed files from Debian's packages. All goes well, until
cd ~/VeraCrypt/src
make 

The command ended with linking VeraCrypt or something. No errors. Yet, I can't find VeraCrypt anywhere on my system.

I tried the generic installer and the installer for Debian 12. Both didn't let me successfully install it either. This is the first time I ever asked someone for help (despite Google) to install a software on Linux. I have always been able to find a solution myself. 

Does anyone have a solution?

**Comment by Jertzukka** [comment]
I just booted a fresh Debian 12 VM to test this.

Out of the box, downloading the Debian 12 .deb from VeraCrypt's website, opening it in either Software Install, or running `apt install -f ./veracrypt-1.26.7-Debian-12-amd64.deb` as root both installs and works fine for me.

Also, you don't need to build the program from source necessarily unless you need it for development. To mainstream the building from source steps, the package names and instructions are what you would need to do on an Ubuntu system (for example the package names differ on other distrobution repos). When you finished the make, the binary should be in `src/Main/veracrypt`. If the .deb doesn't work for you for some reason, you can try the Linux generic installer, and running the `veracrypt-1.26.7-setup-gtk3-gui-x64` script.

**Comment by morton-f** [comment]
Successfully installed `veracrypt-1.26.7-Debian-12-amd64.deb` on Debian 12 on real hardware. For installation was used the same command as provided by Jertzukka. Also followed with another successful installation with GDebi. Don't try to install the package with `dpkg -i` command as it will cause dependency errors.
