### ISSUE TITLE
Spelling Error in "VeraCrypt User Guide.pdf"

### ISSUE THREAD

**Issue by TestingContributor** [veracrypt/VeraCrypt#125]
On page 84 of "VeraCrypt User Guide.pdf" (located C:/Program Files/VeraCrypt/VeraCrypt User Guide.pdf)
there is a missing letter.

Specifically, it is missing an "e" in the quote "Please not that this switch may [...]" after "not"

**Comment by idrassi** [comment]
Thanks! I have fixed this spelling error in the source ODT file (https://github.com/veracrypt/VeraCrypt/commit/386f7bc9b043a2140b61210289ee27b03ca3fda8)
The PDF of the next release will include this fix.
