### ISSUE TITLE
OpenBSD VeraCrypt crashes at startup

### ISSUE THREAD

**Issue by justanotherscript** [veracrypt/VeraCrypt#1290]
# Expected behavior

# Observed behavior

cat veracrypt.log                                             
ASSERT INFO:
./src/common/sizer.cpp(2294): assert "CheckSizerFlags(!((flags) & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)))" failed in DoInsert(): wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL will be ignored in this sizer: wxEXPAND overrides alignment flags in box sizers

DO NOT PANIC !!

If you're an end user running a program not developed by you, please ignore this message, it is harmless, and please try reporting the problem to the program developers.

You may also set WXSUPPRESS_SIZER_FLAGS_CHECK environment variable to suppress all such checks when running this program.

If you're the developer, simply remove this flag from your code to avoid getting this message. You can also call wxSizerFlags::DisableConsistencyChecks() to globally disable all such checks, but this is strongly not recommended.

BACKTRACE:
(null)

# Steps to reproduce

1.  openbsd terminal pkg_add veracrypt (already ported to openbsd)
2. launch it for example: veracrypt or veracrypt &

# Screenshots

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 
pkg_info veracrypt
Information for inst:veracrypt-1.25.9p1

**Operating system and version:** 
OS: OpenBSD 7.4 amd64

**System type:** 
64bit

**Comment by Jertzukka** [comment]
VeraCrypt doesn't officially support OpenBSD and thus is not tested on it. Even the support for FreeBSD has a lot of room for improvement and is not that often tested as it has less users.

**Comment by bugtracker2019** [comment]
You use an old version of Veracrypt. This bug was fixed in 1.26.7.
If you wanna learn more about your issue, have a look [here](https://github.com/veracrypt/VeraCrypt/pull/999).
