### ISSUE TITLE
Veracrypt hangs Windows Defender / Windows with CLOCK_WATCHDOG_TIMEOUT

### ISSUE THREAD

**Issue by darmbrust** [veracrypt/VeraCrypt#130]
On Windows 10, when Windows Defender scans an installation of Veracrypt 1.19 (or even when trying to run the installer extract-only option of veracrypt) Windows 10 hangs hard, with a CLOCK_WATCHDOG_TIMEOUT

If you install Veracrypt, it appears to install ok, but then windows hangs randomly quite frequently with the same, (or a similar) error.

I was able to extract the windows Veracrypt files on a Windows 7 system, and put them on the Windows 10 system (but only if I disabled windows defender for a time).  Veracrypt would launch fine with defender disabled.  But when on, windows would instantly hang if you touched the Veracrypt files in a way that triggered the scan.

**Comment by alt3r-3go** [comment]
It's been a while and looks like this is no longer a problem - I can't reproduce this on a current Win10 with updated WinDefender and its definitions. @darmbrust, is that still a problem for you by any chance?

**Comment by darmbrust** [comment]
No, I don't believe this is still a problem.  At some point, I installed 1.21 of veracrypt, forgetting I filed this bug, and I haven't seen the issue again.
