### ISSUE TITLE
Serious flaw in plausible deniability on encrypted drives!

### ISSUE THREAD

**Issue by Rakly3** [veracrypt/VeraCrypt#1328]
# Description
When creating an encrypted drive it is very easy to tell whether there is or isn't a hidden volume.

# Current behavior
When mounting an encrypted drive _without_ a hidden volume, VeraCrypt 'type' will show type 'normal'.
When mounting the _outer volume of an encrypted drive_, which does have a hidden volume, the type will show 'Outer'.

If a malicious actor is aware of this, they can easily tell if you are lying or not, defeating plausible deniability.
Now, I'm not an expert on this by any means, but it stands to reason forensics COULD possibly also somehow detect this, perhaps.

# Desired behavior
There should be no way of telling a hidden partition exists. Understandably this would also then not be detectible by the owner/user of the drive.

# Screenshots/Mockup/Designs
![image](https://github.com/veracrypt/VeraCrypt/assets/41653584/8443c37f-798a-46f7-9800-debdab839fed)

# Your Environment
Windows 10 x64

**VeraCrypt version:** 
1.26.7 (64-bit)
Released by IDIX on October 1, 2023

**Comment by Rakly3** [comment]
PS, this has to be fixed in all languages. Otherwise changing the language could still give it away.

**Comment by Jertzukka** [comment]
A volume with or without a hidden volume will show as "Normal" when mounted, unless you use hidden volume protection in which case it will show as "Outer". If you were forced to reveal your volume password, you would only give out your outer volume password.

**Comment by Rakly3** [comment]
> A volume with or without a hidden volume will show as "Normal" when mounted, unless you use hidden volume protection in which case it will show as "Outer". If you were forced to reveal your volume password, you would only give out your outer volume password.

I'm talking about encrypted drives. With drives it will say 'outer'.

**Comment by Rakly3** [comment]
> A volume with or without a hidden volume will show as "Normal" when mounted, unless you use hidden volume protection in which case it will show as "Outer". If you were forced to reveal your volume password, you would only give out your outer volume password.

ok, thanks!
