### ISSUE TITLE
Further prevent ability to access memory on Windows

### ISSUE THREAD

**Issue by wendig0x** [veracrypt/VeraCrypt#1337]
In KeePassXC project:
https://github.com/keepassxreboot/keepassxc/pull/10618

Maybe we should do the same?

**Comment by idrassi** [comment]
Indeed, this is a good addition. I will add similar change.
Thank you for sharing this.

**Comment by idrassi** [comment]
I have pushed a commit to implement this enhancement: https://github.com/veracrypt/VeraCrypt/commit/e96f3035d9f3fb579de947d57317e596d67468be

Interestingly, I have found a bug in KeePassXC code related to this functionality and I filled a bug report (https://github.com/keepassxreboot/keepassxc/issues/10713) and a PR to fix it (https://github.com/keepassxreboot/keepassxc/pull/10712).
