### ISSUE TITLE
Compiling with Xcode 8.2.1 on macOS 10.12.3 Sierra

### ISSUE THREAD

**Issue by snap9** [veracrypt/VeraCrypt#135]
From the README.md:

> Because of incompatibility issues with OSXFUSE, the SDK 10.9 generates a VeraCrypt binary that has issues communicating with the OSXFUSE kernel extension. Thus, we recommend to use the SDK 10.8 or earlier for building VeraCrypt.

The problem is, Xcode 8.2.1 only comes with 10.12 SDK.

How do I build Veracrypt with Xcode 8.2.1 on macOS 10.12.3 Sierra?

**Comment by idrassi** [comment]
The Readme has been updated to indicate that the issue happens only with 10.9 SDK (see https://github.com/veracrypt/VeraCrypt/commit/8089c9d69fc16640b7acf4194c05dc0e2509babe).
You can build VeraCrypt with Xcode 8 and 10.12 SDK and it will work without any problem.
