### ISSUE TITLE
Compilation error on macOS Sonoma 14.5

### ISSUE THREAD

**Issue by Mattoje** [veracrypt/VeraCrypt#1361]
Latest (Jun 19th) commit, macOS sonoma 14.5, xcode 15.4

Compilation breaks here:
Compiling Keyfile.cpp
In file included from Keyfile.cpp:15:
In file included from /Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVToken.h:9:
In file included from /Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVCard.h:12:
In file included from /Volumes/Data/userdata/ports/VeraCrypt/src/Common/SCard.h:6:
In file included from /Volumes/Data/userdata/ports/VeraCrypt/src/Common/SCardManager.h:5:
/Volumes/Data/userdata/ports/VeraCrypt/src/Common/SCardReader.h:157:26: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
                SCardReader(SCardReader&& other);
                                       ^
/Volumes/Data/userdata/ports/VeraCrypt/src/Common/SCardReader.h:159:39: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
                SCardReader& operator = (SCardReader&& other);
                                                    ^
In file included from Keyfile.cpp:15:
In file included from /Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVToken.h:9:
In file included from /Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVCard.h:12:
/Volumes/Data/userdata/ports/VeraCrypt/src/Common/SCard.h:19:14: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
                SCard(SCard&& other);
                           ^
/Volumes/Data/userdata/ports/VeraCrypt/src/Common/SCard.h:21:27: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
                SCard& operator = (SCard&& other);
                                        ^
In file included from Keyfile.cpp:15:
In file included from /Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVToken.h:9:
/Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVCard.h:33:28: error: a space is required between consecutive right angle brackets (use '> >')
        vector<vector<uint8>> m_supportedAids;
                           ^~
                           > >
/Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVCard.h:47:45: error: a space is required between consecutive right angle brackets (use '> >')
                const static map<EMVCardType, vector<uint8>> SUPPORTED_AIDS;
                                                          ^~
                                                          > >
/Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVCard.h:52:18: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
                EMVCard(EMVCard&& other);
                               ^
/Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVCard.h:54:31: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
                EMVCard& operator = (EMVCard&& other);
                                            ^
In file included from Keyfile.cpp:15:
/Volumes/Data/userdata/ports/VeraCrypt/src/Common/EMVToken.h:38:52: error: a space is required between consecutive right angle brackets (use '> >')
                static map <unsigned long int, shared_ptr<EMVCard>> EMVCards;
                                                                 ^~
                                                                 > >
6 warnings and 3 errors generated.

**Comment by Mattoje** [comment]
Given my next to zero knowledge of C++ i tried to fix the error with this little patch:

``` diff --git a/src/Common/EMVCard.h b/src/Common/EMVCard.h
index 70ef035f..87acebe3 100644
--- a/src/Common/EMVCard.h
+++ b/src/Common/EMVCard.h
@@ -30,7 +30,7 @@ namespace VeraCrypt
         // object will be considered invalid and will not be included in the list of available cards
         // of EMVToken.
         vector<uint8> m_aid;
-        vector<vector<uint8>> m_supportedAids;
+        vector<vector<uint8> > m_supportedAids;
         vector<uint8> m_iccCert;
         vector<uint8> m_issuerCert;
         vector<uint8> m_cplcData;
@@ -44,7 +44,7 @@ namespace VeraCrypt
                const static uint8 AMEX_AID[7];
                const static uint8 MASTERCARD_AID[7];
                const static uint8 VISA_AID[7];
-               const static map<EMVCardType, vector<uint8>> SUPPORTED_AIDS;
+               const static map<EMVCardType, vector<uint8> > SUPPORTED_AIDS;
 
         EMVCard();
                EMVCard(size_t slotId);
diff --git a/src/Common/EMVToken.h b/src/Common/EMVToken.h
index d82ea542..8fd7496f 100644
--- a/src/Common/EMVToken.h
+++ b/src/Common/EMVToken.h
@@ -35,7 +35,7 @@ namespace VeraCrypt
 
                friend void EMVTokenKeyfile::GetKeyfileData(vector <uint8>& keyfileData) const;
 
-               static map <unsigned long int, shared_ptr<EMVCard>> EMVCards;
+               static map <unsigned long int, shared_ptr<EMVCard> > EMVCards;
        };
 }
```
Ofc i have no idea if this fix works but this lead to another error which is far beyond my c++ coding skills:
Compiling SCardManager.cpp
In file included from ../Common/SCardManager.cpp:1:
In file included from ../Common/SCardManager.h:5:
../Common/SCardReader.h:157:26: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
                SCardReader(SCardReader&& other);
                                       ^
../Common/SCardReader.h:159:39: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
                SCardReader& operator = (SCardReader&& other);
                                                    ^
../Common/SCardManager.cpp:6:40: error: redefinition of 'loader' with a different type: 'VeraCrypt::SharedPtr<SCardLoader>' vs 'shared_ptr<SCardLoader>'
        shared_ptr<SCardLoader> SCardManager::loader = make_shared<SCardLoader>();
                                              ^
../Common/SCardManager.h:12:34: note: previous declaration is here
                static shared_ptr<SCardLoader> loader;
                                               ^
../Common/SCardManager.cpp:90:40: error: return type of out-of-line definition of 'VeraCrypt::SCardManager::GetReader' differs from that in the declaration
        shared_ptr<SCardReader> SCardManager::GetReader(size_t readerNumber)
        ~~~~~~~~~~~~~~~~~~~~~~~               ^
../Common/SCardManager.h:17:34: note: previous declaration is here
                static shared_ptr<SCardReader> GetReader(size_t readerNumber);
                       ~~~~~~~~~~~~~~~~~~~~~~~ ^
../Common/SCardManager.cpp:100:22: error: no matching function for call to 'make_shared'
                        smartCardReader = make_shared<SCardReader>(readers[readerNumber], loader);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/Data/userdata/ports/VeraCrypt/src/Platform/SharedPtr.h:171:21: note: expanded from macro 'make_shared'
#define make_shared VeraCrypt::make_shared
                    ^
/Volumes/Data/userdata/ports/VeraCrypt/src/Platform/SharedPtr.h:166:45: note: candidate function template not viable: requires single argument 'arg', but 2 arguments were provided
        template <class T, class A> shared_ptr <T> make_shared (const A &arg)
                                                   ^
/Volumes/Data/userdata/ports/VeraCrypt/src/Platform/SharedPtr.h:161:36: note: candidate function template not viable: requires 0 arguments, but 2 were provided
        template <class T> shared_ptr <T> make_shared ()
                                          ^
2 warnings and 3 errors generated.
make[1]: *** [../Common/SCardManager.o] Error 1
make: *** [all] Error 2

**Comment by idrassi** [comment]
This issue happens because  `-std=c++11` is defined in Makefile only in case of Release build and when LOCAL_DEVELOPMENT_BUILD is set to true which seems to be your case.

To solve it, we need to define `CXXFLAGS += -std=c++11` in all cases. I have pushed a commit that does this: https://github.com/veracrypt/VeraCrypt/commit/8b01b533cfeafc989137c202af61c83f63c5f531

No other modifications are needed.

**Comment by idrassi** [comment]
Thank you for this report. I will close this issue as fixed but please feel free to reopen it in case you are still encountering issues.
