### ISSUE TITLE
 Linux System to build VeraCrypt

### ISSUE THREAD

**Issue by kazemnasab** [veracrypt/VeraCrypt#1364]
I want to have an integrated installer for different versions of Linux (for each distribution). how i can resolve library version error?

**Comment by idrassi** [comment]
what do you mean by "integrated installer"? 
In VeraCrypt, we have a generic installer that works on all Linux distribution and it is built on CertOS:

- for GTK2 generic installer, we use CentOS 6 for the build.
- for GTK3 generic installer, we use CentOS 7 for the build.

Does this answer your question?

**Comment by idrassi** [comment]
Closing this issue since building under CentOS 6/7 provides maximum compatibility across Linux distributions.
