### ISSUE TITLE
Unable to activate Windows Store apps

### ISSUE THREAD

**Issue by tobiasstraub** [veracrypt/VeraCrypt#138]
There is a problem with developing Windows UWP Apps with Visual Studio and the subsequent activation of these apps.

1. Open Visual Studio
2. Create an UWP project and save it on an encrypted volume
3. Build it
4. Run it in Debug mode on Local Machine
**Error**: Unable to activate Windows Store app. The *.exe process started, but the activation request failed with error 'The app didn't start'.

There are more users, which have the same problem:

- http://stackoverflow.com/questions/19847563/unable-to-activate-windows-store-app-the-app-didnt-start/20270214#20270214 
- http://stackoverflow.com/questions/13404315/unable-to-activate-windows-store-app/23606983#23606983
- https://social.msdn.microsoft.com/Forums/en-US/29b3afe7-ef59-4269-8652-3cc0ff044e96/unable-to-activate-windows-metro-style-application?forum=toolsforwinapps
- http://howcanisolve.com/29879/unable-to-activate-windows-store-app-the-app-didnt-start

_**Edit**: Sorry there was opened an issue with the same problem long time ago, see #14._

Is there any workaround?

**Comment by wniva** [comment]
I have the same problem with current VS 2022 and VeraCrypt 1.25.9 (64-bit). If the project folder on a VeraCrypt drive then comes the failure. I tried mklink and junction (Sysinternals) from a "normal" drive to a VeraCrypt drive, but with no success.

**Comment by wniva** [comment]
Workaround: "Remote" Debugging with lokal machine:

![grafik](https://user-images.githubusercontent.com/103184839/162188392-e349d172-8f97-4010-b8d3-4e00611ee1cd.png)
