### ISSUE TITLE
.hc file extension

### ISSUE THREAD

**Issue by spotter226** [veracrypt/VeraCrypt#1393]
Although the file has the extension .hc it is not recognized by VeraCrypt and I cannot open it directly.

# Expected behavior

If the file has the .hc extension, the VeraCrypt icon should appear so you can open it directly

# Observed behavior

Although the file has the extension .hc it is not possible to quickly open the file

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 
1.26.7

**Operating system and version:** 
Windows 11 23H2 Build 22631.3880

**System type:** 
64 bit

**Comment by Jertzukka** [comment]
Choose "Associate .hc extension with VeraCrypt" on the Setup installer.

**Comment by spotter226** [comment]
I did but it didn't work

**Comment by idrassi** [comment]
If the `.hc` association setting is selected in the installer, the registry key "`HKEY_CLASSES_ROOT\VeraCryptVolume\Shell\open\command`" is created and it will contain a default value set as "`"C:\Program Files\VeraCrypt\VeraCrypt.exe" /v "%1"`".  
Also the registry key "`HKEY_CLASSES_ROOT\.hc`" is created and its default value is set to "`VeraCryptVolume`".  
So it looks like these registry keys are missing in your case. Can you please check?

I don't have an explanation as to why it fails on your machine but you can set the association manually in a persistent way by right-clicking on a `.hc` file and selecting **"Open with"**, then choosing **"Choose another app"**.  
After that, select **VeraCrypt** from the list or browse to `C:\Program Files\VeraCrypt\VeraCrypt.exe` if it’s not listed.  
Make sure to click **"Always"** afterwards.

This will ensure that `.hc` files are always associated with VeraCrypt.

**Comment by spotter226** [comment]
I checked the registry and, indeed, the entry "VeraCryptVolume" was missing in "HKEY_CLASSES_ROOT\.hc". Now the files work, but this icon appears. I remembered the original VeraCrypt icon appearing. Is this normal?
![immagine](https://github.com/user-attachments/assets/fab60f98-ebc9-4d2f-afad-98d1a5381270)

**Comment by spotter226** [comment]
I checked the registry and, indeed, the entry "VeraCryptVolume" was missing in "HKEY_CLASSES_ROOT.hc". Now the files work. Thank you very much 😊

**Comment by idrassi** [comment]
Thank you for the feedback and the confirmation. I'm glad manual association worked.
I will close this issue for now. We will see if other report similar behavior.
