### ISSUE TITLE
Windows Store App Debugging in VS and VeraCrypt

### ISSUE THREAD

**Issue by 0x8DEADF00D** [veracrypt/VeraCrypt#14]
I actually don't know where to report this issue exactly but I will give this a try here:

If you open up Visual Studio and start a new Windows 8.1 Store project you will probably receive an error message similar to this one:

> Unable to activate Windows Store app 'Package Name'. The App1.exe process started, but the activation request failed with error 'The app didn't start'.
> 
> See help for advice on troubleshooting the issue.

As I was researching what the cause may be, I stumbled upon this [question on SO](http://stackoverflow.com/questions/19847563/unable-to-activate-windows-store-app-the-app-didnt-start) where the accepted answer is claiming that the issue lies within TrueCrypt and moving the project to an unencrypted drive would resolve this.

Yes, this is true. The project did compile as I moved the project to my system parition which is also encrypted. However, there might be something wrong with the containers because the only thing that differs is that my system volume is completely encrypted while my external disk (where the project was initially stored) got a VeraCrypt container.

As VeraCrypt is originating from TrueCrypt I think that there has been this bug which has never been fixed. Do you have an idea what this is causing or where the root of the problem might be?

**Comment by Iamnvincible** [comment]
I have the same problem.

**Comment by andreas-becker** [comment]
Is this issue still alive or can it be replaced by #138 ? If so, @0x8DEADF00D please close the issue
