### ISSUE TITLE
Please keep supporting Windows XP

### ISSUE THREAD

**Issue by palikacska** [veracrypt/VeraCrypt#141]
As far as I know, Microsoft Visual Studio 2010 is the last one to support Windows XP. Please keep up the support for Windows XP. A lot of people still use this operating system and don't want to buy new computers for the high resource consumption of Vista/7.

**Comment by FadeMind** [comment]
XP is dead, Vista is dead, 7 will be dead very soon.

**Comment by kleuter** [comment]
You can target XP in [Visual Studio 2015](http://stackoverflow.com/questions/35664861/how-to-target-windows-xp-in-microsoft-visual-studio-c) (not sure about 2017)

**Comment by palikacska** [comment]
An operating system is dead when nobody ever uses it. XP is still in use. 9% of the users still use XP. The problem with upgrade is higher hardware requirements. Don't expect anyone to throw trash their computer just Microsoft couldn't optimize Windows 7 for older hardware. Please keep up suporting XP. There are great  and up-to-date tools (like Visual Studio) that supports XP.

**Comment by trumpet205** [comment]
If XP can be still supported without too much work, sure. If not it should be dropped, as people have said, it is a dead OS. XP stopped receiving security updates long ago.

As long as your PC supports SSE2 and NX bit you can install a modern lightweight Linux and continue to use it. If your PC doesn't support SSE2 and NX bit it would be way too old anyway.

**Comment by palikacska** [comment]
An OS is not dead until it is being used. The presence of security updates do not influence VeraCrypt functionality as it didn't influence TrueCrypt either.

Btw, thanks for letting me know. Hope you'll support XP at least until the usage drops below 1%. Now it's around 10% worldwide.

**Comment by 5moufl** [comment]
Your numbers are way off. people shouldn’t use an OS with no security updates anyway.
https://en.wikipedia.org/wiki/Usage_share_of_operating_systems

**Comment by palikacska** [comment]
No they're not way off. 100 million people use Windows XP and you can stay secure if you are not stupid and not clicking on every advertisement you see.

**Comment by bazzilic** [comment]
100 million people is way less than 10% of the OS market. Anyway, you can't stay secure on an outdated OS unless it never gets connected to networks and never has anything new plugged in.

**Comment by palikacska** [comment]
Network security has **nothing** to do with features provided by Veracrypt. Let's not be idealists. Please.

It does not matter how many percent it makes. It is about **hundred million people** whom you potentially leave alone if you discontinue support. Microsoft has already left them alone with pulling the plug on security updates. This was unethical. Let's not follow them.

**Comment by bazzilic** [comment]
So, first it's 10%, then it doesn't matter how many percent it makes, I see. Microsoft pulled the plug after **12 years** of support, name one other OS that was supported for nearly that long. How long should they have supported it for you to consider it ethical? 50 years?

Anyhow, don't drag random figures and numbers into this to make an artificial support for the fact that _you_ use XP for some reason, and _you_ want to have VeraCrypt there. Yes, there's a hundred million or so of XP computers. That does not translate to a hundred million of VeraCrypt users. The question is, how many _VeraCrypt users_ are there on XP: is it enough to justify investment in supporting the platform?

**Comment by palikacska** [comment]
So your we're talking about 'investment' at a free software project. Congratulations. -.-" Your arrogance is exceptional, my dear wild-capitalist friend.

What do you think why is Windows XP still at 7.44% on NetMarketShare three years after support was ended. And why is Vista at 0.72%? Because XP was an usable, well-optimized operating system and switching would require trashing our computers.

You don't have the numbers how many use VeraCrypt on XP. Neither do I. But I do. And a public issue forum has an important purpose: to let others know about important things.

Talking about 'ethical', if more people use VeraCrypt than your developer team consists of, the ethical way is to support XP.

**Comment by bazzilic** [comment]
I find yout definition of "ethical" very random, tbh.

Free software projects don't grow on trees, you know; they still require investment of resources: money, equipment and manpower. As well as they have goals, e.g., increasing user base, solving use cases, etc. Supporting one more OS (esp. an old one) in a cross-plat project means (at the very least) additional testing, limited use of OS APIs, dancing around OS-specific quirks and bugs, all of which directly translates into additional resources that need to be spent.

If these investments are justified (which I'm not saying they are not!), then supporting the OS makes sense. It could be that half of VeraCrypt users are actually on XP, and it totally makes sense to support it. However, I highly doubt that that's the case.

**Comment by AARRGGHHH** [comment]
> [P]eople shouldn’t use an OS with no security updates anyway.

I see.  So you want me to trust Microsoft with my computer security?  If I did, I'd use Bit Locker and I wouldn't even be here.  I use VeraCrypt on my XP machine and a third party firewall and anti virus and anti malware and could not possibly care less about the lack of Microsoft "security".

**Comment by taukausanake** [comment]
Can't you just build it for Windows Embedded and get XP support that way? It's almost the exact same thing.

But I agree. Doesn't matter if an operating system is in use anymore, it's all about the end user and if they know what they are doing then they should be allowed to keep doing it

**Comment by AARRGGHHH** [comment]
Something that crossed my mind regarding product support and "dead" software:  Microsoft released Visual Basic 6 in 1998.  They went on to mutilate the language with the release of Visual Basic 7 (VB.Net) and all subsequent releases.  Even though extended support ended in 2008, they were pressured to bring back limited support through the life cycle of Windows 7, and then Windows 8, and now Windows 10.  So limited support of this "dead" language is now guaranteed through at least 2025.  

If users like something, and find that it suits their needs, you can't kill it just by telling them not to use it.

**Comment by bazzilic** [comment]
Well,
a) Yes you can. Google has a notorious track record of doing this.
b) VB is still supported not because people said "pretty please", it's because large Microsoft customers who pay hundreds and hundreds of thousands of dollars in license and support fees every year have a large VB codebase, and it's not in MS's interest to let down a big customer, even though dragging VB into new releases is a burden.
c) Regarding your phrase "So you want me to trust Microsoft with my computer security?": I'd like to see how your antivirus, firewall, and whatever else you use would have helped you with the recent ETERNALBLUE vulnerability in SMBv1, which MS has patched even though XP is not supported anymore. Using something like VeraCrypt on an unsupported system is similar to having a vault door on a camping tent.

**Comment by Atavic** [comment]
I have XP offline and I encrypt precious files in it. Please keep supporting XP if possible.
