### ISSUE TITLE
[Linux/Gnome] Cannot open volume if file-manager is not nautilus

### ISSUE THREAD

**Issue by bugtracker2019** [veracrypt/VeraCrypt#1420]
Running VeraCrypt 1.26.14 under Gnome with Caja instead of Nautilus (default) as file-manager.
Mounting a volume and then double-click on it, in order to open the volume in the file-manager, results in an error message (see screenshot).

# Expected behavior
Volume should open in any file-manager.

# Steps to reproduce
1. Install VeraCrypt under Gnome.
2. Get rid (uninstall) of Nautilus and install any other file-manager (i.e. Caja).
3. Start VeraCrypt, mount a volume and double-click on it.
4. Error message

# Workaround
Reverse the order of "desktop" in UserInterface.cpp (line 902 and following) is a solution.
See attached file [UserInterface.patch.zip](https://github.com/user-attachments/files/17103049/UserInterface.patch.zip)

# Screenshots
![VeraCrypt-error88](https://github.com/user-attachments/assets/ddc793f1-d3e1-491b-aa58-a75d24373a6c)

Please tell us more about your environment

**VeraCrypt version:** 1.26.14

**Operating system and version:** Arch Linux, Gnome 47, Caja 1.28

**Comment by Jertzukka** [comment]
I think xdg-open is quite well and widely supported nowadays so I agree that it should be the default nowadays, but the patch probably still needs a check to ensure you actually have nautilus before trying to launch it, and not just assume it so because you're on GNOME. I can probably look at making a PR at some point when I have the time.

**Comment by idrassi** [comment]
@Jertzukka @bugtracker2019 
I have just pushed a change that combines the idea of using xdg-open and checks for popular filemanagers: https://github.com/veracrypt/VeraCrypt/commit/92ad97ef33c88ef15d4e267472bae447a2a0f09c
Let me know your thoughts.

**Comment by bugtracker2019** [comment]
Hello Jertzukka and idrassi,

thx for looking into this and your change, idrassi.

I would go one step further and erase the check for popular filemanagers completly.
No need for that, just use xdg-open. Works fine without. Also you burden yourself some additional work: regulary check, if the corresponding filemanagers are still existent and check for new ones.
