### ISSUE TITLE
Feature Request: Encrypt to Erase

### ISSUE THREAD

**Issue by MrChriZ** [veracrypt/VeraCrypt#143]
It would be handy if Encryption tools had an encrypt to erase function which encrypts an entire volume with a completely unknown randomly generated password.

This way anywhere you had VeraCrypt installed you'd instantly also have a quick way of effectively erasing a volume.

This would also add a potential legal defence in which you were forced to reveal a volumes password - in that you can state you just used the encrypt erase function - rather than actually using the encryption to store data - and as such you have no password to give.

**Comment by NumDeP** [comment]
+1 

In addition, I think it won't matter much the level of hash or encryption type/method, a simple 'Auto. E-to-E' function will suffice. 

Should someone contact PrivaZer to contribute?
