### ISSUE TITLE
Veracrypt_fuse-t Not able to mount a volume on MacOS Sonoma 14.7.1 (23H222) 

### ISSUE THREAD

**Issue by carefulcomputer** [veracrypt/VeraCrypt#1438]
Not able to mount a new volume or create a new volume on MacOS Sonoma 14.7.1 (23H222) 
Get this error when either mouting existing volume or creating a new volume from scratch

<img width="268" alt="image" src="https://github.com/user-attachments/assets/966e91fb-0455-42a9-9341-8590d5137530">

# Expected behavior
Volume mounted without issue and new volume created without issue.

# Observed behavior
Get error popup with message

No such file or directory:
/var/folders/_8/_0b_4dmd4rv1rxpq40y2v43m0000gr/T//.veracrypt_aux_mnt1/control
VeraCrypt::FilesystemPath::GetType:48

# Steps to reproduce
1.  Use MacOS Sonoma 14.7.1 (23H222) 
2. install fuse-t 1.0.44 (latest as of this message)
3. Install fuse-t-sshfs 1.0.2.pkg (latest as of this message)
4. Try to mount an existing volume (created with non fuse-t version of veracrypt) or create a new volume
5. Get the error

# Screenshots

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 
Veracrypt 1.26.14 (Fuse-T build)
<img width="588" alt="image" src="https://github.com/user-attachments/assets/1aa120ec-3ae8-47fe-b52c-e129e0e86f52">

**Operating system and version:** 
MacOS Sonoma 14.7.1 (23H222) 

**System type:** 
64 bit

**Comment by ChubbyAnt** [comment]
For Macos 15.1.1 the solution appears to be modify the .ini  file as follows:

;namedattr=false
;attrcache=false

sudo nano /Library/Application\ Support/fuse-t/cfg/fuse-t.ini

The default .ini settings have both of the entries above set to "true." Change both of these to "false". Restart the mac.

This issue is mentioned here: https://github.com/cryptomator/cryptomator/issues/3538

Note, for me changing namedattr to false alone did not help. Changing both namedattr and attrcache to "false" appears to have solved the "Type:48" error mentioned above for my Macbook M4.

**Comment by carefulcomputer** [comment]
Perfect! that worked. Thank you @ChubbyAnt !

**Comment by ChubbyAnt** [comment]
Although still on MacOS 15.1.1, it appears that something may have changed in my config, and the following is no longer working:

;namedattr=false
;attrcache=false

Getting GetType:48 error as noted by OP above.

**Comment by codeomme** [comment]
Same for me. 
Since a few days, Veracrypt is not working.
No matter if I’ve made the changes in the config or not. 
Reinstalled it without success. 

Someone has a fix for that?

**Comment by codeomme** [comment]
I fixed it. Solution was damn simple...
Completely uninstall fuse-t and veracrypt. Cleaned up all left over files from them.
Restarted my mac and clean installed fuse-t and then veracrypt. Now its working.

**Comment by caselmann** [comment]
MacOS 15.3.1...same error, both "fixes" mentioned above don't work. :(

**Comment by Gil-Grissom24** [comment]
MacOS 15.3.1...same error, both "fixes" mentioned above don't work. :(

**Comment by carefulcomputer** [comment]
Try rebooting. It worked for me after clean install and rebooting.

**Comment by codeomme** [comment]
@jamesdrake101 pls don’t panic. I have the same iOS installed and using it every day. It works fine. 

As I said before:
> I fixed it. Solution was damn simple...
> Completely uninstall fuse-t and veracrypt. Cleaned up all left over files from them.
> Restarted my mac and clean installed fuse-t and then veracrypt. Now its working.

**Comment by ZingyAwesome** [comment]
Same issue here, no amount of reinstalling and rebooting fixed it for me. See https://github.com/veracrypt/VeraCrypt/issues/1579#issuecomment-3398964448.
