### ISSUE TITLE
Linux: Broken build system

### ISSUE THREAD

**Issue by lachs0r** [veracrypt/VeraCrypt#145]
Building and packaging on Linux is kind of a pain. The current makefile does not detect architecture features correctly and attempts to compile without `-maes` on GCC 6+. It also lacks a proper install rule and always attempts to build some makeself archive no Linux user wants.

**Comment by idrassi** [comment]
I can't reproduce `-mase` issue with GCC 6: I tested on Ubuntu 17.04 with gcc 6.3.0 and VeraCrypt Makefile correctly `-maes` to gcc flags. Can you please share your environement details?

Concerning the second point, I have modified Makefiles to separate between build and packaging and also add an install target: https://github.com/veracrypt/VeraCrypt/commit/5d0321291f4df297b0d9f9837099a36cdf1c83b6
