### ISSUE TITLE
unable to create NTFS-formatted container

### ISSUE THREAD

**Issue by jitbit** [veracrypt/VeraCrypt#147]
Same bug TrueCrypt had. On Windows 10 it impossible to format container as NTFS

https://superuser.com/questions/630097/cant-format-truectypt-file-container-to-ntfs many people having this issue.

**Comment by FabianFrancoRoldan** [comment]
I created a NTFS container on Windows 10 without issue.

**Comment by jitbit** [comment]
"works on my machine" (tm)

**Comment by Helyk** [comment]
I faced this issue too and also it's present with exFAT. It repeats with both file container and encrypted volume. Tried with sizes 250 Gb and 2 Tb, it formats for like 3 hours then says that it can't but FAT can be done, if I agree it does FAT in few seconds. Issue appeared after I updated Windows 10 (previous update was around a year ago).
Looks identical to this: https://superuser.com/questions/630097/cant-format-truectypt-file-container-to-ntfs
