### ISSUE TITLE
Veracrypt GUI is not working on Kali

### ISSUE THREAD

**Issue by immodest** [veracrypt/VeraCrypt#150]
Hello, 

I've installed Veracrypt using provided scripts, but after the installation the GUI is not working. 
Nothing happens when I click the icon on Gnome dash. CLI version works fine. 

Is there a  ommand to launch the graphical version of the program from the terminal? 

Thanks.

**Comment by idrassi** [comment]
Hi,

I have just tested VeraCrypt 1.19 with Linux Kali 2017.1 and the GUI without any issue.
Are you sure you installed the GUI version veracrypt-1.19-setup-gui-x64?

I think you installed the console version which doesn't have any GUI. Try using the GUI installer to get the GUI version.
You can still use the GUI version through the command line by adding the switch --text as first argument.

Closing this ticket. Please feel free to reopen if you still have an issue.
