### ISSUE TITLE
VC crashes on Raspberry Pi 3 running on Raspbian Jessie (with Pixel) 

### ISSUE THREAD

**Issue by noctcrawler** [veracrypt/VeraCrypt#158]
I'm not exactly an expert on Linux/Unix, but I have managed to get VeraCrypt installed. Only thing is, when I try to run it, the hour glass appears on the cursor, but then... nothing! What's wrong? Is there a way to get it to run?

**Comment by noctcrawler** [comment]
Anyone???!!!!!!

**Comment by idrassi** [comment]
Can you please check if the crash still occurs with the latest 1.21 release available at https://www.veracrypt.fr/en/Downloads.html?
