### ISSUE TITLE
please help - can't boot/unencrypt PARTIALLY encrypted Win10 system-SSD / repair loop

### ISSUE THREAD

**Issue by Micha1305** [veracrypt/VeraCrypt#159]
Hi everybody,

I would like to ask for your help. I guess I made my ssd unaccessible forever – but still want to ask here, because I’ve seen IT-pros doing awesome stuff. Maybe one of you can actually still help me – or confirm me that I actually lost my data forever.

I messed up trying to fully encrypt my win10 64bit system partition drive (Samsung ssd, 1 gig) on an uefi-bios, using veracrypt 1.19. Board is an ASUS Z170 PRO GAMING.

Problem short: After partial (a few seconds) encryption, sudden reboot happened and now I am being caught in an endless Windows 10-repair-loop. Rescue-USB-Stick doesn’t seem to help (can’t encrypt – nor does booting work). “Mount without pre-boot” doesn’t work because encryption isn’t finished yet.

What I did so far (from

- Run pretest -> failed -> so I turned off the secure-boot
- Pretest succeeded -> clicked on start encryption now -> Encryption started and a few seconds later, the Computer rebooted unannounced and…
- … is caught in an Windows 10-repair-loop (tried anything to get out of this ->no way)
- Tried the verycrypt-rescue-usb-stick ->was shocked, because it’s a new menu, starting with d) and isn’t that clear to me like former rescue-disk-menus (I am not a native English speaker)
- Couldn’t manage to either totally unencrypt the ssd or getting the system to boot
- Plugged the SSD into another computer and tried to “mount without pre-boot-authentication” -> not possible, because “Error: The process of encryption of the partition/drive has not been completed. It must be completed first.”
- But I can’t do that…
- Being really(!) desperate now and afraid that I lost my data forever.

I read that there is a bug in 1.19 rescue-disk and also downloaded a fix from another thread on codeplex.com, but I don’t dare to do anything now as I am afraid that I have a) only one chance and b) fxxk it up totally just before finding out too late what I SHOULD HAVE done… I am just too stuxxd in these things. Just scared now to do anything wrong and lose all data and the chance the regain it.

I beg a professional to help me and promise to be grateful if someone invests time and has a solution to get at least my personal data back. Thank you for your time. I hope someone knows a way out of this. I also apologize in advance if I lacked giving information that would have been important. Please ask and I’ll tell you what you need to know.

Thank you!
Micha

**Comment by mnordlin** [comment]
You should not expect support from a professional here, as it's not an issue with VC (VeraCrypt). VC has not been designed for Windows 10, which has made the encrypted boot partition a requirement on new PCs. You cannot boot your ASUS PC from your SSD, which has no MBR. If it had had MBR, the forced Windows updates would have removed it like they did mine. As you want to backup your SSD now, better late than never, you obviously have to run the backup process on a PC which can access the SSD in question. That PC might well be the ASUS PC only, in which case you would have to boot it from another bootable medium which your ASUS would allow (secure boot disabled of course). The medium would have to accomodate for the backup image(s) as well, so a 4 GB SD(Card) would not suffice. - If you cannot bring your ASUS to boot from a SDC, the other option would be to replace the SSD and then back it up, but there probably would be no interface (SATA/ATA) to attach the cable to. My Asus laptop came with Windows 10 preinstalled, SSD onboard and EDI/GPT, so the only option would be encryption from MS. I'm pretty sure that VC won't one day come with a rescue disk that fixes messed-up GPT partitions. That's not what it's there for. Companies like TeraByte Unlimited might be better suited for such an endeavor (and they endorse MBR, claiming EDI/GPT is flawed). Sorry for that, but I will inspect my next PC more carefully before buying it. But it will then probably not come with Windows 10 preinstalled (not on SSD at least). I hope this clarifies your options. Good luck!
