### ISSUE TITLE
Upgrade from 1.12 to 1.13-BETA doesn't upgrade bootloader

### ISSUE THREAD

**Issue by c0d3z3r0** [veracrypt/VeraCrypt#16]
Upgrade from 1.12 to 1.13-BETA doesn't upgrade bootloader on Windows 10

**Comment by idrassi** [comment]
The 1.13-BETA was an emergency build to solve an issue with Tor Browser and the bootloader was not rebuilt during its packaging.
The final 1.13 that I will release in less than hour will have its own bootloader.

**Comment by c0d3z3r0** [comment]
Ah great! The Problem was that I got an 'Evial Maid' error because of the version mismatch.

**Comment by idrassi** [comment]
Yes!

I have uploaded the finalized 1.13 version to Codeplex and Source. You can install to solve this issue.

**Comment by c0d3z3r0** [comment]
Problem solved, thanks
