### ISSUE TITLE
Submit to distros

### ISSUE THREAD

**Issue by rugk** [veracrypt/VeraCrypt#162]
It would be nice if this application could be included in Debian's, Fedora's, etc. packages.

**Comment by Mikaela** [comment]
Another possibly universal method would be #187. I sometimes use 2-6 devices physically and fear the effort of manual updating would make me slip or forget to update somewhere that I use less often. 

*I am adding this comment so the issues get aware of each other as I would be interested in finding both of them with a single search and I consider them as related.*

**Comment by ElMostafaIdrassi** [comment]
#511

**Comment by ElMostafaIdrassi** [comment]
Distribution via Debian / RPM packages has been included starting version 1.24 using `CMake / CPack` combo, and will hopefully be the way to go from now on. See #511

**Comment by godfuture** [comment]
> Distribution via Debian / RPM packages has been included starting version 1.24 using `CMake / CPack` combo, and will hopefully be the way to go from now on. See #511 and #512

As I would like to see Clonezilla supporting Veracrypt, it is required that Debian adds it to official repositories. Do I understand it right that Veracrypt did not fulfill the requirements of official Debian repository and thus it was never part of it?

In other words...will Veracrypt be part of Debian repo considering changes you just announced?
