### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nonegit** [veracrypt/VeraCrypt#176]
0. Open GUI.
1. Right-click "System Drive" and click properties.
3. Look at VC Boot Loader version.

Expected result:
1.20

Actual result:
1.2

**Comment by idrassi** [comment]
Thanks for spotting this. It was caused by a legacy code that was considering the last zero as not significant.
I have push a fix: https://github.com/veracrypt/VeraCrypt/commit/b7ed0c48924b030a8133c84e98a572c41bcaf1a1
