### ISSUE TITLE
1.20 - Windows binaries missing?

### ISSUE THREAD

**Issue by panther2** [veracrypt/VeraCrypt#179]
![vc](https://user-images.githubusercontent.com/20812775/27738578-fcf60fec-5dab-11e7-8156-bf545ca8fdff.gif)

**Comment by kleuter** [comment]
Also missing at sourceforge

**Comment by idrassi** [comment]
Following a crash report on Sourceforge forum, I temporarily removed Windows installer for 1.20 while investigating this issue.
I can not reproduce it but it seems to happen on some low end CPU.
More information here: https://sourceforge.net/p/veracrypt/discussion/general/thread/4a30f11c/#e4b6

That being said, if you can help test if the issue also happens on your side, I can share with you the installer.

**Comment by panther2** [comment]
Glad to read it has been fixed with the upcoming version 1.21. Thanks.
