### ISSUE TITLE
Performance related

### ISSUE THREAD

**Issue by necros2k7** [veracrypt/VeraCrypt#180]
[src\Common\SecurityToken.cpp:705]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[src\Main\VolumeHistory.cpp:43]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[src\Platform\Serializer.h:26]: (performance) Function parameter 'stream' should be passed by reference.
[src\Platform\Serializable.h:34]: (performance) Function parameter 'stream' should be passed by reference.
[src\Platform\FilesystemPath.h:41]: (performance) Function parameter 'path' should be passed by reference.
[src\Platform\FilesystemPath.h:43]: (performance) Function parameter 'path' should be passed by reference.
[src\Platform\MemoryStream.cpp:21]: (performance) Variable 'Data' is assigned in constructor body. Consider performing initialization in initialization list.
[src\Platform\FileStream.h:26]: (performance) Function parameter 'file' should be passed by reference.
[src\Platform\TextReader.h:28]: (performance) Function parameter 'stream' should be passed by reference.
[src\Volume\VolumePasswordCache.cpp:37]: (performance) Prefer prefix ++/-- operators for non-primitive types.

**Comment by idrassi** [comment]
There is no significant performance impact from these issues. The operations were these are used are not executed very often and they don't handle so much data.
If VeraCrypt was a text processor, then this would apply but in our case it is almost irrelevant.
Anyway, for the sake of code quality, I will take into account some of them.
