### ISSUE TITLE
[Bug] Veracrypt v1.21 Windows x64 BSOD

### ISSUE THREAD

**Issue by sierraatomic** [veracrypt/VeraCrypt#182]
BSOD while mounting container file.
Enter password -> OK -> BSOD.

Windows version: Microsoft Windows 10 (10.0) Professional 64-bit v15063.447
CPU: Intel Core 2 Duo E6850
Instruction sets: MMX, SSE, SSE2, SSE3, SSSE3, EM64T, VT-x

BSOD details:
- Bug Check String:     SYSTEM_THREAD_EXCEPTION_NOT_HANDLED
- Bug Check Code :     0x1000007e
- Parameter 1: 	         ffffffff`c0000005
- Parameter 2:	         fffff80e`87a93287
- Parameter 3: 	         ffffc400`77268418
- Parameter 4:             ffffc400`77267c60
- Caused By Driver:     veracrypt.sys
- Caused By Address:	 veracrypt.sys+14a49
- Crash Address:         veracrypt.sys+33287

**Comment by idrassi** [comment]
Can you please give more details about the PRF hash algorithm and encryption algorithm you are using?
For the sake of simplicity, it is better to select the correct PRF is the password dialog.

Do you reproduce the crash if you run tests from UI using the menu Tools -> Test Vectors?
Does the crash occur if you run benchmarks on hash algorithms and PRFS using menu Tools -> Benchmark?

Thank you for your help.

**Comment by sierraatomic** [comment]
VeraCrypt v1.19 works fine.

After some more tests: VeraCrypt v1.21 sometimes mount container correctly (no BSOD).

Requested information:
Encryption Algorithm: AES
Primary Key Size:         256 bits
Secondart Key Size:     256 bits
Block Size:                    128 bits
Mode of Operation:    XTS
PKCS-5 PRF:             HMAC-SHA-512
Volume Format Version:	2

VeraCrypt x64:		
Test Vectors - Passed
Benchmark Encryption Algorithm - OK
Benchmark PKCS-5 PRF - OK
Benchmark Hash Alhorithm - OK

VeraCrypt x86:		
Test Vectors - Passed
Benchmark Encryption Algorithm - OK
Benchmark PKCS-5 PRF - OK
Benchmark Hash Alhorithm - OK

**Comment by idrassi** [comment]
Thanks.
I have published 3rd Release Candidates for 1.21 at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/ which should fix all remaining crash issues.

Can you please test it and confirm that you have no more issues?

Thank you.

**Comment by sierraatomic** [comment]
I will have access to Intel Core 2 Duo E6850 machine tomorrow.

I've tested VeraCrypt v1.21-RC3 on:
Windows version: Microsoft Windows 10 (10.0) Professional 64-bit v15063.447
CPU: AMD Phenom II X4 940
Instruction sets: MMX (+), 3DNow! (+), SSE, SSE2, SSE3, SSE4A, x86-64, AMD-V

Multiple containers/partitions with:
Encryption Algorithm: AES
PKCS-5 PRF: HMAC-SHA-512
or
Encryption Algorithm: AES
PKCS-5 PRF: HMAC-RIPEMD-160

VeraCrypt x64 and x86:
Test Vectors - Passed
Benchmark Encryption Algorithm - OK
Benchmark PKCS-5 PRF - OK
Benchmark Hash Algorithm - OK

**Everything looks fine. No BSOD observed.**

Some [benchmarks](https://github.com/veracrypt/VeraCrypt/files/1122652/Benchmarks.txt):
Twofish speedup on x64
Camellia speedup on x64
SHA512 speedup on x64
**SHA256 speedup on x86**

**Comment by sierraatomic** [comment]
VeraCrypt v1.21-RC3 on:
Windows version: Microsoft Windows 10 (10.0) Professional 64-bit v15063.447
CPU: Intel Core 2 Duo E6850
Instruction sets: MMX, SSE, SSE2, SSE3, SSSE3, EM64T, VT-x
Container partitions with:
Encryption Algorithm: AES
PKCS-5 PRF: HMAC-SHA-512

VeraCrypt x64 and x86:
Test Vectors - Passed
Benchmark Encryption Algorithm - OK
Benchmark PKCS-5 PRF - OK
Benchmark Hash Algorithm - OK

**No BSOD observed.**

Some [benchmarks](https://github.com/veracrypt/VeraCrypt/files/1123611/Benchmarks_01.txt):
Twofish speedup on x64
Camellia speedup on x64
SHA512 speedup on x64 **and x86
SHA256 speedup on x86**

**Comment by idrassi** [comment]
Thank you very much for your tests and the good quality benchmarks. It confirms that the fix is OK.

SSE4 results are a little disappointing on the AMD Phenom processor. I knew that AVX instructions are slow on AMD chips and that's why I disabled AVX support for AMD on VeraCrypt but it looks like SSE4 instructions on AMD are not as fast as on Intel.

I will prepare VeraCrypt 1.21 packages and hopefully I will be able to publish them today.
