### ISSUE TITLE
Behaviour of "shift"-key during pre-boot authentication

### ISSUE THREAD

**Issue by schmodd** [veracrypt/VeraCrypt#186]
I was wondering why my password was not accepted during pre-boot authentication. After seeing what I typed via F5, I realized, that whenever I kept pressing the shift-key and entered multiple characters, only the first entered character was written correctly. I had to release "shift" and press it again for a second capital character.
Is this some kind of veracrypt bug or may this be related to my UEFI (Gigabyte board)?

Setup:
Veracrypt 1.21-RC4 (also tried 1.19)
UEFI + GPT
Gigabyte GA-Z77-D3H
Windows 10 Pro
Crucial M500 120GB

**Comment by dlongjohn** [comment]
Hi, did you ever find the answer to this issue?

**Comment by schmodd** [comment]
Unfortunately I didn't find a solution other than adjusting my password.
