### ISSUE TITLE
Dual Boot, both OS are Windows: How do I do this? 

### ISSUE THREAD

**Issue by AARRGGHHH** [veracrypt/VeraCrypt#189]
My best guess is that I boot into each drive and encrypt the system drive.  Then access the non-system drive via "mount without pre boot authentication"  Is there anything else that I need to do to ensure that both Operating Systems will show up as options in the VeraCrypt Boot Menu?  

Thank you.  And thank you idrassi for this amazing privacy product.

**Comment by cerberii** [comment]
Veracrypt does not encrypt the system drive of mac osx.

**Comment by AARRGGHHH** [comment]
I didn't even mention Mac OS X.  Both OS are Windows (on a PC).
