### ISSUE TITLE
License shown in Windows installer is truncated

### ISSUE THREAD

**Issue by xofe** [veracrypt/VeraCrypt#191]
The license terms shown within the Windows installer for VeraCrypt seem to be truncated to 32767 characters (approx. line 679 of 744 in the current version of [License.txt](https://github.com/veracrypt/VeraCrypt/blob/76167ceba3f0a3ec91174620283f451815daa288/License.txt#L679)) in versions of VeraCrypt from 1.12 to the current 1.22 beta.

Not sure if this is the best place to report issues, but I couldn't find any specific info on where they should be sent.

**Comment by idrassi** [comment]
Thank you for reporting this.
I have fixed this issue (https://github.com/veracrypt/VeraCrypt/commit/0fb2befe3ab57696d5b4c9de6fee344bfd520bf6) and you can get latest installer for 1.22-BETA that includes it from https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/.

**Comment by xofe** [comment]
Confirmed fixed, thanks!
