### ISSUE TITLE
Release notes shown after update are old

### ISSUE THREAD

**Issue by banym** [veracrypt/VeraCrypt#192]
**Description:**
If you update veracrypt to Version 1.21 the old release notes from version 1.19 (October 17th, 2016) are shown after update.

**System:** Windows
**Version:** 1.21

**Reproduce:** 
Open VeraCrypt 1.21 on Windows -> Help -> Version History

The shown version history: file:///C:/Program%20Files/VeraCrypt/docs/html/en/Release%20Notes.html is an old version.

**Comment by idrassi** [comment]
Thanks for the report.
It was a deployments mistake.
This has been fixed (https://github.com/veracrypt/VeraCrypt/commit/295d5affbb5ca283595b6eb664d0c301871e2fbe) and the latest [1.22-BETA2](https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/) installer shows the correct release notes.
