### ISSUE TITLE
Why Require OSXFUSE?

### ISSUE THREAD

**Issue by cerberii** [veracrypt/VeraCrypt#194]
Something is wrong to require osxfuse.  Veracrypt is not nativly handling functions and the file system.  

I will never install OSX Fuse because it is a nightmare.  Even using EXFAT filesystems is a nightmare on osx.  Using anything other than mac file systems and dealing with them in a mac way is a COMPLETE NIGHTMARE.  I still remember losing TB's of drives and having to reinstall windows because of problems with OSXFUSE.  Paragon NTFS, OSXFUSE, MACFUSE, anything that tries to write to NTFS on a mac will eventually fail and screw the whole drive.

I suggest rewriting veracrypt to not require any FUSE components, its a terrible idea in the first place that you require that package.

**Comment by MRebhan** [comment]
Unless the Mac version is completely different from other versions, it definitely does require a way to mount it's file system natively. How else would you access the stored files? I don't think there's any alternative to FUSE ("Filesystem in Userspace"). The linux version depends on FUSE2 too…

**Comment by cerberii** [comment]
handling non-native filesystems in linux is also terrible.  dirty bits, cant fsck, load into windows to fix, oh wait your windows is screwed? Then you are finished.  

Dont use FUSE, if you want to be able to mount any filesystem, then mount as read only if its not native.   There should be an option to not have to install or use the FUSE package as its experimental and terrible.

Apple does not use FUSE to read NTFS file systems, and neither does linux.

**Comment by MRebhan** [comment]
The only alternative is using kernel drivers which are way harder to write and debug. And read-only is really not an option with VeraCrypt, isn't it?

**Comment by lambdaupb** [comment]
The alternative is to implement a disk device driver.
https://github.com/elsteveogrande/osx-nbd/blob/master/NBDDisk/NBDDiskStorageDevice.cpp is doing something similar.

There is https://developer.apple.com/documentation/kernel/ioblockstoragedevice which passes to tasks to an  https://developer.apple.com/documentation/kernel/ioservice.

I'm not a kernel or C programmer, but that seems to be the most straight forward way to implement it, which makes me wonder if there is a reason for going to FUSE+DiskImage route. (Which has noticeable performance overhead.)
