### ISSUE TITLE
Pretest failure after BIOS POST pc turns off

### ISSUE THREAD

**Issue by cmachold** [veracrypt/VeraCrypt#199]
Hello,

- I want to encrypt my system partition.
- First try with veracrypt 1.22.
- I update my secure boot configuration as explained here: https://github.com/veracrypt/VeraCrypt-DCS/tree/master/SecureBoot/readme.txt - works fine without ecryption
- creation wizard works fine until restart - AES-SHA512 - no PIM
- the pretest failed after bios post, **pc turns off and nothing happens**
- Notebook ASUS G752VS-BA191T Windows 10 64 bit.
- Toshiba XG3 256GB M.2 SSD THNSN5256GPU7
- I had to change the bootloader in the bios so I could start the system
- i tried https://github.com/veracrypt/VeraCrypt/issues/160#issuecomment-314153231 and got no errors
- result of a fsutil fsinfo ntfsinfo c:

NTFS Volume Serial Number :        0x241208ba1208934a
NTFS-Version   :                   3.1
LFS-Version    :                   2.0
Number Sectors :                   0x000000001da990df
Total Clusters :                   0x0000000003b5321b
Free Clusters  :                   0x00000000031c3f39
Total Reserved :                   0x000000000000111d
Bytes Per Sector :                 512
Bytes Per Physical Sector :        512
Bytes Per Cluster :                4096
Bytes Per FileRecord Segment :     1024
Clusters Per FileRecord Segment :  0
Mft Valid Data Length :            0x000000001b800000
Mft Start Lcn :                    0x00000000000c0000
Mft2 Start Lcn :                   0x0000000000000002
Mft Zone Start :                   0x00000000009f3800
Mft Zone End :                     0x00000000009f41a0
Max Device Trim Extent Count :     256
Max Device Trim Byte Count :       0xffffffff
Max Volume Trim Extent Count :     62
Max Volume Trim Byte Count :       0x40000000
Resource Manager Identifier :      30D8D90F-79E7-11E6-92DB-38D54731596B

- next try with veracrypt version 1.22 BETA3 - same problem
- after windows had startet again, the veracrypt volume creation wizard shows the pretest failed
- bcdedit  [bcdedit.png](https://postimg.org/image/jkv1ng7ut/)
- is the veracrypt loader wrong? \Device\Hardisk\Volume2() because Windows 10 points to \Device\Hardisk\Volume4(C:)

any solution?

**Comment by rubisco57** [comment]
Hi, 
I am experiencing similar symptoms as described by _cmachold_ on a Lenovo ThinkPad device with Windows Version 1703 (OS Build 15063.540) installed on it.

The command _fsutil fsinfo ntfsinfo c_ yielded:
NTFS Volume Serial Number :        0x5ec4afe8c4afc09f
NTFS Version   :                   3.1
LFS Version    :                   2.0
Number Sectors :                   0x0000000018584fff
Total Clusters :                   0x00000000030b09ff
Free Clusters  :                   0x0000000002b98a62
Total Reserved :                   0x0000000000001df9
Bytes Per Sector  :                512
Bytes Per Physical Sector :        512
Bytes Per Cluster :                4096
Bytes Per FileRecord Segment    :  1024
Clusters Per FileRecord Segment :  0
Mft Valid Data Length :            0x0000000009a00000
Mft Start Lcn  :                   0x00000000000c0000
Mft2 Start Lcn :                   0x0000000000000002
Mft Zone Start :                   0x00000000000c9a00
Mft Zone End   :                   0x00000000000cc820
Max Device Trim Extent Count :     512
Max Device Trim Byte Count :       0xffffffff
Max Volume Trim Extent Count :     62
Max Volume Trim Byte Count :       0x40000000
Resource Manager Identifier :      4EA4FA0D-81E5-11E7-92E4-B8359DDFADF3

I would appreciate any hint for solving this problem. 
If further information regarding the system configuration is needed, please do not hesitate to inquire.

**Comment by houmles** [comment]
Hi,
I also have similar problem. My laptop (Clevo P650RS) turning off if I boot using DcsBoot.efi newer than 1.19.
I can encrypt system drive using 1.21 (or 1.22 beta) but I have to use 1.19 rescue disk to boot Windows (or to pass pretest) otherwise my laptop shutdown.

**Comment by Coolcord** [comment]
Any word on this? It's definitely a VeraCrypt bug that was introduced sometime after v1.19.

I'm having the same issue with an ASUS P9X79 motherboard on Windows 10 (Secure boot is disabled). I have 2 other devices running VeraCrypt with UEFI and they both work fine, but this motherboard powers off upon loading DcsBoot.efi. However, VeraCrypt v1.19 works fine on this device.

I can confirm that this bug exists in both v1.21 and v1.22-BETA3. I can provide more information if needed.

**Comment by aslaki** [comment]
Confirmed on Dell Vostro 15 3000 series laptop. Secure boot disabled.
System partition encryption results in boot loop. Works with v.1.19

**Comment by alt3r-3go** [comment]
All, is this still a problem on either the latest released 1.23-Hotfix2 or latest pre-release 1.24-Beta5?

**Comment by Eusebius1920** [comment]
I am experiencing a similar issue (both 1.23-hotfix2 and 1.24-beta5).

After rebooting for pretest the veracrypt password prompt shows up and after entering the correct password the windows boot-logo appears. Shortly after that the screens go black (but no shutdown)

I then have to restore the windows bootloader via installation medium (where I can see that the \EFI\Veracrypt-directory was created and filled with files)

**Comment by alt3r-3go** [comment]
Thanks, and this is onwhich Windows version (`winver` command in Start->Run will tell you all the details)?

**Comment by Eusebius1920** [comment]
I am not 100% sure if this is the exact issue.

v1.19 does **not** work for me (with the same issue as described)

I tried Windows 1803 (with v1.23-hotfix2) and it did not work and then I decided to first upgrade to windows 1903, because there is some other issue mentioning that windows 1803 pretest does not work. But after the upgrade I got the exact same issue again (with v1.23-hotfix2, v1.24-Beta5, v1.19, v1.22)

Each time I have to rebuild the bootloader (via formatting EFI partition and running bcdboot C:\windows /s N: /f UEFI). Of course, booting then gives me a prompt from veracrypt that the pretest failed.

I tried every suggestion I could find in the bugtracker (bcdedit /set ... before rebooting to pretest, adding a <config>-entry to DcsProps to load bootmgfw_ms.vc - which was already created by veracrypt), but I always end up with the password prompt and then a black screen after entering the password. 

Maybe worth to mention: It does not matter if I boot VeraCrypt Dcs or the Windows-Bootloader from the boot options, both prompt me with a password to enter end then go to a black screen - but sometimes windows bootloader goes into a blue screen to suggest I boot in safe mode)

I encrypted on this very same machine successfully before - but using legacy BIOS instead of the UEFI variant. But I wanted to switch to UEFI (also to get painless windows feature updates in the future).

Maybe I should open a separate issue? Any addional information needed.

**Comment by alt3r-3go** [comment]
Hmm, indeed sounds both similar and not so similar, so I guess only a deep debug and root causing would help understand that. Let's leave it here for now and see what the debugging leads to. That will take some time as this week seems to be too hectic for me to able to do anything, but I have this on my ToDo shortlist, so whenever I have time, I'll look into this - just to set the expectations straight :)

**Comment by Eusebius1920** [comment]
I will try if the problem still persists and come back after that... unfortunately it may take a few days / weeks though...
