### ISSUE TITLE
Auto-dismount doesn't work on Windows 10 when shutting down

### ISSUE THREAD

**Issue by andrasfuchs** [veracrypt/VeraCrypt#200]
I'm using VeraCrypt 1.19 (64 bit) on Windows 10 Pro (64 bit, build 15063.483).

In the preferences/auto-dismount the "User logs off" and "Force auto-dismount even if volume contains open files or directories" are ticked.

I usually shut down my computer using the Alt+F4 keystroke on the desktop. It pops up the Shut Down Windows dialog.

If I select "Sign out" and I sign back in, VeraCrypt asks for the volume password again. This happens also if I select "Restart" or there is a power outage and I switch the computer back on. This is correct.

If I select "Shut down" though, the computer shuts down, and when I turn it back on, I just get the message that "The volume you are trying to mount is already mounted." and I can access the encrypted drive without entering the password for it.

Interestingly if I select "Shut down" and hold Shift while pressing OK on that dialog, VeraCrypt works again like it is expected.

**Comment by idrassi** [comment]
Hi,

This is a Windows limitation and not VeraCrypt issue. It is explained in https://www.veracrypt.fr/en/Issues%20and%20Limitations.html (look at the 3rd point from the button concerning the Windows feature called "Hybrid boot and shutdown" or "fastboot"). You can also read the following post about the same issue https://sourceforge.net/p/veracrypt/discussion/technical/thread/ab96939d/#0db8

Basically, shutdown in Windows 10 doesn't shutdown if you don't force it to do so...Microsoft has done some strange naming choices.

Closing this ticket. Feel free to reopen if you encounter further problems.
