### ISSUE TITLE
PRETEST DOES NOT WORK AND FAILS SYSTEM VOLUME ENCRYPTION PROCESS

### ISSUE THREAD

**Issue by inliquid** [veracrypt/VeraCrypt#205]
Hi,

With previous version of VeraCrypt (1.19) everything was fine:

- MSI GS70
- Only 1 disk with system
- VeraCrypt 1.19 + Windows 10 (version < 1703)
- **System volume was encrypted and everything was ok**

What was changed:

1. Have upgraded VeraCrypt 1.19 -> 1.21 and all worked nice since that
2. Permanently decrypted system volume and installed latest Windows 10 (=1703) update for designers - with VeraCrypt loader it could not update (there was error during Windows upgrade procedure after restart, so I had to decrypt and try to run upgrade on the system without VeraCrypt - this actually solved the problem)
3. After upgrade was done, I initiated VeraCrypt system volume decryption, expecting same procedure as it was with VeraCrypt 1.19, however with **VeraCrypt 1.21** on PRE-TEST nothing happened! The device turns off and then Windows start normally WITHOUT ANY PASSWORD PROMPT! Like nothing has happened! I have only 1 disk in the system and no other devices connected during procedure. Tried a number of times - same result.

//Regards

**Comment by inliquid** [comment]
I checked EFI filesystem and I see that EFI/VeraCrypt directory with bootloader and other files is created before pre-test run and this dir finally removed after it failed and I press "No" to "try again" (or something) dialog.

**Comment by inliquid** [comment]
Some more details and quick workaround:

1. If I say to VeraCrypt wizard go ahead for pre-test and then stop before reboot (answer "no" to last dialog), and look at EFI filesystem, there is no EFI/VeraCrypt folder
2. After reboot with no password prompt, VeraCrypt says that pre-test faild, however at this moment I can see that EFI/VeraCrypt was created. I say VeraCrypt wizard that I want to try again, but hold on with reboot and follow with these steps manually:

1. copy EFI\Microsoft\Boot\bootmgfw.efi to bootmgfw_ms.efi
2. copy and replace EFI\VeraCrypt\DcsBoot.efi to EFI\Microsoft\Boot\bootmgfw.efi
3. edit EFI\VeraCrypt\DcsProp and put this key within configuration:
`<config key="ActionSuccess">postexec file(EFI\Microsoft\Boot\bootmgfw_ms.efi)</config>`
(found on some forum, hove no idea does make any sense or not)

After reboot I enter the pass and VeraCrypt finally says it was ok.

**Comment by idrassi** [comment]
I have implemented a workaround for such issues in the latest 1.23-BETA0. Now there is no need to manually modify efi files or DcsProp configuration file.

Moreover, this version also adds support for Windows 10 major updates (for example from 1703 to 1709) so that decryption of the OS is not needed.

1.23-BETA0 installer is available at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/
