### ISSUE TITLE
I upgraded to macOS High Sierra now can't access VeraCrypt drives

### ISSUE THREAD

**Issue by nast90210** [veracrypt/VeraCrypt#216]
Veracrypt don't see any partitions. It's seems to be problem with fuse. Because I can create and mount container. But when I try to mount partition with APFS veracrypt say that it's read-only. So I think fuse just can't see APFS disk.

![31006606-67e06c4a-a50e-11e7-9a14-b112e344e999](https://user-images.githubusercontent.com/6872890/31068486-dd2177f2-a760-11e7-96a0-63d5249b703c.jpg)

**Comment by typcn** [comment]
![image](https://user-images.githubusercontent.com/8022103/31075141-b912ba28-a739-11e7-8e7e-778a99ef617c.png)

Same here, I can only see the DMGs.
My bitcoin wallet is in this container...

**Comment by typcn** [comment]
Workaround:

/Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt /dev/rdisk0s*

**Comment by gnosly** [comment]
Workaround 2:

Only "device selection" doesn't show you up the available devices. You could use Volume text box to insert the device to mount.

![schermata 2017-10-14 alle 11 21 47](https://user-images.githubusercontent.com/2919922/31574528-e6655af2-b0d1-11e7-8b46-5f88b7047b79.png)

To know the encrypted _block device_ you could use disk utility

![schermata 2017-10-14 alle 11 22 52](https://user-images.githubusercontent.com/2919922/31574536-0c688e86-b0d2-11e7-87cb-a78bb76f6272.png)

In my case the _block device_ /dev/disk0s3 has got a corresponding _character device_  /dev/rdisk0s3.

Who doesn't know the difference between _block device_  and _character device_ I suggest to read https://en.wikipedia.org/wiki/Device_file#Character_devices as starting point.

**Comment by bakku** [comment]
Has anyone encountered this error ?


<img width="422" alt="screen shot 2017-11-27 at 08 24 55" src="https://user-images.githubusercontent.com/9559624/33255165-8ce29f88-d34c-11e7-8832-6cb756028312.png">

**Comment by bakku** [comment]
Updating osxfuse AND rebooting fixed it for me 👍

**Comment by 3bbing** [comment]
Also "Mount All Devices" works for me. It also shows the path once found, so next time can use it directly as "Mount All" seems very slow for me. Still present in Mojave and with FUSE 3.8.2 by the way.
