### ISSUE TITLE
openBSD

### ISSUE THREAD

**Issue by Popkultur** [veracrypt/VeraCrypt#217]
Hi,
trying to build on openBSD with gmake:
`
> gmake WXSTATIC=1 NOGUI=1 
Compiling FileCommon.cpp
FileCommon.cpp: In static member function 'static void VeraCrypt::File::Copy(const VeraCrypt::FilePath&, const VeraCrypt::FilePath&, bool)':
FileCommon.cpp:53: error: aggregate 'VeraCrypt::stat statData' has incomplete type and cannot be defined
FileCommon.cpp:54: error: invalid use of incomplete type 'struct VeraCrypt::stat'
FileCommon.cpp:53: error: forward declaration of 'struct VeraCrypt::stat'
FileCommon.cpp:56: error: aggregate 'VeraCrypt::utimbuf u' has incomplete type and cannot be defined
FileCommon.cpp:59: error: 'utime' was not declared in this scope
gmake[1]: *** [/home/emanuel/VeraCrypt/src/Build/Include/Makefile.inc:25: FileCommon.o] Error 1
gmake: *** [Makefile:372: all] Error 2
`

any hints would be appreciated.

// I guess I need wxwidgets after all.

**Comment by Popkultur** [comment]
ok, I guess I need wxwidgets after all.

**Comment by Popkultur** [comment]
okay, I get this on openBSD:

`
$ doas gmake
Compiling File.cpp
Unix/File.cpp:113:41: error: use of undeclared identifier 'DIOCGSECTORSIZE'
                        throw_sys_sub_if (ioctl (FileHandle, DIOCGSECTORSIZE, &sectorSize) == -1, wstring (Path));
                                                             ^
Unix/File.cpp:176:41: error: use of undeclared identifier 'DIOCGMEDIASIZE'
                        throw_sys_sub_if (ioctl (FileHandle, DIOCGMEDIASIZE, &mediaSize) == -1, wstring (Path));
                                                             ^
2 errors generated.
`
Is it because openBSD has only wxWidgets 2.8 so far?

**Comment by lessless** [comment]
Is it resolved?

**Comment by Popkultur** [comment]
dunno, I gave up.
