### ISSUE TITLE
macOS container problem  File::Open:232

### ISSUE THREAD

**Issue by 0xjacobb** [veracrypt/VeraCrypt#218]
Hi there

I have a problem with the installing process of VeraCrypt:

- FUSE for macOS 3.7.1 installed (complete installation)
- VeraCrypt 1.21
- macOS 10.12.6

After installation of FUSE I have chosen following setup in VeryCrypt:

- create volume
- Create an encrypted file container
- Standard VeryCrypt volume
- File von Macintosh HD --> Name "test"
- Alog: AES, Hash: SHA-512
- 500MB (Free Space 471 GB)
- password ...
- Filesystem type: MacOS Extended
- I will mount the volume only on Mac OS X
- Random Pool PW.... --> Format 

--> Error
Permission denied:
/test
VeryCrypt::File::Open:232

**Comment by raywood1** [comment]
I don't know Mac, but on Linux I get that error after creating a new partition, if I then forget to change the permissions to allow me, a user (as distinct from root), to make changes on that partition.
