### ISSUE TITLE
Question about PIM: PIM explained in a simple way

### ISSUE THREAD

**Issue by 91DarioDev** [veracrypt/VeraCrypt#220]
I read some comments about PIM. I can say that for a regular user it’s not that simple explained.

As far as I understood PIM is just a value that the more it is high and the more veracrypt requires time to decrypt in order to make more difficult brute force attacks.

Also as far as I understood PIM is like a second key to guess for an attacker so he has to guess the password and then the PIM.

PIM offers two point of security:
- the delay in decryption with an high value
- the need to guess the value 

Is it fine so far?

Also I was wondering if so, deciding not to prompt the PIM, disable just the security level of the need to guess it for an attacker, but keep the security level of the delay in mounting on.

Have I done some mistake in understanding it? Unfortunately I did not find a very simple explanation in base terms for regular users.
Thank you in advance.

**Comment by Schweineschwarte** [comment]
Mostly, the issue section is a bad place to ask about explanation (else, bug- and feature-report getting disappear).
Better you write your asks into the veracrypt forum ;)
https://sourceforge.net/p/veracrypt/discussion/

**Comment by 91DarioDev** [comment]
Thank you. I close the issue
