### ISSUE TITLE
VeraCrypt not displaying text properly on some buttons depending on used GTK Theme

### ISSUE THREAD

**Issue by pommetjehorlepiep** [veracrypt/VeraCrypt#223]
I have an issue where the text in the VeraCrypt desktop application (v1.21) is not displayed properly on some of the buttons.

I initially raised the problem with the Adapta-project, since it is specifically happening with the Adapta & Adapta-Nocta themes. Response was: not our problem.....

All required details + screenshot can be found here: [Issue raised in Adapta-project](https://github.com/adapta-project/adapta-gtk-theme/issues/540)

Thx

**Comment by smurphos** [comment]
@idrassi 
This isn't an Adapta bug - the buttons in veracrypt built against the wxwidget GTK2 libraries fail to expand to fit their contents in all themes.

E.g Adwaita-dark with a system font size of 15..

![screenshot-window-2018-12-06-060916](https://user-images.githubusercontent.com/29017677/49565042-b290c500-f91d-11e8-8d7a-58bda1544462.png)

Solution is to amend the make file and dependencies to build veracrypt as standard on linux against the GTK3 wx libraries.

**Comment by idrassi** [comment]
Thank you for the explanation.

Indeed, official VeraCrypt Linux binaries are linked against wxWidgets GTK2 for maximum compatibility across all Linux distributions even relatively older ones.

The best approach would to provide two set of installers: one for GTK2 and one for GTK3 while keeping GTK2 one as the default one for download.
