### ISSUE TITLE
VC in command line NOT accepting special characters (possibly bug?)

### ISSUE THREAD

**Issue by zenminimalist** [veracrypt/VeraCrypt#224]
I tried auto-mounting my favorite VC volumes using the following command line paramters, following the VC documentation:

**Works**
/Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt --auto-mount=favorites --password=mygoodsecurepassword

but as soon as I use a special characters such as "!" in my password like so: 

**Does NOT work**
/Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt --auto-mount=favorites --password=mygoodsecure!password 

I get an error message: 
-bash: !password: event not found

telling me that VC does not like special characters, because it rejects everything after the special character. 

**This seems to be a bug, or is this indeed a feature (then please excuse my ignorance and explain it to me)?** 

I'm using VeraCrypt v1.21 on Mac High Sierra.

**Comment by gv5470** [comment]
Hello,

The problem you are describing is not really related to Veracrypt itself, but rather to the bash shell your terminal uses. Indeed, in bash the exclamation mark is interpreted as a command, which is causing the error message in this particular example. To avoid interpretation of the exclamation mark, try enclosing your password in simple quotes, like this: 

/Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt --auto-mount=favorites --password='mygoodsecure!password'

The same will apply if your password contains spaces.

**Comment by zenminimalist** [comment]
@gv5470 Thanks, for explaining the cause of the issue. Guess this "issue" can be closed now, thanks to you :)

**Comment by gv5470** [comment]
You're welcome :) Though I think it could be a good thing to include a warning on the subject in the command-line documentation of the --password option. I might do this modification and hope it makes it to the main repository.
