### ISSUE TITLE
Unable to mount veracrypt volume on smb share - permission denied

### ISSUE THREAD

**Issue by armaccloud** [veracrypt/VeraCrypt#23]
Hi Veracrypt guru(z),

I have transitioned to ubuntu desktop (15.04) for my daily work and am encountering the following issue. I would have posted a video, but it's not possible here so it will be in screenshots.

First thing I did was create a local Veracrypt volume on the local drive and mounted that, which goes well. This way, I know I can mount without any issues.

Next, I created a Veracrypt volume on a SMB share from the Veracrypt interface; that goes well.
Then when I try to mount that volume, the following happens;

![selection_005](https://cloud.githubusercontent.com/assets/9272078/9395422/b22153f8-478e-11e5-8125-a83c96782fdd.png)
![selection_006](https://cloud.githubusercontent.com/assets/9272078/9395444/d814d012-478e-11e5-99fb-272088f4f2f7.png)
![selection_007](https://cloud.githubusercontent.com/assets/9272078/9395461/efa566ec-478e-11e5-846d-0c356d0a08c1.png)
![selection_008](https://cloud.githubusercontent.com/assets/9272078/9395476/0bb7da68-478f-11e5-81a9-0d31eee66511.png)
![selection_009](https://cloud.githubusercontent.com/assets/9272078/9395555/6ee55746-478f-11e5-9971-96933c681516.png)

I am unsure what password or permission is denied, for I have full write access to the share, since it didn't give any errors while creating the volume there. Is there anything I am not overseeing?
Thanks.

**Comment by idrassi** [comment]
Hi,

The same issue was reported on Codeplex: https://veracrypt.codeplex.com/discussions/644377
Direct link to my analysis: https://veracrypt.codeplex.com/discussions/644377#post1442713

I quote here part of it:

>I was able to reproduce your issue and I found it was caused by the fact that the permissions of the shared files only allow the current Ubuntu user, not even root. But VeraCrypt launched the mount process as root to be able to create mount points and that's why it can't access the file.

>The only solution that I found is to manually mount the network folder to a local directory. I will explain the steps:
>* Get the IP address of the server. Here we suppose it is 192.168.1.123
>* We suppose that the user name for Windows share is WINUSER and its password is WINPASS
>* We suppose that the current Linux user name is LINUSER
>* Create a directory called Sauvegarde.
>* Open Terminal and type the following command: 
>```
>sudo mount -t cifs //192.168.1.123/sauvegarde /home/LINUSER/Desktop/Sauvegarde -o user=WINUSER,password=WINPASS
>```
>After that you will find, your containers in the Sauvegarde folder in the Linux desktop and you can mount them using VeraCrypt without a problem.

**Comment by armaccloud** [comment]
Hi, many thanks for the solution, it worked!

**Comment by svanoort** [comment]
@idrassi I have just encountered this on Ubuntu 14.04 LTS with Veracrypt 1.16 and unfortunately find that manual mounts do *not* work for me, following the procedure as described. 

I have tried also setting the uid and gid for the mount to the user, which unfortunately does not work either.

**Comment by svanoort** [comment]
It appears this is not specific to Veracrypt -- it is the result of mounting a folder by NFS.  At that point it is possible to create files with owning users and groups that do not map to a valid SAMBA user.   These files will not be readable by any local user when the mount is visited.

**Comment by Atalanttore** [comment]
I try to use VeraCrypt on Linux regularly, but also VeraCrypt 1.23 still fails mounting a container on a Samba share after entering my Administrator password.

_Error that appears:_
`Permission denied:`
`/run/user/1000/gvfs/smb-share:server=nas.local,share=a`

`VeraCrypt::File::Open:232`

**Comment by onstrt** [comment]
Unable to mount a VC container in ~/pCloudDrive.

**_veracrypt -t -k '' --pim=0 --protect-hidden=no --slot 2 /home/username/pCloudDrive/encrypt-file.vc_**

 **Error: Permission denied:
 /home/username/pCloudDrive/encrypt-file.vc

 VeraCrypt::File::Open:287**
