### ISSUE TITLE
How to compile it statically?

### ISSUE THREAD

**Issue by iomintz** [veracrypt/VeraCrypt#231]
I'm trying to create a cross platform Traveler disk that works on macOS, Windows, and Linux.
In order to do so, I'll need compile VeraCrypt with static linking on macOS and Linux.

I tried this:

```makefile
export CFLAGS := -Wall -static
export CXXFLAGS := -Wall -Wno-unused-parameter -static
C_CXX_FLAGS := -MMD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -I$(BASE_DIR) -I$(BASE_DIR)/Crypto -static
export ASFLAGS := -D __GNUC__ -D __YASM__
export LFLAGS :=
```

but the output of `ldd Main/veracrypt` indicated that it was not statically linked.

How do I do so?

**Comment by qdm12** [comment]
I am also interested into, as I am trying to create a lightweight Docker image containing a static Veracrypt binary program
