### ISSUE TITLE
Failed to execute child process "/usr/bin/veracrypt"

### ISSUE THREAD

**Issue by Felius** [veracrypt/VeraCrypt#235]
After having installed on Ubuntu 17.10 I receive the following error message when trying to open VeraCrypt:

> Failed to launch "VeraCrypt"
> Failed to execute child process "/usr/bin/veracrypt" (No such file or directory)

When I check in Nautilus for the file it is there though.

What could be the problem here and how to solve it?

**Comment by gv5470** [comment]
@Felius Hello,
Could you open a terminal and give the output of: ls -lh /usr/bin/veracrypt
Also, which variant did you install (x86 or x64, gui or console-only) ?

**Comment by Felius** [comment]
Hey gv5470!

You solved my problem already! Idiot me always installed the x86 versions on a 64 bit system.
I installed the x64 version now and it works as it should, of course! I don't know how I could forget about this!

Thanks a lot for your help!

**Comment by gv5470** [comment]
Hey,
You're welcome, glad that this one was easy to solve ^^ And admittedly this "no such file or directory" is rather confusing (some explanation: https://askubuntu.com/questions/133389/no-such-file-or-directory-but-the-file-exists)
