### ISSUE TITLE
can veracrypt use password passed via environment variable

### ISSUE THREAD

**Issue by bedros** [veracrypt/VeraCrypt#24]
this is a lot more helpful than passing password in command line, since all command line parameters including passwords stay visible when listing all running processes and that may expose the password.

if we use an environment variable, you can run veracrypt, and then unset the variable.

Thanks

Bedros

**Comment by idrassi** [comment]
Version 1.14 introduced a new switch under Linux and MacOSX ({`--stdin`) that enabled passing the password using stdin in non interactive mode. You can use this feature to use a password from an environment variable.
The example given in the [release notes](https://github.com/veracrypt/VeraCrypt/releases/tag/VeraCrypt_1.14) is:  `veracrypt -t ${IMAGE_PATH} ${MOUNT_PATH} --mount --non-interactive --stdin <<< "$PWD"`

I think this answers your need...unless you are running under Windows.

**Comment by stp-ip** [comment]
Any equivalent in windows?
