### ISSUE TITLE
The hotkey design is just a mess

### ISSUE THREAD

**Issue by AngelFalse** [veracrypt/VeraCrypt#241]
Don't know what to tell ya, but when I tried to use Veracrypt without a mouse, it's a mess.

![default](https://user-images.githubusercontent.com/28922095/33251456-a6e55e00-d371-11e7-96f7-4658c7e39f09.PNG)

In the password entering window I see "cache password and keyfiles in memory (&A)" and "Mount Options(&A)" shared the same hotkey " Alt + A ", and In the "Mount Options" window I see the Textbox " Password to Hidden Volume(&A)", Checkbox "Display Password(&A)" and Checkbox "Use keyfiles (&A)" shared the same hotkey " Alt + A ". Holy shit, do you guys like " Alt + A " SOOOOOOOOO much that you have to design Veracrypt like that??? Even in my eyes, Truecrypt, yeah your predecessor, is a lot better than you.

When I was posting this online, I screenshotted a few Truecrypt window, no hotkey conflict found, not even one.

![2](https://user-images.githubusercontent.com/28922095/33251700-b3eb3582-d373-11e7-9a19-ca5bf77937d2.PNG)

**Comment by mcsilver** [comment]
I'm not sure whether it improved since this issue was initially written but it seems much better now.  What I would like to see is an accessor key for the `Password` textbox, please! Is it not missing altogether, at least in Windows?

![Veracrypt Enter Password Screenshot, 2019-05-09](https://user-images.githubusercontent.com/2747224/57499453-98745d80-7294-11e9-8c4f-ec50766e48c1.png)

**Comment by AngelFalse** [comment]
@mcsilver Not improved, at all! Hahahahahahahahahahahaha!!!
The accessor key in the Chinese language pack is still f**ked up, in the 1.23 hotfix 2 version!!!
![image](https://user-images.githubusercontent.com/28922095/58251862-56204580-7d97-11e9-87b8-d9f72e472627.png)

**Comment by NumDeP** [comment]
I have to agree, not having the `Hidden Volume Protection` in **Mount Options** can screw up a container big time.
