### ISSUE TITLE
Request for Language.th.xml for Thai language translation

### ISSUE THREAD

**Issue by bact** [veracrypt/VeraCrypt#251]
I would like to contribute a Thai translation for the UI

Could we have a file Language.th.xml in VeraCrypt/Translations/
so I can start the contribution.

Sorry if this is a wrong place for the request.

(Asking because I'm sure if I can just add a new file to that directory by myself or not.)

**Comment by idrassi** [comment]
I have pushed an untranslated Thai language file Language.th.xml to VeraCrypt/Translations. 
Feel free to use it as a base for your translation work.
Thank you for help.

**Comment by bact** [comment]
Thank you :)
