### ISSUE TITLE
Quick format

### ISSUE THREAD

**Issue by iknowcrypto** [veracrypt/VeraCrypt#256]
Is it possible to do a "quick format" while creating a encrypted "file container"? GUI/CLI, Linux/Windows, just give me the option to do a quick format. 

It's also a bug because --quick option does not seem to be doing anything.

**Comment by gashtal** [comment]
Actually I also noticed that there is no quick format option provided when creating containers. I think Truecrypt did provide such option. Such option would save a lot of time when creating large containers.

**Comment by gv5470** [comment]
Hello,
I grabbed my old truecrypt 7.1a archive for Linux, and it looks like the option was already disabled for file containers at this time, which is confirmed by the commit history on the relevant files.

While I understand why the option is locked for outer and hidden volume creation, I don't know the official reason(s) why it was disabled in normal file containers (those without hidden volume). The only reason I can imagine is that plausible deniability is adversely affected by quick formatting, but I think the user should be able to choose it when said deniability is not needed.
