### ISSUE TITLE
Win10 UEFI PreBoot-Auth fails always

### ISSUE THREAD

**Issue by MalteHillmann** [veracrypt/VeraCrypt#264]
Hello!

I've just setup a new PC with Windows 10 1709 x64 and tried to do a full system encryption. In Windows everything works fine. Also VeraCrypt changes keyboard layout to QWERTY. After reboot it boots correctly the VeraCrypt UEFI-Boot-loader which asks for password and PIM. I entered the same password as before (tried that password multiple times, including removing and adding system encryption).
The boot-loader shows always an authentication failure.

Can you help me with this issue? Is there any debug mode for the test boot-loader? It does not show any errors. 

Thank you very much.

Kind regards

**Comment by AlexeiScherbakov** [comment]
1. SecureBoot enabled?
2. Is public key added to UEFI BIOS? (https://github.com/veracrypt/VeraCrypt-DCS/tree/master/SecureBoot)

**Comment by MalteHillmann** [comment]
@AlexeiScherbakov 
1. Yes SecureBoot is enabled
2. I've tried it again with manually added keys, but the problem persisted.

So i tried to use some very easy password like "abc". Its working.
I tried another password like "abcABC". Its NOT working.
Some tests later I found the problem:
If i type: [a][b][c][shift][a][b][c] (while holding down shift) it does NOT work. But when I type: [a][b][c][shift][a][shift][b][shift][c] it succeeds!

I think you might have a problem with the recognition of the shift key?

Kind regards

**Comment by michaeljgray** [comment]
https://github.com/veracrypt/VeraCrypt/issues/269 duplicates this issue, but has more responses.

**Comment by jgoggan** [comment]
@michaeljgray How are 264 (where someone has the Veracrypt bootloader installed, but has trouble with a SHIFT KEY) and 269 (where no one can install Veracrypt at all because it won't pass the pre-test and never EVER even ASKS for a password) duplicates of each other?  They don't even seem close to the same thing!

**Comment by MalteHillmann** [comment]
> Is it possible to know your BIOS/motherboard model? Are you using external keyboard? This will help record this in incompatibility list.
The board is an "GIGABYTE AORUS GA-AX370-Gaming K7".
I found out, that the problem is gone when using USB keyboard instead of PS/2.
