### ISSUE TITLE
Managing '&amp;' in translated strings

### ISSUE THREAD

**Issue by ekcnl** [veracrypt/VeraCrypt#265]
Several source strings contain ampersands either before or within words. How should these ampersands be treated? Ignored or maintained in the translated string?

Ex:
<control lang="en" key="IDC_BROWSE">Bro&amp;wse...</control>
<control lang="en" key="IDC_DESKTOP_ICON">Add VeraCrypt icon to &amp;desktop</control>

**Comment by comradekingu** [comment]
@ekcnl http://docs.translatehouse.org/projects/localization-guide/en/latest/guide/translation/accelerators.html

**Comment by ekcnl** [comment]
Takk @comradekingu. Referring to keyboard shortcuts in the Microsoft Style Guide, particularly for languages using different scripts.
