### ISSUE TITLE
Add ShellBag registry key information to the Data Leak Documentation

### ISSUE THREAD

**Issue by DrunkenSasquatch** [veracrypt/VeraCrypt#276]
Windows uses a set of Registry keys known as “shellbags” to store the name, size, view, icon, and position of a folder when using Explorer. Each time you open a folder, this information is updated including the time and date of access. This information should be added to the data leak documentation for people using file containers or hidden volumes on partitions other than the system.

<b>Shellbag locations</b>

Shellbags may be found in a few locations, depending on operating system version and user profile. On a Windows XP system, shellbags may be found under:

    HKEY\_USERS\{USERID}\Software\Microsoft\Windows\Shell\
    HKEY\_USERS\{USERID}\Software\Microsoft\Windows\ShellNoRoam\

On a Windows 7 system, shellbags may be found under:

    HEKY\_USERS\{USERID}\Local Settings\Software\Microsoft\Windows\Shell\

More info: https://www.sans.org/reading-room/whitepapers/forensics/windows-shellbag-forensics-in-depth-34545

**Comment by idrassi** [comment]
Thank you for reporting this.
I have updated the documentation to include the information you mentioned (https://github.com/veracrypt/VeraCrypt/commit/c24105feac80d046d6cf90b182ff3187d629bd7). The online version has also been updated.

Thank you again.
