### ISSUE TITLE
How can I encrypt system partition without CD/DVD?

### ISSUE THREAD

**Issue by stil** [veracrypt/VeraCrypt#28]
I have spare microSD cards and pendrives. However, I don't own any CDs or even CD drive. Can you tell me how I can burn memory card with Rescue Disk ISO? And how to fool VeraCrypt I that I actually have Rescue Disk created?

**Comment by idrassi** [comment]
Which version of VeraCrypt are you using? In the latest version, if no CD recorder exists on the machine, you'll be presented with the dialog below where you can skip Rescue Disk creation.

As for burning the rescue disk in USB pen drive or a memory card, a user posted steps on Sourceforge: https://sourceforge.net/p/veracrypt/discussion/general/thread/b6725803/

To make VeraCrypt believe that you have a rescue disk inserted, you can use the excellent [Virtual Clone Drive](http://www.slysoft.com/en/virtual-clonedrive.html)

![VeraCryptNoBurner](https://i.imgur.com/vRjLP8d.png)

**Comment by stil** [comment]
I used Virtual Clone Drive to mount ISO image and bypass the check.
I copied rescue disk to two SD cards for redundancy and put them in safe place.
