### ISSUE TITLE
New algorithm config

### ISSUE THREAD

**Issue by Eyremba** [veracrypt/VeraCrypt#284]
Currently, you can use different combinations of encryption algorithms in VeraCrypt, like Serpent-Twofish-AES and such.
However, this are only fixed combinations.
It would be much better if the combinations could be chosen more freely so that a user could combine them like he wants to.

For example, you could use your own combinations that are not supported by default, like Camellia-Serpent or Kuznyechik-Camellia. And a more paranoid user could, for example, use a more heavy combination like Serpent-Twofish-AES-Camellia for small volumes.

This would be much better than those fixed combinations.

**Comment by Eyremba** [comment]
@idrassi wouldn't this be much better than those fixed combinations that are currently in use?
So that every user could combine the algorithms freely.

**Comment by cookieenabled** [comment]
4 months passed and no comments.

@idrassi I want this. +1. Why not start a crowdfunding?

@Eyremba
This task will have medium~high level difficulty because this will require UI & core update.

```
[ xxx ][V] is a drop-down menu.

Current UI:
[ Serpent-Twofish-AES ][V]

New UI idea #1:
[ Serpent ][V][ Twofish ][V][ Kamilla ][V]

New UI idea #2:
1: [ Serpent ][V] <-- is required to select,
2: [ Twofish ][V] <--- 2 and
3: [ Kamilla ][V] <--- 3 are optional (default to "-")

```

**Comment by cookieenabled** [comment]
core idea:
```
Header data:
name: "encryptionMethod"
value: "13|23|0"

13 = Serpent,
23 = Twofish,
and
0 = nothing

So VC will think this disk is encrypted with 13->23->0 ---> "Serpent-Twofish" method.

```

**Comment by TensorTom** [comment]
There's probably a pain-in-the-ass-to-code reason for that. Just guessing.

**Comment by NumDeP** [comment]
@Eyremba I think since one of the previous beta versions, you could technically do that except there isn't a choice and I'm sort of glad there isn't a choice because this would just confuse users more and those standard on offer in the the selection is cleverly implemented. Just my personal opinion.
