### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by Etken2016** [veracrypt/VeraCrypt#287]
I follow all instruction to build the code on win7 , by VS2010 
but when I run the build , the result of building BOOT is  : 

`Assembling: ..\BootSector.asm

1>   Assembling: ..\BootCrt.asm

1>  ..\decompressor.c

1>  Out of memory

1>NMAKE : fatal error U1077: 'C:\Users\etken\Desktop\VeraCrypt-master\vc1.52\MSVC15\bin\cl.exe' : return code '0x2'`

what's the problem ?

**Comment by idrassi** [comment]
We never encountered this issue.
Obviously, the compiler failed to allocate the memory necessary for compiling the file decompressor.c .
I don’t think we can help you. You have to check that your machine has enough RAM available and if you are using a VM try using a physical machine.

**Comment by quangnh89** [comment]
Hi. I follow all instruction to build the code on win7-64bit, by VS2015. I encounter the same issue. My computer has 8GB RAM and doesn't run out of memory.
```
 Assembling: ..\BootSector.asm
1>   Assembling: ..\BootCrt.asm
1>  ..\decompressor.c
1>  ..\bootconfig.cpp
1>  ..\bootconsoleio.cpp
1>  ..\bootdebug.cpp
1>  ..\bootdiskio.cpp
1>  ..\bootencryptedio.cpp
1>  Out of memory
1>NMAKE : fatal error U1077: 'D:\build-VeraCrypt\MSVC15\bin\cl.exe' : return code '0x2'
1>  Stop.
1>   Assembling: ..\BootSector.asm
1>   Assembling: ..\BootCrt.asm
1>  ..\decompressor.c
1>  Out of memory
1>NMAKE : fatal error U1077: 'D:\build-VeraCrypt\MSVC15\bin\cl.exe' : return code '0x2'
1>  Stop.
1>   Assembling: ..\BootSector.asm
1>   Assembling: ..\BootCrt.asm
1>  ..\decompressor.c
1>  Out of memory
1>NMAKE : fatal error U1077: 'D:\build-VeraCrypt\MSVC15\bin\cl.exe' : return code '0x2'
1>  Stop.
1>   Assembling: ..\BootSector.asm
1>   Assembling: ..\BootCrt.asm
1>  ..\decompressor.c
1>  Out of memory
1>NMAKE : fatal error U1077: 'D:\build-VeraCrypt\MSVC15\bin\cl.exe' : return code '0x2'
1>  Stop.
```
