### ISSUE TITLE
CLI password input prompt

### ISSUE THREAD

**Issue by bazzilic** [veracrypt/VeraCrypt#299]
Logged on to a Windows server via SSH and wanted to mount the volume using cli (the only option with SSH), but it requires specifying password as an argument to the command. Would it be possible to add a standard password prompt if the `/p` flag is specified without a password?

E.g.,
```
    > veracrypt.exe /q /v my.volume /l X /p
    Enter password:
```

**Comment by electric-ladyland** [comment]
I cannot tell if this is possible already, but if not, it really needs to be. Otherwise the passwords are visible plainly in the process list.

**Comment by bazzilic** [comment]
Can this issue be reopened? AFAIK this wasn't added and it's a really useful feature. Also, doesn't seem to be too hard to implement.

**Comment by bazzilic** [comment]
Can this issue be reopened (sorry to tag you @idrassi just to make sure this doesn't get lost in the closed issues)?
AFAIK this wasn't added and it's a really useful feature. Also, doesn't seem to be too hard to implement.

**Comment by wrozwad** [comment]
I know that I shouldn't write a comment but still +1 for this
