### ISSUE TITLE
Wireless Mouse Entropy

### ISSUE THREAD

**Issue by pmjdebruijn** [veracrypt/VeraCrypt#3]
It seems that VeraCrypt collects the majority of its entropy via mouse movements. However neither VeraCrypt or it's documentation seems to warn against the use of employing a wireless mouse to generate this private key generation entropy.

Presumably it would be prudent have a brief warning about wireless (or bluetooth) mice in the GUI and documentation.

**Comment by espress0** [comment]
@idrassi

How about adding 'dance on your keyboard Entropy'?

User must dance their finger on the keyboard 1 minute XD

e.g.,

r97fgya38gh80ghn8e;agj;08asef-3xti4=q'3yh04im'[0IG9'-57ynva){UT$tv8ynp85v7ytsz0a;MNW
8Y:$TGN"_#(TGU#M-tic=z-wfn zut5g'u9UR$@*) ^Tt 40-uamt09- yutga y8y7TR$@ PTF{R_43t=-q8my]=gr[ i435m0y'-siy53yi-ai[gf{UM )F$W..

**Comment by idrassi** [comment]
humm...I'm starting to think that you are just polluting the VeraCrypt tracker...

Please, this is a serious project and there is no room for jokes. If you don't like something, just move on...

**Comment by espress0** [comment]
@idrassi

> you are just polluting the VeraCrypt tracker
I'm not offending you, sorry.

So, what do you think about 'keyboard entrophy' I posted above?

**Comment by smithb1994** [comment]
@espress0  Keyboard entropy is less secure than the mouse, because you're more likely to hit the same characters.

**Comment by andreas-becker** [comment]
I think here is nothing more to say, so @pmjdebruijn please close this five year old issue.
