### ISSUE TITLE
Full-desk encryption on linux 

### ISSUE THREAD

**Issue by Jinovas** [veracrypt/VeraCrypt#301]
Does Veracrypt support full-disk encryption for linux? I haven't been able to figure out how to get the option to do so in the gui for now.  I am wanting to encrypt my whole drive.

![veracrypt](https://user-images.githubusercontent.com/13728103/38222987-2d38940c-369d-11e8-8748-8b01643c7f1e.png)

Any help is greatly appreciated ^_^

**Comment by pahakalle** [comment]
How does one use his desk when its fully encrypted 😂

**Comment by Jinovas** [comment]
disk** >_<

**Comment by vadiof** [comment]
Why not use dm-crypt/LUKS?

**Comment by Schweineschwarte** [comment]
@vadiof 
dm-crypt/LUKS is too complex for standardusers (e.g. you must use LVM, if you want to use only one password for all; some distributions have no GUI for encryption at installation; you can't encrypt your system after installation etc.)

**Comment by Destroyinator69420** [comment]
I would prefer veracrypt becuase it has more security features and is easier to use. I especially like the ability to overwrite empty space with random data to make analysis of the disk harder.
