### ISSUE TITLE
System encryption failed before PRE-TEST at Collecting Random Data.

### ISSUE THREAD

**Issue by susarlanikhilesh** [veracrypt/VeraCrypt#302]
I tried encrypting my system drive i.e 'C' Drive. The steps I followed are : 

1. Create Volume.
2. Encrypt the system partition or entire system drive.
3. Normal (type of system encryption).
4. Encrypt the windows system partition (area to encrypt).
5. Single-boot (number of operating systems).
6. AES (encryption algorithm), SHA-512 (hash algorithm).
7. Password.
8. Collecting Random Data.

After clicking next in "**Collecting Random Data**" page the application **throws an exception** with the following error attached in the below screen shot. 

![veracryptbootpretesterror](https://user-images.githubusercontent.com/4359080/38233823-8be1e49e-3739-11e8-8723-778f21e14e58.PNG)

Please also find the System details attached in the below screen shot on which I tried to encrypt the system drive. 

![systeminfo](https://user-images.githubusercontent.com/4359080/38234323-2c4d578c-373b-11e8-9a8c-f8fedc4d7323.PNG)

Please let me know why it is failing and how it can be resolved.

Thank you.

**Comment by idrassi** [comment]
I have made changes to fix this issue by not requiring  "EFI\Boot\Bootx64.efi" to be present.

I have uploaded an installer for 1.23-BETA1 that contains this fox to https://www.veracrypt.fr/downloads/VeraCrypt%20Setup%201.23-BETA1.exe (pgp signature at https://www.veracrypt.fr/downloads/VeraCrypt%20Setup%201.23-BETA1.exe.sig)

Can you please test and confirm that it doesn’t occur anymore?

Thank you.

**Comment by ecx86** [comment]
You can try this workaround too. https://github.com/veracrypt/VeraCrypt/issues/315
