### ISSUE TITLE
Windows 10 version 1709 as hidden system

### ISSUE THREAD

**Issue by ultradj83** [veracrypt/VeraCrypt#304]
Hi everibody.

Anybody succeeded in installing Windows 10 version 1709 as hidden system?

Tks a lot.

**Comment by BlurryFlurry** [comment]
I'm interested too.
I'm already running Windows 10 on 120GB SSD, UEFI enabled.
I installed VeraCrypt and I can see the hidden option has grayed out 

![image](https://user-images.githubusercontent.com/10475081/39943761-b1667d86-5581-11e8-884f-5a2bb16c3221.png)

![image](https://user-images.githubusercontent.com/10475081/39943848-fbe43236-5581-11e8-94e4-444812dee6ef.png)
Can anyone spot my problem?
