### ISSUE TITLE
Mounting progress is a disaster

### ISSUE THREAD

**Issue by palikacska** [veracrypt/VeraCrypt#311]
Today I wanted to mount a TrueCrypt volume using a key file but forgot to check Truecrypt mode. Veracrypt started trying to mount the volume while displaying the `VeraCrypt may seem unresponsive` message. It was displaying this progress bar for **5 minutes** (!) after telling me that the volume can't be mounted.

During the progress, neither the operation can be canceled, nor can be VeraCrypt killed from the Task Manager or by `taskkill /im veracrypt.exe /f` thanks to `veracrypt.sys` kernel-level driver incontrollably trying to mount the volume or doing PIM iterations.

This is the least professional and most inconvenient way of an end-user software to function. You literally ruined the simplicity of TrueCrypt. Please implement a cancel logic into `veracrypt.sys` and a cancel button to the progress dialog.

**Comment by cookieenabled** [comment]
@idrassi " If it sees the filename ends in '.tc' then try TrueCrypt mode first"

**Comment by BenBE** [comment]
Or even more convenient: Just try TC mounting automatically and hint the user about TC mounting being used (with an option to not show again).

**Comment by BenBE** [comment]
I wonder if the proposed fix of automatically trying TC mount has at all been considered … I wonder if the issue.

**Comment by palikacska** [comment]
Shame on you @idrassi and other devs, for ignoring this.
