### ISSUE TITLE
Windows EFI Bootloader setup doesn't work if user doesn't have \EFI\Boot

### ISSUE THREAD

**Issue by ecx86** [veracrypt/VeraCrypt#315]
Hi, I have been using your software for about a year and I am very pleased with it.

I was upgrading my bootloader today, and I ran into the problem I ran into when I installed it the first time:
```
---------------------------VeraCrypt Setup---------------------------
The system cannot find the path specified.
Source: VeraCrypt::File::Write:880
---------------------------OK---------------------------
```
or
```
---------------------------VeraCrypt Setup---------------------------
The system cannot find the path specified.
Source: VeraCrypt::File::Write:628
---------------------------OK---------------------------
```
The installation proceeds successfully up until this point and then stops.

I tracked the issue down to [BootEncryption.cpp](https://github.com/veracrypt/VeraCrypt/blob/master/src/Common/BootEncryption.cpp), specifically the lines:

```C++
EfiBootInst.SaveFile(Is64BitOs()? L"\\EFI\\Boot\\bootx64.efi": L"\\EFI\\Boot\\bootia32.efi", dcsBootImg, sizeDcsBoot);
// ...

// move the original bootloader backup from old location (if it exists) to new location
// we don't force the move operation if the new location already exists
if (Is64BitOs())
	EfiBootInst.RenameFile (L"\\EFI\\Boot\\original_bootx64_vc_backup.efi", L"\\EFI\\Boot\\original_bootx64.vc_backup", FALSE);
else
	EfiBootInst.RenameFile (L"\\EFI\\Boot\\original_bootia32_vc_backup.efi", L"\\EFI\\Boot\\original_bootia32.vc_backup", FALSE);
```

On my Windows installation, I have no `\\EFI\\Boot`, and `bootia32.efi` and `bootx64.efi` are instead found in `\\EFI\Microsoft\Boot`. I am running Windows 10 LTSB x64.

So, my workaround was:
 - Mount my EFI system partition
 - Create the directory `\\EFI\Boot`
 - Run the Veracrypt installer
 - Rename original (Microsoft) bootloader at `\\EFI\Microsoft\Boot\bootx64.efi` to `\\EFI\Microsoft\Boot\original_bootx64_vc_backup.efi`
- Move Veracrypt bootloader at `\\EFI\Boot\bootx64.efi` to `\\EFI\Microsoft\Boot\bootx64.efi`

So, would it be possible to support users with this kind of configuration in the future? Thanks!

**Comment by idrassi** [comment]
Thank you for reporting this.
I have made changes to support configuration without “EFI\Boot” and now it should work without the need of manual manipulations.
I have uploaded an installer for version 1.23-BETA1 that contains this to https://www.veracrypt.fr/downloads/VeraCrypt%20Setup%201.23-BETA1.exe (pgp signature: https://www.veracrypt.fr/downloads/VeraCrypt%20Setup%201.23-BETA1.exe.sig).

Can you please do a test to confirm that it is working now?

Thank you.

**Comment by ecx86** [comment]
Works fine, thanks.
