### ISSUE TITLE
1.22 release .dmg for mac download corrupted

### ISSUE THREAD

**Issue by lambdaupb** [veracrypt/VeraCrypt#316]
I downloaded the 1.22 release from https://launchpad.net/veracrypt/trunk/1.22/+download/VeraCrypt_1.22.dmg and the file dows not mount:
```
hdiutil attach ~/Downloads/VeraCrypt_1.22.dmg
hdiutil: attach failed - error 3840
```

the file also has a sha256 
```
feddf68dbc9ed3815a0f510aa1f00dac87bbfb2be6e2568eff907689965df98d VeraCrypt_1.22.dmg
```
which does not match with the checksums provided at the page.

https://www.fosshub.com/VeraCrypt.html had a .dmg file with the correct sha256, that one works.

**Comment by idrassi** [comment]
I checked the file on launchpad and it is not corrupted (checksum and pgp signature match).

You are certainly affected by a simple network issue. Try downloading again and if it persists, use a VPN or a proxy to bypass your ISP.

**Comment by lambdaupb** [comment]
Turns out this was caused by a Chrome bug in the non-default feature of Parallel-Downloads which partitioned the download in chunks, but just downloaded the whole file into the second chunk, creating a 19MiB file.

**Comment by idrassi** [comment]
Thank you for the update.
It is interesting (and surprising) to know about this Chrome bug!
