### ISSUE TITLE
Modification of User Interface for the VeraCrpt Create Volume Wizard

### ISSUE THREAD

**Issue by goleandrew** [veracrypt/VeraCrypt#319]
Hello, we are a team of human rights defenders and activists who have recently been introduced to using Veracrypt for protecting our data/information. 

However, our interaction with this very wonderful tool raises a few concerns on the following interfaces as attached here under.

![img_20180503_174211](https://user-images.githubusercontent.com/29465829/39585091-a1425582-4efc-11e8-8083-d3516e781c24.jpg)

We feel the user interface for the volume creation wizard should be modified as follows,

1. Change the label on the "select file" button to "select" because it is confusing
2. Change the heading from "Volume Location" to "Select Volume Location" because it is also confusing the user

Still on the **Volume Creation Wizard** under the **Volume Format Interface**, the users felt the following modifications should be done as shown in the mockup below

![img_20180503_174157](https://user-images.githubusercontent.com/29465829/39585599-e2a6e1f4-4efd-11e8-8c7f-9a1618ddb8cb.jpg)

1. Change the title from "Volume Format" to "Volume Creation" because it is more understandable by the user
2. Hide the options sub-interface inside an Advanced section because the ordinary user does not need to view it
3. Change the label on the "Abort" button to "Stop" because every user understands the meaning of stop.
4. Change the label on the "Format" button to "Create" for better guidance since at this stage the user expects to create a volume.

If it is not a safety precaution, the users also feel the following should be added on the "Volume Created" window
1. Volume Name
2. Volume Size
3. Volume Location
4. Volume File System

The users would also like to appreciate the tremendous effort the VeraCrypt team has put into developing and maintaining this very useful security tool.

Greetings from Wii-Otem Community Center located in Lira District, Uganda, Africa
Signed by
**Solidarity Uganda**

Thank you

**Comment by Eyremba** [comment]
> Hide the options sub-interface inside an Advanced section because the ordinary user does not need to view it

Well... I think VeraCrypt is more used by professionals as ordinary users either don't encrypt their stuff or use simple on-board Tools like BitLocker or like 7zip.

> Change the label on the "Abort" button to "Stop" because every user understands the meaning of stop.

"Cancel" would be much better and is also used more widely in Windows.

But it would be also nice to have a button to pause the volume creation process and a button to change the write speed / IO priority.
