### ISSUE TITLE
Modification Time not updated

### ISSUE THREAD

**Issue by lordofscripts** [veracrypt/VeraCrypt#321]
I have a mobile volume, I keep it on my USB and synchronize it on copies I have on my PC and on my wife's laptop.

But when I open an HC volume and change any file in it, when I dismount it, the Veracrypt Volume File Modification Time is NOT updated so it does not let me know if I have changed that volume or not. If it did I can just check the File Modification Time to see which one is NEWER. Currently, you change something within the container, dismount and the modification time is not changed.

**Comment by Bender-** [comment]
Hi,
if someone is going to work on this bug. Please note that it seems to be broken only in the gui. When you mount a file with the parameter "/m ts" via commandline it seems to work as its supposed. See my comment in the thread linked in the post above.
