### ISSUE TITLE
Feature Request: CLI Exit Code

### ISSUE THREAD

**Issue by Programazing** [veracrypt/VeraCrypt#322]
It would be nice if an exit or error code was returned to the command line when a volume fails to mount instead of having the GUI pop up.

That way those of us who use scripts to mount our volumes would have a way to catch an error and deal with it.

**Comment by Schweineschwarte** [comment]
Are you sure, that you use the console-version of Veracrypt?
If I use the console-version of VC, VC doesn't open a GUI popup ;)
![screenshot_20180515_180120](https://user-images.githubusercontent.com/12170903/40068822-d1fa6324-5869-11e8-90d1-83aab0bda2ec.png)

**Comment by Programazing** [comment]
I'm using VeraCrypt on Windows and following this [guide](https://www.veracrypt.fr/en/Command%20Line%20Usage.html).

**Comment by idrassi** [comment]
VeraCrypt on Windows already returns an exit code that indicate if the
operation succeeded or not (0 means success and 1 means failure). This,
combined with the command line switch /silent, enables to do exactly
what you are looking for.
For example, here is a PowerShell script that tries to mount a file that
doesn't exist and it displays the exit code returned by VeraCrypt:

```
$process = (Start-Process -FilePath "C:\Program
Files\VeraCrypt\VeraCrypt.exe" -ArgumentList '/q','/v
wrongfilename.hc','/l z','/silent','/p password' -PassThru -Wait)
Write-Host "Mount exited with code " $process.ExitCode
```

Can you share how are you dealing with exit code in your scripts?
Probably, you are just missing a small thing to make it work.

**Comment by Programazing** [comment]
What I've been doing is just using the command-line to switch the VeraCrypt folder then run:

`veracrypt /silent /q /v "D:\P.Desktop\temp" /p "MyPassword"`

I never see anything after running this even if I just do it in the command-line. What I'm hoping for is some kind of error returned to the command-line if the file address or password is incorrect.

**Comment by idrassi** [comment]
On Windows, VeraCrypt binaries are not console application but rather
native Windows applications. This means that they are not attached to a
console and for this reason they can not print text to the console from
where they are launched. In this regards, VeraCrypt is similar to other
native Windows applications like Firefox or LibreOffice.
