### ISSUE TITLE
Win10 rel 1803, VeraCrypt 1.23-BETA1 always fails pretest

### ISSUE THREAD

**Issue by MCS000** [veracrypt/VeraCrypt#323]
After updating to Windows 10 Pro April 2018 Version 1803, VeraCrypt no longer works.  All was fine before the Windows update. Old version was 1709. 

#### ** WHAT I DID ** ####

I decrypted the C: drive,  (system drive on my system) 
Installed Windows 10 ver 1803 using the Microsoft Media Creation Tool, 
Tried to re-encrypt the C: drive. 

VeraCrypt does it stuff, but the pretest fails
The PC will Post, 
waits a few seconds, 
resets,
and repeat.

#### ** NEXT STEPS ** ####

Boot using the ver 1803 ISO downloaded from Microsoft.
Click Repair
Click Troubleshoot
Open a command prompt

In the command prompt (still in Windows recovery) 
diskpart
list disk
sel disk 0   {on my system}
list vol
sel vol 4    {on my system}
assign letter V:
exit

format V: /fs:fat32
bcdboot c:\Windows /s V: /f UEFI

At this point, in theory, I have a pristine boot loader.

#### ** MORE TRYING ** ####

I tried 1.23-BETA1
as well as the the bcdedit suggestion from other threads. 
as well as booting into the VeraCrypt Rescue Disk.zip. 

Still stuck in the Post-reboot loop regardless of boot device options or boot order. Can only exit the loop by reformatting the V: drive and reinstalling via bcdboot. 

#### ** Other info ####

msinfo32 Bios mode = UEFI
fsutil bytes per sector = 512, bytes per physical sector = 512
secure boot not supported on my Mobo
the unaltered boot sector has folders 
/EFI/Microsoft/Boot
/EFI/Microsoft/Recovery
/EFI/Boot

--MCS

**Comment by blu-IT** [comment]
I can confirm that VeraCrypt v. 1.21 (64-bit) on Windows 10 (64-bit) Build 1709 is **blocking** the MS Windows "functional update" (Windows 10 Pro April 2018 Version 1803).
I had problems for serval months now installing that update! After a reboot the system did not boot regulary and alwas showed the error code 0xc1900101 when trying to install the April update V. 1803.

After a lot of different tries (there where only serveral hints that a corrupt driver could be the problem) I found the soloution here:
https://answers.microsoft.com/de-de/windows/forum/windows_10-update/fehler-0xc1900101-bei-april-update/955949c6-c631-4b80-a1ac-50ad6650f969

It says that when using "**a non Microsoft disk encryption method/tool**" the update could lead to problems.
So I decrypted my complete system partition and... voilà ... the April update went fine.

I don't know if this is a VerCrypt or Microsft issue but I took me a lot of time and it was a very hard process to find exact information for that strange behavior.

Please take a look at that! Thanks!

Regards

**Comment by blu-IT** [comment]
A litte update: After finishing 1803 Update I installed VeraCrypt v. 1.22 and encrypted my system partition again. Everything went fine, including pretest!

**Comment by idrassi** [comment]
@blu-IT : Thank you for sharing your experience. Indeed, VeraCryption
version before 1.23-BETA1 didn't implement a Windows specific mechanism
(called ReflectDrivers) that became mandatory for major upgrades like
1803. This was implemented starting from 1.23-BETA1 and upgrades like
1803 have been confirmed to work without the need of decryption.

@MCS000: Can you please try with the latest 1.23-BETA4 build available
at
https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/?
I'm not quiet sure about the cause of your issue but there was a
workaround implemented for some special cases and it is possible that
this may fix the issue.

**Comment by MCS000** [comment]
>> Can you please try with the latest 1.23-BETA4 build available

I tried version 1.23 beta5. Same problem. I had to use Windows Recovery to rebuild the boot sector to get back to a valid bootable configuration. 

Thanks for your efforts.

--MCS

.

**Comment by blu-IT** [comment]
Hi,

I had problems with booting Windows after latest Windows update (KB4487017).
The system was not able to boot any more. I had this behavior also some time ago after another Windows update. I am afraid of future updates...
Every time I have to decrypt the complete system partition and encrypt it again, to get back a functional boot. Until the next update...

VeraCrypt v. 1.23 (64-bit) & Windows 10 Pro 64-bit (1803)

Regards

**Comment by idrassi** [comment]
There are still cases where Windows Update can break the bootloader but it is never necessary to decrypt the system in order to recover. Often, Windows can be booted by manually selecting VeraCrypt DCS in boot menu of the motherboard BIOS or by using the BIOS function to manually boot from the file "EFI\VeraCrypt\DcsBoot.efi".

In all cases, a combination of Rescue Disc usage and manual fix of EFI system partition content restores the system to its normal state.

That being said, and after studying the issues reported with 1.23, I have developed a new mechanism to ensure that VeraCrypt will always fix the boot partition if Windows Update corrupts its content and I have also made the Rescue Disk EFI repair mode more clever in handling such cases.

The latest 1.24-Beta2 includes these enhancements and it can downloaded from https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/.

Moreover, I have developed a tool called VcFixBoot that can be used to fix the EFI bootloader but it requires the user to be able to boot Windows manually as I described at the beginning of this post. This tool can be found at https://sourceforge.net/projects/veracrypt/files/Contributions/

**Comment by blu-IT** [comment]
Hi,

yes, I had to go that way: Boot Windows by manually selecting VeraCrypt DCS in boot menu, but every time until the boot record/menu was fixed. To do that I booted, decrypted my system partition and encrypted again.

I hope that with 1.24 the auto fix ease things :-)

Thanks!

**Comment by blu-IT** [comment]
Maybe this issue is also related to the probelm?

https://github.com/veracrypt/VeraCrypt/issues/415

**Comment by idrassi** [comment]
Thanks for pointing out the other issue. I posted an answer there to tell the user to use VcFixBoot tool.
Until 1.24 is released, this tool will also help you in case the issue happens again.

**Comment by blu-IT** [comment]
Thanks!!!

**Comment by blu-IT** [comment]
Just to complement that topic: 
I think that the knowlegde about that fix tool should be published in the FAQ section or some other central location. 
The knowledge that a encrypted system is not "lost" with that boot problem is crucial in my opinion. I myself was think about abandoning (and also not considering to other users) the veracrypt tool after having this expierence with the boot problem twice. Now that I know that there is a solution I'am encouraged to go on...

**Comment by blu-IT** [comment]
Hello,

last monthly MS security update KB4493464 left my system unbootable again, still anyoing this behavior..., but this time I could quickly fix it with the veracrypt fixboot tool. Thanks for that!

I wondering if no one else is experiencing this monthly behavior...?

Regards

VeraCrypt v. 1.23-Hotfix 2 (64-bit) & Windows 10 Pro 64-bit (1803)
