### ISSUE TITLE
Bootloader has no display output

### ISSUE THREAD

**Issue by donn** [veracrypt/VeraCrypt#324]
Just used Veracrypt to encrypt my Windows 10 partition. It works, but the bootloader does not display anything. I have to just guess as to when the password prompt was shown and write the password in, blindly. Then it moves on to Windows normally.

MacBook Pro 2017, Windows 10 April 2018, VeraCrypt 1.22.

**Comment by Zaczero** [comment]
Sounds like you have "Do not show any texts in the pre-boot..." enabled.  
`Settings > Preferences > More Settings > System Encryption`

![](https://prtsc.me/i/bead711f.jpeg)

**Comment by donn** [comment]
Not it. On other machines when I moved the hard drive, the prompt showed up fine.

**Comment by JSWorkspace1** [comment]
I have the same Problem. 
OS: Windows 10 
VeraCrypt 1.25.9 (64-bit)
