### ISSUE TITLE
Fails to install when directory is not default

### ISSUE THREAD

**Issue by DamianSuess** [veracrypt/VeraCrypt#333]
As a user, I would like to install the software into another directory other than "C:\Program Files\VeraCrypt\". When I change directory to, "C:\Prog\VeraCrypt" the installer fails with an error.

**Comment by idrassi** [comment]
I can't reproduce the issue in either Windows 7 or Windows 10.
Can you please share information about your configuration?
Also, can your please post the error message your get from the installer?

**Comment by DamianSuess** [comment]
@idrassi, thanks for getting back to me. When I get a chance, I'll warm up a new VM with a clean setup.
