### ISSUE TITLE
Question : is it possible to limit the password prompt options?

### ISSUE THREAD

**Issue by CutiePi** [veracrypt/VeraCrypt#334]
- The default prompt has mutliple options
![image](https://user-images.githubusercontent.com/17714927/42285626-2fa59f6c-7f7e-11e8-8926-85f4c8b18123.png)
- I would like my user to only be able to see this
![image](https://user-images.githubusercontent.com/17714927/42285645-3e7f05d2-7f7e-11e8-9831-6f3f44f69dfc.png)

**Comment by cookieenabled** [comment]
Maybe he could add [...] button (optional UI settings; disabled by default)

```
Password: [                          ]  [   OK    ] [ ... ]

... will open/close the extra menu.
```
