### ISSUE TITLE
Rescue Disk Not Found??

### ISSUE THREAD

**Issue by sephethus** [veracrypt/VeraCrypt#335]
I formatted my USB stick with exFat in Windows 10 1803

I extracted the zip file to the root. Now it's F:\EFI

I click next. Nope, it doesn't see it. Why? It's there. It's telling me to try another USB? I did, besides, how does that even help?

**Comment by Van-Fouran** [comment]
For creating a bootable Rescue USB Stick, please see: https://sourceforge.net/p/veracrypt/discussion/features/thread/5453c652/#8e81
