### ISSUE TITLE
Unable to mount Veracrypt volume in Citrix Xenapp 7.x session 

### ISSUE THREAD

**Issue by praxiscare** [veracrypt/VeraCrypt#339]
Hi guys

I am trying to mount a Veracrypt volume located on a USB flash drive connected to a Raspberry Pi 3 configured as a thin client running a Citrix Xenapp session. Normal USB file transfers are possible meaning I can copy files to and from a file server and the USB flash drive. 

When I try mounting the volume I am getting as far as entering the encryption password for the volume and then get an "Access is denied. Source:MountVolume:8048" error message.

Any light you could shed on this would be greatly appreciated,

Kind regards

John

**Comment by lalalolo49** [comment]
I just had that error, it mounted perfectly this morning. Now I have this error _mountvolume:8048_
Let see later after a reboot.
