### ISSUE TITLE
[Feature] Make VeraCrypt verify available free disk space before creating a volume of a specified size.

### ISSUE THREAD

**Issue by supercom32** [veracrypt/VeraCrypt#341]
Currently when you create a new encrypted volume, VeraCrypt will tell you how much free space is available, then ask you how large you want your volume to be. However, if the user enters a number that is greater than what is available, the wizard will still allow you to proceed! The only time the user finds out that they allocated more space than is available is when container creation fails (which could take several hours, depending on volume size, and how the device is connected). 

The only recourse the user has is to go through the wizard again, reduce the size by a bit, then wait several more hours to see if it worked or not. This problem could be minimized if VeraCrypt would set the default size of a volume to be the total size available on disk, but naturally a proper "free space" check would be the definitive solution.

**Comment by cookieenabled** [comment]
@supercom32

Dude, you could write more clearly.
Don't forget to add step-by-step, expected, and actual.


@idrassi

```
Steps
1. Open "Veracrypt Volume Creation Wizard"
2. Select "Create an encrypted file container" and click Next
3. Select "Standard" and click Next
4. Select file location, such as "C:\test.container.db". Click Next.
5. Select any encryption options and click Next
6. GUI will show "Free space on drive C:\ is 33.44 GB"
7. Input "50", and select "GB". Click Next.

Actual behavior:
The GUI advanced to next step, asking for a password.

Expected behavior:
The GUI _should_ check user input, and if the value is bigger than free space integer,
show a warning dialogue "Value is bigger than free size" and do not go to the next step.
```

**Comment by cookieenabled** [comment]
```
int userInputValueBytes = getUserInputValue();
int freespaceBytes;
if (freespaceBytes < userInputValueBytes)
 raise Warning;
```

**Comment by idrassi** [comment]
The check on the size is not done at this step of the wizard because
VeraCrypt allows the creation of dynamic containers (based on NTFS spare
files) for which the entered size value is not there real size upon
creation but rather their maximum size when they grow.

Of course, the wizard can enhanced to avoid error later during the
creation process using the following approach:

  - If we detect that the filesystem of the target drive is not NTFS,
then the entered size value will be check in the "Volume Size" step of
the wizard since we are sure that no dynamic volume can be created.
  - If the filesystem of the target drive is NTFS, then we can check the
entered size when the user click "Format" button at the last step if the
user doesn't select the "Dynamic" option.

I will implement this approach and publish a beta that contains it for
testing.

**Comment by supercom32** [comment]
This is just a friendly check in, but has there been any movement on this? I tried out the latest version of Veracrypt and noted that this still seems to be an outstanding issue. I also looked over the latest beta changes and it doesn't seem to mention anything about this ether.

**Comment by supercom32** [comment]
Just another check in. Assuming this has not already been implemented, I would like to petition that this gets looked at. 

Spending hours creating a container, only to find that you slightly ran out of space, is a serious waste of time. Especially since the GUI can't tell you exactly how much space you have available to allocate on the drive. Because it just gives you a general estimate (like "10.5GB" for example, which usually ends up being slightly off from what your OS tells you), your left being conservative with your value (wasting space), or spending hours/days trying a value, having creation fail, and trying a slightly lower value. 

Considering all this needs is a disk space check before starting, it seems like low hanging fruit for a significant quality of life improvement.

**Comment by idrassi** [comment]
Did you try with version 1.23 or newer? A check was added in version 1.23 un Windows to ensure that the size of the file container is smaller than available disk space.
This is documented in the Release Notes of version 1.23: https://www.veracrypt.fr/en/Release%20Notes.html

In version 1.23-Hotfix-2, a CLI switch was added to disable this check.

**Comment by idrassi** [comment]
Just to say that I also implemented the check on file container size on Linux and MacOSX (this the commit https://github.com/veracrypt/VeraCrypt/commit/400bb5224700e7dcaa2eb3572a3ba2a3fbdf02e1). And I also added in this commit a CLI switch to disable it.

**Comment by Menard01** [comment]
Veracrypt has just failed with this and version 1.25.9 for Linux, I was trusting VC to chose the maximum size for the file, but I lost.
