### ISSUE TITLE
[SECURITY!] "Random Pool Enrichment" window doesn't fill anymore when I move my mouse

### ISSUE THREAD

**Issue by secerrorreporter** [veracrypt/VeraCrypt#342]
Using latest Veracrypt 1.22 x64

1. Select File container in GUI,
2. Click "Volume tools" - "Change volume password"
3. Input password & PIN, and input new pair of password/PIN,
4. then Random Pool enrichment GUI will appear.
5. You move your mouse within window.

Expected behavior:
The randomness bar is empty.

Actual behavior:
The bar will fill when I move my mouse within GUI window.
I'm sure this feature is working for me when I tried v1.20.

Can you fix this? I think this is a serious security problem.

**Comment by cookieenabled** [comment]
@idrassi Confirmed on other computers. This is a serious problem, please fix this in v1.23.

**Comment by cookieenabled** [comment]
PC--- USB HUB --- USB Mouse

**Comment by cookieenabled** [comment]
@idrassi "Random pool enrichment bar" in "New volume creation wizard" GUI works, but not on password change GUI.
Please fix this so I can change password with confidence.

**Comment by alt3r-3go** [comment]
Looks like you're mixing the expected and actual behaviour, however the indicator indeed doesn't seem to work - but only during the first invocation. I can reproduce this on 1.23-Hotfix-2 x64 on Windows 7, but only once, if I then change the password on the same file or create a new one and change password there - the progress bar works as intended for me.

It doesn't necessarily mean the randomness from mouse gestures isn't getting collected BTW (and only then this may have security implications, though severity is debatable).

All in all this indeed looks like a bug worth investigating and fixing. I'll look into this.

**Comment by alt3r-3go** [comment]
...and after trying the very latest 1.24-Beta5 I can't reproduce this any more. Neither on Windows 10 nor Windows 7.

@secerrorreporter, if this is still relevant to you - feel free to try the latest Beta (don't forget to make the data backup before upgrading just in case). If it's not, please let us know as well, we probably can just close this one given the circumstances.
