### ISSUE TITLE
Favorite Volumes automatically mounted log on to Windows

### ISSUE THREAD

**Issue by KovalevArtem** [veracrypt/VeraCrypt#343]
[Source](https://www.veracrypt.fr/en/Favorite%20Volumes.html): "Note: VeraCrypt will not prompt you for a password if you have enabled caching of the pre-boot authentication password ( Settings > ' System Encryption ') and the volumes use the same password as the system partition/drive."

I do not want VeraCrypt to ask for a password, but I want to use a different password in the volumes than the one used in the system partition / drive.

Is it possible?

**Comment by cookieenabled** [comment]
It is possible, just encrypt your other disk or container using different password.

**Comment by blu-IT** [comment]
Which volumes do you mean? D:, E:, ... when creating a new encrypted volume/container you are able to set differnt passwords.

Regards

**Comment by GH-Rake** [comment]
No it's not possible.  The only way to do this would be to cache the passwords which would negate the security benefits.
