### ISSUE TITLE
VC on W10 x64 pro single passwd entry mounts _all_ ? But should not!

### ISSUE THREAD

**Issue by EC-O-DE** [veracrypt/VeraCrypt#344]
When did this happen? Previously it was that every container/hdd/partition needed passwd entry. 
But now suddenly it was entered only once (using "mount favorite volumes") and all container were encrypted. This single entry happens after dismounts & reboots~so..?
Using latest stable since release (long time...) and no - VC settings have not been changed(!)
Shouldn't VC need passwd entry per container? Not just entered once...?
Settings are off when it comes to caching the passwds - so? What's happening?

**Comment by cookieenabled** [comment]
Favorites > Organize Favorite Volumes

Are you sure above UI is empty?

**Comment by EC-O-DE** [comment]
Containers have always been saved there to 'favorites' but still VC always asked passwd per container/favorite... So it's a wonder ~ it seems.

**Comment by cookieenabled** [comment]
Can you provide a screenshot of "Veracrypt - Preferences" window?
If your configuration is correct, then this is a bug.

Veracrypt GUI > Settings > Preferences
