### ISSUE TITLE
Failed to read cluster 0x4

### ISSUE THREAD

**Issue by MaxXor** [veracrypt/VeraCrypt#347]
I'm trying to open an encrypted partition on my external USB drive and it always fails with "Failed to read cluster 0x4.". Does it mean my data is lost? :fearful:

**Comment by Schweineschwarte** [comment]
Is it a HDD? Then, can you check your HDD with a diagnostic tool?
You can find some tools on the Ultimate Boot CD or you download it from the developer site.
http://www.ultimatebootcd.com/
Is it an USB-Stick, you should search for an other check tool, like h2testw for Windows or F3 for Linux.
If the tools find an error, it is no Veracrypt issue.
