### ISSUE TITLE
Debian 8.11 Jessie = StartElevated:368

### ISSUE THREAD

**Issue by MESWEB** [veracrypt/VeraCrypt#350]
I'm trying mount virtual disk but as you can see on picture I have problem with mounting.
Error say:

> No such file or directory:
   sudo   
   VeraCrypt::CoreService::StartElevated:368

I don't know what is this mean.
![screenshot from 2018-08-19 20-15-12](https://user-images.githubusercontent.com/2931024/44312272-80e70300-a3ed-11e8-8bea-2b03df961d54.png)

**Comment by idrassi** [comment]
The “sudo” command seems to be missing from your installation. Normally it is present by default.
You can install it manually using “apt install sudo”

**Comment by MESWEB** [comment]
@idrassi : Thank U. Installing help me a lot.
