### ISSUE TITLE
Veracrypt problem

### ISSUE THREAD

**Issue by MK1312** [veracrypt/VeraCrypt#352]
Hey guys,
Yesterday was veracrypt perfekt, now i will start and get an error... :
Cant Exec \Efi\Microsoft\Boot\Bootmgfw.efi start Partation ****
Status Unsupported..

What that means?
Was hat das zu heißen? .. Gestern ist alles noch normal gelaufen -:/

**Comment by idrassi** [comment]
Can you please give details about your configuration?
VeraCrypt version, Windows version, Hidden OS or normal OS, any updates
performed in between...etc

**Comment by MK1312** [comment]
Hey
How i can get informatrions about the veracrypt version? i cant go in my pc... 
https://www.medion.com/de/shop/p/core-gaming-notebooks-medion-erazer-p6679-intel-core-i5-7200u-windows-10-home-39-6-cm-15-6-fhd-display-gtx-950m-256-gb-ssd-8-gb-ram-gaming-notebook-b-ware--30024060B?wt_mc=64016125131_289479769142&wt_kw=p_64016125131_medion%20erazer%20p6679&gclid=CjwKCAjwtvnbBRA5EiwAcRvnptzHVmC6Rb-4PPj8nGaIz5G2cK-kSs6IisJi6DCyRM5ENLMGb5FdshoCeM8QAvD_BwE&gclsrc=aw.ds thats my pc
Windows 10 version
Normal OS

**Comment by MK1312** [comment]
​Push, jemand on der mir weitergehend hilfestellung leisten kann?
Ich benötige die Dokumenten und Unterlagen von diesem Laptop... sonst bin ich ruiiniert, daher möchte ich ungern etwas alleine machen und dann geht was kaputt... das wäre sehr sehr mies..

Danke!

**Comment by MK1312** [comment]
Hey thanks bro,
The problem is, my english is very bad, i need german help...
on Sourceforge, nobody can help me at now
greetz

**Comment by Schweineschwarte** [comment]
Da es für Veracrypt keine deutschen Hilfsforen gibt, wirst du dich vermutlich mit englischen Antworten begnügen müssen. Du kannst aber Dinge wie die Google Übersetzung (https://translate.google.de) oder verschiedene Wörterbücher, wie Leo.org oder dict.cc, verwenden. Ich denke, dass du damit verstehst, was dir entsprechenden Personen sagen möchten.

**Comment by MK1312** [comment]
Hallo,
Update :

Ich habe die Rescue Datei gefunden,
Was kann ich nun tun? Ich habe die HDD ausgebaut, und die HDD eingebunden bei vera, um sie einzubinden wird ein PW verlangt, dieses wird erfolgreich eingegeben, wenn ich dann das PW abändern möchte, kommt eine fehlermeldung mit PW nicht richtig...

Was kann ich mit der Rescue Datei anfangen, ohne die Datein zu verlieren? Die Platte komplett entschlüsseln?

Mfg

**Comment by Schweineschwarte** [comment]
Wenn das vielleicht eine Systempartition oder ein altes TrueCrypt-Volumen ist, dann musst du das beim Kennwortfenster einstellen. Ebenso wie die PIM oder andere Optionen.
Mehr werde ich hier aber auch nicht dazu schreiben, denn wie idrassi richtig schrieb:
"Github is more for developers so it is better to seek help on Sourceforge."

**Comment by wzhbbq** [comment]
Hey guys,
when we click buttom "Mount", where is the specific location of the code for the complete process?
I want to try to add a new algorithm in the source code, but it can't be successful. If you want to add an algorithm to it, does the code that needs to be updated involve Driver?
