### ISSUE TITLE
language packs for Linux and MacOS

### ISSUE THREAD

**Issue by Schweineschwarte** [veracrypt/VeraCrypt#355]
Hello,
it exists some language packs for Windows, but no for Linux and MacOS
https://www.veracrypt.fr/en/Language%20Packs.html
Is it possible to extent the Linux and Mac version, to use these packages too?
Thank you!

Veracrypt version: 1.21

**Comment by Atalanttore** [comment]
That would be nice, but Linux and macOS seem to be second class platforms for VeraCrypt developers.

**Comment by omaidb** [comment]
I'm very confused as to why language packs are not available for Linux and Mac. Multi-platform support for language packs, which is a very reasonable requirement
Veracrypt version: 1.7
