### ISSUE TITLE
FS shown as FAT when ext4 was selected

### ISSUE THREAD

**Issue by m1cm1c** [veracrypt/VeraCrypt#361]
When choosing to format a volume with ext4 in the volume creator, then choosing that you want to store files larger than 4 GB on it and that it should be mountable on platforms other than Linux, this message appears:

> Please note that the volume will not be formatted with a FAT filesystem and, therefore, you may be required to install additional filesystem drivers on platforms other than Linux, which will enable you to mount the volume.

Despite this message, the volume is still formatted with ext4, not FAT.

**Comment by UkeFan** [comment]
having the same problem!
