### ISSUE TITLE
Gtk-Message: Failed to load module "overlay-scrollbar"

### ISSUE THREAD

**Issue by Atalanttore** [veracrypt/VeraCrypt#363]
It appears following error message in console when starting VeraCrypt 1.23.
**Gtk-Message: hh:mm:ss.ms: Failed to load module "overlay-scrollbar"**

**Comment by idrassi** [comment]
This is not specific to VeraCrypt. For example:
https://askubuntu.com/questions/984556/gtk-message-failed-to-load-module-overlay-scrollbar-ubuntu-17-10
and
https://askubuntu.com/questions/538993/gtk-message-failed-to-load-module-overlay-scrollbar

VeraCrypt uses wxWidgets, which in turns uses GTK. In our side, we don't
have any GTK specific code and so probably wxWidgets is doing something
behind the scene. Not sure for now where to look.
