### ISSUE TITLE
Bluescreen on Partition Mounting and running Acronis

### ISSUE THREAD

**Issue by Hodel1** [veracrypt/VeraCrypt#367]
Hello,

i was wondered about a bluescreen after i mounted my encrypted partition.
i changed a many settings and searched for bugs, but the Minidump created from Windows 10 had expected, that veracrypt and acronis not able to run at once.

So i deactivated the Acronis TrueImage Protection and closed all services, mounted again - work as well.
It will be nice, when you find a solution or if you can't fix it, reporting to Acronis.

Tested: 
Mounting Container - works 
Mounting Partition - Bluescreen
Mounting Partition with wrong Password - works (no bluescreen)
Versions: 1.22, 1.23-Hotfix-1

Dumpfile: https://www.dropbox.com/s/2tppdsyqfmkrens/092218-12031-01.dmp?dl=0
Error: system thread exception not handled

Greets

**Comment by idrassi** [comment]
Hi,
Thank you for the report.

This issue has already been reported to Acronis who acknowledged that it
is a bug in their driver protector.sys and they published a hotfix for
it at https://kb.acronis.com/content/61717

Users should install this hotfix until Ancronis publishes an updated
version of TrueImage.
