### ISSUE TITLE
Difficult to type the password correctly

### ISSUE THREAD

**Issue by ecx86** [veracrypt/VeraCrypt#369]
Hello, and thanks for your hard work on Veracrypt. I'm very pleased with it.

I've used Veracrypt for a long time now, and I always found it difficult to type in my password at the bootloader. On Linux, I can type my password in easily on the first try without difficulty, as fast as I want. On Veracrypt, if I type too quickly it almost never is right. It always takes me 2 or 3 tries to get it right, usually making sure to press only 1 key at a time.

It feels like if I type too fast, some of my keystrokes are getting dropped. Do you know why this might be? For reference I use a n-key rollover USB keyboard, the Quick Fire TK.

This doesn't actually break functionality, it's just a small annoyance. It's not a very important issue, but any help is appreciated, thanks.

**Comment by GH-Rake** [comment]
For me if I press F5 at the bootloader screen it will show me the password as I type it, which reduces the number of mistakes I make.  Have you tried that?

**Comment by ecx86** [comment]
Wow, what a cool easter egg. I didn’t know that. Actually since I filed
this issue I have just gotten really good at typing my password even with
the weirdness so I guess this can be closed.
