### ISSUE TITLE
Changes to system favorites global settings are discarded when selecting another drive before clicking OK

### ISSUE THREAD

**Issue by guiweber** [veracrypt/VeraCrypt#37]
In the _Organize system favorite volumes_ window, there are global settings that affect all system favorite volumes. If a user has two or more system favorite volumes, changes to the settings are discarded if the user selects another volume before clicking OK. This was tested in VC 1.16 under Windows 10 x64.

Steps:
- Add at least two volumes to the system favorites
- Go to _Favorites -> Organize system favorite volumes..._
- Check any of the two checkboxes in the _Global Settings_ section
- Select any unselected drive in the list
- Notice that the checkbox just just checked is now unchecked

Expected behavior: The global settings should not change when selecting another drive.

**Comment by andreas-becker** [comment]
@guiweber is this issue is still present or can it be closed?

**Comment by guiweber** [comment]
@andreas-becker Unfortunately my current system configuration prevents me from verifying this issue. Someone else would need to check.
