### ISSUE TITLE
Update from v. 1.22 to v. 1.23 left Win10 unbootable

### ISSUE THREAD

**Issue by blu-IT** [veracrypt/VeraCrypt#371]
Hello,

unfortunately I had a very ugly experience _again_ updating Verycrypt from v. 1.22 to v.1.23 on Win 10 (x64).
After the first reboot everything seemd to work fine. After the second reboot the system was not able to boot anymore. It even did not ask for the pre-authentication password and always tried to start recovery mode, but was not able to reapair. 

After a while I found an entry in Advanced options -> Boot from USB-Disk and there was a option to boot from VeryCrypt. So I booted the system successfully and decrypted my system-partition. Booting was normal then. After encrypting my system-partition with v. 1.23 "from scratch" the system works fine now.

Regards

**Comment by OfficialMuffin** [comment]
I have the same problem. Just updating veracrypt didnt work for me. What do you mean "from scratch"? Like, uninstalling veracrypt and then reinstalling and encrypting the drive again?

**Comment by blu-IT** [comment]
Decrypt drive, update veracrypt, encrypt again.

Regards 

Am 31. Oktober 2018 15:48:12 MEZ schrieb Leon <notifications@github.com>:
>I have the same problem. Just updating veracrypt didnt work for me.
>What do you mean "from scratch"? Like, uninstalling veracrypt and then
>reinstalling and encrypting the drive again? 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/veracrypt/VeraCrypt/issues/371#issuecomment-434715445

-- 
Diese Nachricht wurde von einem mobilen Gerät versendet.

**Comment by OfficialMuffin** [comment]
Wouldn't this leave files unprotected? e.g Encrypting drive after computer use would not be protected.

-------- Original Message --------

**Comment by blu-IT** [comment]
@OfficialMuffin 

The solution went on here:

https://github.com/veracrypt/VeraCrypt/issues/323#issuecomment-463828246
