### ISSUE TITLE
auto-mount favorite volume on Mac not working 

### ISSUE THREAD

**Issue by TarekGomres** [veracrypt/VeraCrypt#376]
Hi, 
I would like to auto-mount a volume that I have on a USB Stick (Ancrypted File on the USB) so when I plug in the USB stick, the Vracrypt schould popup and ask for the password to mount the volume. 
I have aktivated the Option Background Task + Mount favorite Volumes and add the Veracrypt App to Start at logon Applications/user. 
All this did not work on my mac when I put the usb Stick no thing happen, I have to mount the volume manually. 
Thank you in advance for your help 
(Mac, Hight Serra, VeraCrypt 1.23) 

![bildschirmfoto 2018-11-02 um 14 57 49](https://user-images.githubusercontent.com/10109518/47919521-d771c280-deaf-11e8-8b05-1326feccd486.png)

**Comment by Kugelfang666** [comment]
I‘ just encountered the similar problem, was this ever resolved?

**Comment by UkeFan** [comment]
@Kugelfang666 no, your issue was closed?! Both describe the same problem. Hopefully auto-mount will work on Mac, too, some day!

**Comment by TheSearchOfSolution** [comment]
Hi,
I am currently encountering the same problem. It does to seems possible to auto mount an external drive when plugin it (unlike on windows where it work perfectly). Can we hope for a fix ? Can we help for a fix ?

Thanks for your work
