### ISSUE TITLE
VeraCrypt is preventing sleeping my computer (Linux Debian, XFCE4)

### ISSUE THREAD

**Issue by slrslr** [veracrypt/VeraCrypt#377]
Hi, in my case, Veracrypt 1.21 on linux Debian (kernel 4.15.0-1-amd64) is attempting to dismount my decrypted volume/container (unsuccessfully cause it is used by various apps) when i do "sudo pm-suspend", but i do not want Veracrypt to do it. Any idea how to prevent it?

This silently breaks the sleep without me knowing the cause, because the dismount error message appears only when i request sleep via command line using mentioned command, not via standard XFCE4 logout/suspend GUI procedure. Closing all connected apps before sleeping is not an option for me. I just need veracrypt to stop this activity and do not interrupt sleep. I never had problem on my other WIndows PC with mounted volumes during sleep. If programmers think Veracrypt should continue to be set to unmount volumes during sleep request, then please give option to user to disable this behavior (i see Windows apparently [have this option](https://i.imgur.com/W0tdKcj.png) and in the light of this issue, Linux option or not dismounting by default would be handy too).

**Comment by hasanalizxc** [comment]
Hi,

Go to Settings and Preferences. You will see a section that named Auto-Dismount. Uncheck all.

http://prntscr.com/lf8m6c
