### ISSUE TITLE
Volume Mounts without Password (not cached)

### ISSUE THREAD

**Issue by PilotFlying** [veracrypt/VeraCrypt#382]
See here:

https://www.reddit.com/r/VeraCrypt/comments/91acql/randomly_started_mounting_the_volume_without/eaa99d5/

**Comment by Enigma2Illusion** [comment]
In Windows, turn-off Fast Startup.

https://www.tenforums.com/tutorials/4189-turn-off-fast-startup-windows-10-a.html

Reboot PC.

Vote-up my request to have VeraCrypt disable the Windows fast startup option to avoid this and other issues it causes VeraCrypt.

https://veracrypt.codeplex.com/workitem/475
