### ISSUE TITLE
Can't mount, why and how to fix it?

### ISSUE THREAD

**Issue by aquatic7** [veracrypt/VeraCrypt#383]
OS: Manjaro
![selection_003](https://user-images.githubusercontent.com/18247537/48972612-4dd88f00-f02e-11e8-8a8f-a554c0e36178.png)

**Comment by Schweineschwarte** [comment]
I don't know why your libdevmapper is incompatible, but you can try to go to settings > preferences > system integration and set the checkbox with "Do not use kernel cryptographic services"
