### ISSUE TITLE
Unable to create volume from command line

### ISSUE THREAD

**Issue by davistan** [veracrypt/VeraCrypt#39]
Hi, I've just installed and trying to make a script for creation of volume, however I am facing the error - "Incorrect Volume Size".

Here's the command I used in ubuntu - `veracrypt -t -c --encryption=AES-Twofish -k=kf --filesystem=ext4 --hash=SHA512 --volume-type=normal --size=10M`

**Comment by initbar** [comment]
Based on this line: (https://github.com/veracrypt/VeraCrypt/blob/master/src/Main/TextUserInterface.cpp#L666-L667) and the man page:

![test2](https://cloud.githubusercontent.com/assets/12630151/12374905/bf330fb8-bc79-11e5-9c84-ce8f399dfc94.png)

I think the `--size` is indicated by actual bytes (i.e. `10M == 1e^7`). I've tried making a `100M` container and it works:

![test](https://cloud.githubusercontent.com/assets/12630151/12374921/3ff14066-bc7a-11e5-95c9-4c95a39c8023.png)

**Comment by idrassi** [comment]
@initbar answer is correct.
That being said, I have implement suffix support (K,M,G,T) for the --size switch:
- https://github.com/veracrypt/VeraCrypt/commit/c86697f51b0b71d327ba7f4b9211cacde0bbd2f0
- https://github.com/veracrypt/VeraCrypt/commit/e9d3ba0b113433f634324d2c407fba3e825af1ce

**Comment by davistan** [comment]
Ok, got it. Yes, its kind of confusing. Thanks @idrassi for taking a proactive step to include the suffixes.
