### ISSUE TITLE
Feature request: per file encryption for easier cloud integration sync minimal files on change

### ISSUE THREAD

**Issue by rorygsales** [veracrypt/VeraCrypt#396]
Hi , firstly thank you for taking over TrueCrypt and maintaining, its much appreciated. Well done.

This might already have been asked, but how difficult would it be to add functionality to compete with boxcryptor and cryptomator. Where instead of encrypting a entire drive, or creating a file container you create a file container per file copied into a virtual mounted drive?

This obviously means we can store the virtual dynamic growing drive inside our google drive or dropbox auto sync folder and more efficiently sync files that only get changed.

Many thanks in advance.

**Comment by sir106** [comment]
this would be a perfect match! Like this feature request!
