### ISSUE TITLE
Encrypted partition deadlock on exhaustive writes in multiple threads

### ISSUE THREAD

**Issue by trumpeta** [veracrypt/VeraCrypt#397]
I'm having stability issues using latest VC (1.23-hf2). Occassionally when writing to encrypted partition, the volume becomes inaccessible, ie. no way to unmount, no way to interrupt the operations and requirement to restart, fix the filesystem to recover. The filesystem is exFAT on 32GB physical partition (drive connected directly to internal SATA port). Encryption tokens: keyfile, no password.

This issue is annoying as imminent system reboot is required to continue using the encrypted volume.
(Had this volume earlier encrypted by TrueCrypt using the same method, and the present drive locks never occured). That's why I consider it to be a bug (possibly unhandled racing condition).

Please fix this asap as it really devaluates the real time encryption UX.

**Comment by trumpeta** [comment]
Alternately I'm getting BSOD with stop code REFERENCE_BY_POINTER.

**Comment by alt3r-3go** [comment]
@trumpeta, could you please provide the exact scenario you observe this in? The title suggests multiple threads and "exhaustive writes", none of which is elaborated in the description and is crucial to understanding the situation. A step-by-step reproducer would be ideal.

**Comment by trumpeta** [comment]
Not quite. I don't archive crash dumps or other details. After series of BSODs I realized that keeping the concerned volume encrypted is not so important to continually suffer by random computer deadlocks and reverted it to standard volume, no more Windows crashes since then.
Only what I remind is that the problem volume was formatted to exFAT as standard encrypted volume. I still use several VC encrypted volumes formatted as NTFS and never had described issue wrinting to them but it's also fact these volumes are used exclusively for storing long term data where I copy files in single thread.
I would focus attention on implemented exFAT format and doing disk stress tests on volume.
Software invoking the crtitical condition was foobar2000 making conversions in multiple threads outputing to encrypted volume. A specific formula of writng finished data may be on cause of course.
