### ISSUE TITLE
VeraCrypt Container with owncloud

### ISSUE THREAD

**Issue by bes1002t** [veracrypt/VeraCrypt#40]
Hi,

I created a hidden container inside a non hidden container. Then I put the encryptet file to my owncloud directory and owncloud synced it to my other devices (work pc and smartphone). 
Afterwards I mounted that file on my home pc and put simple image files inside the hidden volume. Now Owncloud was not able to sync the content change with my other devices. 
 I noticed that the alteration date of my container file has not changed, so I think that's the problem. A guy in Owncloud community said in truecrypt there was an option to enable the alteration date, but I can not find some configuration like that in veracrypt.

So how could I get owncloud to sync my container file after its content changed?

**Comment by idrassi** [comment]
The same option exists in VeraCrypt: In VeraCrypt main window, go to Settings > Preferences, and look for "Preserve modification timestamp of file containers" and uncheck the box. After that, each time you modify your container, its modification date will be updated and it will synchronized.

![VeraCrypt - Option Preserve Timestamp](https://i.imgur.com/x4Tp23O.png)

**Comment by jeremyclarke** [comment]
Isn't there some other way for OC to know that the contents have changed?

This is an extremely frustrating bug to discover on your own and not at all intuitive.
