### ISSUE TITLE
DIST_PACKAGE_CORRUPTED in windows XP SP3

### ISSUE THREAD

**Issue by cjl3230** [veracrypt/VeraCrypt#405]
I have a similar problem(https://sourceforge.net/p/veracrypt/discussion/technical/thread/6da4314708/?limit=25#1d35)

operating system:
windows XP sp3

VeraCrypt Version:
VeraCrypt Setup 1.23-Hotfix-2.exe

**Comment by idrassi** [comment]
I have posted an answer on the linked Sourceforge thread.

Basically, the issue is caused by a missing Thawte root certificate on the machine. In my answer I give details on how this can be fixed, either automatically if the machine is connected to the internet or manually.

Let me know if this solves the problem.

**Comment by cjl3230** [comment]
@idrassi I think it should be the situation you said. Because the computer of this xp system is a computer that is not connected to the Internet. I will test it after I return to the company around February 10.

**Comment by cjl3230** [comment]
> If the machine doesn't have internet, then you can download the missing certificate from https://www.thawte.com/roots/thawte_Primary_Root_CA.pem, rename it to thawte_Primary_Root_CA.crt, double click on it and then click "Install Certificate".

It can be used normally now. Thank you.

**Comment by idrassi** [comment]
Thank you for the confirmation.

**Comment by idrassi** [comment]
Since version 1.24, VeraCrypt is signed with a certificate issued by DigiCert and so if this issue happens, then one must manually install the missing DigiCert High Assurance EV Root CA certificate which is available at https://cacerts.digicert.com/DigiCertHighAssuranceEVRootCA.crt

**Comment by cjl3230** [comment]
I test VeraCrypt Legacy Setup 1.24-Update7.exe in my windows XP system. and I download https://cacerts.digicert.com/DigiCertHighAssuranceEVRootCA.crt. rename it to thawte_Primary_Root_CA.crt, double click on it and then click "Install Certificate". but It show me 'This distribution package is damaged. Please try downloading it again(preferably from official VeraCrypt website at https://www.veracrypt.fr).'
