### ISSUE TITLE
Error during compilation windows

### ISSUE THREAD

**Issue by sriharshapk1** [veracrypt/VeraCrypt#407]
Hi,

Getting the below error during compilation in windows.

#############################################
_NT_TARGET_VERSION SET TO WINXP
  1>errors in directory c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto
1>c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto\link : error LNK1181: cannot open input file 'c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto\obj_driver_debug\i386\sha512_avx1_x86.obj'
  BUILD: Linking for c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto directory
  
  _NT_TARGET_VERSION SET TO WINXP
1>c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto\link : error LNK1181: cannot open input file 'c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto\obj_driver_debug\i386\sha512_avx1_x86.obj'
  BUILD: Finish time: Sat Jan 26 11:46:26 2019
  BUILD: Done

##################################################

Can you help me out by telling what might be the reason.

Regards
Sriharsha P K

**Comment by idrassi** [comment]
It looks like yasm and/or nasm are missing from your PATH.
You have to ensure that all dependencies describes in the README are installed and particularly that gzip, upx, nasm and yasm binaries location are added to PATH during build.
