### ISSUE TITLE
1.23-Hotfix-2 display flickering bug

### ISSUE THREAD

**Issue by hexnone** [veracrypt/VeraCrypt#410]
1) Enable "Use secure desktop for password entry"
2) Enable hotkey to mount favotrite volumes
3) Press hotkey to mount favorite volumes. After desktop switiched to secure press hotkey again. And again...
4) You will see that several secure desktops are shown and they overlap each other.
5) In this way you can cause the system to hang completely
Windows 7 x64 with latest updates.
VC v. 1.23-Hotfix-2

**Comment by idrassi** [comment]
Thank you for reporting this.
I have pushed 2 commits that fixes this issue (https://github.com/veracrypt/VeraCrypt/commit/3903fcc595cbdcd403fa6713e663cf542e99c814 and https://github.com/veracrypt/VeraCrypt/commit/2061b4c28ca189781dc9d2625f1bd4899fccbd81).
It will included in the next beta 1.24-Beta3.
