### ISSUE TITLE
is it dangerous to have your rescue disk laying around?

### ISSUE THREAD

**Issue by hanswurst31** [veracrypt/VeraCrypt#414]
could the encryption password cann be compromised via the rescue.zip file which is created after the encryption of a system drive?

**Comment by idrassi** [comment]
No.
Without the password, the Rescue Disk is useless to an attacker. Its function is to hold a copy of the encryption header in order to be able to restore it in case of issue with the system disk. It doesn’t contain any other information that could compromise the password.
