### ISSUE TITLE
Probably typo in CPU RNG detection condition

### ISSUE THREAD

**Issue by manison** [veracrypt/VeraCrypt#417]
The condition here https://github.com/veracrypt/VeraCrypt/commit/e5b9cee8681dc45340321f759079b344a3b2676c#diff-16d98258fab9df665b2b16ef8eed9475R1226 states
`HasRDSEED() || HasRDSEED()`
where probably
`HasRDSEED() ||`**`HasRDRAND()`**
was intended.

**Comment by idrassi** [comment]
Thank you for spotting this. I have pushed the proposed fix.
