### ISSUE TITLE
Veracrypt Causing Windows Store Applications to Crash

### ISSUE THREAD

**Issue by AusomeOllie10** [veracrypt/VeraCrypt#418]
Hi All, 

I have an issue with veracrypt which I cannot seem to resolve, On windows 1809, I bought forza horision 4, When installing it to an alternate location, Windows Seems to load the application then instantly crash, this repeats itself for other application such as any store downloadable availible app.

When Loading the application, this Error appear within the Event viewer:

 The server Microsoft.XboxDevices_300.1809.28002.0_x64__8wekyb3d8bbwe!App did not register with DCOM within the required timeout.

The Application Will Start Brefily then proceed to fail, however this does not occour when using the System Drive (C) or any unecrypted USB

Help Would be grateful

Olivier

**Comment by niko247** [comment]
I had the same problem, after decrypting disk, game starts

**Comment by addy90** [comment]
I can confirm the problem when using XBox Game Pass. DCOM 10010 error like above.
It does work with some games, like Metro Exodus, but does not work with others, like ReCore.
