### ISSUE TITLE
Dubious S-Boxes in the algorithms Kuznyechik and Streebog?

### ISSUE THREAD

**Issue by Schweineschwarte** [veracrypt/VeraCrypt#419]
Hello,
I read on the german IT-News-page Golem.de the message, that the S-Boxes in the algorithms Kuznyechik and Streebog have a "dubious structure".
What is your oppinion and is it responsible in this situation to use this algorithms in Veracrypt?

https://www.golem.de/news/kuznyechik-streebog-russische-verschluesselungsalgorithmen-infrage-gestellt-1902-139333.html
More:
https://mailarchive.ietf.org/arch/msg/cfrg/4PmssKzCBsxTmLCieDgqD7Nynwg
https://eprint.iacr.org/2019/092

**Comment by idrassi** [comment]
Indeed, the research made by Léo Perrin is very interesting as he discovered a type of "master" mathematical transformation that completely describes the SBoxes used by Kuznyechic and Streebog.

If you read the paper, you will see that the author explored 3 possibilities behind the use of this special construction for the SBoxes in page 20. At this stage, there is nothing that points towards a backdoor in the SBoxes, especially for Kuznyechic and the question remains open if these mathematic formalas for the SBoxes could lead to any attacks.

Indeed, hiding how the SBoxes were generated goes against the transparently required for such critical algorithms and it can lead to suspicions of backdoors.

In my opinion, it would have been foolish form the part of the designers to introduce a backdoor in such critical national standards knowing all the current advances in algebraic studies. Moreover, despite the discovery of the mathematic design behind these SBoxes, there is no indication whatsoever that it is weakening the security of Kuznyechic and Streebog.

This leads me to think that maybe there is another interesting possibility: the designer of Streebog and Kuznyechic are aware of new type of algebraic attacks affecting modern ciphers and hash functions and they wanted to ensure that these algorithms are immune against this attack without revealing anything about the attacks they are protecting against!

This may seem to be far fetched as it would mean that someone has made a breakthrough cryptanalysis but history tells us that this is in the realm of possibilities.

For example, people were suspicious of the SBoxes forced by the NSA in the 70s for the DES encryption standard and everybody was saying that they were backdoored. But more that 10 years later, we discovered that actually the NSA was aware of Differential cryptanalysis before it was discovered by academics and they designed the DES SBoxes to resist it.

So, if history is repeating it self which is often the case, what we are witnessing here is like the discovery of a cure before the illness is even publicly announced. In which case, we should really worry about existing ciphers like AES and Serpent.

At this stage, I don’t see a reason to remove Kuznyechic and Streebog from VeraCrypt but I may change my opinion before 1.24 release. Meanwhile, for people needing high assurances, it is adviced to use Kuznyechic in cascade with another cipher and to replace Streebog with Whirlpool.

つづく...

**Comment by Schweineschwarte** [comment]
Thank you very much for your longer assessment! :)

**Comment by Eyremba** [comment]
@idrassi If Streebog gets removed, will it be replaced by SHA3/Keccak?
It would be cool anyways if you would add SHA3-256 and SHA3-512.

**Comment by saelic** [comment]
I would love to see SHA-3 algorithms in VC!

**Comment by luckied** [comment]
Hi,

Well shit, I am currently 60% done encrypting my system volume on Win10-1909 w/ Kuznyechic & Streebog before I saw this. Should I cancel it an swap Streebog for Whirlpool as suggested?

I was going for the best encryption in terms of longest time to encrypt/decrypt...

**Comment by alt3r-3go** [comment]
It really depends on your threat model :) but as Mounir very clearly described in his comment, it doesn't look like there's any specific *security problem* with those algorithms.
