### ISSUE TITLE
Mount VeraCrypt container in Tails

### ISSUE THREAD

**Issue by SecUpwN** [veracrypt/VeraCrypt#42]
Good morning @veracrypt developers, thanks for doing such an awesome job on this tool, especially for staying cutting edge on fixing security vulnerabilities! Since I am using the amnestic incognito live system [Tails](https://tails.boum.org/) on a regular basis, I would like to mount my VeraCrypt USB from there. Tails itself supports [opening TrueCrypt volumes](https://tails.boum.org/doc/encryption_and_privacy/truecrypt/index.en.html) using the `cryptsetup` command line tool, but is that compatible with VeraCrypt?

**Comment by idrassi** [comment]
The official VeraCrypt linux package works well under Tails (tested with Tails 1.8.2, you have to use the 32-bit version of VeraCrypt): either install VeraCrypt using the installation script or have the 32-bit VeraCrypt Linux binary available somewhere and copy it to your Tails system. It must be noted your Tails system must have a root password which should set during Tails startup.

Recent versions of cryptsetup (released on 2015) support VeraCrypt format but Tails doesn't include yet such recent version. So, you can't use Tails cryptsetup and you have to use the official VeraCrypt binary (for example by placing it in your USB key).

Here is a screenshot showing the official VeraCrypt binary running under Tails 1.8.2
![VeraCryptTails1.8.2](https://i.imgur.com/FZtLirU.png)

**Comment by SecUpwN** [comment]
>Recent versions of cryptsetup (released on 2015) support VeraCrypt format but Tails doesn't include yet such recent version.

Thanks for doing a bit reaserch on this, @idrassi. I'll notify the Tails developers of this existing Issue.

**Comment by SecUpwN** [comment]
Just to keep everyone monitoring this Issue uopdated: I've received a reply from the Tails developers:

>Unfortunately we can't include software that are not shipped in Debian as you can read:

>https://tails.boum.org/support/faq/#index28h2

>Please see our dedicated ticket about VeraCrypt: https://labs.riseup.net/code/issues/8911

**Comment by idrassi** [comment]
I think their answer is out of context since the need is to include the latest version of cryptsetup that supports VeraCrypt volumes and not including VeraCrypt itself.

It is better to ask them to include cryptsetup version 1.6.7 or above since VeraCrypt support has been included since this version: https://www.kernel.org/pub/linux/utils/cryptsetup/v1.6/v1.6.7-ReleaseNotes

The latest Debian 8.3 "Jessie" comes with cryptsetup 1.6.6 which is unfortunate...I guess this means that TAILS will only include this 1.6.6 version for the time being until Debian starts including cryptsetup 1.6.7

**Comment by SecUpwN** [comment]
>It is better to ask them to include cryptsetup version 1.6.7 or above since VeraCrypt support has been included since this version: https://www.kernel.org/pub/linux/utils/cryptsetup/v1.6/v1.6.7-ReleaseNotes

Thanks for telling me, @idrassi. I'll send them your suggestion as reply. Maybe I'll update this Issue again.
