### ISSUE TITLE
Feature request: Tools for use VeraCrypt in a corporate/enterprise environment

### ISSUE THREAD

**Issue by blu-IT** [veracrypt/VeraCrypt#421]
Hello,

I am not sure if I already mentioned it somwhere else before...
I'd like to have a tool for rollout/configuration/administration **VeraCrypt in corporate environments.** While rollout with tools like OPSI is no problem, the administration from a central configuration point or tool would be perfect.

I already know the **very helpful** FAQ article here, but that many work by hand ;-)

https://www.veracrypt.fr/en/FAQ.html

Are there any plans or ideas?

Regards

**Comment by worldsdream** [comment]
It would be great if we had a VeraCrypt management center. We can install it on a server. Then we can make groups in the management center. Customer 1. Customer 2 and so on. We make the veracrypt packages to each customer. When we install it on the machine. We can see it shows up in the folder of the customer. From there we can manage if the system is encrypted or not. 

I think this is a big project. Not easy to do.
