### ISSUE TITLE
why is encryption in windows 10 safemode faster then normal?

### ISSUE THREAD

**Issue by hanswurst31** [veracrypt/VeraCrypt#424]
in safemode it takes around 5 sec. in normal.mode 20 sec and plus.

edit: i ment decryption.

**Comment by GH-Rake** [comment]
Everything is typically faster in safe mode, something like 1/3rd of the processes are running and graphics are simplified, resolution is reduced etc...File permissions are also more basic.  All this allows Veracrypt more access to disk, memory and CPU resources.
