### ISSUE TITLE
Unable to mount veracrypt volume on sshfs share (error: VeraCrypt::File::Open:232)

### ISSUE THREAD

**Issue by edmundlaugasson** [veracrypt/VeraCrypt#428]
Similarly to bug #23 (seems to be still unsolved regardless its closed) cannot mount using [sshfs](https://en.wikipedia.org/wiki/SSHFS). But this time is not the GVFS (more: [1](https://en.wikipedia.org/wiki/GnomeVFS), [2](https://en.wikipedia.org/wiki/GVfs)) used like showed in case of smb but [sshfs](https://en.wikipedia.org/wiki/SSHFS) is used. Using the 100 MiB VeraCrypt container (EXT4 filesystem inside) with [PIM](https://www.veracrypt.fr/en/Personal%20Iterations%20Multiplier%20(PIM).html) (default value).

**The error message** while trying to mount VeraCrypt container: 
`Permission denied. VeraCrypt::File::Open:232`

Have read the [sharing over network](https://www.veracrypt.fr/en/Sharing%20over%20Network.html) chapter. As using alone, would like to mount with read-write permissions. [The network sharing article](https://www.veracrypt.fr/en/Sharing%20over%20Network.html) says nothing about supported network protocols. People may use [smb](https://en.wikipedia.org/wiki/Server_Message_Block), [webdav](https://en.wikipedia.org/wiki/WebDAV)(s), [nfs](https://en.wikipedia.org/wiki/Network_File_System), [sshfs](https://en.wikipedia.org/wiki/SSHFS) etc. Tried different [sshfs mount options](https://linux.die.net/man/1/sshfs) (_-C_ (using compression), _-o idmap=user_) but no difference (with or without those options) - still same error. The mounted path did not contain spaces (even I assume that spaces should not cause any issues), it was something like _/home/user/my.server.address/folder1/folder2/veracrypt.volume_ after remote share was mounted over sshfs and what I tried to mount using VeraCrypt. So no GVFS-related entries nor spaces in the path of container. After sshfs mounted, I checked VeraCrypt container permissions - all fine - there is rwx for owner and client computer user was the owner due to _-o idmap=user_ parameter . Tested also without that parameter - still same error. So  there seems to be no issues by permission side.

Software on computers used:
* client: 64-bit Linux Mint 19.1 MATE (based on Ubuntu 18.04 LTS)
  * OpenSSH_7.6p1 Ubuntu-4ubuntu0.2, OpenSSL 1.0.2n  7 Dec 2017
  * Ed25519 key-based authentication with server
* server: 64-bit Ubuntu 18.04.2 LTS
  * OpenSSH_7.6p1 Ubuntu-4ubuntu0.2, OpenSSL 1.0.2n  7 Dec 2017
* VeraCrypt 1.23 (September 12, 2018) installed via [PPA](https://launchpad.net/~unit193/+archive/ubuntu/encryption)

**Comment by edmundlaugasson** [comment]
Sounds like regression in security must be allowed in order to get it work:
- /etc/fuse.conf
- uncomment
  - _user_allow_other_
- save file
- when mounting with sshfs, use the parameter
  - _-o allow_other_

**Comment by jackomo42** [comment]
I would like to reopen this issue. My setup is similar to @edmundlaugasson, just with the current OS versions. Btw. thank you for the clear right up @edmundlaugasson. I get the same error when trying to mount the container from the server, connected via sshfs.

Client: Ubuntu 20.04 LTS - MATE
- VeraCrypt 1.24 - Update 7
- key-based authentication with server
Server: Ubuntu 20.04 LTS

@edmundlaugasson did you manage to get it working with your suggestion from Feb. 25 2019?

**Comment by Elmi77** [comment]
Using Windows VeraCrypt fails with sshfs-shares too: the error message is different (it complaisn about not beign able to mount a drive and lists several possible reasons in an error message box), but it does not work at all.

**Comment by rudhar55** [comment]
I had the same problem. Versions:
Local: Linux Mint 20.3 Una, Veracrypt 1.25.9
Remote: Alpine Linux 3.17.
Locally trying to mount a remote Veracrypt container file, accessed through sshfs.

The point in my case was a different numbering of users in /etc/passwd . The same username was number 1000 on one machine, 1001 on the other. Solution: when establishing the share locally with sshfs, I added the option "-o idmap=user" (without the quotes). The default is none instead of user, so numeric user-ids are used. 

I could verify locally that ls -l showed the correct user for the remote Veracrypt container file (the group-id was still wrong, but the permission 600, so it doesn't matter). And then veracrypt could mount the container!
