### ISSUE TITLE
veracrypt still says permission denied in version 1.16

### ISSUE THREAD

**Issue by forumuser** [veracrypt/VeraCrypt#43]
I'm German and so I've to apologize for a poor english.
The problem:
While there was mentioned that this issue has been fixed in further versions of veracrypt,
(found this: https://github.com/veracrypt/VeraCrypt/issues/23 and linked threads)
 it still occurs to me in this environment:
armv7 (odroid mini pc) with ubuntu server 14.04, 32 Bit.
First i installed a pre compiled veracrypt 1.01. After the "permission denied error" I performed the uninstall of veracrypt, get the sorces of the newest version and compiled it without installing wxwidget parts. Therefore i followed the instructions in the veracrypt Readme, which told me to use the wxwidet sources.
Everything went fine, veracrpt seems to run as expected, encrypts and decrypts volumes.
But in a mounted volume and in a samba share it denies the write permission.
And there is a strange behaviour: Through the samba share I can change an existing file (open text file, edit ist an save it without problems). But if I try to create a new file or directory - "permission denied". No chance by using other user accounts or made the user account the same name an passwort as the windows user.
Is it possible, that the first installation with that precompile package has left something, what should be deleted before the self compiled installation ist performed?
Your help would be very appreciated, I'm desperate and will have to move back to truecrypt, if I'm not able to fix this problem. Thank You in advanced.

**Comment by forumuser** [comment]
update:
it works:
after purge of all files related to wxwidget an veracrypt, doownload the sources of veracrypt again, recompiling and performing a new install with the new builded install script.
Thank you.

**Comment by idrassi** [comment]
Thank you for the update.
By the way, since you seem to compile under Armv7, is it possible to share your installation package?
Many users will be interested since the current available arm build is outdated.

**Comment by forumuser** [comment]
I'm tardy, the thread is closed - what should i do to share the file? 
never done this before...?

Am 24.01.2016 00:21, schrieb Mounir IDRASSI:

**Comment by idrassi** [comment]
You can send email to veracrypt at idrix [dot] fr with the generated installers or just the binary as attachment, preferably signed with your PGP key.
You can also post them in this discussion (normally you can attach files).
