### ISSUE TITLE
Linux system cannot add Chinese language

### ISSUE THREAD

**Issue by Aquarian-Age** [veracrypt/VeraCrypt#430]
```
sudo itstool Language.zh-cn.xml -o zh-cn.pot

file zh-cn.pot 
zh-cn.pot: GNU gettext message catalogue, UTF-8 Unicode text, with very long lines
```

```
sudo msginit -l zh_CN.utf-8 -i zh-cn.pot 
[sudo] xuan 的密码：
新的翻译库应该包含您的电子邮件地址，这样用户就可以对您的翻译提出意见，
同时软件维护者也可以在出现技术问题时联络您。

Is the following your email address?
  root@localhost
Please confirm by pressing Return, or enter your email address.

取回 http://translationproject.org/team/index.html... 完成。
A translation team for your language (zh) does not exist yet.
If you want to create a new translation team for zh or zh_CN, please visit
  http://www.iro.umontreal.ca/contrib/po/HTML/teams.html
  http://www.iro.umontreal.ca/contrib/po/HTML/leaders.html
  http://www.iro.umontreal.ca/contrib/po/HTML/index.html

已创建 zh_CN.po。

file zh_CN.po 
zh_CN.po: GNU gettext message catalogue, UTF-8 Unicode text
```

```
sudo msgfmt zh_CN.po -o zh_CN.mo
[sudo] xuan 的密码：

file zh_CN.mo 
zh_CN.mo: GNU message catalog (little endian), revision 0.0, 1 messages
```

```
sudo mv zh_CN.mo veracrypt.mo
sudo cp veracrypt.mo /usr/share/locale/zh_CN/LC_MESSAGES/
```

**Comment by alt3r-3go** [comment]
@Aquarian-Age, I'm sorry, I don't see any errors or problems in the command log you pasted. Care to elaborate what problem do you have, so that I or someone else could help?

**Comment by omaidb** [comment]
> ```
> sudo itstool Language.zh-cn.xml -o zh-cn.pot
> 
> file zh-cn.pot 
> zh-cn.pot: GNU gettext message catalogue, UTF-8 Unicode text, with very long lines
> ```
> 
> ```
> sudo msginit -l zh_CN.utf-8 -i zh-cn.pot 
> [sudo] xuan 的密码：
> 新的翻译库应该包含您的电子邮件地址，这样用户就可以对您的翻译提出意见，
> 同时软件维护者也可以在出现技术问题时联络您。
> 
> Is the following your email address?
>   root@localhost
> Please confirm by pressing Return, or enter your email address.
> 
> 取回 http://translationproject.org/team/index.html... 完成。
> A translation team for your language (zh) does not exist yet.
> If you want to create a new translation team for zh or zh_CN, please visit
>   http://www.iro.umontreal.ca/contrib/po/HTML/teams.html
>   http://www.iro.umontreal.ca/contrib/po/HTML/leaders.html
>   http://www.iro.umontreal.ca/contrib/po/HTML/index.html
> 
> 已创建 zh_CN.po。
> 
> file zh_CN.po 
> zh_CN.po: GNU gettext message catalogue, UTF-8 Unicode text
> ```
> 
> ```
> sudo msgfmt zh_CN.po -o zh_CN.mo
> [sudo] xuan 的密码：
> 
> file zh_CN.mo 
> zh_CN.mo: GNU message catalog (little endian), revision 0.0, 1 messages
> ```
> 
> ```
> sudo mv zh_CN.mo veracrypt.mo
> sudo cp veracrypt.mo /usr/share/locale/zh_CN/LC_MESSAGES/
> ```

你的中文语言包搞定了 嘛？
https://github.com/veracrypt/VeraCrypt/issues/355
