### ISSUE TITLE
Authentication Issue after   changing Bios Admin/User Pass

### ISSUE THREAD

**Issue by madmax01** [veracrypt/VeraCrypt#432]
I have an very strange Issue.

i got a brand new Dell G7 17.

all fine.  i encrypted the System NVME System Partition with AES. Pretest worked.  all good.  also after i was able to successfully authenticate.

for additional Security i changed Admin Password and User Password inside UEFI .  after it i got Authentication Errors for Veracrypt.

Also the system rescue same Issue.  Didn't found any way to decrypt .

i tried also an other Keyboard. 

i done then "Dell OS recovery".  > strange for any Reasons Veracrypt worked again > but system jumped into non working auto-repair.

i was able then to boot with stick and was able to make an Decrypt.

Factory Image worked after again. had to start from scratch > but better then nothing

But i still had the Veracrypt boot loader still after decrypt.  after factory i tried to install it again and to re/encrypt.  then it alerted me loader exist already > so wanted to override.  reboot to pre/test and again "Authentication" Error.

So something very strange happens.

booting with the rescue disk > its not removing the boot loader. even if disk not encrypted.

Best regards

max

**Comment by GH-Rake** [comment]
Did you ever find a resolution?
