### ISSUE TITLE
Cannot log into my laptop

### ISSUE THREAD

**Issue by RohitJain13** [veracrypt/VeraCrypt#435]
I encrypted my laptop with VerCrypt since I had to send the laptop for repair to HP.  Before I sent it in all I had to do was enter the password I had set and it logged me into the laptop.  But after my laptop came back from repair it also asks me for a PIM.  I don't know what PIM is and I chose default and did not enter a PIM.  It comes back with a message "Authorization failed. Wrong password, PIM or hash.  I think I have the right password.  So, it seems it has something to do with the PIM.  How do I get into my laptop now??!!

**Comment by GH-Rake** [comment]
Did you ever find a solution to this issue?  If you didn't use a PIM, then just leave it blank and hit enter.  The "I think I have the right password" concerns me, the evidence you provided is making me think you forgot your password which is a bad position to be in :(.  If that's the case, I think you're out of luck, nothing much can be done about that.

**Comment by RohitJain13** [comment]
I had the right password.  I wrote it down to make sure.  I probably should not have said “I think” but one tends to start doubting oneself when things like this don’t work.  Yes, I always hit enter leaving PIM blank since I did not know what it was since I never even set it.  I had to wipe out my laptop and I lost everything!  I think VeraCrypt is a piece of crap.  I ended up paying an extra $100 to get Windows Pro and use Bitlocker now.

**Comment by GH-Rake** [comment]
I recommend you always maintain a good backup, especially when sending a computer in for something like a warranty repair.

I know you've already moved on but for anyone in a similar situation, the next step is to use the [instructions regarding the Recovery Disk](https://www.veracrypt.fr/en/VeraCrypt%20Rescue%20Disk.html) that you made during the initial encryption:

> If you repeatedly enter the correct password but VeraCrypt says that the password is incorrect, it is possible that the master key or other critical data are damaged. The VeraCrypt Rescue Disk allows you to restore them and thus to regain access to your encrypted system and data (however, note that you will still have to enter the correct password then). In the Rescue Disk screen, select Repair Options > Restore key data. Then enter your password, press 'Y' to confirm the action, remove the Rescue Disk from your CD/DVD drive, and restart your computer.

**Comment by RohitJain13** [comment]
Yes, I used the rescue disk (USB stick) and booted from it and had the same issue.  So, I thought I followed the instructions.  When it did not work, I sent that message to the community for help.  But since I got no response for months, essentially I had to bite the bullet and move on.  Now, I had already replicated my data on to another laptop.  So, I had the data backed up just fine.  But you know that most of the effort we spend in restoring a laptop is in reinstalling all the apps and setting the right configuration options in things like Windows Office products and the like – custom dictionaries, recovering all the Chrome tabs, etc.  Even then, some of the configuration files for the apps cannot be recovered and you have to build them up again over time.  Of course, since I had much of that on my other laptop, and fortunately since I had taken copious notes when I set up my other laptop, that made the process of recovering this laptop somewhat easier.  But I ended up spending hours, if not days, to set up the laptop again, when it should have taken me no time at all.  Chances are that I did not even need to encrypt the laptop when I sent it to HP.  But I did no want to take a chance.

**Comment by GH-Rake** [comment]
That sucks, thank you for providing some additional insight

**Comment by RedSparrow2** [comment]
I don't ever recommend using bitlocker as there is a security risk. You can bypass the password by pressing the poweroff button several times and it will ignore. (This does not always work on all computer but at least where I work some laptops do).
Maybe they tried to get in to your computer and screwed it up a bit.
