### ISSUE TITLE
Unattend Install

### ISSUE THREAD

**Issue by CornyMaster** [veracrypt/VeraCrypt#436]
Is it possible to implement a install paramter to run the setup in unattend install mode, like other quiet install modifier? 

eg.: 
setup.exe /q
setup.exe /i
setup.exe /s
...
thanks

**Comment by OgreTransporter** [comment]
FYI: https://sourceforge.net/p/veracrypt/discussion/features/thread/e38495eb/

**Comment by OgreTransporter** [comment]
I would still prefer a silent install.
