### ISSUE TITLE
The problem with the launch of windows 10 after encryption veracrypt

### ISSUE THREAD

**Issue by TamaraSS** [veracrypt/VeraCrypt#437]
Hello, this problem has been fully encrypted drive with windows 10 program veracrypt, after upgrading the OS will not start, starts immediately restore tool. Respectively to restore system it is impossible as the disk is encrypted, it is necessary to get from a disk only 1 file how it can be made? It is impossible to mount a disk.

**Comment by JohnBrower** [comment]
Maybe the upgrade only reset the boot priority. Just try to find the old entry in your boot menue and set it as first option. If it doesn't exist try to restore the boot entry from rescue disk.
To get only one file u'll probably need a second pc and connect ur HDD via SATA. But Idk if the normal VeraCrypt disk-decryption also works for system disks.
...But as it's 26 days ago now I think u've solved the problem urself or u reinstalled windows.

**Comment by GH-Rake** [comment]
If you have not already done so, make sure you are using the latest version of VeraCrypt that includes the ability to use ReflectDrivers.  When it's time to upgrade to a 1803 or 1809 style upgrade, download the Windows Media Creator tool, extract the iso and do as this guide says https://sourceforge.net/p/veracrypt/discussion/general/thread/431df6e5/#22cb

It works great, I haven't had an issue and I've used it 3-4 times.
