### ISSUE TITLE
Unable to mount read-only volume from read-only media

### ISSUE THREAD

**Issue by zestysoft** [veracrypt/VeraCrypt#440]
I asked this question last week, but maybe sourceforge isn't the correct place? https://sourceforge.net/p/veracrypt/discussion/technical/thread/4e8126f1f2/

I have a drive that should never be written to. As such I'm using a device that prevents writes to external usb devices. (Tablaeu Forensic USB 3.0 Bridge)

The entire drive is encrypted (no partitions).

When I attempt to mount the volume, even with "Mount volume as read-only" enabled, I am given this error:

> device-mapper: reload ioctl on veracrypt1 failed: Read-only file system
> Command failed

I know this -- I WANT this -- is there no way to mount a read-only veracrypt volume without writing to it?

Ubuntu 18.04 LTS
VeraCrypt 1.23

**Comment by zestysoft** [comment]
Any thoughts on this?  Is this a design decision where VeraCrypt still somehow writes to the drive when read-only mounting, or is this likely just a bug or limitation with Linux (i.e. I'd get different results if I attempted this from Windows?)

**Comment by mathio3** [comment]
Try : `veracrypt -m=nokernelcrypto VeraVolume  mountpoint`
