### ISSUE TITLE
veracrypt doesn't work with clonezilla?

### ISSUE THREAD

**Issue by AscendChina** [veracrypt/VeraCrypt#443]
In the past when I wanted to migrate a FDE (TrueCrypt) harddrive to another, I would use clonezilla and the 'dd' method and it works 100%.

Now in a UEFI computer with Veracrypt (which doesn't support GPT full disk encryption which is greyed out, it only supports windows os partition level encryption) disk encryption, when attemting to migrate harddrive, even though I'm NOT using a PIM code, using a UEFI version of cloneazilla it allows me to clone it, but after restoring the Vera is not taking my passcode to boot... 

I was able to migrate it just fine (GPT/UEFI) by decrypting it first completely then by using the exact same method and the same version of clonezilla and then later post migration I re-encrypted it again. 

Was this a fluke or is there something in veracrypt that prevents it from being perfectly cloned and then decryption/encryption of the disk drive to also work 100%?

**Comment by ArunYogesh** [comment]
So, i cloned an entire disk with a encrypted windows 10 ltsc OS + a hidden encrypted windows 10 installation. It was UEFI with CSM and secure boot disabled (cloned using clonezilla with dd). I was able to get it working with some work. Right after restore it booted to veracrypt bootloader but it didn't accept the password, tried the recovery usb to boot, that didn't work too. So I restored the veracrypt config and os header keys (of dummy os) from the veracrypt recovery usb. After that it booted into the dummy os. 

Previously I had the gpt_enc and os_hdr backed up in my recovery usb. I had created a separate partition to store these keys ( to avoid requiring a separate usb for booting hidden os), so restored these back to the secure keys partition from Efi shell. After this I added the SecRegionSearch=1 and DcsBootForce=1. Voila, I can now boot into both dummy and hidden os.
