### ISSUE TITLE
Clonezilla won't mount veracrypt partition

### ISSUE THREAD

**Issue by peter099** [veracrypt/VeraCrypt#444]
I don't know if this is a issue with Clonezilla or VeraCrypt but it won't mount encrypted with veracrypt partition. I am mounting the veracrypt partition with --filesystem=none parameter, but when i point Clonezilla to the partition it shows that the mount point is busy or the partition is already mounted. Is there way to make Clonezilla mount this partition?

**Comment by blu-IT** [comment]
Could that affect this issue?

https://github.com/veracrypt/VeraCrypt/issues/443

**Comment by peter099** [comment]
I think it's different issue. It's about cloning encrypted partition, if i understand correctly, not saving backup image to encrypted partition.
