### ISSUE TITLE
Linux External NVME SSD - Slow speed (comparison included)

### ISSUE THREAD

**Issue by Utini2000** [veracrypt/VeraCrypt#445]
Hello everyone,
I am running an external SSD (Corsair MP510 2TB) via USB-C which on ext4 gets 900-1000MB/s read and write.
I now tried several different setups and compared the speed. How ever, it seems like VeraCrypt always slows down the read/write by at least 50% to the native performance. 
Also I would like to use the container/SSD on Linux and Windows.

System:
Archlinux
i7-8850H
32GB RAM CL15
Main SSD: Samsung 970 Pro 1TB
AES + SHA-512
VeraCrypt benchmark: 8,8GB/s 

ext4: 900MB/s - 1000MB/s
ext4 + veracrypt (ext4): 500MB/s - 650MB/s
ext4-luks: 650MB/s - 800MB/s
exfat: 680MB/s
exfat + verycrypt (exfat): 250MB/s
exfat-luks: 450MB/s - 500MB/s
ntfs: 175MB/s

Anyone has an advice or can recommend a different approach? I already thought about doing just a big .zip file with a password. I think that way I could even dynamically expand the "container".

**Comment by Utini2000** [comment]
No one? :/

**Comment by GH-Rake** [comment]
I don't have an answer or an opinion but here is some relevant reading material:
https://github.com/veracrypt/VeraCrypt/issues/136
https://superuser.com/questions/1317954/why-are-truecrypt-veracrypt-write-speeds-so-disproportionately-slow
https://sourceforge.net/p/veracrypt/discussion/technical/thread/ead5ae6c/

**Comment by Utini2000** [comment]
So this issue is present for ~2 years and VeraCrypt isn't fixed yet.
Is there even some development going on? From the links you posted it seems like VeraCrypt is abonded/dead.  

Are there any reliable alternatives? 
The performance decrease is huge on SSDs and NVME :/

**Comment by GH-Rake** [comment]
Last commit was ~2-3 months ago.  There is only one developer, which is one of the project's many challenges.

Open source, free, vetted, updated alternatives for Windows?  I don't believe there are any.  

Bitlocker is the best alternative if you don't have privacy/security concerns, especially if you're concerned about speed.  Symantec and other vendors sell disk encryption that is pretty good but they're $100+.

I have never benchmarked my rigs but I have veracrypt on all 3 computers and never noticed a speed decrease.  I'm don't consider myself a heavy disk usage user but I do some video encoding, use VMs and I backup all my files to an external regularly.  All 8 of my hard drives are encrypted.  I never noticed a slowdown or had a complaint, but that's just me.

Veracrypt is the only free, open source, recently updated and featured disk encryption software that has been vetted to my knowledge.  The project could use an infusion of new volunteers to support the project,  I am trying to help out in the issue tracker if I can.

**Comment by hardhub** [comment]
@GH-Rake 

DiskCryptor?

**Comment by GH-Rake** [comment]
> 
> 
> @GH-Rake
> 
> DiskCryptor?

Hasn't been updated since 2014, otherwise I don't know much about it.

**Comment by hardhub** [comment]
I have used it last 4 years. No problem.. it is stable.

Of course it does not support UEFI and probably it will not be added. But for me it is not a problem.

**Comment by SkyWriter** [comment]
I was able to get some performance gain (60 Mb/s vanilla VeraCrypt vs 100 MB/s custom build vs 250 Mb/s raw unencrypted writes) on Mac OS X by increasing some of the FUSE IO block parameters (https://github.com/SkyWriter/VeraCrypt/pull/1). Maybe makes sense including this in the upstream. I am hesitant to submit a pull request though since I hardly know about the implications (possibly security related too?) regarding these changes.

**Comment by NumDeP** [comment]
Hi @Utini2000 and @SkyWriter have you updated to the latest 1.24 and seen whether it's better with all the necessary features selected for enhancement?

**Comment by Utini2000** [comment]
I am on Archlinux and the official repo is still hat 1.23. I will try once it is updated.

Btw, the release notes of 1.24 dont mention anything new related to this enhanced options?

**Comment by NumDeP** [comment]
I was just about to ask you if you have **exfat-utils and fuse-exfat** installed then read what you mentioned. I wonder if Microsoft's official support of exFAT helps, though I sort of doubt it would.


One other hthing having read what you said abount wanting to use the conainter in both Winodws and Linux, you don know that you can't use ext4, right?

**Comment by Utini2000** [comment]
Hi @NumDeP and thank for replying!

1. Yes I want to use the drive + container on Windows + Linux. While ext4 is possible on windows, it is not very convient. It needs special drivers, admin rights, a certain setup time and then the speed might just be as slow as exfat-fuse on linux. Also I read about several data crashes/loss due to the buggy ext4 driver on windows. I plan on simply plugging the drive into a windows laptop and using it. So ext4 wasn't an option for me.

2. I am not using fuse for exfat on linux. I have "exfat-utils-nofuse" installed on Arch.

3. Yes 400MB/s is fast. But not as fast as 650MB/s (which ext4 encryption would offer) and not as fast as the 1000MB/s that the USB 3.0 port can deliver on the drive and even further away from the 8,8GB/s that the veracrypt benchmark is telling me. So the maximum limitation should be the USB port speed (1000MB/s) which is still a lot fast than the 400MB/s I currently get :)

**Comment by NumDeP** [comment]
@Utini2000 have you ever created a potion of the external drive into an an encrypted partition and seen what that does?

I wouldn't expect to achieve the great speeds those technological devices, cables and ports offer, naturally the encryption side of things would have to take force which would result in slower speed, surely you understand that. VeraCrypt is the standard encrypt and decrypt solution, though I do sort of agree with you, that benchmark does present some dubious figures.

**Comment by Utini2000** [comment]
@NumDeP what do you mean with a potion? :o 

The 1000MB/s are possible by simply copying on the unencrypted drive via the USB 3.0 port. 
So the drive, the USB port and the veracrypt benchmark seem to offer 1000MB/s.

**Comment by NumDeP** [comment]
Crap :) Sorry about that, I meant a portion. Though I do believe I saw purple somewhere around VC.

`Create a volume with a partition/drive` I read that part on the application again and I think it only allows you to encrypt the entire partition drive or secondary drive and something tells me you'd prefer to have some items on the drive you can quickly access and drop things into.

As for your second comment, I very much doubt that. What you're essentially talking about is GB/s speeds, which has to be very rare. If you ever do achieve that in any encrypted circumstance please take a quick screenshot and upload it here for me to see. Thanks in advance.

**Comment by Utini2000** [comment]
Ahh now I get it :)

Yes I already tried partitioning the whole drive but it didn't give me any speed results. Also I wanted to have ~100GB unencrypted for quick access (its a 2TB or 3TB NVME SSD).

No no, I meant something different when talking about the possible speed:
1. There is VC telling me in a benchmark that my CPU can handle 8,8GB/s speed.
2. Then there is the NVME SSD which has a maximum speed of ~2500MB/s
3. Afterwards there is the USB Port that limits me to 1000MB/s (verified by my own tests without encryption).
4. As soon as I copy something in the encrypted container on the external NVME SSD, I get limited to ~400MB/s which I cannot fully understand because the drive, the USB port and the encryption CPU should allow me way more with the maximum limitation beeing the USB port at 1000MB/s.

**Comment by GSPP** [comment]
I believe there is significant interest in improving performance on SSD drives.
