### ISSUE TITLE
[Feature request]: Collecting randomness from /dev/random (with the support of haveged)

### ISSUE THREAD

**Issue by stevenleeS0ht** [veracrypt/VeraCrypt#450]
It would be awesome if veracrypt can collect randomness in /dev/random which can be empowered by haveged.

**Comment by alt3r-3go** [comment]
This is already available - see documents [here](https://www.veracrypt.fr/en/Random%20Number%20Generator.html) and code [here](https://github.com/veracrypt/VeraCrypt/blob/master/src/Core/RandomNumberGenerator.cpp#L32-L50)
