### ISSUE TITLE
[Feature Request] Support Linux Apps on ChromeOS

### ISSUE THREAD

**Issue by ghackett** [veracrypt/VeraCrypt#456]
Currently VeraCrypt cannot mount encryped containers on ChromeOS (with "Linux Apps" aka Crostini). It appears this is because VeraCrypt is using "loop device" (https://www.reddit.com/r/Crostini/comments/aqkhdj/chrome_os_73_bring_fuse_to_crostini/eggr36n/)

Would it be possible to (optionally) mount containers using fuse on linux (which is now supported in crostini)?

**Comment by campey** [comment]
This is still an issue for me, not resolved dear stale bot.

**Comment by jaromil** [comment]
If there is  terminal you may try this script https://github.com/dyne/Tomb/tree/master/portable is a proof of work and I'd be interested to know if it works, to develop it further also on chromeos.

**Comment by ccchan234** [comment]
> This is still an issue for me, not resolved dear stale bot.

hi, how about using gocryptfs?

same thing, just the external media is read-able as rubbish, i.e. encrypt-ed files could be copied in encrypt-ed form.
but still keep the secret?

https://github.com/rfjakob/gocryptfs/issues/731

thanks

**Comment by script26** [comment]
does baguette (crostini-containerless) work with veracrypt because now it gives the full vm instead of in an lxc container, so maybe it has loop modules now?

if not i know you could run virt-manager, run user qemu/kvm, but usb passthrough does not really work
