### ISSUE TITLE
after (every?) windows update i need to use rescue disc

### ISSUE THREAD

**Issue by hanswurst31** [veracrypt/VeraCrypt#457]
why do the windows 10 updates corrupt the VC partition? vcfixboot.exe fixes the bootloader everytime but still a bit anoying.

thx

**Comment by GH-Rake** [comment]
Are you talking about smaller updates or the upgrades such as 1709 and 1809 etc?

Are you using the ReflectDrivers method for the big upgrades?  Upgrade to the latest version of Veracrypt and start using this feature for the upgrades: https://sourceforge.net/p/veracrypt/discussion/general/thread/431df6e5/#22cb it's worked flawlessly for me

**Comment by hanswurst31** [comment]
installed the linked version from the following post still had to restore the boot efi after the update:

https://sourceforge.net/p/veracrypt/discussion/general/thread/431df6e5/#22cb

**Comment by GH-Rake** [comment]
In your case I would manually install the upgrades by using the Media Creation Tool & /ReflectDrivers method.

The other alternative I can recommend is decrypting and uninstalling Veracrypt and then reinstall it and re-encrypt, maybe you have some weird bug and this might help solve it.

**Comment by alt3r-3go** [comment]
@hanswurst31, just to make sure - there were additional relevant VeraCrypt fixes after version mentioned in the post you refer to (1.23-beta0). I'd suggest you to install the latest one released at this moment, which is 1.23-hotfix2.

There were at least several reports of successful updates both in manual and automated modes, but also some apparent confusion in that thread, so overall by reading it, I have an impression it actually works ok with the latest VC version and it were either older versions or unrelated problems lurking around (as reported by people there themselves).

So please try that one and feel free to report here whether it works or not upon the next update. I also plan to run some tests on this, but can't say how soon that would be, so any additional information is more than welcome.
