### ISSUE TITLE
Is AMD StoreMI and veracrypt compatible?

### ISSUE THREAD

**Issue by hanswurst31** [veracrypt/VeraCrypt#458]
Is AMD StoreMI and veracrypt compatible?

**Comment by alt3r-3go** [comment]
I haven't personally tried, but looks like someone already did (including talking to the vendor of the software behind that - Emnotus FuzeDrive) and the answer is - partially. Meaning that "data" drives should be okay, but the VeraCrypt system encryption and StoreMI are incompatible.

See details [here](https://www.reddit.com/r/Amd/comments/8g1qom/amd_storemi_vs_intel_smart_response_technology/dy8m2tf/)
