### ISSUE TITLE
Some files corrupted in container

### ISSUE THREAD

**Issue by deryb** [veracrypt/VeraCrypt#460]
I had some files on an encrypted container which became corrupted. I cannot find cases where this happened and cannot reproduce this at the moment (it happened a while ago and did not have time to waste), but needless to say I freaked out and hoped this wasn't a widespread issue. I use this container to store financial documents, mostly pdf files. The corruption appeared when trying to open some of these files and the reader app complained the files were corrupt. I tried with a bunch, Acrobat, Foxit, Chrome, etc. 

I realize there's nothing to debug with this blurb of anecdotal info, but at the very least I'd like to know steps to try and help pinpoint what was the issue. 

My environment:
- Windows 10 
- Veracrypt 1.21
- Container file is located on a network attached storage (NAS).
- Auto dismount after 60 minutes of inactivity = enabled
- Force dismount if volume contains open files = enabled
- Preserve modification time-stamp = disabled. I use this so that backup software copies newer versions. I wish there was a way to do incremental backups but did not find any so far... 

Here's my typical usage scenario:
- Open the container
- Save a few files (reports from financial institution, etc)
- Close the container
- time passes, typically a few days / weeks until next read/write is needed.
- I started noticing this issue on a few files I saved perhaps a few weeks before. No more details, sorry, from my dusty memory ;-)

I'm pretty sure no dismount happened while these files were being written, and usually am careful to dismount manually volumes. Please suggest steps I can do to tackle this. One idea I had was to look at log files somewhere, but did not find how.

**Comment by alt3r-3go** [comment]
So your scenario indeed looks like quite "normal" one and indeed I've been doing something very similar for years without any problem.

One very small thing that's probably irrelevant is that 1.21 is a bit old by now and I'd recommend you to upgrade to the latest 1.23-hotfix2 instead.

As for the corruption though - in this setting, if we rule out VeraCrypt bug for now (which is not impossible, but very unlikely given this is a very typical scenario and you haven't observed any explicit malfunction), I'd say the network or your host RAM or a NAS may be the suspect.

As you open the file on your share (I assume using either a mapped drive on your Windows host or directly via a UNC path to the container, `\\your.nas\vol\file`), Windows uses SMB/CIFS protocol for that and depending on the specifics, there _may_ be some data corruption going on without any explicit manifestations - or that was a one-time thing.

This one could be checked (if that's still active only though) by running some data transfer workload withween your WIndows host and NAS and capturing the network traffic using Wireshark. The trace should expose some of the basic problems like retransmissions and so on.

NAS may have disk or RAM problems, which could manifest themselves as [silent] data corruption. This could be checked by running S.M.A.R.T. tests and memory tests. Whether this is possible and how specifically would depend on your NAS model.

Finally RAM on your host could be checked by something like [`memtest86+`](https://www.memtest86.com/).

As for log files - on Windows you could check Event Log. Specifics of accessing it depend on the Windows version, but usually right-click the My/This Computer icon, Manage and it will be there in the tree. Look for Application and System logs.

**Comment by sorin0101** [comment]
I had exactly the same issue today. Windows 11 and VeraCrypt v1.25.9, HDD encryption, NTFS file system. I have copied 2Tb of data (mostly mp4 files) to a encrypted drive and 4 files were corrupted. After comparing both files I found out that the difference was only, in 1 bit, so on each file only 1 bit was corrupted.
