### ISSUE TITLE
Which libfuse version does this thing need?

### ISSUE THREAD

**Issue by cgoea** [veracrypt/VeraCrypt#467]
Hello,

As per subject. Trying to build on Linux with libfuse 3.6.1 => build fails.

**Comment by unit193** [comment]
Howdy,

As you can see in the Makefile[0], it's looking for 'fuse.pc' which is provided by the 2.x series, as fuse3.pc is provided by the 3.x series.

[0]: https://github.com/veracrypt/VeraCrypt/blob/master/src/Main/Main.make#L107

~Unit 193

**Comment by cgoea** [comment]
> Howdy,
> 
> As you can see in the Makefile[0](https://github.com/veracrypt/VeraCrypt/blob/master/src/Main/Main.make#L107), it's looking for 'fuse.pc' which is provided by the 2.x series, as fuse3.pc is provided by the 3.x series.
> 
> ~Unit 193

Thanks.
