### ISSUE TITLE
[Feature Discussion] Encryption Wrapper

### ISSUE THREAD

**Issue by NumDeP** [veracrypt/VeraCrypt#468]
Hello @ynasser I sort of forwarded a long winded proposal to your cyber.harvard.edu email and figured just in case you didn't catch what I mentioned in the side note or you thought it was silly, I might as well include it here for others to get a glimpse of it.

I was thinking, do you think an "encryption wrapper" is possible? 
So imagine you already have a sophisticated encryption solution but it's just a simple create an encrypted folder/partition and drag/copy/cut and paste files into the new encrypted folder/partition. However, if you utilise an OS that isn't secure or a usb stick for that matter, technically residue from a drag/copy/cut would be left behind, right? Unless of course you already had an encryption solution already set up and you're effectively creating new files into the encrypted folder instead of drag/copy/cut, correct?

So is it possible to wrap encrypt a file without leaving residue of the file?

**Comment by ynasser** [comment]
I am not involved with this project, and also I don't know much about the nuances of file encryption, sorry.

**Comment by NumDeP** [comment]
Don't apologise, I figured all cryptographers love tackling all kinds of encryption and thought you might have found it interesting considering it was open source. I know its quite cheeky of me but I avoid social media like the plague and couldn't find a way to direct mail you and was also hoping to use it as a segue to propose something to you. Did you happen to catch my email I sent to your @cyber.harvard.edu ?

**Comment by tomlowenthal** [comment]
Hey @NumDeP it doesn't look like your unsolicited multi-channel message was welcome. Probably time to leave this alone.

**Comment by NumDeP** [comment]
Sorry for having annoyed anyone :( I'll leave it open to understand whether the topic at hand is still practical by the maintainer or someone who understands the nuances of file encryption at a greater depth.
