### ISSUE TITLE
VeraCrypt System Favorites service delays Windows 10 startup, also fails to mount system favorites

### ISSUE THREAD

**Issue by xistense** [veracrypt/VeraCrypt#475]
System configuration:

**Windows 10 v1903 x64**
Disk0(uefi boot, system): NVME
Disk1: SSD
CPU: hardware accelerated AES
**Veracrypt v1.24-Beta5**
 
After encrypting system partition, Windows boots normally, but the welcome screen is delayed with about a minute, no matter if there are drives added to system favorites list or not. During this delay, there is almost no CPU or hard drive activity.

If there are any drives added to the system favorites list, they are not mounted.

Disabling the "VeraCrypt System Favorites" service removes the delay.

Also tested and confirmed in a virtual machine.

**Comment by alt3r-3go** [comment]
This sounds like the third last bullet in [Known Issues and Limitations](https://www.veracrypt.fr/en/Issues%20and%20Limitations.html). I don't have Win10 at hand to test, but as it also has the same feature of "fake shutdown", this looks plausible to me.

Could you please test the fix proposed there and share the result?

**Comment by xistense** [comment]
> Could you please test the fix proposed there and share the result?

This seems to have fixed the issue, thank you!!!

**Comment by alt3r-3go** [comment]
Wonderful, thanks for checking and reporting back.

**Comment by mr-falafel** [comment]
I seem to be experiencing this exact behaviour but I'm certain fast boot is disabled. What else can I try?
