### ISSUE TITLE
[Bug] calling veracrypt --auto-mount=favorites does not honor mount options settings

### ISSUE THREAD

**Issue by alex-dot** [veracrypt/VeraCrypt#48]
Calling `veracrypt --auto-mount=favorites` will not honor mount options settings, if set in Properties -> Mount Options. 

I have an encrypted FAT system which needs utf8 encoding explicitly set in Linux, otherwise special characters like umlauts will not be displayed correctly and will make some applications choke. For this veracrypt supports passing additional mount options, in my case I'd put `iocharset=utf8` in. 

If I try to mount my defined favorites by using the GUI, the additional mount option is automatically applied to the dialog. However if I start veracrypt through the command line (or a script), the option is not automatically applied to the dialog.

**Comment by RealEnder** [comment]
Also mount options should be stored separately for every volume in favorites, eg. when mounting more than one volume with different filesystems, requiring different mount options.

**Comment by andreas-becker** [comment]
Is this "Bug" in the current version still present or can it be closed?
