### ISSUE TITLE
How come 'Hidden OS' feature is not supported on Linux?

### ISSUE THREAD

**Issue by Joe23232** [veracrypt/VeraCrypt#480]
How come the 'Hidden OS' feature is not supported on Linux but it is supported on Windows? I would like to see this feature for Linux as well.

**Comment by NumDeP** [comment]
@Joe23232 it is. I think this can be closed.

![Screenshot_20191008_205103](https://user-images.githubusercontent.com/31957540/66428225-93673600-ea0d-11e9-8aca-f240702c24bd.png)

**Comment by Joe23232** [comment]
I am sorry but it may support creating deniable encrypted volumes but it does not support creating a "Hidden OS" just like it does on Windows and I believe this feature should be supported on GNU/Linux as well.

**Comment by NumDeP** [comment]
Sorry I was mistaken. You're right it isn't available. I thought about this once before and I thought this was down to Luks and the complication that come with it when installing a typical Linux based distro, where as with Windows I think VC practically replaces BitLocker and obviously improves privacy and security.

Did you use this feature in Win10 or MacOS?

**Comment by Joe23232** [comment]
@NumDeP 

> Sorry I was mistaken.

All good :)

> I thought this was down to Luks and the complication that come with it when installing a typical Linux based distro,

Yeah the only problem is that Luks only supports standard encryption, not denaible encryption.

> where as with Windows I think VC practically replaces BitLocker and obviously improves privacy and security.

Yes this is true.

> Did you use this feature in Win10 or MacOS?

Nah I haven't used this feature yet. Windows has terrible privacy and I want to move to GNU/Linux but then the only issue is that VC does not support the hidden os feature on GNU/Linux which makes no sense.

**Comment by NumDeP** [comment]
Future article - Torvalds and Idrassi collaborate to improve system encryption for Linux distributions.

**Comment by Joe23232** [comment]
@NumDeP Does it have deniable encryption?
