### ISSUE TITLE
files copied to veracrypt without copy progress bar

### ISSUE THREAD

**Issue by pete111** [veracrypt/VeraCrypt#482]
ORIGINAL THOUGHTS:
Hi, I am using encrypted veracrypt conatiner file this way:
Veracrypt file is stored on another computer in network (or on the server remotely). Folder with veracrypt file is shared so I can connect to remote server and connect server as remote network location (Win10). Then on my local computer I mount veracrypt file as a drive letter. Then I "copy" ~200MB file into mounted drive (it is "copied" in fraction of second). BUT when I click on unmount this drive from my system, just NOW veracrypt starts copying this big 200MB file into it and I must wait. It seems, that first time it just stored that file in RAM and just before unmount veracrypt starts to apply changes. 
This is bad, because if I work whole day with mounted drive and accidentally network connection is broken at the end of the day, I lose whole day and changes are not there when I mount drive again. 
Is it possible somehow to tell veracrypt to apply changes directly when file is being copied or saved to mounted drive?

**UPDATE:** 
**I found out that my assumption of writing was not perfect. In fact, it starts to write data after you drag big file to mounted drive. 
_BUT_** there is no progress bar about writing (no windows progress bar, nor total commander progress bar). It is confusing when user thinks that file has been written but on background process still lasts (that is also explanation why I thought in my original question that veracrypt is writing file just on unmounting). This should be fixed or improved to keep user informed that file is still being written.

**Comment by alt3r-3go** [comment]
> when I click on unmount this drive from my system

Do you mean the VeraCrypt container unmount on the system where the container actually resides or the remote system "mapped drive" unmount where you do the work?

In general, this sounds like the usual work of the Windows filesystem cache, which is sort of expected.
If you mean the container unmount though, there's an option in VC called "Mount volume as removable medium", that should disable the cachins and do write-through - give it a try if not using it already.

![image](https://user-images.githubusercontent.com/45139988/64287346-b494bc80-cf5f-11e9-9345-7f0d61a7a0f2.png)

**Comment by alt3r-3go** [comment]
Glad to help :)

**Comment by alt3r-3go** [comment]
@idrassi, this one can be closed as resolved, JFYI.
