### ISSUE TITLE
Passwort not working - how to remove it

### ISSUE THREAD

**Issue by Tehral** [veracrypt/VeraCrypt#483]
Hello,

I just tried to encrypt a new Win10 Disk.
After the Setup it restarted and is nto accapting the Password.
I checked the layout and everything but it is still nto accepting it.
I tried restore disk and loaded the boot laoder and head new -> still nto working.

How to I remove veracrypt or start the System?

Thank you

**Comment by pipboy96** [comment]
Reinstall Windows 10 using a DVD disk or a flash drive.
