### ISSUE TITLE
security issue due to german translation

### ISSUE THREAD

**Issue by Van-Fouran** [veracrypt/VeraCrypt#489]
There is a critical issue due to the german translation:
Within the system encryption VeraCrypt will create a rescue disk. At the creation the wizard will ask you if you want to skip the rescue disk verification.
In the german version only the string "Rettungsdatenträgerüberprüf" will be displayed. This word is obviously incomplete.
Many people I've worked with, including myself, have assumed that this is a simple spelling mistake and should read the word "Rettungsdatenträger überprüfen". This means something like "Verify Rescue Disk". We were encouraged by the fact that there was enough space behind the word and it could be assumed that it was not cut off.
If you look in the source code you can see that the entry "Rettungsdatenträgerüberprüfung überspringen" should be called. This means something like "Skip verification of the Rescue Disk". It means the complete opposite!
We have all checked this option because we wanted to do the verification. As it turned out, we skipped it instead!

**Comment by xrv0** [comment]
I can confirm this

**Comment by Van-Fouran** [comment]
See: https://sourceforge.net/p/veracrypt/discussion/technical/thread/db05fd02f1/#9cad
