### ISSUE TITLE
PIM value unclear

### ISSUE THREAD

**Issue by Van-Fouran** [veracrypt/VeraCrypt#493]
If you do a system encryption you can make it more secure by using a Personal Iterations Multiplier (PIM): https://www.veracrypt.fr/en/Personal%20Iterations%20Multiplier%20%28PIM%29.html
Even if the user does not select a PIM to be used in the setup wizard, he or she is prompted to enter a PIM value during pre-boot authentication. VeraCrypt has used the default value, so the correct procedure for pre-boot authentication is simply to press ENTER to use the default value. Unfortunately, many users who are not familiar with the PIM value are not aware of this, so they will not be able to unlock their computer. Since they can not unlock their computer, in the worst case, they can no longer access the documentation and search for any help.
In my opinion, there are two different solutions:
1. The PIM field in the Pre-Boot Authentication should be hidden if the user has deselected the use of the PIM with the wizard.
2. A statement should be included in the wizards before the pre-test.

I would be glad about feedback or other ideas.

**Comment by GH-Rake** [comment]
Or maybe a quick fix on the bootloader, something to the tune of:
"If no PIM, just hit enter"

**Comment by Van-Fouran** [comment]
Yes this could be a fix, too.

**Comment by NumDeP** [comment]
Duplicate #488

**Comment by Van-Fouran** [comment]
> Duplicate #488

Thank you for the link. You are right, both cases are regarding the information of the PIM Value.
But this case is for information within the pre-boot screen and the case #488 is for information within the wizard.

**Comment by Van-Fouran** [comment]
> Or maybe a quick fix on the bootloader, something to the tune of:
> "If no PIM, just hit enter"

This was corrected in Version 1.24-Hotfix1

Nevertheless I would recommend to give a short statement about the PIM value in the wizard.

**Comment by Van-Fouran** [comment]
Correction: Only fixed if EFI Bios is used. If legacy Bios is used there will be no information during start up
