### ISSUE TITLE
How to use Rescue Disk?

### ISSUE THREAD

**Issue by UnleavenedEagle** [veracrypt/VeraCrypt#499]
Hello, I do not know how to select stuff in the VeraCrypt rescue disk 1.23 software.

I press `D` to go to `Decrypt OS`, type in my password, press Enter, leave the PIM empty, press Enter. Some information appears and a text saying 'Decrypt?' I seem to be able to enter a single character after this. I've tried typing in `y`, `Y`, `1`, or just simply pressing enter, but all of them resulted in a `Read error: Invalid Parameter`.

If I select `C` to restore VeraCrypt loader configuration to system disk, it asks me to `Select EFI boot volume:`. I do not know what to type there. I've tried typing in `0`, `1`, `0x0`, `0x1`, `HD`, etc., but none of them seemed to do anything. Regardless of what I write inthere, it will return me to the main menu with all the options, but now I won't be able to select any of them, and can only exit.

Is this a normal behavior, or do I have a "bugged" recovery disk?

---------------------------------------------------------------------------------------------------

The reason why I needed the Recovery Disk in the first place, is because everything was working, then I shut the system off, by clicking the `Shut Down` button in Windows. Then it told me that VeraCrypt is still running, please close it, but it then automatically turned off. Next time I tried to boot up the system, VeraCrypt didn't ask for a password, instead the boot menu came up, where if I selected VeraCrypt Loader, it blinked once, and the boot menu appeared again.

Fixing this problem is very urgent for me, any help is appreciated.

**Comment by GH-Rake** [comment]
hmm tricky situation, I have not used the recovery disk before.

When you originally encrypted the system drive, were you using UEFI or Legacy BIOS?  I'd just double check to make sure that is still the same.

Rescue Disk Documentation:
https://www.veracrypt.fr/en/VeraCrypt%20Rescue%20Disk.html

Maybe try running a hard drive test like Seatools?  maybe the hard drive is damaged, maybe it can repair a few sectors as well.

Do you have another computer or a live USB stick you can boot up, and then try to decrypt your original drive from within one of those OSes?  Bypassing the rescue disk

Sorry not much help here, but maybe you can rule out a few things based on my reply

**Comment by UnleavenedEagle** [comment]
Hi! Just letting you know I've solved the problem, it wasn't related to VeraCrypt, my bad. Thank you.
