### ISSUE TITLE
[Feature] Propagate VeraCrypt's ability to verify available free disk space before creating a volume of a specified size to Linux.

### ISSUE THREAD

**Issue by supercom32** [veracrypt/VeraCrypt#502]
On Windows, if you create a new encrypted volume, VeraCrypt will check if the volume exceeds the amount of disk space available and prevent you from proceeding (unless you disable the check via command line option). 

This works fine for Windows, but does not help users running Veracrypt on other operating systems (such as Linux). Since it was assumed the fix could be generically applied to all versions, no OS was specified in the original request. If the solution is not trivial to apply to Linux or other versions of VeraCrypt, feel free to leave this open for tracking purposes.

**Comment by NumDeP** [comment]
Hi @supercom32 I believe this is fixed with the most recent update, correct?
> 
> Linux:
> - Add check on size of file container during creation to ensure it's smaller than available free disk space.

**Comment by idrassi** [comment]
Yes this has been implement just in time for 1.24 release.
