### ISSUE TITLE
Windows 10 vs Linux Mint 19

### ISSUE THREAD

**Issue by c4tom** [veracrypt/VeraCrypt#504]
when I use veracrypt on linux, it's very slow. But when using on Windows10, it's not slow

Why this difference?

**Comment by Flupkees** [comment]
I don't use VeraCrypt myself, but ran into this when looking into VeraCrypt:
"Performance

VeraCrypt supports parallelized encryption for multi-core systems and, under Microsoft Windows, pipelined read and write operations (a form of asynchronous processing) to reduce the performance hit of encryption and decryption."
https://en.wikipedia.org/wiki/VeraCrypt#Performance
It doesn't mention veracrypt on linux, but seems to imply a performance difference. Have you looked into the load on your cores? Are you speaking about the same encrypted container that you use cross platform?

**Comment by AlexeiScherbakov** [comment]
I used veracrypt on Raspberry Pi 3 via crypttab and it doesn't slow down any operations on SD-card or harddrive.

Also check hardware support of AES-NI instruction set under Linux
```
grep -m1 -o aes /proc/cpuinfo
```

**Comment by NumDeP** [comment]
It's actually suppose to be the other way round. From experience I can tell you that in Linux the application is significantly more efficient than when I used it on Windows OS.

One other thing, you didn't state which version you were running and which aspect of it is slow. I think we're assuming the decryption side of it on the last beta version which fixed a few bugs, if so, can you share what features and preferences you've selected with the length of pass and pim if selected. Obviously you don't have to be accurate with the pim number :)

Does the new 1.24 better?

**Comment by c4tom** [comment]
# grep -m1 -o aes /proc/cpuinfo

aes

**Comment by c4tom** [comment]
I updated it to 1.24, it seems to improve, to copy files, it's almost the same as copying from windows
