### ISSUE TITLE
Update Libzip

### ISSUE THREAD

**Issue by TheSorrow1** [veracrypt/VeraCrypt#508]
Libzip version 1.5.2 is available, we are currently using 1.5.1,

Changelog:

- Fix bug in AES encryption affecting certain file sizes
- Keep file permissions when modifying zip archives
- Support systems with small stack size.
- Support mbed TLS as crypto backend.
- Add nullability annotations.

**Comment by idrassi** [comment]
I have pushed the update for libzip: https://github.com/veracrypt/VeraCrypt/commit/b6babc688d3d49ca32c3dbadfb2a4e32e9a43cdd

Thanks
