### ISSUE TITLE
[v1.17] USB flash drive not showing multiple partitions

### ISSUE THREAD

**Issue by CodeGordon** [veracrypt/VeraCrypt#51]
I have a SanDisk USB stick partitioned as shown below.

![image](https://cloud.githubusercontent.com/assets/7526525/13260440/6c624cb8-da29-11e5-899d-c4a1f2dfbdd3.png)

When I try to create an encrypted volume using this second partition, VeraCrypt can't see it.

![image](https://cloud.githubusercontent.com/assets/7526525/13260477/942df652-da29-11e5-95ee-ffba0e1a69a4.png)

According to the FAQ "How can I use VeraCrypt on a USB flash drive?", this should fall under option 2. While I understand that Windows can't use the extra partitions, according to that FAQ entry, VeraCrypt should be able to.

I've been looking all over the documentation, existing issues, forum posts, etc. and have not been able to find a solution. How can I get VeraCrypt to acknowledge the extra partition?

**Comment by idrassi** [comment]
VeraCrypt can not use a partition on a removable drive if it is blocked from normal I/O by Windows at the driver level. This is what's happening in your case.

On XP days, there were technical solutions to enable applications to access extra partitions on USB sticks but these don't work anymore on Windows 7/8/10. Thus, the FAQ text should probably be rewritten to avoid any misunderstanding.

Anyway, to see if the extra partition is usable or not, you can use an application I developed called ConcealDrive: it displays a device list dialog similar to VeraCrypt one but implemented differently and it should show your extra partition alongside its path in Windows. 
If this path ends with a digit, then it should work but if it ends with ?? then it means that Windows blocks I/O operations on this partition and VeraCrypt in this case can not bypass it.

Version 1.1 of ConcealDrive is available at https://github.com/veracrypt/ConcealDrive/releases/tag/ConcealDrive_1.1.

**Comment by CodeGordon** [comment]
It shows ??, so that's not going to work. Thank you for the help and info.
