### ISSUE TITLE
[Discussion] Is the Large Files section in the Volume Creation Wizard necessary?

### ISSUE THREAD

**Issue by NumDeP** [veracrypt/VeraCrypt#514]
When a user selects a **Standard VC Volume**, I don't understand the purpose behind having the **Large Files** section in the Creation Wizard when a user for certain on the previous **Volume Size** section typed in 5 GB or more.

![Screenshot_20191008_194216](https://user-images.githubusercontent.com/31957540/66432313-b0076c00-ea15-11e9-8482-cbb2e18671d4.png)

**Comment by idrassi** [comment]
Even if the user is created a file container larger than 4GB, it is possible that he will not want to store a file larger than 4GB (for example he knows that he will store only files with a size less than 100 MB) and so in this case a FAT32 filesystem will be enough for him.

**Comment by NumDeP** [comment]
Thanks for the reply @idrassi 

You can close this issue to tidy up the current list off issues in the repository. However I think similar to **Encryption Options** the bit of information that you included I found/find to be very useful and perhaps can also be helpful in future in relation to the next series of steps, as there are a few things that could cause issues for (new) users if they incorrectly choose a specific option but don't realise that it would cause a fault in the system or another OS because of Format Options or the selection of one-of-two in Cross-Platform Support. It doesn't have to be verbose but just the essential to allow a user to make a sound choice.
I've actually been wanting to discuss something related to this and VC in general regarding a project matter I'd been contemplating for quite sometime now with yourself/idrix so perhaps I could go into much more detail later-on.

Just on a side note, kudos on **1.24-Hotfix1**. I didn't see it in the release notes but the improvement of startup is certainly more rapid on start than ever before in Linux. I don't know whether it was because you had a specific `openSUSE-15-x86_64.rpm` install because I'm used to installing the generic console and gui.

Thanks again.

**Comment by jbaker6953** [comment]
> 
> 
> Even if the user is created a file container larger than 4GB, it is possible that he will not want to store a file larger than 4GB (for example he knows that he will store only files with a size less than 100 MB) and so in this case a FAT32 filesystem will be enough for him.

FAT32 or exFAT will not be suitable if he wants to be able to use file permissions, compress files, or use the benefits of a journaling filesystem. I guess what I'm saying is that there is more to choosing the best file system on Windows than large file support. Perhaps in the future it would be better to make clear the capabilities and limitations of the various supported filesystems.
