### ISSUE TITLE
Error popup before lauching pretest

### ISSUE THREAD

**Issue by ElKoleoptere** [veracrypt/VeraCrypt#517]
Hi,

I'm trying to crypt the system partition on a HP ProBook 4540s with VeraCrypt 1.24 64bits. The OS is Windows 10 Pro version 10.0.18362. The problem is when I'm about to launch the pretest, the popup asking if I want to reboot the PC now is showing, I click "yes" and then I have several error popup. 
These are, in order : 
- "Can not detect EFI environment 
Source: VeraCrypt::EfiBoot::DeleteStartExec:2573"
- "Can not detect EFI environment
Source: VeraCrypt::EfiBoot::SetStartExec:2622"
- The message telling me it is impossible to initialise the encryption pre-test. 

The BIOS mode is UEFI and the encryption worked on other PC with different OS. Do you have any idea how to work aroud this problem so I can encrypt this PC as well ?

**Comment by alt3r-3go** [comment]
@ElKoleoptere, there were some robustness fixes loosely around those pieces the error has in 1.24-hotfix1. Please give that one a try and post the results.

**Comment by alt3r-3go** [comment]
@ElKoleoptere, is this still actual?

**Comment by ElKoleoptere** [comment]
Hello, I didn't had the chance to try that for now. I'll have to wait another two weeks at least before that. I'll let you know if it works. 

Thanks for the tip though !
