### ISSUE TITLE
Windows crashes after boot. 

### ISSUE THREAD

**Issue by Natrocx** [veracrypt/VeraCrypt#52]
I'll try to put everything I can find and consider useful in here. If you have a question ask please the most should be possible to find out. 
I have encrypted my 2 Windows partition (sda1 with the system installed, sdb0 belongs to an additional hdd drive) completely. Sda is an SSD with the bootloader installed on it. Sdb should be unimportant,  because I have only installed an Ubuntu there I can't access at all because of missing grub. When I boot something happens which happend to me before and is somewhat familiar to me. 
My windows 10 crashes everytime I boot, 20-30 after authenticating. In that state my pc tells me it has constant disk usage although nothing is written afterwards. 
I've had that issue before once after booting my Ubuntu and I couldn't fix it till now, but it hasn't been so important because after hard reset my pc would boot normally. This is actually not the case. I can boot my windows as often as I want the same error would occur every time. 

I would be very glad for any help because I can't decrypt my system at the moment due to a missing cd reader.

**Comment by idrassi** [comment]
Ideally, it would helpful to check the Windows Event Viewer for entries related to the crash to see which component is causing it but I guess 20 seconds are too short for such manipulation.
Is the crash a BSOD or a freeze? You post is not clear about that but usually a crash is synonym for BSOD.

If it is a BSOD, can you capture that message displayed? It indicates the components that is causing the crash. You can for example shoot a video or take a picture of the BSOD screen.

It looks to me like a hard drive issue anyway. There are many articles and posts on the internet about Windows freezing when using an SSD drive and this has nothing to do with encryption. For example this link explains how such issue could be solved by changing the sata mode from AHCI to IDE: http://z9.io/2013/11/26/yes-finally-fixed-ssd-freezing-computer/

**Comment by Natrocx** [comment]
My computer freezes completely, not responding to anything. I have to reboot it manually afterwards. 
Sadly my motherboard does only provide AHCI or RAID mode and in RAID it doesn't boot at all after verifying the encryption key.

**Comment by Natrocx** [comment]
I just managed to get into Windows safe mode. 
I displays a critical warning to "Kernel-Power" telling me that the system haven't been shut down correctly. 
Also there's been an error with "Kernel-Event-Traicing" telling me something about a session named : "Circular Kernel Context Logger". It's something about the maximum size of the file is reached.

**Comment by Natrocx** [comment]
Problem solved. 
I booted to safe mode deactivated my user-password and everything works fine. 
But really thank you. You helped me a lot.
