### ISSUE TITLE
need to mount via rescue disc since last windows feature update.

### ISSUE THREAD

**Issue by hanswurst31** [veracrypt/VeraCrypt#522]
after every update my verycrypt partition wont boot so i have to use VcFixBoot64.exe in order to fix this problem. no big deal since its just every other month or so. my problem is that the last update gave it really hard to my vera partition it seems :D since the last update my vera partiion wont boot like after every big update but this time i get no error message and VcFixBoot64.exe wont work to fix this. any idea how to fix this?

**Comment by idrassi** [comment]
Can you please explain what happens after you type VeraCrypt boot password? Does it get stuck in a black screen or does Windows start but blocks afterwards?
