### ISSUE TITLE
FDE passphrase is limited to 51 Characters

### ISSUE THREAD

**Issue by CryptoJones** [veracrypt/VeraCrypt#527]
Can't enter more than 51 characters in the passphrase TextBox on Windows when setting up FDE.

**Comment by CryptoJones** [comment]
the characters I used are were simply ',.0123456789qazwsxedcrfvtgbyhnujmik'

**Comment by idrassi** [comment]
I have just done a test of Windows system encryption where I entered a 64 characters password in the wizard and there was no problem.
I recorded a video of this and the link is below (I choose to display password and I typed characters in sequences of 10 characters so to be sure that I entered 64 characters):

https://youtu.be/tfEqKFcKT5Y

Are you doing the same thing?

**Comment by CryptoJones** [comment]
I changed the password to 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef and it workd just fine. Sorry for creating a false ticket.
