### ISSUE TITLE
VeraCrypt User Guide grammatical errors

### ISSUE THREAD

**Issue by motovate** [veracrypt/VeraCrypt#537]
thank you for all your hard work. love VeraCrypt! while browsing the guide I noticed the errors **bolded** below.

Known Issues
On Windows, it may happen that two drive letters are assigned to a mounted volume instead of a single one. This is caused by an issue with Windows Mount Manager cache and it can be **solve** (prefer solved)

and a little further down

On some Windows machines, VeraCrypt may hang intermittently when mounting or dismounting a volume. Similar hanging may affect other running applications during **veraCrypt** (capitalization)

thank you again. I hope this is helpful and not an annoyance
Keith

**Comment by idrassi** [comment]
Thank you for taking the time to report and fix these errors, I really appreciate.

I have pushed a commit that contains the corrections you proposed. So, I will close this issue. Don’t hesitate to report any other mistake you may find.
