### ISSUE TITLE
VeraCrypt 1.24-Hotfix1: boot password always incorrect on first try

### ISSUE THREAD

**Issue by PhilipvD** [veracrypt/VeraCrypt#538]
I'm running VeraCrypt 1.24-Hotfix1 on Windows 10 1903. Since the update from 1.23 the first attempt to boot from the bootloader always returns that the password is incorrect (even though the password is correct). On the second attempt (same password) the computer boots normally into Windows. 

Is this a known issue? Any way to resolve this?

**Comment by idrassi** [comment]
We have never encountered this issue on our PCs and other users don’t seem to be affected by this. So there must be something specific on your configuration that is causing this after 1.24 update.

All changes in 1.24 are jot related to keyboard handling and there is only one change where we disable EFI watchdog but this is not supposed to affect the first character types in the keyboard (here is the commit https://github.com/veracrypt/VeraCrypt-DCS/commit/c2582cc9a199b606835e8cdbf37991778efede4a)

Is it possible to know the model of your motherboard and its BIOS version?
Also, can you test with another keyboard?
If you are using a wireless keyboard, try using a standard USB one.

**Comment by PhilipvD** [comment]
Thank you! Trying another keyboard solved the issue.. not sure why. Both are USB keyboards and UK English QWERTY layout. It indeed seemed like the first character that was typed in caused the issue.
