### ISSUE TITLE
Feature request: Use disk label as the mount point on Linux

### ISSUE THREAD

**Issue by stp242** [veracrypt/VeraCrypt#54]
Hi,

It would be a huge timesaver for me if VeraCrypt would always use the disk label instead of /media/veracryptx

I noticed it already does this on OS X, but not on Linux :disappointed:

Any chance this can be implemented? :smiley_cat:

**Comment by davidfoerster** [comment]
You can work around this by mounting the encrypted volume through the command line. A while back I wrote a bunch of [TrueCrypt mount helpers](/davidfoerster/truecrypt-tools) which can be adapted  trivially to VeraCrypt.

Alternatively, more recent versions of [cryptsetup](https://gitlab.com/cryptsetup/cryptsetup) can open the more common TrueCrypt/VeraCrypt container setups.

**Comment by stp242** [comment]
Thanks for the links David :smiley:

Those are some great scripts. I will try to adapt them to VeraCrypt.

**Comment by andreas-becker** [comment]
@stp242 does it mean, that this issue can be closed? If so, please close :-)
