### ISSUE TITLE
Veracrypt 1.24-Hotfix-1 Windows 7 Issue

### ISSUE THREAD

**Issue by jbaker6953** [veracrypt/VeraCrypt#545]
Double-click or right-click -> open on a mounted volume in the Veracrypt UI does not open a Windows Explorer window. Instead the cursor just spins for 30 seconds and then stops. Anti-virus is disabled and running Veracrypt as Administrator.

Also, maybe related to Windows Explorer issue: Dismounting a Veracrypt container that is in a Dropbox folder doesn't allow Dropbox to synchronize the file. Instead Dropbox throws an error that the file is locked. This was never an issue until after 1.24, but it could also be a Dropbox issue.

**Comment by ghostArch** [comment]
for 
>Dismounting a Veracrypt

Assuming you have a up-to-date backup of the file. I would suggest first finding out what program is keeping the file locked. Then you can try restarting the OS, that should free the file as the program should be closed by the OS during shutdown or log-out.
----
**peace out**
_ghostArch_

**Comment by alt3r-3go** [comment]
I've just tried installing a fresh 1.24-hotfix1 onto Windows 7, both mounting and opening the mounted container work fine for me. No file locking either. Sounds like you may have something else there, besides antivirus that you say is disabled. 

You can try to find what's locking it by using e.g. Systinternals ProcessExplorer, it has this functionality. Try searching the container file name and see what's holding onto it - and please report back if you have troubles understanding teh results of that action.
