### ISSUE TITLE
Resizing display on Mac looses window off screen

### ISSUE THREAD

**Issue by artmg** [veracrypt/VeraCrypt#546]
Using the MacOSX build (currently 1.24 Hotfix 1 but issue exists with older versions too).
When I undock my PC the display resolution changes and the top part of the VeraCrypt window shifts outside the screen area. The way to move a window on a Mac is to drag the window heading bar, but unfortunately that is in the bit that is chopped off.

The other way to reposition a window on a Mac is to use the Menu option Window / Zoom. There is a Window menu on the Mac build, after the Help Menu. I believe it is added automatically (by wxWidgets?) on the Mac, as there is no reference to it in [Forms.cpp](https://github.com/veracrypt/VeraCrypt/blob/master/src/Main/Forms/Forms.cpp)
where the MenuBar is built up. However the Zoom option in there is greyed out. (I wonder if this is because the window is set up as a fixed dialog?)

I have not yet found any other way to reposition the window, short of un-mounting all Volumes by exiting the application, then re-launching it and opening all the volumes one more. Do you have any suggestions of how to circumvent this issue? Thanks

**Comment by idrassi** [comment]
Thank you for this report.
I will try to implement a workaround for this issue. Maybe we can detect such case by handling wxEVT_MOVE event and if we detect that part of UI is out of screen, we move the frame to make it visible again. I will update this issue if I have any results.

**Comment by idrassi** [comment]
@artmg : I have implemented a workaround that should fix this issue: if we detect that the window was moved so that its heading bar is not visible anymore, we automatically move it so that the heading bar is visible again.
Also, I have added a new behavior when About dialog is displayed: we ensure that the full VeraCrypt window is visible on the screen by moving it if necessary before showing About dialog.

This change will be included in upcoming 1.24-Update2 release. You can test it then and report if the issue is fixed.

**Comment by artmg** [comment]
That sounds great @idrassi I appreciate you putting together a fix, and for having the foresight to use About dialog as a trigger. I look forward to the U2 release. Je te remerci

**Comment by idrassi** [comment]
@artmg 1.24-Update2 version has been released. I hope it will work as expected. En vous remerciant d'avance pour votre test.

**Comment by artmg** [comment]
Merveilleux Mounir, that resolves the issue very well indeed. When the window resizes, it automatically snaps a suitable fully-visible place, and I can make it do so any time by using Menu About. Great work, and many thanks for keeping this valuable tool available and up to date. Bonne fête de noël
