### ISSUE TITLE
Windows 1.24-Hotfix1 - "change password" still has the old character limitation

### ISSUE THREAD

**Issue by scarduck** [veracrypt/VeraCrypt#550]
When trying to change the password for a volume, it still has the 64 chars limitation.

**Comment by alt3r-3go** [comment]
Hey @scarduck,

I've just tried the following sequence:
1. Installed 1.24-hotfix1
1. Created a new volume with 70-character password - worked fine (including mounting it afterwards)
1. Changed the password to a 73-character string - worked fine as well (incl. mounting)

Just to make sure - you don't have that option highlighted below enabled, do you?

If that's not the case - could you please describe the steps you perform in more detail, as well as provide more details on your environment and the volume?

![screenshot](https://user-images.githubusercontent.com/45139988/69012607-ea9ae780-0977-11ea-84ae-0b19bb4a6b19.png)
