### ISSUE TITLE
Can't mount volumes on Windows 10.17134.1069

### ISSUE THREAD

**Issue by piperun** [veracrypt/VeraCrypt#554]
With the latest stable version 1.12-Hotfix1 I can create or change password on a volume but I can't mount it, it just gives me this error:
http://i.imgur.com/Ti1E0fQ.png

**Comment by nikkopt** [comment]
Ver 1.12 is very old. Is it a typo?
Can you try making a new volume with its default settings and a easy short password to see if it mounts?
Can you try it in another machine to rule out yours?

**Comment by alt3r-3go** [comment]
@piperun, is this still actual? If yes, have you tried the most recent version as 1.12 is ancient?

**Comment by piperun** [comment]
It seems to have been fixed in the later versions. 
The issue in the newest version is that the error pop up message doesn't get focused (or blink in the taskbar) and the pop up appears where you left veracrypt before you started to mount.

**Comment by alt3r-3go** [comment]
Thanks for checking with the new version. I'm not sure I get the new problem though - would it be possible for you to maybe record a screen capture or e.g. just a video with your phone, illustrating that?
