### ISSUE TITLE
Polish localization bug

### ISSUE THREAD

**Issue by p0k33m0n** [veracrypt/VeraCrypt#557]
```
BUG: <entry lang="pl" key="MENU_WEBSITE">   St&amp;rona WWW   </entry>
FIXED:  <entry lang="pl" key="MENU_WEBSITE">St&amp;rona WWW</entry>
```

This little bug create main menu/UI problems.

**Comment by alt3r-3go** [comment]
@p0k33m0n, which exact problems you observe here? AFAIU, those double spaces are a "feature" to make sure the right-justified menu item (it's [intended](https://github.com/veracrypt/VeraCrypt/blob/master/src/Mount/Mount.c#L480-L481) to be at the right side of the window, if that's what you mean) doesn't get too close to the window border.

![image](https://user-images.githubusercontent.com/45139988/69914980-4a01f880-144a-11ea-808e-118f64827be4.png)

**Comment by alt3r-3go** [comment]
@p0k33m0n, is this still actual?
@idrassi, I think this one could be closed, as there's no actual issue here.
