### ISSUE TITLE
Feature request: Additional status display during quick format

### ISSUE THREAD

**Issue by private-account** [veracrypt/VeraCrypt#558]
#388 implemented very promising new quick format functionality, thank you. As discussed, the process will still take time for the operating system to reserve the filespace, which can still take multiple days for a large external drive (which can now be at least 10 TB) - [mine](https://www.storagereview.com/node/4712) is still ongoing after ~50 hours. However, one new negative to the new functionality is that there is no status displayed during this process. At present, during this process it appears the Volume Format screen shows "Done: 100%", but with the only button not disabled being an "Abort" button. Is it possible to get/display any additional information about the status?

> when VeraCrypt tells Windows to create a file with a given size (e.g 250 GB), VeraCrypt do this by calling a single function but Windows will need a lot of time depending on the filesystem users because Windows will have to reserve the physical space on the disk and deal with disk fragmentation. This explains why this simple operation can take a lot of time.

**Comment by smallerxie** [comment]
In fact the objective is not to add a feature "additional status display during quick format", it should be "to fix the bug(s) within the function quick format", please see my comments in #388 .
Or, you can try to enlarge a small volume by using the "volume expander" tool and choose "quick expand" to compare.

**Comment by idrassi** [comment]
@smallerxie as I explained in Sourceforge forum thread, this is not a bug in "quick format" functionality. "quick format" is doing exactly what is supposed to do (which is quick formatting) but as explained by @private-account it is windows who takes time to reserve the disk space requested for the file.
Expander has an option "Quick Expand" which uses a insecure way to make file creation faster and I have already implemented a new command line switch in VeraCrypt Format called `/FastCreateFile` and which makes VeraCrypt Format use the insecure but faster way to create files.
The commit for this change is https://github.com/veracrypt/VeraCrypt/commit/f9d95ef2c84ebc61e4e0c77f8b9f054c65abd7cd and it will be included in the upcoming 1.24-Update2 version. But you can already test it using the 1.24-Update2-RC build available at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/

@private-account : we have no way to check the progress of process of reserving the size for the file. This is handled by Windows and we block while writing data to the file after Windows reports to us that it was created successfully. If we wanted to control the whole process, we would need to handle file size reservation ourselves: this is technically possible by combining the insecure way to creating file and manually writing zeros for the whole file. Maybe in next versions we can implement this approach. Meanwhile, using the new `/FastCreateFile` switch or the Expander is an alternative if the security risks associated with them are acceptable.

**Comment by private-account** [comment]
Thank you again!

I was previously not completely aware that by default, Windows offers no progress/status feedback to the app, but it's impressive that you've found possible alternative(s). Based on all that, I am fine for this issue to be closed however you prefer @idrassi ?

(Regardless of any of these 'quick' options, I believe data stored is still 'secure' in that it is encrypted from others. I believe the potential security implications are that 1) an attacker could potentially identify *whether* data is stored, and 2) could see whatever was previously stored on the disk as it hasn't yet been overwritten.
In my *particular* case, even those potential security issues I believe wouldn't be present, as the driver previously held a VeraCrypt container before it was lost due to a filesystem failure.)

**Comment by Zythyr** [comment]
> 
> 
> #388 implemented very promising new quick format functionality, thank you. As discussed, the process will still take time for the operating system to reserve the filespace, which can still take multiple days for a large external drive (which can now be at least 10 TB) - [mine](https://www.storagereview.com/node/4712) is still ongoing after ~50 hours. 

@idrassi @private-account I am still facing this issue on Windows. However I wonder if the same steps were replicated on a linux system (ex: Ubuntu), would it still take 50+ hours? I currently don't have access to a Linux system to test. However, if Linux system dones't have this issue, one possible solution would be to create the file container on a linux system since this is a one time occurrence

**Comment by private-account** [comment]
@Zythyr:

> I am still facing this issue on Windows. However I wonder if the same steps were replicated on a linux system (ex: Ubuntu), would it still take 50+ hours? I currently don't have access to a Linux system to test. However, if Linux system dones't have this issue, one possible solution would be to create the file container on a linux system since this is a one time occurrence

I can't speak to Linux, but:
- I ended up cancelling the process after ~50 hours; I wasn't sure if it was making progress or whether there was some issue. And of course the time it takes depends on the volume size and disk access speed.
- Likely more importantly, @idrassi mentioned a possible workaround at https://github.com/veracrypt/VeraCrypt/issues/558#issuecomment-565764460
