### ISSUE TITLE
[Feature Request] Enable TrueCrypt Mode if file extension ends in *.tc

### ISSUE THREAD

**Issue by nikkopt** [veracrypt/VeraCrypt#560]
Yes i know, i should convert my truecrypt volumes to veracrypt ones. The thing is, i have lot's of volumes on blu-ray discs and their contents aren't that sensitive. 
All my veracrypt volumes end in *.vc and my truecrypt ones end in *.tc 
When i want to mount a volume (not on my favorites), i double click it, type the password and press enter. 99% of the time i forget to put the tick in the truecrypt mode and it makes me wait more than 15 seconds before failing. 
Can't the "Truecrypt Mode" option get ticked automatically if the volume i'm trying to open ends in *.tc ?
And what i mean by that is: is the implementation of that "silly" feature easy enough to even bother with it?

**Comment by nikkopt** [comment]
Ok scratch what i said. I forgot that those file extensions are made up by me and not default to the program itself.

**Comment by nikkopt** [comment]
Ok, after using googling the subject i found out that *.tc was indeed the extension used by truecrypt. I guess my original question still makes a bit of sense after all. Sorry about that.

**Comment by idrassi** [comment]
This is already the case on Linux and MacOSX but it was missing from Windows build.
I have implemented it in this commit: https://github.com/veracrypt/VeraCrypt/commit/1fd097c666be570fedf612ed7caa7e809881e072

It will be included in the upcoming 1.24-Update2 version and you can already test it using the latest 1.24-Update2-RC build available at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/
