### ISSUE TITLE
Decrease memory usage of IOCTL_DISK_VERIFY handling in driver

### ISSUE THREAD

**Issue by Dobatymo** [veracrypt/VeraCrypt#562]
I am often sending `IOCTL_DISK_VERIFY` to my drives to check them for errors. Real hard drives support verifying large sizes at once (1gb for example). The VeraCrypt driver however tries to allocate memory according to the verify size. This is not necessary, because the read data actually doesn't matter.

So it would be great if the driver could instead read the drive in smaller chunks.

**Comment by idrassi** [comment]
Thank you for reporting this.
I have modified the implementation of `IOCTL_DISK_VERIFY` in order to read the drive using chunks of 64 KiB as you can see in the commit https://github.com/veracrypt/VeraCrypt/commit/5eaa204d83a1d9867094c14b4a35f310f27f6c65.
