### ISSUE TITLE
Lack of a "Gui" switch

### ISSUE THREAD

**Issue by AZMCode** [veracrypt/VeraCrypt#564]
Hello. I have been trying to launch the GUI interface of veracrypt from the command line, and found that in all cases I launched veracrypt with pkexec it always returned the command line help instead of launching the GUI.

Wouldn't it be a good idea to include a command line switch to force veracrypt to launch the GUI?

**Comment by alt3r-3go** [comment]
@AZMCode, in general VC starts in GUI mode by default and the fact that it returned help may suggest that there's simply some problem with running it via `pkexec`. Could you please provide a full command line that you run there, or a full script, which uses `pkexec` to start VC, if that's the case?

**Comment by AZMCode** [comment]
Nevermind, I found the problem on my side. Pkexec doesn't set the DISPLAY variable by default, so it makes sense veracrypt would not run the GUI.

**Comment by alt3r-3go** [comment]
Yep, that was my suspicion (aside from other basic stuff) - thanks for reporting back!
