### ISSUE TITLE
Can't create hidden volume

### ISSUE THREAD

**Issue by mahescho** [veracrypt/VeraCrypt#572]
I'm on Linux with the latest VeraCrypt. I've used a 1TB USB HDD and tried to create a hidden volume. First the outer volume got created and then VeraCrypt asks me for the size of the hidden volume. I tells me that I can use 931 GiB. When I enter 600 GiB "Next" is grayed out. "Next" is greyed out for every value bigger than 7 GiB.

What am I doing wrong, or is this a bug?

**Comment by alt3r-3go** [comment]
@mahescho, which distro is that, just to make sure? Is that a partition- or file-based hidden volume?

**Comment by mahescho** [comment]
I use KDE Neon aka Kubuntu 18.04. I've tried to use the raw device /dev/sdc and a partition /dev/sdc1. I would prefer to use /dev/sdc directly. Tried the same thing with an old TrueCrypt setup on an old Debian Wheezey without any problems.

**Comment by fancy1-max** [comment]
I have this problem too, on Arch Linux (veracrypt 1.24.update3-1), I can't create a hidden volume that's greater than 6 GiB, the Next button is greyed out if I enter 7 GiB (or if I enter 6700 MiB ... despite the maximum possible size being reported as 100 GiB).

**Comment by idrassi** [comment]
This is indeed a regression introduced in version 1.24 but there is a workaround to fix it: specify the switch `—no-size-check` when launching VeraCrypt in command line and the issue will not occur.

I have fixed this issue in git (https://github.com/veracrypt/VeraCrypt/commit/b0b149db836063cc017b2530c305a7d5da92f58d) and I will publish 1.24-Update4  that will include it.
