### ISSUE TITLE
VeraCrypt Expander supports only integer values

### ISSUE THREAD

**Issue by Atalanttore** [veracrypt/VeraCrypt#573]
The VeraCrypt Expander (v1.24) supports only integer value as size.

In addition, an entered value [in KB, MB, GB, or TB] for the size is not automatically converted when the unit is changed.

**Comment by alt3r-3go** [comment]
To be honest, I think both are actually desirable behaviors, as they prevent misunderstanding. E.g. there's no unambiguous and meaningful way to calculate the precise (and meaningful for a disk) value of 1.3359 MB. And as for the second one, imagine you typed in "10" meaning GB and then noticed you have "MB" selected. If you change that and the value changes to 0.009765625, does it really help?

But maybe I'm missing something. How would you want VC to behave in those scenarios?
