### ISSUE TITLE
After Windows 10 update (2020.01.15) bootloader is broken

### ISSUE THREAD

**Issue by bootsmann** [veracrypt/VeraCrypt#578]
It seems that Windows 10 update from yesterday (2020.01.16) broke the boot loader.

Is above mentioned problem related to following?
https://www.reddit.com/r/VeraCrypt/comments/epkicg/problems_with_boot_loader_after_windows_10_update/
https://www.reddit.com/r/VeraCrypt/comments/ejk39a/windows_10_no_longer_booting_after_updating/feaxw71/

**Comment by andreas-becker** [comment]
Hello @bootsmann does the problem still happen with 1.24-Update6 ?
