### ISSUE TITLE
[Feature-Request] Implement RAM encryption for keys and passwords for Linux & MacOS

### ISSUE THREAD

**Issue by Schweineschwarte** [veracrypt/VeraCrypt#579]
Hello,
Since version 1.24, Veracrypt can encrypt the keys and passwords in the RAM on Windows. I think this nice feature is helpful on other platforms, too. Is it possible to implement this nice feature for Linux, MacOS etc? Thank you very much!

**Comment by markboston3502191** [comment]
i agree
