### ISSUE TITLE
Sharing Encrypted Drives On Local Network

### ISSUE THREAD

**Issue by Crayder** [veracrypt/VeraCrypt#58]
I'm not sure if it's possible, but I know I don't see anything relative to this.

I have created an encrypted partition on my desktop computer. It is password encrypted, no key files.
I have VeraCrypt installed on both of my computers (i.e. desktop and laptop).
I want to be able to access this partition from my laptop when it is mounted on the desktop.

Is this possible? Or will I have to make a virtual file container.

**Comment by MrSmite** [comment]
From the way you posted, this seems more like a question than a bug. At any rate, if you're using Windows then use VeraCrypt to mount the partition to an empty drive letter and then use the built-in sharing mechanism in Windows Explorer to assign permissions, etc.

**Comment by Crayder** [comment]
I already know I can do it by mounting it on the desktop and sharing it that way. I was thinking there would be a way to mount it on the laptop. (Also, thanks for all of that low-level user information but I am certified... xD)


> From the way you posted, this seems more like a question than a bug.

This is GitHub bro, the Issues section isn't literally just for issues. Hell, the default issue tags are as follows: 
![image](https://cloud.githubusercontent.com/assets/9919010/14757703/6f8951c4-08c4-11e6-8767-7c82e4ab4c7e.png)

**Comment by MrSmite** [comment]
> I was thinking there would be a way to mount it on the laptop.

What's the point in that? It's effectively the same as mounting it on the host and sharing it. Just remote into the desktop using RDC (or some other) and mount it then share it. In fact mounting it across a wifi would be asking for corruption if your connection was interrupted.

> Also, thanks for all of that low-level user information but I am certified... xD

No problem, I can't guess your certifications and you didn't volunteer them.

**Comment by azev** [comment]
I had this very same issue just now. I fixed it by mounting as a **FIXED DRIVE** instead of removable drive.
