### ISSUE TITLE
glibc 2.28

### ISSUE THREAD

**Issue by Jairjua** [veracrypt/VeraCrypt#582]
After installation I can't run the app

![image](https://user-images.githubusercontent.com/9156799/73371361-5791fe00-4294-11ea-85e1-d36897d8ba72.png)
 
Using Linux Mint 19.2
My system is up to date, but it's using Ubuntu GLIBC 2.27-3ubuntu1.
What can I do?

**Comment by alt3r-3go** [comment]
@Jairjua, how did you install VeraCrypt?

**Comment by andreas-becker** [comment]
@Jairjua Did you try reinstalling VeraCrypt using its Ubuntu 18.04 .deb package
since Mint 19.2 is based on Ubuntu 18.04? This might fix the issue.
