### ISSUE TITLE
Issues with parallelized volume creation

### ISSUE THREAD

**Issue by danielbene** [veracrypt/VeraCrypt#583]
Hello guys, I found a strange behavior when creating volumes on multiple threads via CLI on Linux (tried it in Debian, and Ubuntu based systems too). After each of the creation processes finishes I always get error messages, but the created volumes looks fine (i can mount them, and they has the same size).

This is the error:
```bash
Done: 100.000%  Speed: 2.0 MiB/s  Left: 0 s         

Done: 100.000%  Speed: 1.9 MiB/s  Left: 0 s         

Done: 100.000%  Speed: 1.9 MiB/s  Left: 0 s         

Error: device-mapper: create ioctl on veracrypt1  failed: Device or resource busy
Command failed.
Error: device-mapper: create ioctl on veracrypt1  failed: Device or resource busy
Command failed.
The VeraCrypt volume has been successfully created. 
```

Example code (vera1.sh & batch.sh):
```bash
veracrypt -t -c --non-interactive --volume-type normal --filesystem ExFAT --password 123456 --quick --size 10M --encryption AES --hash SHA-512 ./volume1.hc
```
```bash
./vera1.sh &
./vera2.sh &
./vera3.sh &
```

It looks like n-1 errors generated after the batch. My best bet is that some background validation task mounting the first one, and when the others finishes the mountpoint, or the process is still in use.

Does anyone happens to run into this problem before, and can give me a heads-up, that what is it?

**Comment by andreas-becker** [comment]
Hey @danielbene ,
maybe 'strace batch.sh' or 'strace veracrypt -t -c ...' will give you more information.

In my opinion, the n-1 errors indicate the problem you mentioned - the device-mapper does not allow two or more devices with the same UUID and therefore the error ihappens.

Best regards,
Andreas
