### ISSUE TITLE
Error  _NT_TARGET_VERSION SET TO WINXP or _NT_TARGET_VERSION SET TO WS03

### ISSUE THREAD

**Issue by Gitraj503** [veracrypt/VeraCrypt#588]
I got the following error 
#############################################
_NT_TARGET_VERSION SET TO WINXP
1>errors in directory c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto
1>c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto\link : error LNK1181: cannot open input file 'c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto\obj_driver_debug\i386\sha512_avx1_x86.obj'
BUILD: Linking for c:\users\qtcsdemo\desktop\veracrypt_1.23_source\src\crypto directory

_NT_TARGET_VERSION SET TO WS03
The problem is on  windows 10 , 64 bit machine 
visual studio 2010 with SP1 and nasm added to path and vsyasm (64_bit) added to VC\bin as described in readMe of vsyasmwin64. 
added upx and gzip to added to path . I am able to build all other 8 projects successfully except driver project. Kindly help me out on what went wrong with me.  Thanks in advance

**Comment by andreas-becker** [comment]
Hello @Gitraj503 ,
thank you for reporting this issue.

Is there a specific reason why you tried to compile an outdated version?
Does the error happen with the latest version 1.24-Update5 as well?

Kind regards,
Andreas

**Comment by Gitraj503** [comment]
Thank you @andreas-becker  for reply .
I tried with latest version of veracrypt,  all 8 projects build successfully except Driver project. I am also enclosing the build log for reference 
[Full_Log.txt](https://github.com/veracrypt/VeraCrypt/files/4265584/Full_Log.txt)
Thanks in advance

**Comment by Gitraj503** [comment]
@andreas-becker 
Any update please ?

Kind Regards

**Comment by andreas-becker** [comment]
Hello @Gitraj503, 
so no update at present. I'm not into windows and as far as i know, Mounir is on vacation.

**Comment by idrassi** [comment]
@Gitraj503 Did you add yasm.exe to PATH? It looks like it could not be found during build process and so the file sha512_avx1_x86.asm could not be assembled.

**Comment by Gitraj503** [comment]
Thank you @idrassi  for reply , Yes , I added yasm.exe (win64 version) to PATH , the issue is with  aes_x86.asm and aes_x64.asm (both uses nasm) (Kindly see attached built log
[Full_Log.txt](https://github.com/veracrypt/VeraCrypt/files/4325596/Full_Log.txt) I am able to compile all other 8 projects successfully except driver project. Kindly let me know the mistake what I am doing 
)

**Comment by Gitraj503** [comment]
@idrassi , @andreas-becker  I found the mistake , issue was with PATH only . Thank you for your support  

Kind regards
