### ISSUE TITLE
[Feature-Request] add support for "doas"

### ISSUE THREAD

**Issue by CarDGee** [veracrypt/VeraCrypt#589]
Hi would you consider to add support for "doas"
doas is meant to be a lightweight replacement for sudo that it just works
https://man.openbsd.org/doas
I have been using it on linux and managed to completly replace sudo with it, except for veracrypt. I have tried "doas veracrypt" but then the mounted volume is only visible as root.
Thank you for your time.

**Comment by andreas-becker** [comment]
Hello @CarDGee, are you into development? If so, it would be great if you checkout the project and provide a pull request. 

Kind regards,
Andreas

**Comment by withs** [comment]
> Hi would you consider to add support for "doas" doas is meant to be a lightweight replacement for sudo that it just works https://man.openbsd.org/doas I have been using it on linux and managed to completly replace sudo with it, except for veracrypt. I have tried "doas veracrypt" but then the mounted volume is only visible as root. Thank you for your time.

A workaround is to set SET_UID with the uid you want the volume to be owned by and use the cli version of verracrypt.

in a root session or via doas:
`SUDO_UID=<your_user_uid/guid> veracrypt --text --mount <your_volume_path>`

note: here `--text` indicate that veracrypt will be used as a cli app.
keyfiles, pim etc will be interactively asked or you can supply them in the command  see `veracrypt --text --help`
