### ISSUE TITLE
Update libzip

### ISSUE THREAD

**Issue by TheSorrow1** [veracrypt/VeraCrypt#591]
New version of libzip is out 1.6.1, would be nice to update it.

**Comment by andreas-becker** [comment]
Hey @TheSorrow1, what about checking out the repo, integrate the new libzip and providing a pull request ;-) Man, it is open source so everyone can support.

Best regards,
Andreas

**Comment by idrassi** [comment]
I have updated libzip to 1.6.1 in the commit https://github.com/veracrypt/VeraCrypt/commit/da370af54b419132d5f1e990f79b06ad8ebe66c0
