### ISSUE TITLE
US keyboard

### ISSUE THREAD

**Issue by TheSorrow1** [veracrypt/VeraCrypt#592]
Hello, I noticed in the setup wizard it automaticlly selects US keyboard which in a way is understandable since the boot only accept US characters for the password. However I notice its more ddifficult to write a good strong password when your main keyboard isnot a US one since all the characters is in diffrent areas on a non US keyboard than a US keyboard... I think we should add a option to choose what keyboard to use. Thanks.

**Comment by andreas-becker** [comment]
Hello @TheSorrow1 thank you for your feedback.

I really think this is a good point, but currently we have a huge lack of developers so it might take a while to get this issue done.

Best regards,
Andreas

**Comment by alt3r-3go** [comment]
@TheSorrow1, given that the pre-boot environment doesn't support non-en_US keyboard layout, as you properly identified, how would you correctly type your password there, even if the wizard allowed to use something else at the creation point?
