### ISSUE TITLE
"Required version of the veracrypt bootloader is currently not installed" Problem

### ISSUE THREAD

**Issue by DecipherIt** [veracrypt/VeraCrypt#593]
I've been having issues with veracrypt since 1.24 update 2.
After upgrading it destroyed my bootloader, after restoring it with a new rescue disk everything seems to work alright but the computer randomly locks up after a few days of activity. There is no trace to be found of it in Event logger or anything else but the only thing that works is a hard reset. This started happening after the upgrade to 1.24 u2 to latest..

The biggest issue I have right now is that I can't access any veracrypt menu without getting errors so I want to try and fix that first.
Going to System > Settings I get " The required version of the VeraCrypt Boot Loader is currently not installed. This may prevent some of the settings from being saved". I have no idea how to solve that.
Once I'm in the settings and click on "edit bootl oader configuration" I get an error saying "The system cannot find the file specified. Source: VeraCrypt::Elevator::GetFileSize:442".

Another clear indication something is wrong is that 1 out of 3 times I have to go into my UEFI bios and set Drive Boot Loader Priority to Windows Boot Loader as 1 and ?????????????????? as 2.
If I don't it boots up saying my drive can't be mounted.

I tried creating a new Recovery disk and restoring the boot loader from USB boot but that doesn't fix the problem.

I can boot into my device, it just does not work like it should and it started from 1.24 u2

I have no idea how to fix either issues, I really need some help.

This is both a bug report and feature request, there has to be a way to fix this from the GUI through automation.

**Comment by andreas-becker** [comment]
Hello @DecipherIt , i'm sorry for getting back to you so late but i cannot help you with your problem. We are talking about Windows right? Could you provide more information about your system?

Kind regards,
Andreas
