### ISSUE TITLE
Feature Request/Help Request Clone Drive Guide

### ISSUE THREAD

**Issue by DecipherIt** [veracrypt/VeraCrypt#594]
I know there used to be guides on codeplex that gave step by step instructions of how to clone your encrypted drive (either with dd or not) through Clonezilla but they aren't easily found anymore.

I currently have a failing (almost dead) 1TB Seagate Barracuda (1 partition, fully encrypted) drive that I want to Clone to my new 3TB Seagate Barracuda (brand new) drive (both internal) and after mounting the 3TB expanding the encrypting. but I can't find any way to do it right and there are no guides I can find..

It would be nice to see a good clone guide in the Veracrypt manual.
For now any help would be appreciated.

**Comment by andreas-becker** [comment]
Hello @DecipherIt,
i don't think this is a VeraCrypt related problem. Searching for "dd linux partition" might give you a lot of tutorials on how to clone a partition to a new harddisk.

Kind regards
Andreas

**Comment by alt3r-3go** [comment]
There's also this thread on StackExchange describing all the major steps: https://unix.stackexchange.com/questions/511513/clonezilla-wont-mount-encrypted-with-veracrypt-partition
