### ISSUE TITLE
Change program language for Linux

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [veracrypt/VeraCrypt#595]
Hi!

I wanted to know why the Linux version does not have the ability to change the language?

**Comment by andreas-becker** [comment]
Hello @Khomyak-sibiryak,
thank you for your submission. 
Did you compile the version by yourself or did you use the provided packages?

**Comment by Khomyak-sibiryak** [comment]
I use the finished version from the repositories.

**Comment by Khomyak-sibiryak** [comment]
I created a .mo file for my language from a .xml file, as described [here](https://github.com/veracrypt/VeraCrypt/issues/430#issue-416463635). Then saved it as /usr/share/locale/ru/LC_MESSAGES/veracrypt.mo and launched veracrypt. But I did not see the result. I also tried to explicitly specify the desired language at startup, `LANG=ru_RU veracrypt`, but that didn't work either.
