### ISSUE TITLE
Erase data(failed attempts)

### ISSUE THREAD

**Issue by TheSorrow1** [veracrypt/VeraCrypt#597]
Hi, would it be possible to implement a functionality or have it as a option so that veracrypt erases the data in case too many failed attempts are made or erase the encryption keys?

**Comment by andreas-becker** [comment]
Hello @TheSorrow1, thank you for your submission. 
I think it would be possible to implement, but due to the lack of people contributing to the project, i don't think that this feature will be implemented in the near future.

Kind regards,
Andreas

**Comment by alt3r-3go** [comment]
@TheSorrow1, what kind of problem would you want to fix with this feature?
