### ISSUE TITLE
Password input screen not showing on HP Elitebook 8570w

### ISSUE THREAD

**Issue by minozheros** [veracrypt/VeraCrypt#599]
Okay I was able to pass the pretest and also encryption is working. But in order to get to the veracrypt password dialog I need to press ESC -> Boot Device Options -> Boot from EFI File -> Navigate down until Veracrypt DcsBoot.efi. Select and press enter. That works. If i select the Veracrypt BootLoader in the main menu its not booting and im stuck at the HP Logo again. Have also disabled every boot device except custom boot and so on.

Ideas, please? 

Kind Regards

_Originally posted by @LegendaryB in https://github.com/veracrypt/VeraCrypt/issues/269#issuecomment-385102193_

I have the same issue ... For now i consider it an extra level of security, but it would be nice if it would load the password input without the workaround

![77382715-56a3b700-6d81-11ea-9002-68b6f9f3ae2d](https://user-images.githubusercontent.com/7850621/77428331-33582680-6dd8-11ea-8502-e94fa0eec7bf.PNG)

![77382742-6b804a80-6d81-11ea-955f-90f52466b4d3](https://user-images.githubusercontent.com/7850621/77428349-39e69e00-6dd8-11ea-9cdd-b0a14440b3c1.PNG)

I thought it might be some graphics error.. because if you enter the menu some graphics drivers might be loaded that are missing if you simply load the efi file.. it is a wild guess though

**Comment by andreas-becker** [comment]
Hello @minozheros , thank you for your issue.

Unfortunately we have too few developers for the many tasks, so it will certainly take some time before your problem can be solved.

I hope you appreciate that.

Kind regards,
Andreas

**Comment by alt3r-3go** [comment]
@minozheros, there's no need to copy the whole comments between issues, it is enough to reference them, otherwise it become hard to read.

As you can see, in [this comment](https://github.com/veracrypt/VeraCrypt/issues/269#issuecomment-602981824) it was mentioned that switching to native UEFI boot fixed the problem, could you please try that?
