### ISSUE TITLE
Normalize line terminators of source files

### ISSUE THREAD

**Issue by davidfoerster** [veracrypt/VeraCrypt#60]
The consistency of line terminators in the code base of VeraCrypt is in a pretty bad shape. Some files have LF, some have CRLF and some even have *both*. I understand that some files should *always* keep a certain line terminator style (`*.sln *.bat *.rc`).

Are there any plans to solve this issue? The common solution is to convert all line terminators to LF unless required otherwise and commit the changes. At the same time we can add a `.gitattributes` to tell Git to convert LF to the native line terminator style on some file types and keep them on others. This would apply to every cloned repository immediately upon checkout. Alternatively/additionally Windows users should set `core.autocrlf=true` and everyone else `core.autocrlf=input`.

Unfortunately touching so many lines of code means that previously created, unmerged patches are more difficult to merge. Fortunately it can still be done automatically with `git format-patch | git am` and the right option switches.

I'm willing do perform the changes in a pull request but there needs to be some policy decision.

**Comment by idrassi** [comment]
I agree that this should be addressed. Using LF for all file is the way to go even on Windows since it is supported by Visual Studio with no issues. In this context, I think that .gitattributes is not needed.

Since your pull request, I have changed two files from UTF-16 to UTF-8 without BOM encoding (src\Format\Tcformat.c and src\ExpandVolume\ExpandVolume.c).

A good policy would be that all files should use LF and UTF-8 without BOM.

Unfortunately your pull request can not be merge righ now because of conflicts. I really appreciate the hard work that you did and I'm sorry that my latest changes broke the merge. I will try to solve this as soon as possible.

**Comment by davidfoerster** [comment]
Cool, I didn't know about that fact with line terminators in Visual Studio since I havent's used it in such a long time.

It's no big deal about my "lost" work. Now that I know the recipe (i. e. which commands to run), I can just apply it again on the new HEAD of master.

**Comment by idrassi** [comment]
OK, thank you in advance.
Once done, I'll merge your modifications.

**Comment by davidfoerster** [comment]
Oops, I edited my previous comment heavily while you responded. This comment serves to make you aware of the changes.

**Comment by idrassi** [comment]
OK. I will freeze commits on master until you do the modifications. If you could tomorrow, this would be great.

As for LF support in Visual Studio 2008, it is well supported. I have been working with it for many years and the files keep the LF line ending after saving. The link you posted concerns old versions of Visual Studio and at the bottom of the page it cites Visual C++ 5, 6, 2002 and 2003...no mention of 2008 which is normal which is has no LF issues.

Concerning .gitattibutes file, it can indicate that all files should commited with LF ending.

Thank you.

**Comment by davidfoerster** [comment]
Alright, will do!

**Comment by davidfoerster** [comment]
Sorry, something came up tonight but I'll have time in the morning.

**Comment by davidfoerster** [comment]
I updated the pull request #61 according to this discussion.

BOMs cannot be trivially enforced with Git but it's possible with a custom verification script. FWIW many *nix applications don't deal well with BOMs. Encoding is usually defined as part of the file format (XML), in a mode line at the head of the file, auto-detected, or assumed to conform to the current locale encoding setting (UTF-8 on most modern desktop distributions).

**Comment by idrassi** [comment]
Thanks for the hard work!
Pull request merged.
There is just a small issue in the Polish Language.pl.xml because the space removed at the end of line 1205 resulted in "zpłyty" instead of "z płyty". But I will fix this easily.

**Comment by davidfoerster** [comment]
You're referring to [this](/davidfoerster/VeraCrypt/blob/5f47d8b6f11cdb3c4c2f43e04e5acfc6ffcb3035/Translations/Language.pl.xml#L1205), right? That's odd since whitespace in XML is supposed to be normalized by the parser (unless specified otherwise in the DTD/schema); so trailing whitespace should have no effect on the result at all.

**Comment by idrassi** [comment]
VeraCrypt uses a hand made XML parser inherited from TrueCrypt and which doesn't respect XML standard in all cases. This case is an example for such non compliance.
Anyway, I did a modification to put the text on a single line like other language files and I did some small fixes for other language files.

**Comment by davidfoerster** [comment]
> hand made XML parser

 m(
