### ISSUE TITLE
Linux: can we use crypto subsystem for hardware acceleration in embedded device and how

### ISSUE THREAD

**Issue by BabaYB** [veracrypt/VeraCrypt#600]
For embedded linux device, does Veracrypt supports to use linux kernel crypto subsytem which can use hardware such as arm crypto engine to accelerate.

For example:
Platform with core (Armv8-A)
Algorithem (AES-XTS)

**Comment by andreas-becker** [comment]
Hello @BabaYB , thank you for your issue.

If you have further knowledge in this subject it would be great if you could provide a pull request.

Unfortunately we have too few developers for the many tasks, so it will certainly take some time before your problem can be solved.

I hope you appreciate that.

Kind regards,
Andreas

**Comment by alt3r-3go** [comment]
@BabaYB, the short answer is no, VC doesn't use that. The crypto part in VC is shared between all supported platforms and it would require a noticeable refactoring to start using platform-specific implementations/services available at each platform.

**Comment by BabaYB** [comment]
Hi @andreas-becker @alt3r-3go ,

Thanks for your help! As we know, VC has a good design to split the algo and mode, but linux crypto subsys did the same job, so when we use it need pass algo-mode like "xts(aes)". So maybe
this is not a good think to use it.

I have tried to use libkcapi, a user space api for linux crypto, to call crypto engine in a boadr with Armv8-A cpu to do aes-xts, and it works. So I used the lib api to replace the Encrypt and Decrypt code:
```
EncryptionModeXTS:EncrytptBufferXTS():
```
<img width="552" alt="kcapi" src="https://user-images.githubusercontent.com/16234146/78858373-d490df00-7a5e-11ea-8f60-03159fdee62b.png">
But I don't think it is a good implement for VC

Thanks,
BabaYB

**Comment by alt3r-3go** [comment]
Actually, I stand corrected. I was investigating something else and noticed that Linux version actually *does* use kernel crypto, in certain cases, you can see specific conditions here: https://github.com/veracrypt/VeraCrypt/blob/master/src/Core/Unix/Linux/CoreLinux.cpp#L305-L320
