### ISSUE TITLE
Can't unlock system encryption - incorrect password

### ISSUE THREAD

**Issue by MPeti1** [veracrypt/VeraCrypt#603]
I've set up system encryption earlier, and I was able to unlock my laptop multiple times for months.
Today, for the first time I was able to unlock the system, but I needed to reboot, and now I'm unable to unlock it again.

First I noticed that "verifying password" takes much longer than usually (and also than it took for the first time today, just a few minutes earlier), and I thought I must have mistyped my password and it will hang forever due to a bug, so I rebooted with ctrl+alt+del. I didn't think this is a bad idea because no data should be written to the disk at this phase.
After the hard reboot, I again tried to unlock the system, but it wrote "incorrect password" after a long time for all 3 tries despite me reading the password from a password manager on my PC.
Then I pressed F5 and started typing, and noticed that the boot loader has switched to QWERTY keyboard layout from QWERTZ, so me being a professional QWERTZ-on-QWERTY writer I started typing my password so that I pressed the other buttons to have the same character input as I should.
And neither this method, nor writing it as I did earlier unlocks the system. For both input I get the error message "incorrect password"

My password includes only English letters and `-`-s, and the PIM hasn't been changed from the default, so pressing enter at it should work
I can't use the rescue disk, because I wasn't able to write one. I have many CD's, also CD-ROM's in both my PC and the laptop, but I have no WRITABLE CD's. Thankfully, VeraCrypt didn't allow me to write it on a pendrive that I wouldn't use for other things.. but that shouldn't be a problem, because I don't see why anything would have damaged

**Comment by MPeti1** [comment]
I've booted to the BIOS now, changed the language from English to English (so actually didn't change anything), typed again the password so that it isn't displayed as the same as in my password manager, but I typed the characters that are displayed in it, and now it successfully booted.
I don't think the BIOS setting changed anything, but I have no idea what happened there too.

**Comment by andreas-becker** [comment]
Hello @MPeti1 glad to hear that you have access to your files again.
Sorry but due to the current situation and the lack of VeraCrypt developers, your problem might not get the full attention.

Kind regards,
Andreas

**Comment by MPeti1** [comment]
ok, no problem, it's still possible to log in after a few tries when this occures, and in my case these files are not even important. it's a rarely used system with no documents, just wanted to let you know that there may be problems.

when you'll have the capacity I'll be here to help if you have further questions

**Comment by MPeti1** [comment]
Well, it hasn't occurred since that, so I will just close this now
