### ISSUE TITLE
Notepad "find" not working on Veracrypt volume

### ISSUE THREAD

**Issue by jpaulm** [veracrypt/VeraCrypt#605]
Veracrypt has been working for me perfectly since I installed it, so I usually do a "find" in my files after mounting them (to find saved info such as passwords), and a month or so ago I noticed that "find" was not finding the data I wanted.  As far as I can tell, clicking on the file after doing mount is bringing up Notepad by default, but "find" no longer works!  Notepad works fine elsewhere, and other editors work, such as Jujuedit, in this situation...  So this is a workaround, but it's still a bit frustrating!   Any suggestions would be appreciated!  TIA

**Comment by alt3r-3go** [comment]
That's an interesting one. Do you mean it's the Windows Explorer's "find" feature that stopped working for you or the Notepad's own "find" [within the document text]?

**Comment by jpaulm** [comment]
Good question!  It's Notepad's own "find" within a document.  Could Veracrypt somehow be pulling in a different version of Notepad...?!  "Find" works fine in my Notepad running _outside_ Veracrypt...
