### ISSUE TITLE
CLI option /FastCreateFile on linux?

### ISSUE THREAD

**Issue by arnegroskurth** [veracrypt/VeraCrypt#607]
Seems like the `/FastCreateFile` option as documented [here](https://www.veracrypt.fr/en/Command%20Line%20Usage.html) is not available on linux or am I missing something!?

(I tried `--fast-create-file`, `--fastCreateFile` and `--FastCreateFile`)

**Comment by alt3r-3go** [comment]
There's a note at the very beginning of that page:

> Note that this section applies to the Windows version of VeraCrypt. For information on command line usage applying to the Linux and Mac OS X versions, please run: veracrypt –h

and indeed there's no such option for Linux.

**Comment by arnegroskurth** [comment]
Then I would leave this here as a feature request.
