### ISSUE TITLE
Veracrypt 1.24... overwrites my signed DcsBoot.efi and DcsInt.dcs files and breaks secure boot

### ISSUE THREAD

**Issue by jam3st** [veracrypt/VeraCrypt#609]
I remove the windows signature and add my own signature to the DcsBoot.efi and DcsInt.dcs files. When I boot up this is fine but when I reboot I get an security violation.

Is there a please do not update the boot loader config but I will update this myself when I update the code option anywhere?

**Comment by alt3r-3go** [comment]
I'm not intimately familiar with this part of the code, but FWIW the overwrite logic seems to be located in https://github.com/veracrypt/VeraCrypt/blob/master/src/Common/BootEncryption.cpp, you could check there.

**Comment by jam3st** [comment]
Seems to have been fixed by the reg entry that says, "Please don't update my UEFI, I've got it veracrypt"
