### ISSUE TITLE
Can't locate Windows/System.h in VeraCrypt source code

### ISSUE THREAD

**Issue by saranyag-11** [veracrypt/VeraCrypt#613]
The System.h file in  /src/Platform/  folder contains include statement as follows:-
#ifdef TC_WINDOWS
#include "Windows/System.h"
#endif

I am working on Windows with visual studio. May I know where is this file located?
Couldn't find it in VeraCrypt source code.

**Comment by alt3r-3go** [comment]
Have you installed all the required SDKs? I think that's where it is.

**Comment by saranyag-11** [comment]
Installed both SDK 7.1 and 8.1 and searched the entire system for system.h file but couldn't find it.

> Have you installed all the required SDKs? I think that's where it is.
