### ISSUE TITLE
One way hash function accepting multiple inputs?!

### ISSUE THREAD

**Issue by hydrogenpi** [veracrypt/VeraCrypt#614]
Anyone know any projects on VeraCrypt libraries or other github repos that can do this? 

I'm trying to create a simple "activation" and/or "authentication" system in C++, basically 

The first application just has one button called "ACTIVATION" and when user clicks on it, it opens the activation-process dialog-box. The only purpose of this first application is to test the activation progress, and to see if the activation is successful it will report back as Okay, if the activation fails or any reason, it will report back that it failed. This activation dialog-box process will provide to the end-user a randomly generated (at dynamic run-time when the user clicks the Activation button) 25-digit alphanumeric CHALLENGE CODE and then will ask the user to provide the correct corresponding 25-digit AUTHENTICATION CODE. 

The second application is also C++, and it is a separate standalone application written for Windows which is the "keygen" or the "key generator"... It takes as input the above aforementioned CHALLENGE CODE, and also it take as input the current clock/system date/time of the system or server the keygen resides on, and it also takes as input a static CONST float/int initial "SEED" number or value that was hardcoded into the keygen application during compile-time, and it combines ALL three of these separate inputs and then runs them inside a secure ONE-WAY function/hash algorithm and then spits out the final OUTPUT which is the AUTHENTICATION CODE. 

The end-user finally takes the AUTHENTICATION CODE that it received from the keygen and inputs it back into the AUTHENTICATION CODE field of the activation-process dialog-box and hits enter or submit. The activation-process does a check and calculates if it is the correct authentication code or not. 

In order for the check to pass it MUST satisfy all of the following conditions: 
1) The current clock/system date/time must be within five minutes plus or minute from the time at which the keygen generated the AUTHENTICATION CODE. 
2) The initial seed value that was hardcoded into the keygen application during compile-time must also precisely match the initial seed value that was hardcoded into the application/activation process during compile time. 
3) Obviously the initial CHALLENGE CODE must be valid and the one-way function used in the keygen must be the same as the one-way function inside of the activation process in order for the

**Comment by hydrogenpi** [comment]
![2020-04-22 09_39_58-WindowsFormsApp1 - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/35181396/80028954-9efee380-84ab-11ea-9e62-9445d53d263c.png)
![Uploading 2020-04-22 09_37_37-Window
![2020-04-22 09_47_14-WindowsFormsApp1 - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/35181396/80028956-9f977a00-84ab-11ea-88b3-f721f54e1b39.png)
sFormsApp1 - Microsoft Visual Studio (Administrator).png…]()

**Comment by hydrogenpi** [comment]
http://www.zedwood.com/article/cpp-sha512-function

**Comment by alt3r-3go** [comment]
@hydrogenpi, this is not appropriate for this issue tracker. It's intended for reporting issues and feature requests for VeraCrypt and your posts are nowhere near that and therefore are borderline spam.
