### ISSUE TITLE
SignTool Error: No certificates were found that met all the given criteria.

### ISSUE THREAD

**Issue by pugongying** [veracrypt/VeraCrypt#616]
Windows 7 64bit
I have builded veracrypt source code successfully。
When signing and packaging veracrypt,after running sign.bat the cmd returned "SignTool Error: No certificates were found that met all the given criteria."
![image](https://user-images.githubusercontent.com/3131010/80081382-75b28600-8585-11ea-86b9-9d6d8b6e7cce.png)

**Comment by andreas-becker** [comment]
Did you create the certificates by yourself?

**Comment by pugongying** [comment]
> Did you create the certificates by yourself?
First of all，thank you for your reply。
Not my own certification,i used the file all in the folder "Signing" .It is the case for IDRIX's certificate。
After downloading the source code,I followed the Readme.md completely.

**Comment by andreas-becker** [comment]
So sorry for asking, but if you wanted to use the one from IDRIX, why didn't you just download the [official Windows build](https://www.veracrypt.fr/en/Downloads.html), verify the signature and install it?

**Comment by pugongying** [comment]
I am a programmer and want to learn it.

**Comment by pugongying** [comment]
I rebuild the environment,and this problem solved.
