### ISSUE TITLE
Security of the first set password

### ISSUE THREAD

**Issue by Ceiridge** [veracrypt/VeraCrypt#617]
Hello,
I have a question about how well the files are encrypted:

If you change your password in VeraCrypt, a current password is encrypted with the newly set one and the encrypted passwords is used to decrypt the files.
Now I'm wondering if VeraCrypt encrypts the files with a secure randomly generated password that is encrypted with the first set password or if it encrypts the files with the password that you set in the beginning.

Example:
I set the password to 123 at first (which is insecure). Are the files then encrypted with 123 or a password that can be retrieved by decrypting it with 123 (which is what happens when changing the password)?

**Comment by andreas-becker** [comment]
As quoted in the [documentation](https://www.veracrypt.fr/en/Program%20Menu.html):

> Only the header key and the secondary header key (XTS mode) are changed – the master key remains unchanged. This function re-encrypts the volume header using a header encryption key derived from a new password. Note that the volume header contains the master encryption key with which the volume is encrypted.

Understandable?

**Comment by Ceiridge** [comment]
What I've wanted to know is if the master encryption key is always randomly generated and stored & encrypted in the volume header or if the master encryption key is the first given encryption password.

**Comment by alt3r-3go** [comment]
The former: https://github.com/veracrypt/VeraCrypt/blob/master/src/Core/VolumeCreator.cpp#L300
