### ISSUE TITLE
[QUESTION]: Veracrypt and Windows Hello

### ISSUE THREAD

**Issue by MESWEB** [veracrypt/VeraCrypt#618]
Can we get function Windows Hello to login to Volume using Face recognise from Windows?

**Comment by andreas-becker** [comment]
At the moment i don't think that this feature might get implemented. But maybe you have the knowledge and can provide a pull request.

**Comment by archon810** [comment]
@andreas-becker Could you reopen this please?

**Comment by andreas-becker** [comment]
I'm unable to... @idrassi have to do.

**Comment by victorjagu** [comment]
I would love this feature too :)
