### ISSUE TITLE
Allow for encrypted PIM in MBR

### ISSUE THREAD

**Issue by Thomas12** [veracrypt/VeraCrypt#62]
In this commit you store the PIM in plaintext in the MBR.

https://github.com/veracrypt/VeraCrypt/commit/1396269d573256248bece97e1e291ef0c08e513f

Improvement suggestion: Store the PIM encrypted in MBR - but how?

Here's the idea:

1. User enters a password in PBA
2. Veracrypt bootloader calculates the hash of the password with a PIM of 1 (2048 iterations).
3. I don't know what datatype the PIM is, let's guess it is 32 bit - get the encrypted PIM from MBR
4. Now take the 32 least significant bits of the calculated hash and XOR it with the encrypted PIM from MBR.
5. Result is the PIM in plaintext, now use that PIM and try to calculate the final hash.

During setup, VeraCrypt has calculated the encrypted PIM by XORing the plaintext PIM with the 2048-iterated hash of the entered password and stored in the MBR.

Disadvantage: Wrong passwords can lead to huge PIMs -> waiting "forever".

Idea: Allow for "ESC-key" to abort iterative hash calculation and reenter password in case one thinks it is lasting longer than normal.

**Comment by Thomas12** [comment]
Important: After thinking a bit more, I see the risk that storing such data with a relatively low iteration count might bring valuable information to an attacker to reduce its efforts in cracking the password as he might get access to details that might reduce the search space for valid passwords, namely:

before really cracking the password, the attacker could test against the, let's say 20 most significant bits of the encrypted PIM which might leak details of the password-hash - making it much faster to find valid password-candidates to investigate further in a step later...

hummm... how to solve that? Encrypt the PIM on the one hand but don't reveal details of the password which allow for a reduction in password search space/speed... Even encrypting the PIM with AES would not help as an attacker could then first test for plausible AES answers which is faster (sub-second) than testing each password in a high-iteration-counted hash (takes seconds)...

**Comment by davidfoerster** [comment]
The [Personal Iterations Multiplier](https://veracrypt.codeplex.com/wikipage?title=Personal%20Iterations%20Multiplier%20%28PIM%29) is a cryptographic *parameter*, not a cryptographic *secret* (your pass phrase or key file is). It makes no sense to encrypt it.

**Comment by Thomas12** [comment]
Your linked document says:
---
Motivations behind using a custom PIM value can be:
    Add an extra secret parameter (PIM) that an attacker will have to guess 
---

Based on that, my motivation was:

Instead of providing an extra parameter by the user - which can be a bit inconvenient, the PIM could also be derived from the password combined with a random XOR-complement (to remain secret). But till now with the risk described above.

**Comment by davidfoerster** [comment]
If you derive the PIM or the key to decrypt the PIM from the passphrase you don't gain any security compared to storing the PIM plainly since everything still depends on the passphrase.

**Comment by idrassi** [comment]
This is a classical chicken-egg problem and a logical reasoning shows that there is no secure way to store the PIM. All possible ideas rely on reusing the password or introducing some "secret" random obfuscation.

Not knowing the PIM makes attacks harder but knowing it doesn't break security model provided that the password is secure enough.
Moreover, a warning is clearly displayed in VeraCrypt when the user chooses to store the PIM on disk.

Because of all these elements, no action will be taken to try to hide the PIM in the MBR and VeraCrypt will always recommend not storing the PIM value on disk.
