### ISSUE TITLE
[Question] Size of files and size on disk 

### ISSUE THREAD

**Issue by thibpoullain** [veracrypt/VeraCrypt#620]
Hi, 

I'm on windows with a drive of 1To. I used the hidden disk encryption method with exFAT, 2kb block and Kuzneyechik(Serpent(Camelia)) cascade encryption.

Problem : if I copy 50Go of data, it takes 90Go on the disk. My disk hasn't any bad block.

However, I choose the 2kb block with exFAT. What happen ? :)

I used an other disk with the same configuration, the size on disk is good...

Thx

**Comment by alt3r-3go** [comment]
Could you describe in more detail the specific set of steps you're making and the size measurements you conduct? I personally am not sure I understand the situation clearly enough to comment meaningfully.
