### ISSUE TITLE
cut

### ISSUE THREAD

**Issue by 5x3** [veracrypt/VeraCrypt#621]
cut

**Comment by alt3r-3go** [comment]
I'm not sure, but this may be a side effect of how ext4 stores the metadata across the outer volume's partition. Specifically, please take a look at the last several phrases of https://www.veracrypt.fr/en/Hidden%20Volume.html and the "_When trying to create a hidden volume, its maximum possible size is unexpectedly small (there is much more free space than this on the outer volume)_" question in the Troubleshooting section (https://www.veracrypt.fr/en/Troubleshooting.html).

I haven't checked but my guess is that ext4 stores something within the partition and that trips off the volume protection, like with NTFS case described there. That's probably why FAT is recommended as an outer volume fs type.

**Comment by 5x3** [comment]
FAT is not only recommended, but also used by default (without a chance to choice) in GUI.
Thus, plausible deniability collapses - If you are a Linux user and the outer volume formatted as FAT - 
this is extremely implausible, so any fool (not even an IT expert) will confidently assume the presence of a hidden volume.
It is all you need to know about security and plausible deniability in Veracrypt.

**Comment by RA-Kooi** [comment]
I'm assuming this is for a script, otherwise I'd recommend you to simply use the GUI. I'd say that you should dive in the source code and find the code that calculates the maximum size and rewrite it in bash. Then you can have the script generate the maximum hidden volume size and pass that to Veracrypt as an argument.
