### ISSUE TITLE
RAM encryption clarification

### ISSUE THREAD

**Issue by Skyfail** [veracrypt/VeraCrypt#626]
Hi,

I was interested in the RAM encryption feature for cached passwords and master keys and therefore digged into the source code.
However I did not fully understand how the feature protects against key extraction from memory via cold boot or DMA. What would prevent an attacker from resolving `pbKeyDerivationArea` (for example via signature scanning) and dumping its contents?

Thanks in advance

**Comment by andreas-becker** [comment]
I think @idrassi or @alt3r-3go might help you with this.

**Comment by alt3r-3go** [comment]
In general, my understanding of the idea for these two aspects is that VC monitors device plug-in events and deletes the key, making that attack harder + having the derivation area big enough makes it more probable that some of it will get corrupted during the cold boot attack. I've actually started exploring this in more detail myself a while ago, but then with all that covid-related churn that dropped to the end of the list...

**Comment by TheSorrow1** [comment]
@Skyfail 

here you go:
https://sourceforge.net/p/veracrypt/discussion/technical/thread/3961542951/?limit=25#663e

**Comment by Skyfail** [comment]
> @Skyfail
> 
> here you go:
> https://sourceforge.net/p/veracrypt/discussion/technical/thread/3961542951/?limit=25#663e

Thanks!
