### ISSUE TITLE
pre-boot auth keeps rejecting password

### ISSUE THREAD

**Issue by Dibblerman** [veracrypt/VeraCrypt#627]
Everytime i try to encrypt my ssd, during the test part, it keeps telling me authentication failed despite me putting in the correct password.

I have secure boot enabled and i have followed the steps to add the public key to the bios but the problem persists.

I have even tried using an all lowercase password in case it wasn't picking up the shift key, but same problem.

Anyone have any clue on how to fix this issue?

**Comment by andreas-becker** [comment]
Hello @Dibblerman, as i remember the problem did exist on another issue as well. The "problem" might be that on boot the keyboard language is english and not the selected/normal one.
For example, if your keyboard language normally is german and you have an "y" in your password, you need to type "z" to get the right key ;-)

I hope this information is helping you fixing the problem.

Kind regards,
Andreas

**Comment by Dibblerman** [comment]
@andreas-becker 
I tried setting my password to the letter "a", then i tried just in case, hitting every single letter on my keyboard one after another but not a single one got registered as the correct password. So i can only presume that isn't the issue unless my keyboard is registering a very odd key as a.

**Comment by alt3r-3go** [comment]
Just a set of ideas based on the Troubleshooting doc (https://www.veracrypt.fr/en/Troubleshooting.html):

Check out those questions:
1. "In the VeraCrypt Boot Loader screen, I'm trying to type my password and/or pressing other keys but the VeraCrypt boot loader is not responding."
1. "When trying to encrypt the system partition/drive, during the pretest, the VeraCrypt Boot Loader always reports that the pre-boot authentication password I entered is incorrect (even though I'm sure it is correct)."

Please check those out and feel free to report back if neither works.

**Comment by Dibblerman** [comment]
Sorry for the delayed reply, but neither solutions work. Legacy USB Support was already enabled, and as for the 2nd solution i only used a lowercase letter, but in case it was faulty i tried it with turning caps lock on and off and still no dice. It does mention Data corruption, however I can't see this being the case due to how many repitions i've done it on, unless there's another problem causing repeated corruption. Either way I still have no idea.
