### ISSUE TITLE
Veracrypt unusable on Windows 10 1903 boot partition encrypt

### ISSUE THREAD

**Issue by stuckinthe** [veracrypt/VeraCrypt#628]
I have installed Veracrypt on my Windows 10 PC and creating and mounting a container all works well. The problem is when I went to full boot Windows 10 partition. The system does a hard freeze and the only way to exit is by a hard reboot. I disabled pagefile.sys and write-cache and it stopped the hard freezes but it made it where programs like Chrome, Skype, etc would crash all the time making the computer unusable. I decrypted the drive and uninstalled Veracrypt and I haven't had a problem since. I'm not sure if I have a wrong setting or if there is an issue with VC. I can't imagine other people aren't seeing this issue.

**Comment by alt3r-3go** [comment]
Please check this one out: "When mounting or dismounting a VeraCrypt volume, the system crashes (a 'blue screen' error screen appears or the computer abruptly restarts)." at https://www.veracrypt.fr/en/Troubleshooting.html and try to see if there's any application/driver that causes some sort of conflict as it suggests. I also think it would be much more visible if that was a VC bug (in terms of issue reports).
