### ISSUE TITLE
Windows 10: Decrypting and mounting HarddiskVolume failed in cmd

### ISSUE THREAD

**Issue by Staubgeborener** [veracrypt/VeraCrypt#629]
I have already successfully decrypted and mounted devices via `cmd` in Windows 10 Pro 64-bit with Veracrypt like this:
```powershell
"%ProgramFiles%/VeraCrypt/veracrypt.exe" /q /v \Device\Harddisk0\Partition2 /l y /p p4ssw0rd
```

However, this device `HarddiskVolume6` does not work:
```powershell
"%ProgramFiles%/VeraCrypt/veracrypt.exe" /q /v \Device\HarddiskVolume6 /l x /p an0ther_p4ssw0rd
```
> Wrong password or no Veracrypt Volume

But thats not true, if I mount it manually in the GUI everything works well with this password. 

__As a note:__ The device is formatted as a logicial volume under Windows 10. So does Veracrypt display this as `\Device\HarddiskVolume6`? Is this possibly the reason? If yes why?

![picture](https://user-images.githubusercontent.com/28908603/82800450-08438f00-9e7c-11ea-8228-d73e28c7e3cb.PNG)

**Comment by alt3r-3go** [comment]
I wonder where that name comes from - on both my Windows 7 and 10 test machines the naming of volumes is different:

![image](https://user-images.githubusercontent.com/45139988/83333897-3f160c80-a2a3-11ea-9ec1-e4c36473c4b8.png)

Could you please show how VC GUI presents the available devices in "Select Device..." dialog?

**Comment by Staubgeborener** [comment]
![Unbenannt](https://user-images.githubusercontent.com/28908603/83338315-91ffbc00-a2c3-11ea-96d0-8a69edb2bfce.png)

**Comment by itsho** [comment]
Can you try one or more of the following:
1. Escape your password string?
2. Move the "/q" to the end?

**Comment by Staubgeborener** [comment]
Moving `/q` at the end (after the password string like `/v \Device\HarddiskVolume6  /l y /p p4ssw0rd /q` causes the Veracrypt GUI to open. But no attempt is made to decrypt the hard disk. It's like a "start veracrypt GUI" command.  
Setting `/q` in fron of the password (like `/v /q \Device\HarddiskVolume6  /l y /p p4ssw0rd`) leads to a syntax error.
Putting `/q` somewhere else (like `/v \Device\HarddiskVolume6 /q /l y /p p4ssw0rd`) is the same error as `/q /v \Device\HarddiskVolume6 /l x /p p4ssw0rd`.

What is the best way to escape the password? Let's say my password would be `Uym6q#Og["Fj+{6ExLqD`.

**Comment by itsho** [comment]
@Staubgeborener `"Uym6q#Og[""Fj+{6ExLqD"`

**Comment by Staubgeborener** [comment]
Nope, still `Wrong password or no Veracrypt Volume` - i tried this also with `/q` on different positions.

**Comment by itsho** [comment]
interesting. what about `"Uym6q#Og[\"Fj+{6ExLqD"` ?

**Comment by itsho** [comment]
according to [this](https://ss64.com/nt/syntax-esc.html) you only need to escape `& \ < > ^ |`
But i'm not sure in 100%...

**Comment by Staubgeborener** [comment]
According to your source, the escaping character should be `^`. 

Ok, thinks get weird now:

1. Fact: I have another disk which is displayed as `\Device\Harddisk0\Partition2` (see start post). This one has also a long password __with special characters__. Encryption with cli works fine - the only difference is the name  (`Device\Harddisk2\Partition1` VS  `Device\HarddiskVolume6`). 

1.  Now i changed the password of my disk `Device\HarddiskVolume6` to `12345678`. I tried `"%ProgramFiles%/VeraCrypt/veracrypt.exe" /q /v \Device\HarddiskVolume6 /l y /p 123456` and _tada_ - its encrypted. 

Ok, lets break it down: 
|# |device        | contains the following special characters           |
| - | ------------- |:-------------:|
|1 | `\Device\Harddisk0\Partition2`    | `(*@.#`  |
|2  | `\Device\HarddiskVolume6`*     | `#]"+{}`      |

(*`\Device\HarddiskVolume6` begins with a alphanumeric __not__ with a special character which should be escaped)

[Here](https://www.robvanderwoude.com/escapechars.php#Summary) is another source for escaping sequences in cmd/batch. I cant see the difference between `#1` and `#2`. Weird. I will close this, because it doesn't seem to be a problem with veracrypt. But _maybe_ someone knows the problem and can say something about it.

**Comment by itsho** [comment]
@Staubgeborener I've tested with regular volume and successfully created and mounted with the following commands

Create:
`VeraCrypt Format-x64.exe /create "Temp_Volume_50.vc" /password "Uym6q#Og[\"Fj+{6ExLqD" /size 100M /encryption AES /hash sha512 /filesystem NTFS /silent`

Mount:
`VeraCrypt-x64.exe /volume "Temp_Volume_50.vc" /letter Z /Password "Uym6q#Og[\"Fj+{6ExLqD" /hash sha512 /silent /quit `

the only point I didn't get is your remark about escaping the harddisk name?

**Comment by Staubgeborener** [comment]
> the only point I didn't get is your remark about escaping the harddisk name?

Nah, it's about escaping the password, not the harddisk name. 

 Maybe my problem was `"` and the correct escaping. 

I created a veracrypt container with the password `#]"+{}` and mounted it
`"%ProgramFiles%/VeraCrypt/veracrypt.exe" /q /v "vera.crypt" /l x /p #]\"+{}` works perfect (see the escaped `\"`).
(btw `"%ProgramFiles%/VeraCrypt/veracrypt.exe" /q /v "vera.crypt" /l x /p "#]\"+{}"` with surrounding quotes is also working)
