### ISSUE TITLE
Key file as normal file

### ISSUE THREAD

**Issue by MESWEB** [veracrypt/VeraCrypt#630]
It's possible to use normal file like mp3 or mp4 or any extension?

**Comment by githuborer** [comment]
Yes

**Comment by dhammel** [comment]
Yes.

Extensions don't really matter for anything anyway, extension work more for associations like telling the OS what type of file it is, so when double clicked it will open with whatever program is set to open said type of files. So a file like filename.mp4, knows to open your default video player to open mp4 files.

As the VeraCrypt documentation already mentions, if you set a video or photo or similar common file type extension for your container's &/or your keyfiles, you can chance messing up the data inside the files as some programs may think its a true file type that may have been corrupted and try to repair this file, but by doing so it would alter the meta data rendering your keyfile useless.

So if you plan on using common file type extensions, be sure not to open them up with any other software, if you accidentally do just confirm that the keyfile's are still the same (have not been altered.)

Also, using different extension won't fool an advanced advisory, as the keyfiles generated by veracrypt are purely random data, so are containers. So its not advised to even change the extension.

**Comment by andreas-becker** [comment]
@MESWEB, as the two mentioned before, it is possible.

If this information is enough for you, please close this issue.
