### ISSUE TITLE
This project does not have the ability to be Sponsored on Github

### ISSUE THREAD

**Issue by scramblr** [veracrypt/VeraCrypt#635]
Hello,

This Bug is very easy to fix, and would bring much needed income to the people dedicated to working on this project.

**Comment by andreas-becker** [comment]
Actually there are many ways to donate to the project: https://www.veracrypt.fr/en/Donation.html

The currently biggest problem is the lack of active/supportive developers and also the barely donations to the project to support @idrassi to work full-time for the project.

**Comment by scramblr** [comment]
Ah great that works! Thank you friend. I hope, perhaps, they will consider turning on the Github Support version as well. I'm tempted to leave this bug open until more people donate to this incredibly important project, but I'll defer to you the community on this matter.

**Comment by idrassi** [comment]
Thank you for your support.
Concerning Github Sponsors program, it looks indeed interesting especially thanks to their zero fees policy but I have mixed feeling about it. First, one to one donation are always better for privacy than using a third party (like PayPal or Github) but most people feel safer when using a trusted third party which is understandable. The second thing is that it gives too much power to the third party controlling the donation channel, especially if most donations are going through it (which Github is trying to do using their zero fees policy): this power can be used to easily starve a specific project in the future if it wants to. We should not neglect this point especially that Github is now under Microsoft umbrella.
Anyway, I will give it a thought later. Meanwhile, I'm interested in feedback from others about this new mechanism.

**Comment by scramblr** [comment]
Since the Sponsor "Heart Icon" button now leads to https://www.veracrypt.fr/en/Donation.html I think this can be closed :)
