### ISSUE TITLE
VeraCrypt filter driver breaks new USB drives on Windows 10 Version 2004

### ISSUE THREAD

**Issue by ColinFinck** [veracrypt/VeraCrypt#640]
I have just upgraded to Windows 10 x64 Version 2004 using the Windows 10 Upgrade Assistant, which recreated the SYSTEM registry hive (as other Windows 10 upgrades already did before).
Previously, I have been running Windows 10 x64 Version 1909 and VeraCrypt 1.24-Update6.

Since the upgrade, external USB drives have stopped working.
Whenever I plug in a new external USB drive, it doesn't show up in Explorer and Device Manager shows "One of the filter drivers installed for this device is invalid". I've tried multiple drives, but this happens with any USB drive.

I have then opened `regedit`, went to `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e967-e325-11ce-bfc1-08002be10318}`, and removed "veracrypt" from the `UpperFilters` value (so that only "partmgr" is left). After this change and plugging the USB drive back in, it worked again.
Unfortunately, this change renders the encrypted operating system unbootable, so I had to revert it.

After reverting that change, this one USB drive continues to work, but new USB drives again fail with "One of the filter drivers installed for this device is invalid".

**Comment by idrassi** [comment]
@ColinFinck : I have answered your email about this issue but I didn't get any response. Did you receive it?

I'm not aware of anyone else having this issue and so I was asking in the email about the list of filter drivers installed on the machine.

**Comment by ColinFinck** [comment]
@idrassi: Thanks for your reply! Got it, but had no time yet to debug this further on my machine.

**Comment by ColinFinck** [comment]
Even though I don't know what exactly fixed it, this is no longer a problem for me after the upgrade to Windows 10 20H2.
