### ISSUE TITLE
[Question] Encrypt Windows partion

### ISSUE THREAD

**Issue by MahatmaGonnDir** [veracrypt/VeraCrypt#641]
I am not sure if my question belongs to this page, but I couln't find other FAQs which answered my questions. So I ll try it here.
When I encrypt my partition I am just able to encrypt the "windows system partion". The other option (encrypt whole drive) is not available, it is greyed out. I already found answers why this is the case so thats not the point.
I want to know if I install an other operating system like Linux/Ubuntu in a virtual machine later is it encrypted aswell than? Or would it be possible to get access to my data than, because of my unecrypted virtual operating system?

Thanks for your answers.

**Comment by RA-Kooi** [comment]
Everything that you install on your encrypted partition/drive is encrypted, including any virtual machines you install.
However, if you install Linux on a different partition, or drive, that partition will be unencrypted. You will need to use LUKS to encrypt your Linux-only partitions. If you're a bit Linux-savvy you can use cryptsetup to mount partitions encrypted with Veracrypt, but it's not something I recommend for beginners.
