### ISSUE TITLE
Feature Request: HMAC option for authentication

### ISSUE THREAD

**Issue by Awbmilne** [veracrypt/VeraCrypt#647]
Currently, VeraCrypt supports Smart Cards by having Token files with passwords.\
Hardware security Keys (_such as Yubikey 5_) have support for [HMAC](https://tools.ietf.org/html/rfc2104) style Challenge-Response authentication with key pairs.

It would be nice to be able to use a Hardware Security key as a second factor for Volume mounting.

Another possibly useful option is TOTP based authentication.

I have not looked deep into the source for VeraCrypt to see how practical these approaches are to apply, but they would be FANTASTIC features for more flexible, secure authentication!

**Thanks for the great work VeraCrypt Devs!**

**Comment by ghost** [comment]
related https://github.com/veracrypt/VeraCrypt/issues/1651 cc @NRGLine4Sec, @Lqp1, @foray1010 @szszszsz
