### ISSUE TITLE
[Ubuntu] Dismount volume on lock/sleep 

### ISSUE THREAD

**Issue by TedLePoireau** [veracrypt/VeraCrypt#65]
I don't find any options to automatically dismount all my volumes when I lock my loptop or put it to sleep under Ubuntu.
I rode some forum messages saying it's possible under windows. Is it supposed to be available under Linux too ?

I know I could script it myself with something like ./veracrypt -d but i'd rather not.

**Comment by davidfoerster** [comment]
A few years back I wrote a [PM hook](/davidfoerster/truecrypt-tools/blob/master/etc/pm/sleep.d/10_truecrypt) (plus [a prerequisite](/davidfoerster/truecrypt-tools/blob/master/lib/truecrypt/dismount-volumes)) for that for TrueCrypt. They can be trivially adapted to VeraCrypt.

**Comment by slrslr** [comment]
Hi, in my case, Veracrypt 1.21 on linux debian is attempting to dismount my volume (unsuccessfully cause it is used by various apps) when i do "sudo pm-suspend", but i do not want it to do it. Any idea how to prevent it?

**Comment by andreas-becker** [comment]
@TedLePoireau is this still an issue for the current version?
