### ISSUE TITLE
Upgrade Chinese language files

### ISSUE THREAD

**Issue by freework2000** [veracrypt/VeraCrypt#651]
updata
[Language.zh-cn.zip](https://github.com/veracrypt/VeraCrypt/files/4845332/Language.zh-cn.zip)

**Comment by idrassi** [comment]
Thank you. I have pushed it to master: https://github.com/veracrypt/VeraCrypt/commit/2ca867ef5d4971cee7b0c7fcc494ac5d6712681e

**Comment by freework2000** [comment]
[Language.zh-cn.zip](https://github.com/veracrypt/VeraCrypt/files/4880975/Language.zh-cn.zip)
update

**Comment by freework2000** [comment]
[Language.zh-cn.zip](https://github.com/veracrypt/VeraCrypt/files/4896597/Language.zh-cn.zip)
update

**Comment by freework2000** [comment]
[Language.zh-cn.zip](https://github.com/veracrypt/VeraCrypt/files/4957035/Language.zh-cn.zip)
update
