### ISSUE TITLE
VC captures the focus after mount operation completion

### ISSUE THREAD

**Issue by OasisInDesert** [veracrypt/VeraCrypt#655]
Hello friends,

Please make the notification on mounting completion more graceful - for example, using the tooltip in the taskbar.

The following unpleasant situation arises during mounting operation:
When I start the mount operation and switch to another application, at the end of the mount operation, VC captures the focus, and since the "Dismount" button is focused by default, if I press the Enter key during my work the container is automatically unmounted ... :(

Thanks.

**Comment by junpeikyu** [comment]
Same is happening here. Would be definitely a great idea to stop this from happening.

**Comment by alt3r-3go** [comment]
FWIW, I've looked into this a bit and it looks like the action that brings it to the foreground is executed at the end of the mount thread, this one: https://github.com/veracrypt/VeraCrypt/blob/master/src/Mount/Mount.c#L5296-L5305. The code in there kinda suggests that this is going to happen (that `BringToForeground()` in `finally_do_arg2`), but the interesting part is that even if I comment that whole piece out, leaving only the `Mount()` call, the window still gets into foreground - and there seems to be no code in the `Mount()` itself to do that.

I've run out of time today to debug this further, so just leaving this note here as an intermediate result - for myself or anyone else who's willing to look into this.
