### ISSUE TITLE
Bootloader issues,

### ISSUE THREAD

**Issue by TheSorrow1** [veracrypt/VeraCrypt#657]
Hi, I think it would be a good idea to check these two bootloader issues in the other repository:

https://github.com/veracrypt/VeraCrypt-DCS/issues/21
https://github.com/veracrypt/VeraCrypt-DCS/issues/20

@idrassi

**Comment by idrassi** [comment]
@TheSorrow1 Thank you for pointing out these issues that I have completely overlooked. I have pushed a fix for them.
