### ISSUE TITLE
VC asking to record my screen

### ISSUE THREAD

**Issue by genesiscz** [veracrypt/VeraCrypt#658]
So VeraCrypt started on my MacBook and it asked me a permission to record my display. 

![image](https://user-images.githubusercontent.com/1512353/87556753-4eb4ad80-c6b7-11ea-8c91-8f3c142bd6ad.png)

Is it a bug, a feature or what is that good for? I am kinda scared to use it now.

**Comment by idrassi** [comment]
This is not normal and I have never seen this on my test systems running OSX Catalina and OSX Mojave.
Which version of OSX are you running? 

If you are sure you are using the official VeraCrypt binary, then something changed with an OSX update that makes the system believe that we need such access. The information about your system will help us reproduce and find the cause.

Thank you.

**Comment by genesiscz** [comment]
10.15.5 (19F101)

**Comment by genesiscz** [comment]
So I removed the old binary entirely, installed the one from https://www.veracrypt.fr/en/Downloads.html and after installation process it's there again.

**Comment by genesiscz** [comment]
MAYBE it's due to VC trying to record the screen/access pixels/whatever when creating the key? I am not 100% certain but simple googling lead me to think this is true

**Comment by idrassi** [comment]
I have tested under both OSX 10.5.5 and OSX 10.5.6 and I'm never asked for permission to record display even when creating a volume and moving the mouse for random generator.
Below is a screenshot of my OSX 10.5.6 system and as you can see there is no entry for VeraCrypt under screen recording section (only AnyDesk is present).

So, I think your previous VeraCrypt was not an original binary but some modified one probably with malware.

You can safely uncheck VeraCrypt from the list of screen recording and it will work normally.

![VeraCrypt_OSX_10 15 6](https://user-images.githubusercontent.com/4698669/88485018-3c6a2780-cf73-11ea-99e0-489d117ec2f5.png)

**Comment by genesiscz** [comment]
Is there any possibility you  could help me with determining whether it's a legit one or not? I am being a lot curious about this and paranoid at the same. Is there a point I could look at to make sure it's the correct one?

I ran it through Virus total, looks clean. Md5 of the App is not the same but I guess its because it has more contents that are changing. The binary is same.
