### ISSUE TITLE
error "GTK+ 3 support requires wxGraphicsContext"

### ISSUE THREAD

**Issue by el-cpu** [veracrypt/VeraCrypt#661]
Hello. I can't build Veracrypt from source. After successful installation of wxWidGets in home directory and changing variable WX_ROOT:

sudo make WXSTATIC=1 WX_ROOT=/home/candra/wxWidgets wxbuild

I get:

In file included from /home/candra/wxWidgets/include/wx/chkconf.h:1281:0,
                 from /home/candra/wxWidgets/include/wx/platform.h:544,
                 from /home/candra/wxWidgets/include/wx/defs.h:45,
                 from /home/candra/wxWidgets/include/wx/wxprec.h:12,
                 from /home/candra/wxWidgets/src/common/event.cpp:20:
/home/candra/wxWidgets/include/wx/gtk/chkconf.h:92:14: error: #error "GTK+ 3 support requires wxGraphicsContext"
             #error "GTK+ 3 support requires wxGraphicsContext"
              ^~~~~
In file included from /home/candra/wxWidgets/include/wx/chkconf.h:1281:0,
                 from /home/candra/wxWidgets/include/wx/platform.h:544,
                 from /home/candra/wxWidgets/include/wx/defs.h:45,
                 from /home/candra/wxWidgets/include/wx/wxprec.h:12,
                 from /home/candra/wxWidgets/src/common/fs_mem.cpp:9:
/home/candra/wxWidgets/include/wx/gtk/chkconf.h:92:14: error: #error "GTK+ 3 support requires wxGraphicsContext"
             #error "GTK+ 3 support requires wxGraphicsContext"
              ^~~~~

I did not find in the internet this issue.

**Comment by idrassi** [comment]
Since you are linking against GTK3 instead of GTK2, you need to instruct VeraCrypt to build GTK3 variable of wxWidgets, the same way as it is done in the script build_cmake_rpm_gtk3.sh (https://github.com/veracrypt/VeraCrypt/blob/master/src/Build/build_cmake_rpm_gtk3.sh#L27)

Basically, you need to add `WITHGTK3=1` in the make command line, so you need to type:
`
sudo make WXSTATIC=1 WITHGTK3=1 WX_ROOT=/home/candra/wxWidgets wxbuild
`

Generally, it is good to have a look at the script in the "src/Build" directory since it contains the scripts we use for the official build.

**Comment by el-cpu** [comment]
Thank for the response! Worked much better.

There are still some errors in this build:

In file included from /home/candra/wxWidgets/include/wx/private/addremovectrl.h:149:0,
                 from /home/candra/wxWidgets/src/common/addremovectrl.cpp:32:
/home/candra/wxWidgets/include/wx/gtk/private/addremovectrl.h:77:5: error: ‘wxToolBar’ does not name a type; did you mean ‘wxToolTip’?
     wxToolBar* const m_tbar;
     ^~~~~~~~~
     wxToolTip
/home/candra/wxWidgets/include/wx/gtk/private/addremovectrl.h: In constructor ‘wxAddRemoveImpl::wxAddRemoveImpl(wxAddRemoveAdaptor*, wxAddRemoveCtrl*, wxWindow*)’:
/home/candra/wxWidgets/include/wx/gtk/private/addremovectrl.h:30:11: error: class ‘wxAddRemoveImpl’ does not have any field named ‘m_tbar’
           m_tbar(new wxToolBar(parent, wxID_ANY))
           ^~~~~~
/home/candra/wxWidgets/include/wx/gtk/private/addremovectrl.h:30:22: error: expected type-specifier before ‘wxToolBar’
           m_tbar(new wxToolBar(parent, wxID_ANY))
                      ^~~~~~~~~
/home/candra/wxWidgets/include/wx/gtk/private/addremovectrl.h:32:9: error: ‘m_tbar’ was not declared in this scope
         m_tbar->AddTool(wxID_ADD, wxString(), GetNamedBitmap("list-add"));
         ^~~~~~
/home/candra/wxWidgets/include/wx/gtk/private/addremovectrl.h:32:9: note: suggested alternative: ‘__tan’
         m_tbar->AddTool(wxID_ADD, wxString(), GetNamedBitmap("list-add"));
         ^~~~~~
         __tan
/home/candra/wxWidgets/include/wx/gtk/private/addremovectrl.h: In member function ‘virtual void wxAddRemoveImpl::SetButtonsToolTips(const wxString&, const wxString&)’:
/home/candra/wxWidgets/include/wx/gtk/private/addremovectrl.h:61:9: error: ‘m_tbar’ was not declared in this scope
         m_tbar->SetToolShortHelp(wxID_ADD, addtip);
         ^~~~~~
/home/candra/wxWidgets/include/wx/gtk/private/addremovectrl.h:61:9: note: suggested alternative: ‘__tan’
         m_tbar->SetToolShortHelp(wxID_ADD, addtip);
         ^~~~~~
         __tan
Makefile:35551: recipe for target 'corelib_addremovectrl.o' failed
make[1]: *** [corelib_addremovectrl.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:451: recipe for target 'wxbuild' failed
make: *** [wxbuild] Error 2

**Comment by idrassi** [comment]
We don't have this issue when building against wxWidgets 3.0.4 or 3.0.5 (these are the only versions we tested since they are stable ones).

Are you sure you are using wxWidgets 3.0.x?

On which Linux distribution are you building?

**Comment by el-cpu** [comment]
command 'wx config --version' gave output:

3.1.4

**Comment by el-cpu** [comment]
I use modified Ubuntu 18.04

**Comment by idrassi** [comment]
We never tested the build against 3.1.4 on Linux so maybe there are issues.

Just to be sure, is the source code of wxWidgets present at /home/candra/wxWidgets of version 3.1.4?


As a solution, you can just link

**Comment by el-cpu** [comment]
yes there is a folder ~/wxWidgets and here is a ls output from this folder:

~/wxWidgets$ ls
3rdparty         config.guess  interface      setup.h.in
acinclude.m4     config.sub    lib            setup.h_vms
aclocal.m4       configure     locale         src
appveyor.yml     configure.in  Makefile.in    tests
art              demos         misc           utils
autoconf_inc.m4  descrip.mms   mkinstalldirs  version-script.in
autogen.sh       distrib       README-GIT.md  wx-config.in
build            docs          README.md      wx-config-inplace.in
buildgtk         include       regen          wxwidgets.props
CMakeLists.txt   install-sh    samples        wxwin.m4


Sorry I did not understood what did you mean by link? 

How could i get 3.0.5 version?

**Comment by idrassi** [comment]
The last stable version 3.0.5 can be downloaded from the officiel website at https://www.wxwidgets.org/downloads/#latest-stable-release-305

Sorry for the incomplete sentence in my previous post. I have clarified it.

**Comment by el-cpu** [comment]
Thanks a lot! I just got 3.0.5, changed the names so that VeraCrypt try to build against 3.0.5 and it worked!

Now I have veracrypt in Main directory!!

**Comment by idrassi** [comment]
I'm glad it worked.
I will close this issue since you are able to build under GTK3.

**Comment by archfrog** [comment]
If anybody stumbles across this, then you *can* build using wxWidgets v3.1.4 using these commands:

```bash
make WXSTATIC=FULL WITHGTK3=1 WX_ROOT=~/prj/wxWidgets-3.1.4 wxbuild
make WXSTATIC=FULL WITHGTK3=1 WX_ROOT=~/prj/wxWidgets-3.1.4
```

The trick is to use `WXSTATIC=FULL` instead of `WXSTATIC=1`.  This generates a huge (8 megabytes) executable, but it builds.

I built the above on Manjaro Gnome v20.2 x64, but it should be usable on Ubuntu Desktop 20.10 x64, I guess.

**DISCLAIMER: I HAVE NOT TESTED THE FUNCTIONALITY OF VERACRYPT BUILT THIS WAY!**
