### ISSUE TITLE
[Windows] "VeraCrypt Format.exe" and /secureDesktop

### ISSUE THREAD

**Issue by grolongo** [veracrypt/VeraCrypt#668]
Why is there the option to have `/secureDesktop` with `"VeraCrypt Format.exe"` on the command line?

There is no dialog popup asking for passphrase or tokenpin input if none are specified directly in the command.  

We must have `/password foo` or `/tokenpin 0000` otherwise VeraCrypt returns an error saying the volume cannot be created.

Can someone explain me why is it available? https://www.veracrypt.fr/en/Command%20Line%20Usage.html (last row)

**Comment by idrassi** [comment]
`/secureDesktop` in `"VeraCrypt Format.exe"` enables displaying the PIN dialog for the token holding the keyfile in a Secure Desktop, thus protecting PIN entry.

**Comment by grolongo** [comment]
Thanks for answering.  
Do you plan to implement a pinentry dialog for the password when creating/mounting a volume from the command line too?  
I think that would be great instead of having to type it in plain text in the command.  
`PS> gpg --output foo.txt.gpg --symmetric foo.txt` does it on Windows.
