### ISSUE TITLE
inplacedec command line

### ISSUE THREAD

**Issue by D34G** [veracrypt/VeraCrypt#670]
What is the command line option /inplacedec and /resumeinplacedec used for?  cannot find clear explanation in code comments or documentation.

**Comment by idrassi** [comment]
these are internal switches used by VeraCrypt UI to handle In-Place decryption of non-system volumes. Normally they should not be specified manually.

**Comment by D34G** [comment]
Thank you, with that statement I was able to look at use cases, etc. It might be good to help me save resources in my script.
