### ISSUE TITLE
Veracrypt Traveler Disk Setup error

### ISSUE THREAD

**Issue by Berbe** [veracrypt/VeraCrypt#675]
- System: Windows 7 Professional x64
- Version: 1.24-Update7 Legacy Portable

Steps I followed:
1. Extract portable version to a directory
2. Plug empty NTFS-formatted USB disk in
3. Use `Tools` > `Traveler Disk Setup...`
4. Use default options (`Creation Wizard` & `Expander)`
5. Got an error about an already existing file and `TravelerDlgProc:4818`

**Comment by Berbe** [comment]
?!

**Comment by datenbank-projekt** [comment]
issue still exists in 1.25.9
**when you set the language to English (Settings -> Language) the problem disappeared** for me in 32bit and 64bit versions.
