### ISSUE TITLE
veracrypt needs a very long time to figure out that a password is wrong

### ISSUE THREAD

**Issue by waynongithub** [veracrypt/VeraCrypt#677]
When entering a faulty password, veracrypt needs a minute to detect that it is wrong. Is it possible to have a more immediate response?
tnx!

**Comment by alt3r-3go** [comment]
@waynongithub, you can speed it up by explicitly selecting the PRF value in PKCS5-PRF field (it's set to "Autodetection" by default and tries all of them) upon mounting.

**Comment by Neirpyc** [comment]
It depends on the hash algorithm you use. I believe VeraCrypt tries `sha512` first. If you're using another algorithm, refer to @alt3r-3go's answer.

Anyways, it's not a bug, it's a feature, to prevent password brute-force. You can use a PIM to lower the number of hashing rounds (lowers security).

**Comment by waynongithub** [comment]
thank you
