### ISSUE TITLE
veracrypt 1.24 update 7 create container stuck on Ubuntu 18.04

### ISSUE THREAD

**Issue by 0x0a0d** [veracrypt/VeraCrypt#693]
my actions
```bash
docker pull ubuntu:18.04
docker run -it ubuntu:18.04
#on docker
apt update
apt install wget libfuse2 -y
wget https://launchpad.net/veracrypt/trunk/1.24-update7/+download/veracrypt-1.24-Update7-setup.tar.bz2
tar jxf https://launchpad.net/veracrypt/trunk/1.24-update7/+download/veracrypt-1.24-Update7-setup.tar.bz2
./veracrypt-1.24-Update7-setup-console-x64
# blah blah
veracrypt -c test
# blah blah
# after Please type at least 320 randomly chosen characters and then press Enter
# it stop
```
I downgrade to Update4 and it worked

**Comment by idrassi** [comment]
Can you please try using the native Ubuntu 18.04 .deb package? Its link is in the official download page.

It is possible that there is an issue with the generic binaries in later version and this test can confirm it.

**Comment by 0x0a0d** [comment]
@idrassi thank for your reply. It've long time but I try both .deb and .tar.bz2, with docker ubuntu 18.04 and vps ubuntu 18 too.  Both got stuck after typed 320 chars. I used default recommend options

**Comment by T-Bonhagen** [comment]
have you tried the ubuntu ppa?
[](https://launchpad.net/~unit193/+archive/ubuntu/encryption)
