### ISSUE TITLE
Locked out of windows during pretest

### ISSUE THREAD

**Issue by markus31** [veracrypt/VeraCrypt#697]
Started full system encryption with latest veracrypt .27 on win10 x64 latest build on acer swift laptop. Started pre-test, reboot, entered password, success, but then nothing happens. windows doesn’t boot. Access to rescue disk on usb works, but none of the options seems to work. Access to boot menu works but don‘t know what to do. Please help. Data is backed up but can‘t access windows.

**Comment by markus31** [comment]
If I press esc instead of entering the password, it says „could not find the original windows loader“. If I boot from the veracrypt rescue disc on usb and select „boot original windows loader“, the same error message appears. This is still during pre-testing, the drive is not yet encrypted. Please help, I can‘t access windows anymore...

**Comment by githuborer** [comment]
You could restore the win loader with a win boot cd or the system repair. There are lots of tutorials out there.
If your disk isnt encrypted, its no prob

**Comment by strazzere** [comment]
Please don't just tag random contributors to issues. I have no knowledge of anything you're talking about nor do I own a windows machine to try and assist with.

**Comment by markus31** [comment]
So Veracrypt system encryption pre-testing bricked my machine. Veracrypt rescue disk was useless. Even boot repair didn't help. I had to reinstall the entire windows. Terrible experience. There must be some serious incompatibility with the lastest windows build or acer machines. I did nothing wrong, I just followed the veracrypt configuration steps.
