### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by Wilkolicious** [veracrypt/VeraCrypt#702]
Just some notes on my brief troubleshooting as a _naive_ user:

## 1. [`osxfuse` `3.11.2`](https://github.com/osxfuse/osxfuse/releases/tag/osxfuse-3.11.2)
Attempting to use `osxfuse` `3.11.2` results in Veracrypt failing to mount volume with error message:
```
kext load failed: -603946996
mount_macfuse: the file system is not available (255)
```

This is presumably because `osxfuse` `3.11.2` is incompatible with arch arm64, as seen when trying to directly load the kext:
```
/Library/Filesystems/osxfuse.fs/Contents/Extensions/10.11
❯ sudo kextload osxfuse.kext
Executing: /usr/bin/kmutil load -p /Library/Filesystems/osxfuse.fs/Contents/Extensions/10.11/osxfuse.kext
Incompatible architecture: Binary is for x86_64, but needed arch arm64e
```

## 2. [`macfuse` `4.0.3`](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.3)
If only `macfuse` `4.0.3` is installed/loaded, then Veracrypt will error at start with a cryptic error message/code of `6`:
However, `macfuse` kext loads without error unlike in `osxfuse` `3.11.2`

## 3. Both versions installed
Same error as seen above for `osxfuse`

## 4. Test if Veracrypt is looking for `osxfuse` regardless of `macfuse`
```
/Library/Filesystems
❯ sudo mv osxfuse.fs osxfuse.fs.bak
❯ ll
total 0
drwxr-xr-x  2 root  wheel    64B  1 Jan  2020 NetFSPlugins
drwxr-xr-x  3 root  wheel    96B 18 Nov 22:08 macfuse.fs
drwxr-xr-x  3 root  wheel    96B  4 Oct 18:05 osxfuse.fs.bak
```
Looks like something is hardcoded?
<img width="259" alt="image" src="https://user-images.githubusercontent.com/16191979/99732668-cb1d2a00-2ab7-11eb-9486-308a5599bdb2.png">

## 5. Attempt to point Veracrypt towards `macfuse` kext
```
/Library/Filesystems/osxfuse.fs/Contents/Extensions
❯ l
total 0
drwxr-xr-x  15 root  wheel   480B 19 Nov 22:09 .
drwxr-xr-x   7 root  wheel   224B  4 Oct 18:05 ..
lrwxr-xr-x   1 root  wheel     4B 19 Nov 22:07 10.10 -> 10.9
drwxr-xr-x   3 root  wheel    96B  4 Oct 18:06 10.11
lrwxr-xr-x   1 root  wheel     5B 19 Nov 22:07 10.12 -> 10.11
lrwxr-xr-x   1 root  wheel     5B 19 Nov 22:07 10.13 -> 10.11
lrwxr-xr-x   1 root  wheel     5B 19 Nov 22:07 10.14 -> 10.11
lrwxr-xr-x   1 root  wheel     5B 19 Nov 22:07 10.15 -> 10.11
lrwxr-xr-x   1 root  wheel    54B 19 Nov 22:09 10.16 -> /Library/Filesystems/macfuse.fs/Contents/Extensions/11
drwxr-xr-x   3 root  wheel    96B  4 Oct 18:05 10.5
drwxr-xr-x   3 root  wheel    96B  4 Oct 18:05 10.6
lrwxr-xr-x   1 root  wheel     4B 19 Nov 22:07 10.7 -> 10.6
lrwxr-xr-x   1 root  wheel     4B 19 Nov 22:07 10.8 -> 10.6
drwxr-xr-x   3 root  wheel    96B  4 Oct 18:06 10.9
lrwxr-xr-x   1 root  wheel    54B 19 Nov 22:09 11 -> /Library/Filesystems/macfuse.fs/Contents/Extensions/11
```

Yup, new errors: 
<img width="523" alt="image" src="https://user-images.githubusercontent.com/16191979/99732894-3404a200-2ab8-11eb-8516-9b91ef158469.png">

So in my ignorance, I don't know how much of this will be solved by PR #699; hopefully all.  This ticket slightly differs in that macOS Big Sur works fine with `osxfuse` `3.11.2`, however Apple Silicon as a variable does not.

**Comment by fizzyfrosty** [comment]
Apple Silicon (Macbook Air) running macOS 11.0.1
Same issue here, if FUSE 3.11.2 installed, gives error unable to mount volumes after attempting to mount.
If FUSE 4.0.3 installed, VeraCrypt fails to load.

**Comment by idrassi** [comment]
Thank you for the report.

I have created a notarized installer based on the pull request https://github.com/veracrypt/VeraCrypt/pull/699 which should solve this problem. i'm attaching it below. The zip contains the dmg, its PGP signature using VeraCrypt key and its SHA256 checksum.

Normally, it should work on the M1 machines thanks to x64 emulation and it is compatible with both osxfuse 3.11 and macFUSE 4.0.3.

Let me know if you encounter any issues. Especially I'm interested in the performance on Apple Silicon M1.

Next step will be to modify VeraCrypt in order to have a native ARM64 build.

[VeraCrypt_1.24-Update8.zip](https://github.com/veracrypt/VeraCrypt/files/5605312/VeraCrypt_1.24-Update8.zip)

**Comment by Wilkolicious** [comment]
@idrassi Brilliant, thank you.  That worked for me after a few steps of uninstalling & rebooting. With no hard numbers, the performance is great (not discernible from my previous Macbook Pro 13" 2017) + M1 speedups; little CPU utilisation (saw a spike to 18% of 800%) for the `Veracrypt` process.

I did have a couple of issues when trying to open that build at various points.  Here were my steps on my way to get it working:

1. Had osxfuse 3.11.2 + macfuse 4.0.3 + VeraCrypt version 1.24-Update7 installed
2. Uninstalled osxfuse 3.11.2
3. Installed `VeraCrypt_1.24-Update8` over existing Veracrypt version
5. Got same error as in OP with error code of `6`
6. App clean'd and reinstalled `VeraCrypt_1.24-Update8` in case there was some existing files from previous VeraCrypt version that were causing the error
7. `VeraCrypt_1.24-Update8` wouldn't open (no error)
8. Uninstalled `VeraCrypt_1.24-Update8` + macfuse 4.0.3 (so no veracrypt or osxfuse/macfuse is installed)
9. Restarted
10. Installed macfuse 4.0.3
11. Restarted
12. Installed `VeraCrypt_1.24-Update8`
13. Works!

So to extrapolate, probably best that one removes all previous veracrypt and/or osxfuse/macfuse installations and install new versions in-dispersed with restarts (steps 8-13).

**Comment by dcolley** [comment]
@idrassi thanks, this worked for me
