### ISSUE TITLE
Requirements to build VC on Windows

### ISSUE THREAD

**Issue by josephernest** [veracrypt/VeraCrypt#713]
I'm about to compile VC, and to install the [necessary tools](https://github.com/veracrypt/VeraCrypt#requirements-for-building-veracrypt-for-windows).

Would someone have the links of the official pages or direct download links for each item of these tools? (It might be useful for future users as well):

* Microsoft Visual C++ 2010 SP1 (Professional Edition or compatible)
* Microsoft Visual C++ 1.52 (available from MSDN Subscriber Downloads)
* Microsoft Windows SDK for Windows 7.1 (configured for Visual C++ 2010)
* Microsoft Windows SDK for Windows 8.1 (needed for SHA-256 code signing)
* Microsoft Windows Driver Kit 7.1.0 (build 7600.16385.1)
* NASM assembler 2.08 or compatible

Note: I've done the same thing in the past, for other projects, and it is very long even to localize the right MSVC++ installers (because Microsoft tend to make the old ones more difficult to find and encourage to download the newest Visual Studio versions).

Example for Microsoft Visual C++ 2010 SP1:

Here:
https://support.microsoft.com/fr-fr/help/2977003/the-latest-supported-visual-c-downloads

is a link:

> Téléchargez Visual Studio 2010 Service Pack 1 (programme d’installation). Il s’agit du dernier service pack Visual C ++ pris en charge pour Visual Studio 2010.

When you click on this link, after logging in on a Microsoft account, it doesn't link directly on the right installer. When you then search Visual Studio 2010, you have lots of different installers.

I'll do it when I have time, but just in case, if someone has copied/paste the direct download links somewhere, I would be interested :)

**Comment by idrassi** [comment]
Visual Studio 2010 and Visual C++ 1.52 are available for Visual Studio subscribers. You need indeed to search using their name to find their installers.
Visual Studio 2010 can replace by newer versions like Visual Studio 2019. For Visual C++ 1.52, it is needed for the MBR bootloader and there is no other alternative. I will start to include pre-built binaries of the MBR bootloader like it is the case already for EFI bootloader to make it easier for those not having a Visual Studio subscription to build VeraCrypt.

For the other dependencies, here the links:

- For Windows SDK 7.1 and Windows SDK 8.1, the links are available at https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/
- Windows Driver Kit 7.1: https://www.microsoft.com/en-us/download/details.aspx?id=11800
- NASM binary can be download this link (we use version 2.13.02): https://www.nasm.us/pub/nasm/releasebuilds/?C=M;O=D
- YASM binary can be downloaded from https://yasm.tortall.net/Download.html
- gzip binary can be download from this link (we use version 1.2.4): https://sourceforge.net/projects/gnuwin32/files/gzip/
