### ISSUE TITLE
How to translate

### ISSUE THREAD

**Issue by thewh1teagle** [veracrypt/VeraCrypt#718]
I want to translate this software into Hebrew.
I started by forking the repo and adding a copy of the default XML translate file into the translations folder. 
It's ok to translate it as I do and then when I finish to just pull request?
The link for the fork is [here](https://github.com/thewh1teagle/VeraCrypt/blob/master/Translations/Language.he.xml)

**Comment by idrassi** [comment]
Yes, you can proceed as you proposed using pull requests.
But before accepting the translation, we will need some kind of review or at least some credentials about previous translations of other projects since nobody in the team speaks Hebrew.

**Comment by thewh1teagle** [comment]
Thanks for reply. 
Does VeraCrypt support RTL (right to left) language? - Hebrew is written from right to left.
I tried my translation but it shown as LTR (left to right) language (like english)

**Comment by idrassi** [comment]
Yes, VeraCrypt support RTL languages if the operating system supports it.
For example, Arabic and Farsi translations of VeraCrypt are shown correctly on Windows and Linux. Below are screenshots of Arabic translation of the VeraCrypt UI.
On which operating system are encountering the issue? 
If you can share an example of Hebrew XML file, I can test it on my side.

![VeraCrypt_Arabic_Windows](https://user-images.githubusercontent.com/4698669/103249871-8798c400-4971-11eb-97af-d24b192922c1.png)
![VeraCrypt_Arabic_Linux](https://user-images.githubusercontent.com/4698669/103249880-8c5d7800-4971-11eb-9e5f-cada922018fd.png)

**Comment by thewh1teagle** [comment]
That's good news.
I don't know arabic so actually i can't understand it from your pictures.
Here is the translated file: (Using automated script for tests)

[Language.he.zip](https://github.com/veracrypt/VeraCrypt/files/5749170/Language.he.zip)

**Comment by thewh1teagle** [comment]
I have another question
Should I keep the ampersands characters in the xml file? 
I tried some without them and it worked fine
And actually i didn't understand why we need them at all.. because the value of them does not apper in the program where them written in the xml file (&,< etc)

**Comment by idrassi** [comment]
Thank you for the file and the screenshot.
So actually the text is displayed correctly and the issue is just menu text doesn't start from the right as expected. I thought that the text was displayed in the wrong order.

Indeed, VeraCrypt doesn't display menu text label from right to left. There is a missing system function call to change the layout of the window to RTL when a RTL language is selected. I will see how to implement this in order to have a correct RTL layout.
Meanwhile, the UI remain usable.

By the way, there was an issue in the XML for some entries related to the "..." part in the labels: they were put at the beginning instead of the end. I have fixed it and i'm attaching modified xml. 
[Language.he.modified.zip](https://github.com/veracrypt/VeraCrypt/files/5752997/Language.he.modified.zip)

concerning ampersands, they are using for keyboard shortcuts using ALT key (when you press ALT key, Windows automatically highlights the button/menu entries that have an ampersand shortcut).
For non western languages, I don't know if there is an equivalent. You can drop them if there is no equivalent.

**Comment by thewh1teagle** [comment]
Thanks for your fixes. 

explicit support for RTL languages would be great.

About the ampersands:
Does it matter where I put them in the text? Because I saw multiple sections where the ampersands in random position ( of course where the text and not out of that)

Another question:
How do I test the language on linux build?
compiling VeraCrypt every time Isn't an option because it takes long time to compile the program.
In windows i have just downloaded Portable build and i added the xml file to the translations folder.

**Comment by archfrog** [comment]
I don't know what kind of system you're using, but it shouldn't take long to build VeraCrypt on Linux - the part of the build that takes a long time is the wxWidgets build and you only need to do that once before building VC.

Please try using this command to build on Linux (after having done the `make WXSTATIC=1 WITHGTK3=1 wxbuild` step):

```bash
nice make -j $(nproc) WXSTATIC=1 WITHGTK3=1
```

You should be able to repeat the above command as often as you like and it should take more than a few seconds.  `nice` is just there to make sure your desktop environment doesn't choke; if I leave it out my Manjaro Gnome UI crashes.

I am in the proces of finishing up the Danish translation (I've translated Typora and a number of other projects) and I basically do my work on Windows until such a time that I feel that I am nearly complete, after which I plan to switch to Linux and finish up the translation.  On Windows, you can simply change language to English and back again to Hebrew to see your recent changes.

**Comment by thewh1teagle** [comment]
@archfrog 
I managed to compile VC as you told me, 
I had to download [wxwidgets](https://www.wxwidgets.org/downloads/ )
and install `fuse libary` by `pacman -S fuse`,
Then the last part before running the commands you told me was to modify the `WX_ROOT` variable in VC `Makefile` and point it to the wxwidgets folder (Which i downloaded previously).
Thank you very much for your help.

I see that I can't change the language in the Linux build from the UI, 
How do I change the language on the Linux build of VC?

The system I use is Arch Linux x86_64.

**Comment by archfrog** [comment]
I just discovered myself tonight that VeraCrypt for Linux doesn't appear to support dynamic switching of the UI language yet.  

So, my best guess is that you can manually copy your `Language.he.xml` to `VeraCrypt/src/Common/Language.xml` and then do a remake (using the `nice make...` command from before).  You may need to *temporarily* specify `en` as the language in the `<entry lang="en" key="...">...</entry>` part.  Once your translation is complete and it works as supposed, you'll have to search and replace `lang="en"` with `lang="he"`, I think.  You should test this first - perhaps VC/Linux will accept `lang="he"` without any issues, in which case there's no need to do the search and replace stuff.

My best suggestion is to do the translation on Windows for now and then switch to Linux once the UI language support for Linux is in place.  I suppose somebody is in the process of adding dynamic UI language support to the Linux build, but I don't know for sure.

**Comment by thewh1teagle** [comment]
@archfrog 
I replaced `VeraCrypt/src/Common/Language.xml` with my translated `XML` file 
without modify  `<entry lang="he" key="...">...</entry>`,
then I recompiled the program and it worked! :100:

**Comment by archfrog** [comment]
Great, I'll do the same then, when I am near enough completion to work on the Linux version :-)  Thanks for your feedback!

**Comment by thewh1teagle** [comment]
@archfrog 
I don't want Unexpected surprises after proceeding the translation, that's why I check everything first.

**Comment by thewh1teagle** [comment]
I did not understand the concept of  `&amp` ampersands ( When you click `TAB` you highlight them).
What's the point of that?
It makes the translation harder.
Can I put them when I finish in random position in the text? ( I will just use automated script for that )

**Comment by archfrog** [comment]
Basically, when the XML file is processed, the `&amp;` sequence is replaced with `&`.  The ampersand indicates that the next character in the string is a hot key, which is activated by pressing Alt+that character.

So, if I you have this string: `&amp;Files`, you can press Alt-F to select the `Files` menu item (only when the `Files` menu item is visible).  If, on the other hand, you wrote `F&amp;iles`, you'd need to press Alt-I to select the `Files` menu item.

I don't think it is a good thing to automatically assign these hot keys.  Normally, you have logical groups of hot keys, say all those items that are located in the `File` menu in the main menu, or all the items located in the `Print` dialogue somewhere in the app.

As a rule of thumb, the hot key selectors should not generate overlaps within their corresponding groups.  It won't be useful to the user if there are, say, two Alt-S shortcuts/hotkeys.  They need to be unique in their context - on the menu or in the dialogue, where they appear.

**Comment by thewh1teagle** [comment]
@idrassi 
Quick update for you
I tried myself to create explicit RTL support (Menu from right to left)
I discovered that `wxWidgets` supports RTL aligments.
See [SetLayoutDirection](https://docs.wxwidgets.org/3.0/intl_8h.html#a7e30efec05ef9b40b1750ac046400c81) method in [Window](https://docs.wxwidgets.org/3.0/classwx_window.html) class, it supports right to left aligments.
I tried myself to modify the source code of `VeraCrypt` to see if it works and it worked!!
I added `SetLayoutDirection(wxLayout_RightToLeft);` in [src/Main/Forms/MainFrame.cpp](https://github.com/veracrypt/VeraCrypt/blob/ea9def1a86795ecaa1d8f1ebdc99b23ab0afe1e9/src/Main/Forms/MainFrame.cpp) on [line 59](https://github.com/veracrypt/VeraCrypt/blob/ea9def1a86795ecaa1d8f1ebdc99b23ab0afe1e9/src/Main/Forms/MainFrame.cpp#L59)
immediately after `SetIcon (Resources::GetVeraCryptIcon());`
then I just recompiled the program and when i clicked `Settings->Preferences` (When the language is on RTL language like hebrew)
The menu displayed correctly!

![image](https://user-images.githubusercontent.com/61390950/103467508-56950680-4d58-11eb-8bfb-39f4d6215956.png)
