### ISSUE TITLE
Veracrypt requires OSXFUSE 2.5 or above while my OSXFUSE version is 4.0.4 [MAC]

### ISSUE THREAD

**Issue by Aholicknight** [veracrypt/VeraCrypt#722]
After updating OSXFUSE manually it says VeraCrypt requires OSXFUSE 2.5 or above while my OSXFUSE version is 4.0.4
# Expected behavior

Veracrypt is supposed to work.
# Observed behavior

It should load the drives.
# Steps to reproduce

1. 
2. 
3. 
4.

# Screenshots

<img width="683" alt="Screen Shot 2021-01-01 at 12 38 42 AM" src="https://user-images.githubusercontent.com/7843719/103434619-b610dc00-4bc9-11eb-9afa-9c4924ab3bfd.png">

# Your Environment
MacOS BigSur
Please tell us more about your environment

**VeraCrypt version: 1.24-Update4

**Operating system and version: MacOS BigSur 11.1

**System type:**

**Comment by Aholicknight** [comment]
Uninstalling Veracrypt and installing Veracrypt 1.24-Update8 fixes the problem.

**Comment by SofijaErkin** [comment]
VeraCrypt requires OSXFUSE 2.5 or above while I use VeraCrypt to create hidden volume.

My environment:

macOS: `macOS Monterey 12.6.5`;

laptop CPU: `intel`;

 VeraCrypt version: `VeraCrypt 1.23`;

macFUSE version: `4.2.5`;
