### ISSUE TITLE
Program freeze (built from git)

### ISSUE THREAD

**Issue by thewh1teagle** [veracrypt/VeraCrypt#724]
Hello. 
I'm build the program on arch linux x86_64 from the latest code here in git.
When I click certain encryption algorithm in `VeraCrypt Volume Creation Wizard` the program freezing until i force quit.

To get into that window you need to create new encrypted volume -> then you will get into this setup wizard.

![image](https://user-images.githubusercontent.com/61390950/103953794-71e28600-514b-11eb-91c6-c10547b981e8.png)

**Comment by T-Bonhagen** [comment]
I didn't have this problem. (build on ubuntu 18.04) 
Can you please provide all previous steps is detail?
Container or Partition?
Hidden or not?
Is the problem sporadic?
Please provide your LANG environment setting.
Does it happen for every algorithm?
On which distribution do you build?

**Comment by idrassi** [comment]
Fixed by #726
