### ISSUE TITLE
VeraCrypt - debian jessie - v 1.17 - PIM data not saved to Favorites

### ISSUE THREAD

**Issue by MMelicher** [veracrypt/VeraCrypt#73]
PIM is not saved with the ,,Add Selected Volume to Favorites..." option.

After saving the drive/volume to Favorites and trying to mount it like an Favorite one, it uses default PIM, and not the real one specified in the procese of mounting it the first time.

the /home/user/.VeraCrypt/Favorite Volumes.xml does not contain pim settings, so it uses the default one.

**Comment by andreas-becker** [comment]
@MMelicher is this fixed in the current version? If so, please close the issue.
