### ISSUE TITLE
Improper text substitution in token PIN prompt after commit 38ad76

### ISSUE THREAD

**Issue by alt3r-3go** [veracrypt/VeraCrypt#730]
The issue was introduced in commit 38ad7650ac4f723fd6109e3f55b3ea1c47ec4af9 (I only had time to go through `git bisect` on it, but haven't analyzed what exactly did that commit do). And looks like #726 is going to alter some of the changes introduced in that commit, so I'd suggest to perform more testing to make sure it's not broken further/differently.

# Expected behavior
The prompt should say "User PIN" instead of "{0}" (see screenshot below)

# Observed behavior
"{0}" placeholder is displayed instead of proper text. Interesting though that in the keyfile import dialog, it's displayed properly.

# Steps to reproduce
1. Nothing special - insert your PKCS#11 token (I used Nitrokey Pro), start VC, go to Tools -> Manage Security Token Keyfiles... menu item 
2. Observe the PIN popup window having incorrect text

# Screenshots
Incorrect (after entering the Manage Security Token Keyfiles section):
![image](https://user-images.githubusercontent.com/45139988/104853607-4a857900-5902-11eb-9f4a-886105a9d608.png)

Correct (in the import keyfile dialog):
![image](https://user-images.githubusercontent.com/45139988/104854986-39406a80-590a-11eb-9128-f9335fc8a81a.png)

# Your Environment

**VeraCrypt version:** current git tip.
**Operating system and version:** Linux (Fedora 33 x84_64), haven't tried on Windows.

**Comment by T-Bonhagen** [comment]
#726 fix this as well

![Screenshot_20210118_190743](https://user-images.githubusercontent.com/75760084/104950271-a1ea1e80-59c0-11eb-9c67-8925d7ee63e6.png)

**Comment by alfa7ore** [comment]
> The issue was introduced in commit 38ad7650ac4f723fd6109e3f55b3ea1c47ec4af9 (I only had time to go through `git bisect` on it, but haven't analyzed what exactly did that commit do). And looks like #726 is going to alter some of the changes introduced in that commit, so I'd suggest to perform more testing to make sure it's not broken further/differently.
> 
> aehamasmar@icloud.com
**_****_**
> 
> # Expected behavior
> 
> The prompt should say "User PIN" instead of "{0}" (see screenshot below)
> 
> 
> 
> # Observed behavior
> 
> "{0}" placeholder is displayed instead of proper text. Interesting though that in the keyfile import dialog, it's displayed properly.
> 
> 
> 
> # Steps to reproduce
> 
> 1. Nothing special - insert your PKCS#11 token (I used Nitrokey Pro), start VC, go to Tools -> Manage Security Token Keyfiles... menu item 
> 
> 2. Observe the PIN popup window having incorrect text
> 
> 
> 
> # Screenshots
> 
> Incorrect (after entering the Manage Security Token Keyfiles section):
> 
> ![image](https://user-images.githubusercontent.com/45139988/104853607-4a857900-5902-11eb-9f4a-886105a9d608.png)
> 
> 
> 
> Correct (in the import keyfile dialog):
> 
> ![image](https://user-images.githubusercontent.com/45139988/104854986-39406a80-590a-11eb-9128-f9335fc8a81a.png)
> 
> 
> 
> # Your Environment
> 
> 
> 
> **VeraCrypt version:** current git tip.
> 
> **Operating system and version:** Linux (Fedora 33 x84_64), haven't tried on Windows.
> 
>

**Comment by alfa7ore** [comment]
aeham

**Comment by alt3r-3go** [comment]
> #726 fix this as well imho, but i do not have a hardware token.
> Have you test with #726 ?

I haven't tested ti, but it doesn't matter if that's a HW token or not, if you get into that window on your screenshot, then the code path in question is triggered and looks like it indeed fixes it.

**Comment by idrassi** [comment]
I have done a test with an OpenPGP card and the PIN dialog is now showing correct text.

![veracrypt_openpgp_PIN](https://user-images.githubusercontent.com/4698669/108621469-0de1fb80-7433-11eb-9232-dad8a0c31263.png)

Thank you @T-Bonhagen for your contributions.

Closing this issue as fixed by #726
