### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by LutraLutris** [veracrypt/VeraCrypt#736]
Why does VeraCrypt ask for password on my Debian computer after decryption?

I auto mount my USB stick in VC then I put in my password to decrypt it but then VC asks for another "authentication password" on Debian but it doesn't do it on my main PC (windows 10) which I encrypted it on. 

Does my W10 pc have some "automatic" authentication thing which I can take and copy into my Debian?

Debian version: latest and latest VC version on both machines.

**Comment by CentauriII** [comment]
Because I don't remember adding a "second" password.

**Comment by cypherbits** [comment]
I think what you mean is it asks for your user password.

**Comment by alt3r-3go** [comment]
@CentauriII, please note that this bug tracker is rather intended for namely bug and feature request tracking. The general discussion and "how to/why" questions would belong to the VeraCrypt forum at https://sourceforge.net/p/veracrypt/discussion/

With that said, there's not enough detail (e.g. a screenshot of that second authentication window would be helpful), but given it's Linux I think the second request is for a user/root password to actually mount the volume.

**Comment by CentauriII** [comment]
> @CentauriII, please note that this bug tracker is rather intended for namely bug and feature request tracking. The general discussion and "how to/why" questions would belong to the VeraCrypt forum at https://sourceforge.net/p/veracrypt/discussion/
> 
> 
> 
> With that said, there's not enough detail (e.g. a screenshot of that second authentication window would be helpful), but given it's Linux I think the second request is for a user/root password to actually mount the volume, which is expected.

Ah thanks. Hope someone can remove this thread then sorry ^^

**Comment by andreas-becker** [comment]
> Ah thanks. Hope someone can remove this thread then sorry ^^

@CentauriII just set the status of this issue to closed.

**Comment by CentauriII** [comment]
> > Ah thanks. Hope someone can remove this thread then sorry ^^
> 
> 
> 
> @CentauriII just set the status of this issue to closed.
> 
> 

There's no option for that 😅
