### ISSUE TITLE
List more detailed encryption algorithm names and encryption modes, for example: aes-256-gcm

### ISSUE THREAD

**Issue by Fhokud** [veracrypt/VeraCrypt#740]
# Desired behavior

Describe the encryption algorithm and encryption mode in detail in the options

# Environment

Operating system and version:
ALL

**Comment by alt3r-3go** [comment]
Hi @Fhokud, this is already described in the VC docs, please see here: https://www.veracrypt.fr/en/Encryption%20Algorithms.html

In a nutshell - there's not much to describe as there's only one mode of operation supported - XTS and only one key length - 256 bits.
