### ISSUE TITLE
M1 Mac: Mounting fails with "Operation not permitted: VeraCrypt::File::Open:232"

### ISSUE THREAD

**Issue by layandreas** [veracrypt/VeraCrypt#743]
# Expected behavior
Mounting volume successfully.

# Observed behavior

Mounting volume fails due to "Operation not permitted" (see screenshot below).

The folder ".veracrypt_aux_mnt7" does not seem to exist in the folder given in the error message.

# Steps to reproduce

1. Create Volume (Standard VeraCrypt volume)
2. Choose AES Encryption (SHA-512)
3. Select created volume and mount

# Screenshots
![image](https://user-images.githubusercontent.com/79149948/108208405-4fb82c80-7129-11eb-80b7-7f422b3b4bb3.png)

# Your Environment

**VeraCrypt version:** 1.24-Update8

**Operating system and version:** MacOS BigSur Version 11.2.1

**System type:** Macbook Air (M1)

**Comment by venil7** [comment]
Observice same issue on Intel based Mac, BigSur `11.2.3`

**Comment by idrassi** [comment]
For those having this issue, the solution is to add Veracrypt to "Full Disk Access" under Settings > Security & Privacy > Full Disk Access. Solution already proposed on https://github.com/veracrypt/VeraCrypt/issues/795#issuecomment-856525764

**Comment by krischik** [comment]
Would be nice if you caught the error and displayed a more detailed error message.
