### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by atcapollo** [veracrypt/VeraCrypt#753]
what happened to veracrypt.fr ?

**Comment by idrassi** [comment]
Please refer to the my posts on Twitter and Sourceforge:

- https://sourceforge.net/p/veracrypt/discussion/general/thread/0646f84da6/
- https://twitter.com/VeraCrypt_IDRIX/status/1369523849532936193

The infrastructure behind VeraCrypt and IDRIX was destroyed by the OVH fire and time is needed to rebuild it. Hopefully VeraCrypt website should be back online this weekend.

**Comment by atcapollo** [comment]
Sorry to hear that - I didn't see those other outlets. Good look with recovery.

**Comment by NumDeP** [comment]
Hi @idrassi What OVH solution did you use and do you essentially deploy both the veracypt site and your business onto one instance for cost-effectiveness? Did you also happen to check out Hetzner or Alibaba ?

**Comment by idrassi** [comment]
Hi @NumDeP,
VeraCrypt website is indeed deployed to the same instance as IDRIX site. This is done to simplify maintenance et reduce costs. 
I would like to host all data in France with a french provider for better control over data access. For now, OVH is the best in this category. They have done mistakes in their backup handling which caused the global outage after the fire but I believe that they have learned their lesson and that things will be handled better the next time such issue happens.
