### ISSUE TITLE
Cannot build Veracrypt 1.24U7 with NOGUI=1 and WXSTATIC=1 on Raspberry Pi 4 (ARM64)

### ISSUE THREAD

**Issue by AngeloAvv** [veracrypt/VeraCrypt#767]
When I try to build VeraCrypt on a Raspberry Pi 4 with DietPi 7, the making process reports an error.
wx/wx.h should be ignored from build since I'm trying to build a NOGUI version (I haven't a DE so widgets components are useless)

# Expected behavior
Build should succeed

# Observed behavior
``` bash
root@DietPi:~/VeraCrypt/src# make NOGUI=1 WXSTATIC=1
make[1]: /root/VeraCrypt/src/wxrelease/wx-config: Command not found
make[1]: /root/VeraCrypt/src/wxrelease/wx-config: Command not found
Precompiling SystemPrecompiled.h
SystemPrecompiled.h:13:10: fatal error: wx/wx.h: File o directory non esistente
 #include <wx/wx.h>
          ^~~~~~~~~
compilation terminated.
make[1]: *** [/root/VeraCrypt/src/Build/Include/Makefile.inc:50: SystemPrecompiled.h.gch] Error 1
make: *** [Makefile:424: all] Error 2
root@DietPi:~/VeraCrypt/src# 

```

# Steps to reproduce
``` bash
apt install -y make gcc g++ pkg-config libfuse-dev
wget https://launchpad.net/veracrypt/trunk/1.24-update7/+download/VeraCrypt_1.24-Update7_Source.tar.bz2
mkdir VeraCrypt
tar -xvf VeraCrypt_1.24-Update7_Source.tar.bz2 -C VeraCrypt
cd VeraCrypt/src && make NOGUI=1 WXSTATIC=1

```

# Your Environment

**VeraCrypt version:** 1.24-Update7
**Operating system and version:** DietPi 7.x
**System type:** Raspberry Pi 4 (ARMv8 x64)

**Comment by Sod-Almighty** [comment]
This is NOT FIXED.

**Comment by idrassi** [comment]
Please look at the script [src/Build/build_cmake_deb.sh](https://github.com/veracrypt/VeraCrypt/blob/VeraCrypt_1.25.9/src/Build/build_cmake_deb.sh) which we use to build official VeraCrypt package for Raspberry Pi ARM64. You will understand better the step to follow to have a successful build like ours. You can also look at [src/Build/build_veracrypt_linux_gtk3.sh](https://github.com/veracrypt/VeraCrypt/blob/VeraCrypt_1.25.9/src/Build/build_veracrypt_linux_gtk3.sh).

Key points:

- `WX_ROOT` must be set to the location of wxWidgets sources.
- `WX_BUILD_DIR `must be set to the desired build directory for wxWidgets
- first you have to build wxWidgets using the command: `make WXSTATIC=1 NOGUI=1 wxbuild` (this step can be skipped if it has been already performed previously)
- then you can build VeraCrypt using the command: `make WXSTATIC=1 NOGUI=1`

I hope this claries things to you.

**Comment by idrassi** [comment]
The NOGUI build of VeraCrypt doesn't use any GUI. wxWidgets provides various classes not related to GUI in a crossplaform way that allows us to have the same code running under various OSes. 
wxWidgets is the best choice for us since we need both GUI and NON-GUI services in a portable way. 
So, you statement about wxWidgets not being used is not correct.

**Comment by idrassi** [comment]
For your information, VeraCrypt official Raspberry Pi ARM64 console packages (named veracrypt-console-xxx.deb) work perfectly under headless system.

**Comment by Sod-Almighty** [comment]
> VeraCrypt official Raspberry Pi ARM64 console packages (named veracrypt-console-xxx.deb) work perfectly under headless system.

That's as may be, but I'm using Alpine Linux on a desktop machine. Deb files don't work in Alpine, for a number of reasons, and there's no prebuilt Vera executable for Alpine.

**Comment by Sod-Almighty** [comment]
> wxWidgets provides various classes not related to GUI

Fair enough. I will give it a go. Thanks for your time.
