### ISSUE TITLE
Leave SourceForge

### ISSUE THREAD

**Issue by MadaraUchiha** [veracrypt/VeraCrypt#78]
Really guys, it's a malware site, stop distributing with it...

**Comment by SecTec** [comment]
At least they give us the possibillity to verify the binarys with gpg. In this case the way of distribution is regardless. The NSA can infuse maleware at the time of downloading too.

**Comment by andreas-becker** [comment]
Seems like this issue is fixed. Please @MadaraUchiha close this issue.

**Comment by MadaraUchiha** [comment]
@andreas-becker It isn't my place to determine whether an issue has been fixed or not (there may be some ongoing processes that still need to finish, for example). Please ping the developer.

**Comment by andreas-becker** [comment]
@MadaraUchiha, OK, thank you for your feedback. @idrassi I think this issue can be closed.
