### ISSUE TITLE
Read Only

### ISSUE THREAD

**Issue by OlumOG** [veracrypt/VeraCrypt#781]
Hello, I recently decrypted my external hard drive and put some files on it. One Day later I mounted the volume but I can't add any files to it. I took a look in the volume properties and saw that the volume is on Read only. I use Kali Linux. Can anyone help me with my problems? I am sorry for my bad english...

**Comment by Grimmwicht** [comment]
I assume you have Windows on dual boot. When Windows does not shut down properly, it leaves the opened veracrypt device in a kind of „dirty” state, so when booting Linux later, Linux will mount this device read-only as a security measure. Just boot up Windows, mount the device, and shut down Windows properly. After that, your volume should be ok in Linux again.

**Comment by OlumOG** [comment]
> I assume you have Windows on dual boot. When Windows does not shut down properly, it leaves the opened veracrypt device in a kind of „dirty” state, so when booting Linux later, Linux will mount this device read-only as a security measure. Just boot up Windows, mount the device, and shut down Windows properly. After that, your volume should be ok in Linux again.

Sorry for answering that late... I have Linux on single boot and I decrypted the external hard drive on the same Linux computer. I am glad that I could save the files on an other usb stick. Now my files are on that usb stick and I could delete the veracrypt volume and just create a new one. I tried to delete it with the "shred" command but it can't shred the external hard drive, because it it on "read only"... Is there any way to delete the drive without getting a read only error? Thank you for helping me!
