### ISSUE TITLE
VeraCrypt Expander does not check whether a file actually exists (existence check)

### ISSUE THREAD

**Issue by JustMyGithub** [veracrypt/VeraCrypt#787]
# Expected behavior
If you try to open something (e.g. container file) it should be checked whether it actually exists.

# Observed behavior
 The Main GUI doesn't do this during/after file selection but at least during the mount (even though it does not tell which file cannot be read it is quite obvious to the user). However the VeraCrypt Expander doesn't do this check at any of the two steps. It asks for existence of a hidden volume and the authorization parameters but then just silently fails to mount.

**VeraCrypt version:** 1.24-Update7 Windows 10 64-bit

**Comment by idrassi** [comment]
I have implement existence check in VeraCrypt Expander before proceeding further. Commit: https://github.com/veracrypt/VeraCrypt/commit/2bfeba160c80802287a9c63b0d0e7bd0a1a95079
