### ISSUE TITLE
"Operation not permitted: /var/folders/w6/d2xssyzx.../T/.veracrypt_aux_mnt1/control VeraCrypt::File::Open:232" in macOS Big Sur v11.x when mounting containers... 

### ISSUE THREAD

**Issue by antdude** [veracrypt/VeraCrypt#795]
"Operation not permitted: /var/folders/w6/d2xssyzx.../T/.veracrypt_aux_mnt1/control VeraCrypt::File::Open:232" in macOS Big Sur v11.x when mounting containers since the end of 2020. I noticed the long /var/ path has my exposed mounted .dmg in it. It doesn't goes away when I log out and relogin into my macOS account. https://sourceforge.net/p/veracrypt/discussion/technical/thread/442f2b937d/ and https://www.reddit.com/r/VeraCrypt/comments/knkcje/operation_not_permitted/gstb9wv/ also mentioned this issue too. https://i.redd.it/4leo1r6yqg861.png or https://sourceforge.net/p/veracrypt/tickets/431/attachment/vc.png for a screen shot/capture.

**Comment by doctorcomrade** [comment]
Weirdly not seeing this issue on my M1 mac (but can confirm Veracrypt does not work very well with large containers; looking into that right now.) 

When you just mount the container it just exposes that path instead of mounting it at /Volumes/Untitled? Is the container stored locally or on an external drive? Can you give me the file system it is on? I'd love to test this out and see if I can duplicate it.

**Comment by antdude** [comment]
I'm not at this 13" Intel (not M1) MacBook Pro (2020) right now (will check later). Its 2 TB SSD using APFS that came with its preinstalled macOS Catalina v10.15.x that was immediately upgraded to Big Sur after making an admin account and configuring its wifi. The local container file was over 200 MB and formatted as FAT32. I copy this file between computers since it's portable and easily accessible between OSes. I made the container in my over decade old, updated 64-bit W7 HPE SP1 PC with VeraCrypt. What do you mean by "Are you referring to Terminal's df command for "When you just mount the container it just exposes that path instead of mounting it at /Volumes/Untitled?"?

**Comment by antdude** [comment]
OK. I got back to MBP, made a new 1 MB FAT container file, retested, and took screen shots to share: https://imgur.com/a/S9NumGZ (mounted and after unmounting the brand new test file).

**Comment by doctorcomrade** [comment]
Did some research, and while I can't exactly place the "232" (NSFileErrorMinimum is 0 while the max is 2559, so this error code falls within it. -> https://developer.apple.com/documentation/foundation/1448136-nserror_codes/nsfileerrorminimum) 

which is what I'd expect. I'm gonna guess that it might be an issue with macFUSE/OSXFuse. You might need to uninstall it and reinstall it. I see you upgraded it, but that honestly might not be enough. For troubleshooting, you could try to disable SIP, but I would _not_ leave it disabled. 

Someone's steps with macFUSE:

https://sourceforge.net/p/veracrypt/discussion/general/thread/b7cd930cf7/#5033


Another thing 

It could *maybe* be a permissions issue but "Operation Not Permitted" is a good sign it's some sort of OS security issue. Another recommendation, add Veracrypt to "Full Disk Access" under Settings > Security & Privacy > Full Disk Access.

More than happy to troubleshoot with you. By no means am I an expert but I have been researching macOS all day today for my unrelated veracrypt issue lol

Also, heads up, the path (while the error message is not) is normal. /var/folders/*/*/T/ is a temporary directory for files used by applications, it was defined in the original Darwin stuff and Apple still uses it today. If you run the command "getconf DARWIN_USER_TEMP_DIR" it should return the directory that Veracrypt showed in the error.

Keep me updated.

**Comment by antdude** [comment]
OMG! "Another recommendation, add Veracrypt to "Full Disk Access" under Settings > Security & Privacy > Full Disk Access." worked!! Shouldn't VC tell us this to full disk access?

**Comment by doctorcomrade** [comment]
> OMG! "Another recommendation, add Veracrypt to "Full Disk Access" under Settings > Security & Privacy > Full Disk Access." worked!! Shouldn't VC tell us this to full disk access?

Glad it worked! You can probably just grant it access through Privacy for your desktop or wherever the container lives. And I agree, it should prompt you for access to whatever directory your container lives in.

**Comment by antdude** [comment]
Hmm, I didn't see an option to grant specific area on storage in macOS? Or did I miss it?

**Comment by antdude** [comment]
https://sourceforge.net/p/veracrypt/discussion/technical/thread/442f2b937d/?limi
t=25#ac9e  says it worked for Fernado too. VC people needs to fix this and tell users to allow storage access from Big Sur.

**Comment by idrassi** [comment]
After so many years, I have finally updated FAQ page to mention the solution for this issue (https://github.com/veracrypt/VeraCrypt/commit/0e32e5f398c26ef295a796d2b23dc9d313f9b670) and it is available on the [online](https://veracrypt.fr/en/FAQ.html) version as well.

**Comment by antdude** [comment]
Thank you! :)

**Comment by antdude** [comment]
Also, it would be good to have VC program to tell users this too beside FAQ.

**Comment by idrassi** [comment]
@antdude You are right. The installer seems to best place to inform users about this, probably in the last wizard page. Another possibility is during runtime if we receive the operation not permitted issue. Maybe second option will be more helpful since many users ignore what is displayed during installation and they just click Next.
