### ISSUE TITLE
Files Names Renamed To Wrong 

### ISSUE THREAD

**Issue by MahmOodAbuIssa** [veracrypt/VeraCrypt#799]
Files with Arabic names rename to dashes
for exp, صوره.jpg =>  ____.jpg

I have Fedora 33 64-bit

**Comment by robert028** [comment]
What file system are you using for your veracrypt container?

**Comment by MahmOodAbuIssa** [comment]
I used this configs:

**Comment by MahmOodAbuIssa** [comment]
I used this configs : 
- algorithm: ASE 
-  hash : SHA-512 
- File system : FAT

**Comment by MahmOodAbuIssa** [comment]
When I used file system with type Linux Ext4
it works OK
Thanks
