### ISSUE TITLE
EFI not supported on latest nightly build (2016-07-25)

### ISSUE THREAD

**Issue by johnnyshields** [veracrypt/VeraCrypt#81]
Windows 10

![image](https://cloud.githubusercontent.com/assets/27655/17251971/bc9252ae-55e5-11e6-83ba-baf5a327acda.png)

![image](https://cloud.githubusercontent.com/assets/27655/17251952/b099034e-55e5-11e6-9a9c-7391e63c5868.png)

https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/

**Comment by idrassi** [comment]
EFI is included in a separate installer at the same URL.
Look for the file [VeraCrypt Setup 1.18-EFI-PREVIEW-BETA.exe](https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/VeraCrypt%20Setup%201.18-EFI-PREVIEW-BETA.exe/download). 

Moreover, the EFI installer comes with extra algorithms ([Streebog](https://en.wikipedia.org/wiki/Streebog), [Kuznyechik](https://en.wikipedia.org/wiki/Kuznyechik) and the legacy [Magma](https://en.wikipedia.org/wiki/GOST_(block_cipher))) .

Once the EFI implementation is stabilized, it will be included in the standard installer. This is expected in the 2/3 weeks from now.

**Comment by johnnyshields** [comment]
@idrassi thanks for all your great work, I appreciate the clarification.
