### ISSUE TITLE
Native support for Apple Silicon/M1?

### ISSUE THREAD

**Issue by danielktdoranie** [veracrypt/VeraCrypt#813]
Will you be releasing a native universal binary for Apple Silicon/M1?

Not a Rosetta 2 app.

I note there is an arm64 port so it shouldn’t be too hard to port it over. 

Thanks!

**Comment by idrassi** [comment]
Yes, this is planned.
I hope to be able to release a beta version as Universal Binary (amd64/arm64) for testing next weekend.

**Comment by idrassi** [comment]
I have implemented necessary changes for native Apple Silicon M1 support and I have uploaded dmg for version [1.24-Update9-Beta-21-08-15](https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/VeraCrypt_1.24-Update9-Beta-21-08-15.dmg/download) to Sourceforge [Nightly Builds](https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/) folder (PGP signature is on the same location).

Testing and feedback are welcome.

**Comment by danielktdoranie** [comment]
Just installed it, working well. THANK YOU!

**Comment by idrassi** [comment]
[Version 1.25.4](https://github.com/veracrypt/VeraCrypt/releases/tag/VeraCrypt_1.25.4) has been release and it brings official native Applet M1 support.
