### ISSUE TITLE
Generic installer won't properly install on Fedora (please fix for official 1.25 release - Thanks :)

### ISSUE THREAD

**Issue by NumDeP** [veracrypt/VeraCrypt#841]
As there isn't an official version of VC for Fedora I'm trying to install the Generic Installer version but it doesn't seem to load the app at all after installing. 

# Steps to reproduce
1. Download Generic installer
2. Install the x64 Console & GUI parts of the installer (I also tried the x86)
3. Veracrypt application shows in list of applications but clicking the app doesn't load the software

**OS & Environment:**
The latest 10/2021 Fedora build on AMD Ryzen 4000 series

**VeraCrypt version:** 
 VeraCrypt 1.24-Update7

**System type:**
64-bit

**Comment by NumDeP** [comment]
Any chance we can get an ETA on this @idrassi ?

**Comment by idrassi** [comment]
@NumDeP: For Fedore, please use VeraCrypt CentOS 8 RPM installation package. The generic installer links against GTK2 which is not available in Fedora (GTK2 can be installed using the command yum install gtk2 but this is not recommended).

It is probably a good idea to have the GUI generic installer in two flavors (GTK2 and GTK3). Also, Fedora should be indicated alongside CentOS 8 for RPM download.

**Comment by NumDeP** [comment]
I feel like distro would naturally jump to GTK3 in the near future would they not, so is there any point of having more installers on the download page.

As for the enhancement, I suppose as users/companies transition off of CentOS either onto Alma or Rocky, perhaps you could indicate that one rpm version can be installed on Fedora, openSuse, Rock, Alma & CentOS if that's even possible.

**Comment by idrassi** [comment]
Version 1.25.4 has been released and it includes a GTK3 GUI generic installer in the archive veracrypt-1.25.4-setup.tar.bz2, which works on Fedora.
You can reopen if you encounter any issue.
