### ISSUE TITLE
VeraCrypt (cli, Linux) complains about "Failed to obtain administrator privileges." despite not having asked for them

### ISSUE THREAD

**Issue by fthommen** [veracrypt/VeraCrypt#848]
# Expected behavior
We are trying to run `veracrypt` on the commandline. Randomness file, key file and password file have been prepared beforehand and are working fine (tested with the GUI version).  The following command is supposed to create an encrypted NTFS container

```
veracrypt --text                     \
          --create /tmp/vccontainer  \
          --quick                    \
          --force                    \
          --non-interactive          \
          --encryption=AES           \
          --hash=SHA-512             \
          --keyfiles=./keyfile       \
          --random-source=./randfile \
          --password="`cat pwfile`"  \
          --volume-type=normal       \
          --filesystem=ntfs          \
          --size=5G

Done: 100.000%  Speed:  14 MiB/s  Left: 0 s                

The VeraCrypt volume has been successfully created.
```

# Observed behavior
The command complains about missing administrator privileges and fails
```
veracrypt --text [...]

Done: 100.000%  Speed:  14 MiB/s  Left: 0 s               

Error: Failed to obtain administrator privileges.
```

**Problem**: veracrypt has never asked for administrator privileges

# Steps to reproduce

1. Create randomness file, key file and password file manually with the appropriate commands
2. Run the command above
 

# Your Environment

**VeraCrypt version:** 1.25-RC1
**Operating system and version:** Linux (CentOS 7.9)
**System type:** 64bit

**Comment by idrassi** [comment]
@fthommen : This behavior is normal since you specified `--non-interactive` switch which instructs VeraCrypt to avoid any user interaction.
Since you seem to want prompt for administrator privileges, you should remove `--non-interactive`  and add `--pim=0` so that VeraCrypt prompt only for administrator privileges:

```
veracrypt --text                     \
          --create /tmp/vccontainer  \
          --quick                    \
          --force                    \
          --non-interactive          \
          --encryption=AES           \
          --hash=SHA-512             \
          --keyfiles=./keyfile       \
          --random-source=./randfile \
          --password="`cat pwfile`"  \
          --volume-type=normal       \
          --filesystem=ntfs          \
          --pim=0                    \
          --size=5G

```

**Comment by fthommen** [comment]
@idrassi The person who wrote the script that I am currently trying to use, clearly underestimated the power of `--non-interactive` :-). However I am  normally rather used to a command behaviour, where essential dialogues cannot be avoided even with `--silent` or `--quiet` options. Maybe such an option would be more (or equally) useful than the very strict `--non-interactive` (at least for the use cases I can imagine).

Anyway thank you very much for the clarification.
