### ISSUE TITLE
cannot mount encrypted container non-interactively with CLI if no PIM has been set

### ISSUE THREAD

**Issue by fthommen** [veracrypt/VeraCrypt#849]
# Expected behavior
The command
```
veracrypt --text                                     \
          --keyfiles=./keyfile                       \
          --random-source=./randfile                 \
          --password="`cat pwfile`"                  \
          --protect-hidden=no                        \
          --mount /run/media/user/mydata/vccontainer \
          ./mnt
```
is expected to mount the encrypted container `/run/media/user/mydata/vccontainer` at `./mnt` w/o any user interaction.  No PIM has been set when the container was created and mounting of the container works just fine when using the GUI.
 
# Observed behavior
```
veracrypt --text                                     \
          --keyfiles=./keyfile                       \
          --random-source=./randfile                 \
          --password="`cat pwfile`"                  \
          --protect-hidden=no                        \
          --mount /run/media/user/mydata/vccontainer \
          ./mnt
Enter PIM for /run/media/thommen/mydata/vccontainer: 
```
At this point a PIM (or nothing) has to be entered.  However the process cannot run unattendedly.

I have tried with `--pim=""`, `--pim=''`, `--pim=no` and `--no-pim` to no avail.  In all these cases, veracrypt complains about a wrong parameter (`Error: Parameter incorrect:`).

Please also note, that VeraCrypt does not specify, *which* parameter is incorrect...

# Steps to reproduce

1. Run the command above with a prepared and working encrypted container

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 1.25-RC1
**Operating system and version:** Linux (CentOS 7.9)
**System type:** 64bit

**Comment by idrassi** [comment]
In CLI mode, VeraCrypt doesn't use default values for password, keyfile or PIM. So, if one of these is not specified, then it will be requested from the user.

Concerning PIM, the syntax of its switch is `--pim=PIM` as indicated in VeraCrypt help (veracrypt --help) and so in your case, you should specify `--pim=0` to use the default PIM value. The documentation mentions that specifying 0 will make VeraCrypt use default PIM but maybe it should be mentioned in a cleared way. Current text reads:

> In all cases, leaving the PIM empty or setting its value to 0 will make VeraCrypt use the default high number of iterations as explained in section Header Key Derivation.

So the command line should be:
```
veracrypt --text                                     \
          --keyfiles=./keyfile                       \
          --random-source=./randfile                 \
          --password="`cat pwfile`"                  \
          --pim=0                                    \
          --protect-hidden=no                        \
          --mount /run/media/user/mydata/vccontainer \
          ./mnt
```

**Comment by fthommen** [comment]
> Concerning PIM, the syntax of its switch is --pim=PIM as indicated in VeraCrypt help (veracrypt --help) and so in your case, you should specify --pim=0 to use the default PIM value. The documentation mentions that specifying 0 will make VeraCrypt use default PIM but maybe it should be mentioned in a cleared way. Current text reads:
> > In all cases, leaving the PIM empty or setting its value to 0 will make VeraCrypt use the default high number of iterations as explained in section Header Key Derivation.

`--pim=0` is very good, thanks a lot.  When working on the commandline I usually consult the `--help` information, which only states
```
--pim=PIM
 Use specified PIM to mount/open a volume. Note that passing a PIM on the 
 command line is potentially insecure as the PIM may be visible in the process 
 list (see ps(1)) and/or stored in a command history file or system logs.
```

but you are absolutely right that I missed the respective statement on  on https://www.veracrypt.fr/en/Personal%20Iterations%20Multiplier%20(PIM).html. My bad :-(
