### ISSUE TITLE
VeraCrypt (cli, Linux) does not check for valid filesystem types

### ISSUE THREAD

**Issue by fthommen** [veracrypt/VeraCrypt#850]
# Expected behavior
We are trying to run `veracrypt` on the commandline. Randomness file, key file and password file have been prepared beforehand and are working fine (tested with the GUI version).  The following command should return an error and not create any container, because no valid filesystem type is specified
```
sudo \
veracrypt --text                     \
          --create /tmp/vccontainer  \
          --quick                    \
          --force                    \
          --non-interactive          \
          --encryption=AES           \
          --hash=SHA-512             \
          --keyfiles=./keyfile       \
          --random-source=./randfile \
          --password="`cat pwfile`"  \
          --volume-type=normal       \
          --size=5G                  \
          --filesystem=BLAH

SOME ERROR MESSAGE HERE
```

# Observed behavior
The command ends with
```
Done: 100.000%  Speed:  14 MiB/s  Left: 0 s                

The VeraCrypt volume has been successfully created.
```
but he container is not mountable on the commandline or through the GUI. Mounting fails with the error message
```
mount: wrong fs type, bad option, bad superblock on /dev/mapper/veracrypt1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

```

**Problem**: VeraCrypt does not check the validity of the filesystem type and allows any, even completely random, value.
**Question**: What filesystem does VeraCrypt use in these cases?

This bug also will not stop the user to specify `--filesystem=NTFS`, while it should apparently be `--filesystem=ntfs` (it cost us many days to find out why all our volumes failed...)

# Steps to reproduce

1. Create randomness file, key file and password file manually with the appropriate commands
2. Run the command above
 

# Your Environment

**VeraCrypt version:** 1.25-RC1
**Operating system and version:** Linux (CentOS 7.9)
**System type:** 64bit

**Comment by idrassi** [comment]
VeraCrypt was silently ignoring the unknown filesystem value and proceeding to create the volume but without any filesystem (as if "--filesystem=none" was specified).
A fix was implemented for this issue in the commit https://github.com/veracrypt/VeraCrypt/commit/43cf5d7b53dee96c0652ec5529c484d49045dd36. Now VeraCrypt will report an invalid parameter error and exit.
The fix will be included in the upcoming 1.25 release.

Thank you for this report.
