### ISSUE TITLE
Invalid language pack in VeraCrypt 1.25

### ISSUE THREAD

**Issue by Matthaiks** [veracrypt/VeraCrypt#855]
`<localization prog-version="1.24-Update7">` in Language.he.xml throws this error:

![VC](https://user-images.githubusercontent.com/3577122/144071379-766fa2f7-598a-445f-8557-190792719655.png)

https://github.com/veracrypt/VeraCrypt/blob/master/Translations/Language.he.xml

**Comment by idrassi** [comment]
Thank you for reporting this. It was an oversight during packaging.
I have pushed a fix for the XML file and I will have to create a new version 1.25.4 of VeraCrypt to include it.
