### ISSUE TITLE
Question: When will you release the newer versions on veracrypt.fr?

### ISSUE THREAD

**Issue by Avnsx** [veracrypt/VeraCrypt#856]
I don't feel like building the .exe myself. The latest executable that is available for download on the website is 1.24-Update7 (Friday, August 7, 2020)
But your GitHub repo is already at 1.25.4, please provide a precompiled executable on the website 👍🏼

**Comment by antdude** [comment]
Why are the compiled binaries on SourceForge and not on its official web site? Are they not ready yet?

**Comment by idrassi** [comment]
An issue was discovered in one of the packaged language XML files and so distribution process of 1.25 was interrupted.
I’m currently preparing packages for 1.25.4 that should be released tomorrow.

**Comment by antdude** [comment]
Thanks, idrassi! It's a good thing I didn't download the new version then. ;)

**Comment by idrassi** [comment]
version 1.25.4 has just been released.

**Comment by Avnsx** [comment]
> version 1.25.4 has just been released.

Now, if I already have encrypted drives, that were encrypted with the older veracrypt version 1.24-Update7, should I re-encrypt them, with the new updated veracrypt? Or should I just uninstall the old veracrypt and install the new one, without unencrypting and re-encrypting my drives?

**Comment by idrassi** [comment]
No need to re-encrypt drivers when a new version is out. And also need to uninstall first. Just install the new VeraCrypt version and it will take care of updating all necessary files.
