### ISSUE TITLE
veracrypt msi installation is currently not compatible with windows system encryption

### ISSUE THREAD

**Issue by bingoxo** [veracrypt/VeraCrypt#869]
i'm on windows 10 , veracrypt 1.25.4  , using disk encryption , i noticed a new update was released (1.25.7), the .exe file said it can't update it becasue i originally used msi installer (used it because it seemed to be suggested for newer os) , when trying to update using msi installer i get : "veracrypt msi installation is currently not compatible with windows system encryption" 

so how can i update veracrypt ?

**Comment by lipeberg** [comment]
the same problem here (VeraCrypt_Setup_x64_1.25.7.msi) : "veracrypt msi installation is currently not compatible with windows system encryption"

**Comment by idrassi** [comment]
A fix is being implemented for this issue.
It didn't make it to 1.25.7 release but a new build should be released for testing today if things go as planned.

**Comment by bingoxo** [comment]
> A fix is being implemented for this issue. It didn't make it to 1.25.7 release but a new build should be released for testing today if things go as planned.

don't want to be that guy , but do you have an eta by any chance :) ?

**Comment by idrassi** [comment]
@bingoxo 
The technical solution that I was implementing didn't work as expected. So I'm working on a different approach.
Hopefully in 2 weeks from now I should be able to publish a working version.

**Comment by idrassi** [comment]
This has been fixed in version 1.25.9.
