### ISSUE TITLE
I can't install the package veracrypt-trans (Or compile manually) in Arch Linux

### ISSUE THREAD

**Issue by d3417** [veracrypt/VeraCrypt#872]
![mypcinfo](https://user-images.githubusercontent.com/15702493/149269241-9d463c45-cd0c-4c2a-bea8-b0f96130e332.png)

Hello, i've tried to install [veracrypt-trans](https://aur.archlinux.org/packages/veracrypt-trans/) for have it in Italian, but the compilation process gives to me an error that make impossible to continue to compile and run the program, there's a full log trace of it, so you can investigate with ArchLinux (Or ArchLinux Chroot i think it's not different) and explain how to fix because i need veracrypt in italian because i'm Italian and is more nice :-) 

[Full RAW Log](https://siasky.net/DABaZMbJC0rgxdyJKmOa70Y2YmmzDkdj8xmRHJyaUT6wrA)

![errorveracrypt](https://user-images.githubusercontent.com/15702493/149269405-358a654c-bc97-422f-a15e-793ce38cb57a.png)

**Comment by d3417** [comment]
[PKGBUILD](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=veracrypt-trans)

**Comment by d3417** [comment]
Now i try to clone the original veracrypt git repo and to edit with trans-edit.sh > https://gitlab.com/crimsonote/veracrypt-trans/-/raw/128e174fc3e2d64eeabdd11fa91484c2c1e045cf/trans-edit.sh

**Comment by d3417** [comment]
![veraita](https://user-images.githubusercontent.com/15702493/149274747-25889ef4-7aba-4542-af15-734620c5bd57.png)

OK GUYS! FIXED AND WORKED.

Just:

`git clone  https://github.com/veracrypt/VeraCrypt/ && cd VeraCrypt`
`wget https://gitlab.com/crimsonote/veracrypt-trans/-/raw/128e174fc3e2d64eeabdd11fa91484c2c1e045cf/trans-edit.sh`
`bash trans-edit.sh`
`make && sudo make install`
`sudo cp /usr/local/lib/libwx_gtk3u_core-3.1.so.5 /usr/lib/`
`sudo cp /usr/local/lib/libwx_gtk3u_core-3.1.so.5 /usr/lib64`
`sudo cp /usr/local/lib/libwx_baseu-3.1.so.5 /usr/lib/`
`sudo cp /usr/local/lib/libwx_baseu-3.1.so.5 /usr/lib64/`

Et voilà! :-)

**Comment by idrassi** [comment]
Thank you for sharing the solution. It will be helpful to others.
