### ISSUE TITLE
Change program language for Linux

### ISSUE THREAD

**Issue by giovEra** [veracrypt/VeraCrypt#875]
Hi,
I would like to change the language of the VeraCrypt interface, how can I do that?
I tried to add the string ``<config key="Language">en</config>`` to the ``Configuration.xml`` file but it doesn't work.

Version of VeraCrypt installed: v1.25.4 (downloaded from https://veracrypt.fr/en/Downloads.html)
OS: Ubuntu 20.04

Thanks

**Comment by zmiimz** [comment]
I confirm that. There are numerous reasons why having this option in the GUI is crucial. For instance, I own a notebook with a German keyboard, so in Linux, I also use the German keyboard layout. However, my desktop interface is in English, and all my programs, except VeraCrypt, are also in English. Unfortunately, VeraCrypt always displays the German interface by default.

**Comment by Jertzukka** [comment]
Currently it detects your system LANG environment variable, and bases the language on it. If you want to use different language on your VeraCrypt application than your system, you can change your application launcher command to "env LANG=en_US.UTF-8 veracrypt" for example.

**Comment by zmiimz** [comment]
Thanks, although this is well known. We are talking about an option in a GUI.
