### ISSUE TITLE
A minor typo in zh-CN translation

### ISSUE THREAD

**Issue by ameneko-owo** [veracrypt/VeraCrypt#879]
A minor typo in zh-CN translation.

# Expected behavior

At line 648 there is “注意如果你的密码强度不够强，这回事一个安全隐患。” but the right sentence is “注意如果你的密码强度不够强，这会是一个安全隐患。”
“回事” -> “会是”.

# Observed behavior

When I am encrypting my Windows, I use a small PIM and VeraCrypt jump out this.
I thought it's a typo.
 
# Steps to reproduce

Create an encrypt partition or file, use a password length over 20, use a PIM below default.

# Screenshots

![image](https://user-images.githubusercontent.com/91962831/150631953-f0b563de-0a09-4d75-9315-b42fad686e83.png)

# Your Environment
Please tell us more about your environment

**VeraCrypt version:** 
VeraCrypt 1.25.7

**Operating system and version:** 
Windows 11 build 22000.318

**System type:** 
64-bit

**Comment by idrassi** [comment]
Thank you for the fix. It has been included.
