### ISSUE TITLE
Parameter /nowaitdlg cause parsing error

### ISSUE THREAD

**Issue by igromanru** [veracrypt/VeraCrypt#88]
Today I've tested [command line usage](https://veracrypt.codeplex.com/wikipage?title=Command%20Line%20Usage) of veracrypt.
Anything work fine, but it's looks like `/nowaitdlg` doesn't exist?
I'm using it like this: `VeraCrypt.exe /q /v "G:\_temp\test" /l "K" /p "12345678" /nowaitdlg`
[Screenshot](http://i.imgur.com/yrKVlVi.jpg)
Without `/nowaitdlg` is everything alright.
EDIT: Platform Windows 7 64bit.

**Comment by idrassi** [comment]
The /nowaitdlg was added in 1.18 BETA whose installer is published in the nightly builds folder at Sourceforge: https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/

You certainly tested with version 1.17 and that's why you have the error.

FYI, final 1.18 should be released very soon (today or tomorrow). Here is a list of changes done so far, including the addition of /nowaitdlg:

### Changes between 1.17 and 1.18-BETA12 (15 August 2016) :

  - Windows:
     * Support of EFI system encryption (limitatations: no hidden os, no boot custom message)
     * Fix TrueCrypt vulnerability that enables detection of presence of hidden volumes (reported by Ivanov Aleksey Mikhailovich, alekc96 [at] mail dot ru)
     * Add support for Japanese encryption standard Camellia, including for system encryption.
     * Add support for Russian encryption and hash standards Kuznyechik, Magma and Streebog including for EFI system encryption.
     * Add benchmarking of hash algorithms and PRF with PIM (including for pre-boot).
     * Move build system to Visual C++ 2010 for better stability.
     * Fix boot issues on some machines by increasing required memory by 1 KiB
     * Workaround for AES-NI support under Hyper-V on Windows Server 2008 R2.
     * Enhanced protection against dll hijacking attacks.
     * Correctly remove driver file veracrypt.sys during uninstall on Windows 64-bit.
     * Implement passing smart card PIN as command line argument (/tokenpin) when explicitly mounting a volume.
     * When no drive letter specified, choose A: or B: only when no other free drive letter is available.
     * Reduce CPU usage caused by the option to disable use of disconnected network drives.
     * Add new volume ID mechanism to be used to identify disks/partitions instead of their device name.
     * Add option to avoid PIM prompt in pre-boot authentication by storing PIM value unencrypted in MBR.
     * Add option and command line switch to hide waiting dialog when performing operations.
     * Add checkbox in "VeraCrypt Format" wizard GUI to skip Rescue Disk verification during system encryption procedure.
     * Allow files drag-n-drop when VeraCrypt is running as elevated process.
     * Minor GUI and translations fixes.
  - Linux:
     * Fix mount issue on Fedora 23.
     * Fix mount failure when compiling source code using gcc 5.x.
     * Adhere to XDG Desktop Specification by using XDG_CONFIG_HOME to determine location of configuration files.
  - Mac OSX:
     * Solve compatibility issue with newer versions of OSXFuse.

**Comment by igromanru** [comment]
Thank you. The information about the version isn't in the documentation. Couldn't know.
