### ISSUE TITLE
Windows on ARM64 builds

### ISSUE THREAD

**Issue by xqymain** [veracrypt/VeraCrypt#880]
# Desired behavior

distros or compilation guides available for windows arm64
# Screenshots/Mockup/Designs

# Additional information

I built a light and portable storage pool on my Snapdragon 845 phone and I want to encrypt it with veracrypt. But I can't find a distribution for winarm64 or an adapted compilation guide.
# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 1.24-Update7

**Operating system and version:**  Windows 11 build 22538.1000_arm64

**System type:** arm64

**Comment by idrassi** [comment]
Did you try with version 1.25.7? It has Windows ARM64 support.
You can either run the installer directly from the phone or create portable VeraCrypt binaries on a PC and then transfer them to the phone (in this case, you will have to run VeraCrypt-arm64.exe)
