### ISSUE TITLE
host binaries at GitHub within a release assets

### ISSUE THREAD

**Issue by AdamJel** [veracrypt/VeraCrypt#882]
Hello,

I suggest to host the binaries here at GitHub within a release assets.

IMHO it does not make much sense to host binaries elsewhere then GitHub, if the project itself is being hosted here. GH provides tools for automatic building, etc.. So why not host the binaries here as well? Or at least, why host them exclusively elsewhere? That is, host them on Launchpad and Sourceforge, but host them here as well.

Benefits: same platform as source, which means people do not need to go elsewhere, which IMHO may even help with being trusted software - it is a bit peculiar, when I e.g. `winget show VeraCrypt` in terminal and I see in the stdout, that the project is hosted on GitHub, but the binaries would be downloaded from elsewhere. This immediately raises questioning of the trustworthiness.

**Comment by idrassi** [comment]
@AdamJel 
Binaries for version 1.25.9 that has just been released are now also hosted on Github.
As for automatic builds, I prefer to avoid it for security reason and make the builds exclusively in a trusted environment.
