### ISSUE TITLE
Create a new encrypted volume and select Quick Format to make the formatter unresponsive. 

### ISSUE THREAD

**Issue by fxqy** [veracrypt/VeraCrypt#883]
Create a new encrypted volume and select Quick Format to make the formatter unresponsive. Do not choose to be able to successfully create the encrypted volume, but it will take a long time

I'm running 64-bit exe

# Expected behavior
Quickly format the new encrypted volume

# Observed behavior
the formatter unresponsive.

# Screenshots
![图片保存名称—20220126153654491](https://user-images.githubusercontent.com/42601163/151122251-d0bd21e1-71d8-4011-935b-f4547d66ae14.jpg)

**VeraCrypt version:**  1.25.4  64-bit

**Operating system and version:** win10 Microsoft Windows [版本 10.0.16299.125]
**System type:** 64-bit

**Comment by idrassi** [comment]
@fxqy Can you please indicate the filesystem that you used when the issue happened?
Also, what is the size of your volume?
I did several tests using portable mode like you and with different filesystems (FAT, NTFS, exFAT) but I was not able to reproduce the issue.
Thank you for your help.

**Comment by fxqy** [comment]
@idrassi  I didn't create an encrypted volume with a quick format, and decryption is slow now. I used to use cncrypt, decryption encryption is very fast。I'm using exFAT format, I'll try other formats later
![录制_2022_02_24_21_10_56_189](https://user-images.githubusercontent.com/42601163/155530742-59704f21-a4ac-4ada-a869-4b637f5480c6.gif)

**Comment by fxqy** [comment]
I created a 50G NTFS volume, fast formatting is still particularly slow
![录制_2022_02_24_21_18_00_116](https://user-images.githubusercontent.com/42601163/155532175-4c78fccd-8dae-44c0-a9a7-629905604bd6.gif)

**Comment by fxqy** [comment]
I'm using 1.25.9, I'm encrypted with aes(twofish), which is a lot faster. Seems to be a problem with the kuznyechik(aes)
