### ISSUE TITLE
Icons in OSX

### ISSUE THREAD

**Issue by andreas-becker** [veracrypt/VeraCrypt#9]
The Icons in Mac OSX aren't ready for Retina. In Launchpad they look like they are blurred.
If you could post wich format and sizes you need, maybe we find someone creating new ones... or maybe i will give it a try ;-)

**Comment by idrassi** [comment]
I'm aware of this issue. I'm not an expert in graphics and any help on this field will be welcomed.
Currently, the list of graphic files used:
* src/Resources/Icons/VeraCrypt.icns:
    * the main MacOSX icon of VeraCrypt used by the application bundle.
* src/Resources/Icons/VeraCrypt-16x16.xpm:
    * 16x16 VeraCrypt icon used internally through wxWidgets.
* src/Mount/Drive_icon_96dpi.bmp:
* src/Mount/Drive_icon_mask_96dpi.bmp:
* src/Mount/Logo_96dpi.bmp:
* src/Common/Textual_logo_96dpi.bmp:
* src/Format/VeraCrypt_Wizard.bmp:
    * these BMP files are used internally through wxWidgets for icons and dialogs.

Apart from the icns file, the XPM and BMP files are common to Linux and MacOSX. In order to optimize MacOSX display, we should have new high resolution graphic resources that can replace these XPM and BMP.
Any help to make these graphics better (or even proposing new ones) is more than welcomed.

**Comment by andreas-becker** [comment]
Hey,
i did create a new logo and icon in Illustrator, so it's possible to create images in all different sizes.
I'm curious about your opinion.

![veracrypt_v1_20150618](https://cloud.githubusercontent.com/assets/904496/8234544/dcce22ae-15dc-11e5-8d01-90a08cc0fb21.gif)

**Comment by idrassi** [comment]
Thank you for these images.
This is a good step but I think the "safe" theme is too generic.At least, having a reference to VeraCrypt like using the letter V or something related to the encryption functionality.

**Comment by andreas-becker** [comment]
A second version including the productname. Maybe a key is better :-)
![veracrypt_v2_20150702](https://cloud.githubusercontent.com/assets/904496/8478390/62cfd8f8-20d1-11e5-9b30-ec91b82a198c.gif)

**Comment by andreas-becker** [comment]
And an all new approach 

![veracrypt_v5_20150703](https://cloud.githubusercontent.com/assets/904496/8500056/f1e0b4e6-2198-11e5-953b-6f8a0f5c2687.gif)

Colours, as always, can be changed.

**Comment by idrassi** [comment]
Amazing work! Thank you.
I prefer the first set for its simplicity, visual identity and key-shape-like appoach.

In the second set, the VeraCrypt log is too small compared to the machine image. Also, a generic harddrive image is preferable to the MacMini one.

I'll try to get comments from others about this but for now the first set is my favorite pick.

**Comment by andreas-becker** [comment]
ohh ok, i see it was not quite clear... the last image with the mac harddrive is just to show, how the logo will look like if the dmg/pkg file on a mac is mounted.
The logo itself is just the blue/green VC with the complete name underneath.

**Comment by idrassi** [comment]
I agree that this a good candidate.
I would like to do a build of VeraCrypt that includes these icons to see how it look for real. For that, I will need ics files for MacOSX but also .ico for Windows. On Windows, different icons are needed depending on the context (Application icon, system notification tray icon, installer icon). If you could also help on this, this will be much appreciated.

Of course, your copyright will be preserved and mentionned in VeraCrypt credits.

Here are the current Windows icons (very basic...)
![veracrypt_icons](https://cloud.githubusercontent.com/assets/4698669/8687814/5dc7d1ea-2a94-11e5-92c2-2e8241420c55.PNG)




.

**Comment by basnijholt** [comment]
@andreas-becker these look amazing!

Not only the icons are in low resolution, but also the whole interface looks really blurry.

**Comment by andreas-becker** [comment]
@idrassi did you create a build with the provided icons? If so, could you hand it over to me? I'll check on OS X 10.10.5

**Comment by idrassi** [comment]
@andreas-becker I apologize for not giving an update on the new icons. The release of Windows 10 at the end of July forced me to work exclusively on making VeraCrypt compatible and after the release of version 1.12 and 1.13 I had to tackle several issues on Windows that are impacting many users.

Unfortunately, during this period, I had no time to work on MacOSX and Linux. But I will do my best this weekend to do a test build and share it with you.

**Comment by Ben305** [comment]
Any news on this? Is there a build available for testing?

**Comment by Qaatloz** [comment]
I'm thinking of updating the keepasstruecryptmount plugin to support veracrypt. May i already use the nice styled icons from andreas?

**Comment by Enigma2Illusion** [comment]
Hello,

My preference would be the VC logo with the white background changing color when one or more volumes has been mounted. I will leave it to Andreas to showcase the background color that would work best for the logo when a volume is mounted to signify to the user that they have a volume mounted.

Andreas, I would recommend removing the word VeraCrypt since for system tray icon the word would be too small to see and only use the VC logo. Even for the larger logos, just use the VC logo.

Kind Regards.

**Comment by danijelk** [comment]
+1 on the new icons from here as well, anything to replace current one on OSX would be fine :)

**Comment by idrassi** [comment]
I have included the new icons in OSX build, and also Linux and Windows.
You can get the new OSX installer for VeraCrypt 1.17-BETA from https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/

Feedbacks are welcomed.

Thank you again to @andreas-becker for his amazing contribution.

**Comment by Ben305** [comment]
The icons are looking great. But the icon above the "Mount" button isn't really sharp on retina displays.

To make the text look really sharp on retina displays, two entries need to be added to the info.plist:

<key>NSPrincipalClass</key>
<string>NSApplication</string>
<key>NSHighResolutionCapable</key>
<true/>

I have added these entries on my mac, and now the interface looks really good.

<img width="722" alt="veracrypt 1 17 beta with plist-patch" src="https://cloud.githubusercontent.com/assets/2217367/11613016/f706a70c-9c11-11e5-9015-2ae114745db3.png">

**Comment by elmat0** [comment]
These new icons are great! 

I would like to include svg versions of them in the [elementary-extras](https://github.com/mank319/elementaryPlus) icon theme as per [this](https://github.com/mank319/elementaryPlus/issues/304) request. My proposed version is ever so slightly modified by adding a border and discrete drop shadows to better fit the elementary theme. I may drop the VeraCrypt text and just use the glyph on the smaller scales. 

Do you have any objections to this? I would obviously credit @andreas-becker as the original author [here](https://github.com/mank319/elementaryPlus/blob/master/CREDIT.csv), and you are welcome to use the files if you ever find a need to have them in vector format.

**Comment by andreas-becker** [comment]
@elmat0, i already did create the images in vector format :-)
Actually there is no recommendation or corporate identity/design for how to use the icons. So @idrassi should decide if it's ok to modify. By the way, we should create a "Style Guide" like TYPO3 did (https://typo3.org/about/the-brand/style-guide/), to present the most basic rules for the usage of the VeraCrypt logo and spelling.

**Comment by quantum8** [comment]
@Ben305, can you post those plist lines that you've added? I've tried adding those keys and it didn't work for me.

**Comment by Ben305** [comment]
@quantum8 This is my plist-file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleIdentifier</key>
	<string>org.idrix.VeraCrypt</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>VeraCrypt</string>
	<key>CFBundleIconFile</key>
	<string>VeraCrypt.icns</string>
	<key>CFBundleName</key>
	<string>VeraCrypt</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>TRUE</string>
	<key>CFBundleVersion</key>
	<string>1.16.1</string>
	<key>CFBundleShortVersionString</key>
	<string>1.17-BETA</string>
	<key>CFBundleLongVersionString</key>
	<string>VeraCrypt 1.17-BETA</string>
	<key>LSRequiresCarbon</key>
	<false/>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>CSResourcesFileMapped</key>
	<true/>
</dict>
</plist>
```

**Comment by quantum8** [comment]
Mine was the same as that, but I've pasted your copy into mine and it's still not taking effect for some reason. I've noticed the launch options in the info box shows low res selected and greyed out. Perhaps I'm missing something else?

<img width="262" alt="screen shot 2016-01-11 at 11 28 42 am" src="https://cloud.githubusercontent.com/assets/5791220/12225457/b0862346-b856-11e5-87a5-c004345b06aa.png">

**Comment by squidfunk** [comment]
Hi, Martin here from VOOLA - looks like you got "inspired" by our company logo, Andreas :-) FYI, we have been using this since the end of 2014.

![VOOLA Logo](https://voola.de/images/logo.png)

**Comment by andreas-becker** [comment]
Hi Martin, I promise, i haven't seen this logo before and the similarity is unintentionally. The logo was completely designed by me with no other logo as template (first as a sketch, then in Illustrator).
I had a few versions with different colors choosen in adobe kuler, but this combination seemed best to me.

**Comment by danijelk** [comment]
They sure do look alike - color wise, but then again how many ways can you make a V with triangles :)
http://www.shutterstock.com/cat.mhtml?searchterm=triangle+pattern

**Comment by victorvox** [comment]
nice one!

**Comment by squidfunk** [comment]
True, I already thought it's probably only a matter of time until someone comes up with a similar idea. The funny thing is that the color scheme matches, the forms match (for the V) and both names start with a V. Strange coincidence. However, Andreas, I heard you are already in contact with my co-founder Thomas, so I think this will not be a big problem, should be easily solvable. Maybe it's a good idea to differentiate via color, so we don't get confused for each other, but I leave it up to you.

**Comment by keng42** [comment]
@quantum8 
https://stackoverflow.com/questions/20426140/how-to-enable-use-low-resolution-on-retina-display-for-an-application-when-shi

**Comment by idrassi** [comment]
Some alternative colors for the logo.The idea behind the color choice is simple:

- Red as a color for truly important information => Vera => V
- Blue as a color for cold storage => Crypt (which is also a synonym for an underground vault or chamber, thus the cold temperature theme).

There are two possibilities at this stage:
![veracrypt_red_blue_256x256](https://cloud.githubusercontent.com/assets/4698669/12801791/af54987c-cadf-11e5-87f5-72b7038c92f3.png) ![veracrypt_gradient_256x256](https://cloud.githubusercontent.com/assets/4698669/12801785/a4c9ab04-cadf-11e5-86dc-21754c26514d.png)
Please vote for your favorite choice.

**Comment by Ben305** [comment]
I like the left one!

**Comment by elmat0** [comment]
Also a big fan of the left one. I hate to play devils advocate but it is strikingly similar to the Valvoline logo. ;p

**Comment by stp242** [comment]
:+1: for the left one

**Comment by Enigma2Illusion** [comment]
I vote for the original Blue/Green logo since I do not see any issues with people getting confused between VeraCrypt and Voola logos.

To put it another way, think of the all the startup though large company logos that exist and there are bound to be some similarities.

The new red/blue logo looks like a backward checkmark with the letter C and does not represent the letters V and C. The Orange/Purple maintains the flow of V and C letters via the color transition, however to my eyes is not aesthetically pleasing to view.

**Comment by silvether** [comment]
@andreas-becker would you be willing to share the vectors for the new Veracrypt logo? I have some spare time and wanted to play around with them on a retina screen.
They look great by the way!

**Comment by andreas-becker** [comment]
@idrassi , sorry for not beeing active in the last few months. I will marry soon and therefore had no time and desire for other things. 
@silvether , as you can see, there is no final decision made about the combination of the color. To not have a lot of different Veracrypt logos on the web I would therefore hesitate to made the logo public. If @idrassi s opinion is another, he also had the needed files and could hand them over to you.

**Comment by darkhouse2** [comment]
Veracrypt starter under Linux syntax is wrong in /usr/share/applications/veracrypt.desktop file:
replace first line by second
`# Exec=/usr/bin/veracrypt`
`    Exec=/usr/bin/veracrypt %f`
People, the icons are still not in the package and linked - want to help you with this!

**Comment by jetelina** [comment]
Hi,
I like the left (red) icon.

I would also love this icon for for Windows version of VeraCrypt. See my comment here:
https://sourceforge.net/p/veracrypt/discussion/features/thread/9298d888/#ed24

It would be great if tray icon can be unified and easily distinguishable for mounted and not mounted state.

Here is my suggestion:
![mount unmount](https://cloud.githubusercontent.com/assets/22988266/19612316/2b1a9cee-97e6-11e6-82bb-7174247c37d2.png)

**Comment by andreas-becker** [comment]
Hey @idrassi, long time no see. Do you need further help on icons, graphics or website?

**Comment by idrassi** [comment]
Hi @andreas-becker. Indeed, it has been long time. Your contribution was very helpful in giving VeraCrypt a visual identity.
Although I don’t have a clear idea about tasks related to graphics, I think there is always room for enhancements.
One thing that can enhanced is the bitmap used for Create Volume wizard: it looks blurry in MacOSX and it is not really professionally done (I just put together VeraCrypt logo with IDRIX one). 
Can you help in making a better bitmap for the wizard?
The current bitmap is at https://github.com/veracrypt/VeraCrypt/blob/master/src/Format/VeraCrypt_Wizard.bmp

Thank you for your help.

**Comment by andreas-becker** [comment]
Sure i can. Do you already have a dedicated "picture" in mind?

**Comment by idrassi** [comment]
Thanks. I don’t have any idea any mind...but I trust your creativity!

**Comment by andreas-becker** [comment]
Here's what i quickly put together

![Wizard v1](https://andreasbecker.de/share/VeraCrypt_Wizard_1.png "Version 1")
![Wizard v2](https://andreasbecker.de/share/VeraCrypt_Wizard_2.png "Version 2")
![Wizard v3](https://andreasbecker.de/share/VeraCrypt_Wizard_3.png "Version 3")

**Comment by idrassi** [comment]
@andreas-becker Thank you. Version 1 looks better to me but I feel that a symmetry is missing somewhere. Maybe the top part should be made lateral on the left side instead...or maybe I'm influence by current one. Any opinion @alt3r-3go on this?

Also a higher resolution with same proportion is needed because it is displayed blurry in UI.

**Comment by alt3r-3go** [comment]
Out of those three I also like number 1 the most, however to me personally there's too much empty space between the logo and the picture... :) I actually quite like the current one :D, maybe we should simply make a higher-res version of it?

**Comment by andreas-becker** [comment]
ok, maybe it looks better in context. Does there really have to be the logo in this view?
![VeraCrypt_Wizard_view_2](https://user-images.githubusercontent.com/904496/70853060-34102100-1ea9-11ea-9908-e6fc62349060.jpg)
![VeraCrypt_Wizard_view](https://user-images.githubusercontent.com/904496/70853061-34a8b780-1ea9-11ea-95eb-624924384de6.jpg)

**Comment by alt3r-3go** [comment]
Oh, that I like much better! The second version of it, with the logo, that is. The green part of the logo blending in with the picture a bit, but I think there's actually some charm about that.

**Comment by andreas-becker** [comment]
Jpg, 204x316, 144dpi
![VeraCrypt_Wizard_204x316_144](https://user-images.githubusercontent.com/904496/70866957-1a85dc80-1f70-11ea-91a7-8016c686e0b4.jpg)

**Comment by idrassi** [comment]
Thank you @andreas-becker, I agree that this is good.

I have done an OSX build with and the screenshot below shows how it looks under OSX Mojave with dark mode. It is definitely better than existing one which was too white.
I will include this new image in the upcoming 1.24-Update2 which I hope to be able to release tomorrow (oh wait...it is already tomorrow!!).

Just a small request: is it possible to have a version with a dimension of 204x370? I think a larger height is better in order to leave less space above and below in the wizard window.

![VeraCrypt_Wizard_new_OSX](https://user-images.githubusercontent.com/4698669/70870964-3aca9100-1f9a-11ea-8258-f2f6fe3eb6dd.png)

**Comment by andreas-becker** [comment]
I will provide the image with the new dimensions after work around 4/5pm.

**Additional Infos for the used image**
Photo by Rob King on [Unsplash](https://unsplash.com/photos/Au6eR7Yg9CY)

> All photos published on Unsplash can be used for free. You can use them for commercial and noncommercial purposes. You do not need to ask permission from or provide credit to the photographer or Unsplash, although it is appreciated when possible.

**Comment by andreas-becker** [comment]
Here it is: VeraCrypt_Wizard_204x370_96
![VeraCrypt_Wizard_204x370_96](https://user-images.githubusercontent.com/904496/70919891-f551a680-2021-11ea-9322-8687feaa196b.jpg)
