### ISSUE TITLE
Couldn't build source with Visual Studio 2019

### ISSUE THREAD

**Issue by longhus** [veracrypt/VeraCrypt#907]
Hi all,
I installed all environments in "Requirements for Building VeraCrypt for Windows" in the document. (I used Windows 10 64bits)

Then I open the VeraCrypt.sln by Visual Studio 2010. I also did "Select 'All' as the active solution configuration." but when I clicked build the solution, it show error: 
**fatal error C1083: Cannot open source file: 'blake2s.c': No such file or directory**
Does anyone face the problem above? Please help me with this.

**Comment by idrassi** [comment]
Please try again with latest source code from master. There was an issue with code in master branch when you the clone last time.
Also, there is a dedicated solution for Visual Studio 2019 called [VeraCrypt_vs2019.sln](https://github.com/veracrypt/VeraCrypt/blob/master/src/VeraCrypt_vs2019.sln) so please use it.
