### ISSUE TITLE
Crowdin or Transifex website to manage the VeraCrypt localizations

### ISSUE THREAD

**Issue by Patriccollu** [veracrypt/VeraCrypt#908]
Hello,

I noticed there was a VeraCrypt project page on [Transifex](https://www.transifex.com/otf/veracrypt/). If the page refers to the official VeraCrypt website, it looks to be hosted by '*Localization Lab*'.

I also found a similar page on [Crowdin](https://crowdin.com/project/veracrypt) which looks to be more *official*.

Please can you confirm that the second website is a safe and official place to maintain the VeraCrypt project translations? If this is the case, I will request to add language Corsican (co) and to join the localization team.

Edited on March 21<sup>st</sup>: I just noticed that the Crowdin website had not been updated for a very very long time! So I have some doubt. Please clarify.

On the other hand, tell me if you prefer keeping on using GitHub pull requests to take into account the future translation updates?

Best regards,  
Patriccollu.

**Comment by andreas-becker** [comment]
As i know, the translations are currently handled via Pull requests here on GitHub.
I don't know Transifex or Crowdin, but if these could provide an easy workflow to automatically create Pull requests here on GitHub it might be a good choice.
Every automated workflow might help @idrassi to work on the code/features/bugs.

**Comment by Patriccollu** [comment]
Thank you @andreas-becker I'm going to close this issue.

My previous updates on Corsican translations are done via Pull Requests on GitHub.
The most recent #972 is currently Open and waiting for a Merge.
