### ISSUE TITLE
Windows 10 - (system) favorites vs fast startup

### ISSUE THREAD

**Issue by Phil-Friderici** [veracrypt/VeraCrypt#91]
I have the problem that on Windows 10 (Version 1607, build 14393.51) 64bit my system favorites will only get mounted if the system does a full boot. When the system does a fast startup [1] it will not mount the system favorites nor the favorites.

For the time getting fixed a hint in docs or FAQ would come handy :)

[1] http://www.cnet.com/how-to/what-is-windows-10s-fast-startup/

PS: thanks a lot for your great work !!

**Comment by andreas-becker** [comment]
@Phil-Friderici is this issue is still present?

**Comment by Phil-Friderici** [comment]
@andreas-becker: Thank you for asking.

From my point of view this issue isn't present anymore. On a fresh installed Windows 10 [1] where fast startup is active by default, I don't have that issue anymore :)

Will close the issue now.

phile grüße
[1] Windows 10 64bit (Version 1909, build 18363.592)
