### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Roki100** [veracrypt/VeraCrypt#912]
Hello! I have one drive thats running low on space (~500mb free out of 4tb), and there is a question if it can be safely encrypted with veracrypt without wiping/"cleaning" it to do it? do encrypted drives/files use more disk space or require some amount of it to do so?
i would like to encrypt it but im not sure if ~500mb is enough and safe to even start the process

**Comment by a-raccoon** [comment]
Veracrypt requires less than 1 megabyte for its volume header and footer.  You can safely encrypt the data in place.  Encryption does not create expansion of the data being encrypted.

**Comment by andreas-becker** [comment]
Thank you @a-raccoon for your help.

@Roki100, please close your Issue if your question is satisfied.
