### ISSUE TITLE
Macbook M1 Pro at Monterey 12.1 

### ISSUE THREAD

**Issue by kslman** [veracrypt/VeraCrypt#916]
ok

# Expected behavior

when i open VeraCrypt

# Observed behavior

It crash

# Steps to reproduce

1. Use Macbook M1 Pro at Monterey 12.1 
2. install VeraCrypt VeraCrypt_1.25.4.dmg or VeraCrypt_1.25.9.dmg
3. open VeraCrypt
4. it happen

# Screenshots

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               VeraCrypt [71725]
Path:                  /Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt
Identifier:            org.idrix.VeraCrypt
Version:               1.25.4 (1.25.4)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-03-27 20:49:36.8996 +0800
OS Version:            macOS 12.1 (21C52)
Report Version:        12
Anonymous UUID:        C5EDA0DA-715E-4C76-EF9E-988DF492F9A3

Sleep/Wake UUID:       F3600535-10C5-45A3-A4BB-068CBF327EBF

Time Awake Since Boot: 680000 seconds
Time Since Wake:       3449 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/lib/libfuse.2.dylib
Referenced from: /Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt
Reason: tried: '/usr/local/lib/libfuse.2.dylib' (fat file, but missing compatible architecture (have 'unknown,unknown,i386,x86_64', need 'arm64e')), '/usr/lib/libfuse.2.dylib' (no such file)
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: /usr/local/lib/libfuse.2.dylib
Referenced from: /Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt
Reason: tried: '/usr/local/lib/libfuse.2.dylib' (fat file, but missing compatible architecture (have 'unknown,unknown,i386,x86_64', need 'arm64e')), '/usr/lib/libfuse.2.dylib' (no such file)

Thread 0 Crashed:
0   dyld                          	       0x1053334dc __abort_with_payload + 8
1   dyld                          	       0x10533a4dc abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x10533a510 abort_with_payload + 16
3   dyld                          	       0x1052f28e4 dyld4::halt(char const*) + 328
4   dyld                          	       0x1052edfd4 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3568
5   dyld                          	       0x1052ed0d4 start + 488

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b28aa60   x3: 0x0000000000000068
    x4: 0x000000016b28a660   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x00000000000004c0
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000037  x14: 0x0000000244eb27da  x15: 0x0000000000000000
   x16: 0x0000000000000209  x17: 0x00000001052eb168  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016b28a660  x21: 0x0000000000000068  x22: 0x000000016b28aa60  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016b28b3a8  x26: 0x0000000000000000  x27: 0x000000001f070004
   x28: 0x0000000000000000   fp: 0x000000016b28a630   lr: 0x000000010533a4dc
    sp: 0x000000016b28a5f0   pc: 0x00000001053334dc cpsr: 0x00001000
   far: 0x000000010528c000  esr: 0x56000080  Address size fault

Binary Images:
       0x1052e8000 -        0x105347fff dyld (*) <7e92b284-4b90-3b68-b31a-3ddc4c0e8d40> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=5552K resident=0K(0%) swapped_out_or_unallocated=5552K(100%)
Writable regions: Total=9296K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9296K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                        1.0G        2 
__DATA                             784K        3 
__DATA_CONST                       624K        2 
__LINKEDIT                         832K        2 
__TEXT                            4720K        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                              1.1G       14 

-----------
Full Report
-----------

{"app_name":"VeraCrypt","timestamp":"2022-03-27 20:49:36.00 +0800","app_version":"1.25.4","slice_uuid":"cac4bb1d-2227-3a7b-8ab9-3ae3292462e0","build_version":"1.25.4","platform":1,"bundleID":"org.idrix.VeraCrypt","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.1 (21C52)","incident_id":"0E1DD245-4D03-4795-A20F-9DD9A0BC67CA","name":"VeraCrypt"}
{
  "uptime" : 680000,
  "procLaunch" : "2022-03-27 20:49:36.8424 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "procStartAbsTime" : 16416266126664,
  "coalitionID" : 95506,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C52",
    "releaseType" : "User"
  },
  "captureTime" : "2022-03-27 20:49:36.8996 +0800",
  "incident" : "0E1DD245-4D03-4795-A20F-9DD9A0BC67CA",
  "bug_type" : "309",
  "pid" : 71725,
  "procExitAbsTime" : 16416266498402,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "VeraCrypt",
  "procPath" : "\/Applications\/VeraCrypt.app\/Contents\/MacOS\/VeraCrypt",
  "bundleInfo" : {"CFBundleShortVersionString":"1.25.4","CFBundleVersion":"1.25.4","CFBundleIdentifier":"org.idrix.VeraCrypt"},
  "storeInfo" : {"deviceIdentifierForVendor":"FD1B0F9D-1724-5758-A715-71A2F18256B0","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.idrix.VeraCrypt",
  "crashReporterKey" : "C5EDA0DA-715E-4C76-EF9E-988DF492F9A3",
  "wakeTime" : 3449,
  "sleepWakeUUID" : "F3600535-10C5-45A3-A4BB-068CBF327EBF",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/usr\/local\/lib\/libfuse.2.dylib","Referenced from: \/Applications\/VeraCrypt.app\/Contents\/MacOS\/VeraCrypt","Reason: tried: '\/usr\/local\/lib\/libfuse.2.dylib' (fat file, but missing compatible architecture (have 'unknown,unknown,i386,x86_64', need 'arm64e')), '\/usr\/lib\/libfuse.2.dylib' (no such file)"]},
  "asi" : {"dyld":["Library not loaded: \/usr\/local\/lib\/libfuse.2.dylib","Referenced from: \/Applications\/VeraCrypt.app\/Contents\/MacOS\/VeraCrypt","Reason: tried: '\/usr\/local\/lib\/libfuse.2.dylib' (fat file, but missing compatible architecture (have 'unknown,unknown,i386,x86_64', need 'arm64e')), '\/usr\/lib\/libfuse.2.dylib' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":6823649,"threadState":{"x":[{"value":6},{"value":1},{"value":6092794464},{"value":104},{"value":6092793440},{"value":0},{"value":0},{"value":1216},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":55},{"value":9746196442},{"value":0},{"value":521},{"value":4381913448,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6092793440},{"value":104},{"value":6092794464},{"value":1},{"value":6},{"value":6092796840},{"value":0},{"value":520552452},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4382237916},"cpsr":{"value":4096},"fp":{"value":6092793392},"sp":{"value":6092793328},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4382209244,"matchesCrashFrame":1},"far":{"value":4381523968}},"frames":[{"imageOffset":308444,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":337116,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":337168,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":43236,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":0},{"imageOffset":24532,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3568,"imageIndex":0},{"imageOffset":20692,"symbol":"start","symbolLocation":488,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4381900800,
    "size" : 393216,
    "uuid" : "7e92b284-4b90-3b68-b31a-3ddc4c0e8d40",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6713720832,
  "size" : 3089596416,
  "uuid" : "66c33c62-48a9-31e5-b8b5-7a71c9760d07"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=5552K resident=0K(0%) swapped_out_or_unallocated=5552K(100%)\nWritable regions: Total=9296K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9296K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                        1.0G        2 \n__DATA                             784K        3 \n__DATA_CONST                       624K        2 \n__LINKEDIT                         832K        2 \n__TEXT                            4720K        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                              1.1G       14 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61fb0e87c773c43cde3bb80e"
      },
      "deploymentId" : 240000305
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "621d4d0f680160486b9e1c98"
      },
      "deploymentId" : 240000416
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000123
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000302
    }
  ],
  "experiments" : [

  ]
}
}

# Your Environment

Macbook M1 Pro at Monterey 12.1 

**VeraCrypt version:** 

VeraCrypt_1.25.4.dmg or VeraCrypt_1.25.9.dmg

**Operating system and version:** 

Monterey 12.1

**System type:** 

ARM-64 is 64-bit i think

**Comment by idrassi** [comment]
From the report, the library '/usr/local/lib/libfuse.2.dylib' that is installed by macFUSE doesn't have ARM64 architecture:

> Reason: tried: '/usr/local/lib/libfuse.2.dylib' (fat file, but missing compatible architecture (have 'unknown,unknown,i386,x86_64', **need 'arm64e'**)), '/usr/lib/libfuse.2.dylib' (no such file)

Can you re-install the latest version of [macFUSE](https://github.com/osxfuse/osxfuse/releases) (4.2.4 at time or writing), reinstall VeraCrypt and then try again?

**Comment by kslman** [comment]
> 

after re-install  macFUSE 4.2.4, and reinstall VeraCrypt_1.25.9.dmg, It work!

thx very much.<( _   _ )>

**Comment by idrassi** [comment]
Thank you for the confirmation. I’m glad it helped.
