### ISSUE TITLE
wxWidgets assertion failure

### ISSUE THREAD

**Issue by bugtracker2019** [veracrypt/VeraCrypt#952]
Before start-up a dialog-window pops up, which says (in short):
wxEXPAND overrides alignment flags in box sizers

Although the check-box "Show this dialog the next time" is UNchecked, the window will appear next time.

Possible workaround is to open a terminal and start via:
`$ export WXSUPPRESS_SIZER_FLAGS_CHECK=1 && veracrypt &`

# Expected behavior
No pop-up window, which can be achieved by building the program with NDEBUG defined as stated [here](https://www.wxwidgets.org/blog/2021/06/sizer-asserts-in-wxwidgets-3.1/).

# Steps to reproduce
1. On Arch Linux install/update wxwidgets-gtk3 3.2.0-2
2. Build Veracrypt from source

# Your Environment
Arch Linux 64-bit, Kernel 5.15.2
wxwidgets-gtk3 3.2.0-2

**VeraCrypt version:** 1.25.9

[wxERROR.txt](https://github.com/veracrypt/VeraCrypt/files/9120812/wxERROR.txt)

**Comment by jabbalaci** [comment]
Same error under Manjaro Linux.

**Comment by rsramkis** [comment]
This issue was re-producible on both Gnome and KDE desktops on EndeavourOS

https://forum.endeavouros.com/t/veracrypt-error-message-after-update-wxgtk-wxwidgets/29258

**Comment by tekstryder** [comment]
I just built 1.26.7 for Arch and [this patch](https://github.com/archlinux/svntogit-community/blob/packages/veracrypt/trunk/wx-3.2-size-warnings.patch) was no longer necessary with `wxwidgets-gtk3 3.2.4-2`

**Comment by bugtracker2019** [comment]
This issue was resolved in VeraCrypt 1.26.7 thx to [this](https://github.com/veracrypt/VeraCrypt/pull/999).
