### ISSUE TITLE
Please add option to remember last used drive letter

### ISSUE THREAD

**Issue by SetTrend** [veracrypt/VeraCrypt#96]
TrueCrypt remembered the last drive letter used when mounting an encrypted file.

I'm very much missing this feature in VeraCrypt (for Windows). Lacking a shortcut key to give focus to the drive letter list (or perhaps just missing a label above the list giving a hint on which accessibility key to use) adds quite an additional effort to mounting an encrypted file.

Would you re-establish remembering the most recently used drive letter? If there are reasons for some users against this feature, adding a corresponding Boolean option (enable/disable) to the Settings dialog would be fine.

**Comment by lrq3000** [comment]
As a workaround, it's possible to set [favorite volumes](https://www.veracrypt.fr/en/Favorite%20Volumes.html), but it's not automatic, you need to setup a favorite for each drive.

**Comment by SetTrend** [comment]
Unfortunately that's not a workaround for the case described.

This issue is about mounting any _arbitrary_ volumes, so favorite volumes don't apply here.
<br/>

Actually, the suggested improvement is rather easy to implement:

1. Add a label control to the Drives list and add an accelerator key to it, giving focus to the Drives list:

   ![VeraCrypt - 1](https://user-images.githubusercontent.com/9283914/75344265-966aa200-589a-11ea-96ec-f21890e2bfe9.png)

   **Current Situation**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Desired Situation**
   ![VeraCrypt - 2](https://user-images.githubusercontent.com/9283914/75344376-cade5e00-589a-11ea-8196-55e59a33b924.png)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![VeraCrypt - 3](https://user-images.githubusercontent.com/9283914/75344379-cca82180-589a-11ea-9467-c818612cdc61.png)
<br/>

This way, mounting a volume would be as easy as hitting <kbd>ALT</kbd>+<kbd>D</kbd>, <kbd>ARROW DOWN</kbd> (or the corresponding drive letter as required), <kbd>ALT</kbd>+<kbd>F</kbd> on the keyboard.
