### ISSUE TITLE
Dismount make Windows 10 x64 taskbar hang

### ISSUE THREAD

**Issue by dzungpv** [veracrypt/VeraCrypt#98]
On Windows 10 pro x64 14393.105, after unmounted a partition, veracrypt 1.18a make taskbar hang, mouse click on taskbar area and windows icon impossible. I must use hot key Windows +X to restart computer.

**Comment by Ontario70** [comment]
You need to wait a looooooong time (approx. 2 mins?) til the "successfully dismounted" popup shows up and everything works again.

**Comment by pisces72** [comment]
Confirmed here as well, Win 10 x64. I just restart explorer.exe. Annoying.

**Comment by ptlrk** [comment]
Confirmed W10 x64.
Happens only when dismounting be right-clicking taskbar icon.
You can avoid the behavior by disabling notifications for Verycrypt in W10 control panel.

**Comment by digz6666** [comment]
@ptlrk how can I disable nofitications?

**Comment by ptlrk** [comment]
Open conttrol panel, select "System", then "Notifications", scroll down to "Veracrypt" and set it to "Off".

Hope that the terms are in English as expected.

Latest version 1.21 has the problem, still.

**Comment by idrassi** [comment]
Similar issue has been reported on Sourceforge (https://sourceforge.net/p/veracrypt/discussion/technical/thread/4dfed495/#d6c4) that affected web browser and it could be fixed by disabling VeraCrypt waiting dialog: go to menu Settings -> Preferences and check "Don't show wait message dialog when performing operations" in the "Windows" section as shown in the screenshot below.

Does doing this avoid the hanging?

![VeraCrypt Preferences](https://i.imgur.com/b9mzjAv.png)

**Comment by ptlrk** [comment]
No, it doesn't.

**Comment by Uli-Armbruster** [comment]
Same issue here: Win10 Pro x64 v1703
In 1.19, everything is fine.

**Comment by Gelf54** [comment]
If it helps, the hang doesn't occur when selecting the mounted volume in the main dialog and selecting "Dismount".

**Comment by Gelf54** [comment]
I did wonder if it's trying to dismount all the drives listed as favourites, even if they aren't connected.

**Comment by Ardakilic** [comment]
Same issue here on W10 Pro x64, too. Happens on me when I click dismount from the bottom left button inside the app:

![image](https://user-images.githubusercontent.com/2063957/32022966-9c07f074-b9e0-11e7-9431-ae0b5307c132.png)


Also, similar discussion here: https://sourceforge.net/p/veracrypt/discussion/technical/thread/c8920010/

At there, seems Malwarebytes Anti Malware was the culprit, however, quitting didn't help at all.
