### ISSUE TITLE
Not mounting silently without empty password parameter

### ISSUE THREAD

**Issue by Messna** [veracrypt/VeraCrypt#99]
I have a container with just a keyfile and VeraCrypt doesn't want to mount it silently, if I don't provide an empty password as a parameter. 

Example:
`VeraCrypt.exe /hash sha512 /v "test.hc" /k "keyFile" /l E /a /s /q`
does nothing

`VeraCrypt.exe /hash sha512 /v "test.hc" /k "keyFile" /l E /a /s /q /p ""`
mounts the container correctly

**Comment by andreas-becker** [comment]
@Messna is this issue still present?
